### ISSUE TITLE
EASYRSA_REQ_CN in build-full is overwritten

### ISSUE THREAD

**Issue by hudecof** [OpenVPN/easy-rsa#100]
the `--req-cn="<user defind string>"` is passed to the commandline, the `EASYRSA_REQ_CN` is overwrittent in `build_full` function.

```
diff --git a/easyrsa3/easyrsa b/easyrsa3/easyrsa
index 088faeb..3b20b38 100755
--- a/easyrsa3/easyrsa
+++ b/easyrsa3/easyrsa
@@ -693,7 +693,7 @@ Matching file found at: "
        [ -f "$crt_out" ] && die "Certificate $err_exists $crt_out"

        # create request
-       EASYRSA_REQ_CN="$name"
+       set_var EASYRSA_REQ_CN "$name"
        gen_req "$name" batch $req_opts

        # Sign it
```

**Comment by TCB13** [comment]
+1 I'm also experiencing this issue.

**Comment by discotroy** [comment]
@hudecof I tried out your patch, but it seems that without `--batch` on the commandline, the env variable is still getting overwritten.  I think it may happen in the `gen_req()` function:

```
        # pull filename base and use as default interactive CommonName:
        [ -n "$1" ] || die "\
Error: gen-req must have a file base as the first argument.
Run easyrsa without commands for usage and commands."
        local key_out="$EASYRSA_PKI/private/$1.key"
        local req_out="$EASYRSA_PKI/reqs/$1.req"
        [ ! $EASYRSA_BATCH ] && EASYRSA_REQ_CN="$1"
        shift
```
If `--batch` is required for `--req-cn` to be honoured, then this should probably be made more apparent.

**Comment by hudecof** [comment]
@discotroy I actually use it in batch mode. Feel free to fix it for your needs, if not I will try to find out some time for this.

**Comment by LozanoMatheus** [comment]
Hi @oreinert I guess you could just change line 495 and setup the vars file.

easyrsa script:
```bash
[ "$EASYRSA_BATCH" ] && opts="$opts -batch" || export EASYRSA_REQ_CN="${EASYRSA_REQ_CN:-"Easy-RSA CA"}"
```

vars file:
```text
set_var EASYRSA_REQ_CN		"example.com"
```

**Comment by ecrist** [comment]
Related to #363.  Comment there.  Closing this one.
