### ISSUE TITLE
error easyrsa-start openvpn server windows

### ISSUE THREAD

**Issue by fcmassarotti** [OpenVPN/easy-rsa#1007]
Someone already got the error, MirBSD Korn Shell stopped working, when running easyrsa-start

**Comment by TinCanTech** [comment]
From the description given, I presume this relates to #619

**Comment by TinCanTech** [comment]
EasyRSA has been tested on Windows upto version 11 and it works.

@fcmassarotti Can you add some details about your environment and the error you encounter.

**Comment by fcmassarotti** [comment]
when I try to run easyesa-start.bat, I get the error , as below:
C:\Program Files\OpenVPN\easy-rsa>EasyRSA-Start.bat

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by TinCanTech** [comment]
What is your version of Windows ?

**Comment by fcmassarotti** [comment]
Windows 2016 server datacenter,I have it on 5 servers, only this one gives the error

**Comment by TinCanTech** [comment]
IF only one server gives the error then that strongly suggests it is something unique to that server only.

Perhaps it is a security setting within Windows that you have enabled .. but, honestly, I have no idea and no way to test.

If you manage to get it working then please let us know the cause.

**Comment by fcmassarotti** [comment]
I've done everything too, if I can let you know, in case anyone has an idea

**Comment by TinCanTech** [comment]
I'll leave this open for a while.

**Comment by fcmassarotti** [comment]
I try any versions, look the erro in imagem, when I execute easyrsa-start.bat
![erro vpn](https://github.com/OpenVPN/easy-rsa/assets/143464773/bb3b6ca0-bc30-4896-b28e-9a999e41eda8)

**Comment by fcmassarotti** [comment]
same error happens

**Comment by TinCanTech** [comment]
EasyRSAv3 Windows unit-test successfully runs on:
- **Microsoft Windows Server 2022, 10.0.20348, Datacenter**.

**Comment by TinCanTech** [comment]
If you have an anti-virus program running then try disabling that.

**Comment by fcmassarotti** [comment]
ja desabilitei antivirus também, fiz de tudo

**Comment by fcmassarotti** [comment]
I already disabled antivirus too, I did everything

**Comment by TechChri** [comment]
I have the same problem on windows server 2019, have you solved the problem?

**Comment by TinCanTech** [comment]
@TechChri you can try the `busybox` solution offered here: #1075

**Comment by TechChri** [comment]
![Unbenannt](https://github.com/OpenVPN/easy-rsa/assets/158849872/07d38c5e-832d-4ca7-9d60-b4f70161c72e)
It worked, thank you!! But what should I do now ?

**Comment by TinCanTech** [comment]
> It worked, thank you!! 

Great.

> But what should I do now ?

Continue testing.
