### ISSUE TITLE
Line length in easyrsa script

### ISSUE THREAD

**Issue by aduzsardi** [OpenVPN/easy-rsa#1017]
This is a minor issue in a sense that it's not affecting functionality but those line breaks make it so unnecesarily hard to read this script.
Shellcheck's most useless feature is that of warning about line length , lets be serious ... it's not 1990 anymore with terminal screens of the size of my phone.

Anyway , what i wanted to say is that making it easier to read would make it probably easier to maintain and/or to contribute.

**Comment by aduzsardi** [comment]
Btw , thank you @TinCanTech for picking up this project awesome to see all the new features added and the various fixes merged   🙇🏻‍♂️

**Comment by TinCanTech** [comment]
@aduzsardi do you have an example of a line you cannot understand ?

**Comment by aduzsardi** [comment]
Sure, random function taken out of the script
**Original**
```shell
secure_session() {
	# Session is already defined
	[ "$secured_session" ] && \
		die "session overload"

	# temporary directory must exist
	if [ "$EASYRSA_TEMP_DIR" ] && \
		[ -d "$EASYRSA_TEMP_DIR" ]
	then
		: # ok
	else
		die "secure_session - Missing temporary directory:
* $EASYRSA_TEMP_DIR"
	fi

	for i in 1 2 3; do
		session="$(
			easyrsa_random 4
			)" || die "secure_session - session"
		secured_session="${EASYRSA_TEMP_DIR}/${session}"

		# atomic:
		if mkdir "$secured_session"; then
			# New session requires safe-ssl conf
			unset -v mktemp_counter \
				OPENSSL_CONF safe_ssl_cnf_tmp \
				working_safe_ssl_conf
			easyrsa_err_log="$secured_session/error.log"
			verbose "\
secure_session: CREATED: $secured_session"
			return
		fi
	done
	die "secure_session failed"
} # => secure_session()
```

In my opinion (i might be wrong) this version is easier to follow and to read 
**Fewer line foldings/breaks**
```shell
secure_session() {
	# Session is already defined
	[ "$secured_session" ] && die "session overload"

	# temporary directory must exist
	if [ "$EASYRSA_TEMP_DIR" ] && [ -d "$EASYRSA_TEMP_DIR" ]
	then
		: # ok
	else
		die "secure_session - Missing temporary directory:* $EASYRSA_TEMP_DIR"
	fi

	for i in 1 2 3; do
		session="$(easyrsa_random 4)" || die "secure_session - session"
		secured_session="${EASYRSA_TEMP_DIR}/${session}"

		# atomic:
		if mkdir "$secured_session"; then
			# New session requires safe-ssl conf
			unset -v mktemp_counter OPENSSL_CONF safe_ssl_cnf_tmp working_safe_ssl_conf
			easyrsa_err_log="$secured_session/error.log"
			verbose "secure_session: CREATED: $secured_session"
			return
		fi
	done
	die "secure_session failed"
} # => secure_session()

```

**Comment by TinCanTech** [comment]
My choice of line wrapping may be a little severe, eg:
```
    for $foo in \
        bar \
        baz \
    do
```
Not applied with absolute rigour, eg:
```
    for $foo in bar baz; do
```
Syntactically redundant, eg:
```
    [ $foo ] && \
         print "$bar"
```
and other styles besides ..

However, I prefer shorter lines and more wrapping over longer lines without wrapping. Although, I admit that I have not applied this with an _iron fist_.

I do not see how such stylistic choices have any effect on contributions. There is nothing to stop you contributing your code, wrapped your way, and have it changed in said PR or later on by me.

**Comment by aduzsardi** [comment]
Cool , thank you!
