### ISSUE TITLE
gen-crl recreates crl.pem file - not only contents

### ISSUE THREAD

**Issue by Tabiskabis** [OpenVPN/easy-rsa#1019]
I'd like to have OpenVPN running as nobody/nogroup. For it to be able to read the crl.pem, then, I `chown :nogroup crl.pem; chmod g+r crl.pem` it.  
Now if I use gen-crl or revoke, openssl destroys the file and recreates it with 600 user:user, and if I forget to redo these commands manually, OpenVPN won't be able to read crl.pem (And typically, I'll bonk my head after the next kernel upgrade & reboot).  

Of course I have a script for that. I'm currently thinking about a wrapper for easyrsa, just to do something like if first arg is gen-crl, then `mv crl.pem crl.bak; easyrsa $*; cat crl.pem > crl.bak; mv crl.bak crl.pem`
  
Unless I'm doing it gravely wrong, this is a request for enhancement for Easy-RSA.

**Comment by TinCanTech** [comment]
> Unless I'm doing it gravely wrong, this is a request for enhancement for Easy-RSA.

_Gravely_, no. _Wrong_, yes.  (I understand that English is not your native language.)

What is your _request for enhancement_ ?

You want `easyrsa` to set permissions on the `crl.pem` file ?

**Comment by TinCanTech** [comment]
@Tabiskabis I would recommend that you developa working external script.

It could possibly be included here as a `/contrib` item.

**Comment by Tabiskabis** [comment]
> Gravely, no. Wrong, yes.

Mkay, you mentioned using systemd to isolate OpenVPN from most of the filesystem. The idea then, i assume, is to copy crl.pem to an excepted path, along with things like client specific directives and scripts?
My plan was to run openvpn as "nobody" and easyrsa some other user (to protect the pki from my main user account). Seems I need to educate myself further regarding systemd.

> (I understand that English is not your native language.)

Obviously not. But also, when in a hurry, I tend to not reflect upon things, that otherwise I think about more thoroughly. And not proofread.

> You want easyrsa to set permissions on the crl.pem file ?

No, I expect it to keep existing permissions. So If effect, technically, yes.

Currently, the process is: create $out_file_tmp -> openssl -> mv $out_file_tmp $out_file. 
I was thinking of: create $out_file_tmp -> `[ -r "$out_file" ] && cp -a "$out_file" "$out_file_tmp"` -> openssl -> mv $out_file_tmp $out_file.
That should be simple enough to avoid security nightmares. If crl.pem is unreadable or simply does not yet exist, nothing changes. If it does, "then assume smart user" (to quote from my favorite comment in Debian's bashrc).

**Comment by TinCanTech** [comment]
> That should be simple enough

Both **git** and **github** have _simple enough_ methods for you to express yourself clearly..

**Comment by Tabiskabis** [comment]
I do not fully understand that comment and find it both confusing and irritating.
A pattern appearing ever more the deeper I get into other peoples computers.
So I tried expressing myself in code: https://github.com/OpenVPN/easy-rsa/pull/1020

**Comment by TinCanTech** [comment]
> I tried expressing myself in code: #1020

Good idea, thanks.

The EasyRSA solution would be to use `EASYRSA_UMASK`.
Set the `mask` to include `other`, eg. `022`
Technically, undocumented.

Another approach could be to drop the temp-file mechanism
for command `gen-crl`. Then OpenSSL would write directly to
the CRL file.

**Comment by Tabiskabis** [comment]
Using `EASYRSA_UMASK`, one could achieve a similar effect, but still lose metadata such as ACLs, forks and -more practical- ownership. `cp -r` preserves these. It also requires scripting.

The temp-file mechanism provides atomicity which, I suspect, may have been done specifically for the case where OpenVPN accesses the PKI's crl.pem directly. Writing directly without temp-file would only save one file create and one copy operation. Since gen-crl is not a bulk operation, I see no benefit to that.

**Comment by TinCanTech** [comment]
For `gen-crl`, I prefer to drop the temp-file mechanism.
