### ISSUE TITLE
Expired client still connects

### ISSUE THREAD

**Issue by fardindadashi** [OpenVPN/easy-rsa#1031]
Hi
After expiration time of a client, I run:
`easyrsa update-db`
then the V tag in index.txt changes to E tag, but the client still connects even after disconnecting.
What am I missing? I know how to revoke but I just want to disable client and enable it again after a while.
Please help me

**Comment by TinCanTech** [comment]
> What am I missing?

Using Venn interpretation, _theoretically_, the answer is **_infinity_**.

**Comment by fardindadashi** [comment]
please give a clear answer.

**Comment by ecrist** [comment]
To temporarily disable a client in openvpn you need to use a client-config-dir with an entry for the client you want to disable. Thy config needs a single line of yext that reads "disabled".

Your question is not easyrsa related.

Eric F Crist
________________________________
