### ISSUE TITLE
`v3.2.0` Command removal

### ISSUE THREAD

**Issue by TinCanTech** [OpenVPN/easy-rsa#1044]
These commands will be removed for `v3.2.0`:
- `upgrade` - Use `v3.1.7`
  This only effects people who are still using Easy-RSA `v2.3.x`
- `rewind-renew` - Use `v3.1.7`
  This only effects certificates renewed by Easy-RSA `v3.0.6` - `v3.0.9`
  These certificates must use `rewind-renew` before they can be revoked.
  `rewind-renew` is only available with Easy-RSA `v3.1.x`
- `rebuild` - Should have never existed. Not replaced.
- `set-rsa-pass` - Replaced by `set-pass`
- `set-ec-pass` - Replaced by `set-pass`

Note: `set-*-pass` is still available in `v3.1.7`, although it was deliberately removed from `help`.

**Comment by ivkusan** [comment]
[EasyRSA PKI upgrade process: EasyRSA PKI version 2 to EasyRSA version 3](https://community.openvpn.net/Pages/easyrsa-upgrade#setup) did not reflect this change.

The situation is that, for example, Rocky Linux 10 installs EasyRSA Version 3.2.4 (EPEL 8 has easy-rsa-3.2.1) and there are still some systems that use [easy-rsa 2](https://github.com/OpenVPN/easy-rsa-old) that need to be migrated/upgraded.
