### ISSUE TITLE
Upgrade easy-rsa of OVPN-Server without switching to Debian 13 (Trixie)

### ISSUE THREAD

**Issue by htcfreek** [OpenVPN/easy-rsa#1051]
Is there a way (for example manually replacing files) to upgrade easy-rsa to the newest version on my Debian based OpenVPN-Server without upgrading Debian to version 13 (Trixie)? Ho can I avoid problems when executing `apt upgrade` in the future having a manually patched easy-rsa version.

My problem: I like to use the new `renew` command from `easy-rsa 3.1.1+`.

I found two easy-rsa dirs on my disk:
- `/usr/share/easy-rsa`: v3.0.8
- `/etc/openvpn/easy-rsa`: v3.0.8

_(Current debian version: 11.8)_

**Comment by TinCanTech** [comment]
> Is there a way (for example manually replacing files) to upgrade easy-rsa to the newest version

Please see [Releases](https://github.com/OpenVPN/easy-rsa/releases) for the latest.

If you prefer then you can also use `git`.

As the absolute minimum, all you need to do is download `easyrsa` and replace the version of that file which you currently use.

**Warning**: Keep back-ups of things that you decide to change.

**Comment by htcfreek** [comment]
@TinCanTech 
Where can I find the answer?

**Comment by htcfreek** [comment]
@TinCanTech 
Is it enough to only replace the script `easyrsa` itself or should I replace the config `openssl-easyrsa.cnf` too? Because the config seems to be adjusted.

**Comment by TinCanTech** [comment]
If you use EasyRSA version `3.1.7` then all the _support files_ are created on demand. Which means that you can delete them.

_Support files_: `openssl-easyrsa.cnf` and `x509-types/` directory.

**Comment by htcfreek** [comment]
@TinCanTech 
Thank you.
