### ISSUE TITLE
easy-rsa - renew command v1: Is the old version of the certificate revoked automatically

### ISSUE THREAD

**Issue by htcfreek** [OpenVPN/easy-rsa#1052]
The documentation says that if I use the renew command from v3.0.8 (renew version 1)  the renewed certificate can't get revoked.

It is a bit unclear what exactly is meant:
- Is the old version of the certificate still working (if not expired)?
- Is it impossible to revoke a renewed certificate in the future?

**Comment by TinCanTech** [comment]
Reference documentation: [doc/EasyRSA-Renew-and-Revoke.md](https://github.com/OpenVPN/easy-rsa/blob/master/doc/EasyRSA-Renew-and-Revoke.md)

The best option for you is to upgrade to version `3.1.7` and use that.

Then you can run `easyrsa show-renew`, which will give you the status of your renewed certificates.

If you have any certificates which have been renewed by command `renew` version `1` then you must use `rewind-renew` before you can revoke the old certificate.

Yes, it is complicated.  

It was a mess that I did not create but I did provide a solution to.

**Comment by htcfreek** [comment]
@TinCanTech 
Thank you for the information.
