### ISSUE TITLE
vars file not found

### ISSUE THREAD

**Issue by sysadminpower2019** [OpenVPN/easy-rsa#1079]
I am trying to run
 ./easyrsa upgrade ca 
previously that had told me to move my vars file to the pki directory. 
I did just that and this is the error message i get now 

* Using Easy-RSA configuration: /etc/openvpn/easy-rsa/pki/vars

Easy-RSA error:

vars file not found

EasyRSA Version Information
Version:     3.1.2
Generated:   Fri Jan 13 15:49:32 CST 2023
SSL Lib:     OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.7 1 Nov 2022)
Git Commit:  354c20d82bdc5db364e197aa1290e84b46abe487
Source Repo: https://github.com/OpenVPN/easy-rsa
Host: 3.1.2 | nix | Linux | /bin/zsh

It almost seems like it found the file but isnt using it for some reason

**Comment by TinCanTech** [comment]
Hi, I cannot replicate this problem at all.

Try moving your `vars` file back to where it was previously and try again.

**Comment by sysadminpower2019** [comment]
in the previous folder the error is 
* The preferred location for 'vars' is within the PKI folder.
  To silence this message move your 'vars' file to your PKI
  or declare your 'vars' file with option: --vars=<FILE>

so no matter what i do it doesnt seem to work correctly

**Comment by TinCanTech** [comment]
You can ignore the message about moving your `vars` file.
Ref: #1009

Is there another problem ?
