### ISSUE TITLE
Add equivalent of `--req-*` but for `sign-req`.

### ISSUE THREAD

**Issue by agowa** [OpenVPN/easy-rsa#1099]
Hi, going to make this a feature request then.
I'd like to have a way to overwrite the values within a signing request while signing it. Similar to `--req-*` but while signing.

I.E. a csr with invalid/missing values is provided and one wants to fix that while signing. This happens very often for e.g. appliances. Especially when they're behind a load balancer as they then often do not have the ability to include the load balancers fqdn. And some other appliances do not allow the dn to be user defined and instead always use the same hard coded  one.

From my original ticket (where I thought this was a bug) #1087

              `sign-req` does not honor any Easy-RSA `--req-*` values because they are only valid in a request context. IE. `gen-req`.

_Originally posted by @TinCanTech in https://github.com/OpenVPN/easy-rsa/issues/1087#issuecomment-2021622637_

**Comment by TinCanTech** [comment]
The accepted solution is to create your CSR correctly, in the first place.

**Comment by TinCanTech** [comment]
https://github.com/OpenVPN/easy-rsa/blob/master/doc/EasyRSA-Contributing.md
