### ISSUE TITLE
EasyRSA download

### ISSUE THREAD

**Issue by lapinpt** [OpenVPN/easy-rsa#112]
# Get easy-rsa
wget -O ~/EasyRSA-3.0.1.tgz https://github.com/OpenVPN/easy-rsa/releases/download/3.0.1/EasyRSA-3.0.1.tgz
HTTP request sent, awaiting response... 403 Forbidden
ERROR 403: Forbidden.

curl -Lo ~/EasyRSA-3.0.1.tgz 
works OK

**Comment by slavkoja** [comment]
your wget command works for me

**Comment by lapinpt** [comment]
sorry, my bad

commented [ continue = on ] in .wgetrc made the job
