### ISSUE TITLE
`dev/easyrsa-tools.lib` missing in release build

### ISSUE THREAD

**Issue by freddebacker** [OpenVPN/easy-rsa#1144]
Hi,

`dev/easyrsa-tools.lib` seems to be missing in the release file.
I downloaded [EasyRSA-3.2.0.tgz](https://github.com/OpenVPN/easy-rsa/releases/download/v3.2.0/EasyRSA-3.2.0.tgz) and command `./easyrsa show-expire` does not work complaining missing file.

I worked around by downloading it directly from github.

Fred

**Comment by TinCanTech** [comment]
> worked around by downloading it directly from github

For the time being, _downloading_ is the correct solution.

The rational is:
`easyrsa` `v3.1.7` carries around a lot of old code, including the status reports you mentioned, certificate renewal and the upgrade procedure:
- **Status reports** are still a work in progress; while they work, they are cumbersome. Development can continue without disturbing `easyrsa` code.
- **Command** `renew` has been replaced by better code. The `renew` command did not work properly; it would drop some certificate attributes during renewal and the work required to make `renew` work correctly is an unnecessary maintenance burden. Now, if a certificate is expiring/expired, it can be replaced with a new certificate with all the same attributes as the original, via `sign-req` command.
- **Upgrading** the CA/PKI is now considered to be obsoleted. The code was removed.

`easyrsa` `v3.2.x` is the start of a new version, that will not be overly burdened by old code.

**Comment by marek22k** [comment]
Arch Linux issue: https://gitlab.archlinux.org/archlinux/packaging/packages/easy-rsa/-/issues/1

Is there a workaround (-> what is a `standard system location`)?

**Comment by TinCanTech** [comment]
For Easy-RSA **Standard system location**:
* The Easy-RSA `pki` directory, specified by `$EASYRSA_PKI` env-var.
* The directory specified by `$EASYRSA` env-var.
* The current working directory, specified by `$PWD` env-var.
* The directory specified by the `easyrsa` script location `$0` env-var.
* The directory `/usr/local/share/easy-rsa`.
* The directory `/usr/share/easy-rsa`.
* The directory `/etc/easy-rsa`.
* Any preferred directory, specified by `--tools=<PATH/FILE-NAME>`.

**Comment by TinCanTech** [comment]
I believe `easyrsa-tools.lib` has had enough time to stabalize. I intend to fold it back into the main `easyrsa` script before `v3.2.2` (#1258).

**Comment by TinCanTech** [comment]
It would be simpler, if `easyrsa-tools.lib` were simply moved to the `easyrsa3/` directory. #1259

**Comment by TinCanTech** [comment]
Closed via d30b6885f9b90b422b1eb7102e8702be9d3ebe36
