### ISSUE TITLE
Need Guide for Upgrading 3.0.8 to 3.1.1

### ISSUE THREAD

**Issue by khatfull** [OpenVPN/easy-rsa#1183]
As in title.  I apologize for being an OpenVPN/easyrsa noob, but I seem to have inherited an installation.

Looking for a guide to make the upgrade from easyrsa 3.0.8 to 3.1.1 to make the server cert renewal easier (apparently).  I can't find anything definitive.

CA cert is good for another 8 years, server cert expires in 3 months along with most client certs.  Clients certs I can handle, the server cert is a little befuddling to do without invalidating connections out in the field. 

Running on Ubuntu 22.04 LTS.

Any guide or wiki would be much appreciated.

Thanks!

**Comment by TinCanTech** [comment]
![ddg-easyrsa-upgrade](https://github.com/OpenVPN/easy-rsa/assets/25598447/92279114-2519-4033-9e90-7229f756b6fd)

**Comment by TinCanTech** [comment]
![ddg-easyrsa-upgrade](https://github.com/OpenVPN/easy-rsa/assets/25598447/2270c02e-9466-4b34-afef-a08a8e6a4bd0)
