### ISSUE TITLE
Generate client certs and keys non-interactively on Windows

### ISSUE THREAD

**Issue by alexkmbk** [OpenVPN/easy-rsa#1189]
On Linux we can generate client's cretificate and key by using command: 
./easyrsa gen-req client1 nopass
./easyrsa sign-req client client1

But how to do the same on Windows (non-interactively, without user prompt)?

**Comment by TinCanTech** [comment]
EasyRSA works the same for Windows.

I like your avatar.

**Comment by alexkmbk** [comment]
@TinCanTech Thank you! But there is no such command on Windows like easyrsa, we have to call EasyRSA-Start.bat firstly and it makes impossible (as it seems to me) to generate the key file non-interactively in a .bat file for example.

**Comment by TinCanTech** [comment]
You will need to customize your installation of EasyRSA in Windows.

**Comment by alexkmbk** [comment]
> You will need to customize your installation of EasyRSA in Windows.

I did, but we still need to call  EasyRSA-Start.bat 

![image](https://github.com/user-attachments/assets/95000c83-235a-46c1-b02f-c5c629e2cab8)
