### ISSUE TITLE
vars not sourced if no directory specified explicitely

### ISSUE THREAD

**Issue by deep-42-thought** [OpenVPN/easy-rsa#119]
Currently, the `vars` file is only sourced if either:
* `EASYRSA_VARS_FILE` is set to the file directly via environment or command line argument `--vars`
* `EASYRSA_PKI` or `EASYRSA` is set to the parent directory via environment or command line argument `--pki-dir`
* `vars` is located next to executable `easyrsa`

IMHO, this misses the case that no such arguments are given and simply e.g. `easyrsa build-ca` is executed from the right location (so that `pki` is in the working directory).
In this case, a `vars` file should be found in `./pki/` and `./`, too - just as if they were specified via environment variables.

This should be fixed, since there should be no difference how `EASYRSA_PKI` et al. is set (of course, setting it via `vars` is obviously different).
I've had a brief look into the code and I think, I can provide a patch or pull-request if this is wanted.

regards,
deep-42-thought

**Comment by ecrist** [comment]
Solved in #128 and also duplicates [trac 788](https://community.openvpn.net/openvpn/ticket/788).  Closing.
