### ISSUE TITLE
Embed/Inline configs and certificates together

### ISSUE THREAD

**Issue by bogdanr** [OpenVPN/easy-rsa#122]
It would be nice if the tool could embed the config and the certificates as a single file so that it would be easier to distribute the config to clients.

Right now clients are using different platforms so distributing as separate files is not a good option.

I am using a script like this and works fine for me but it would be nicer to have a better integrated solution:
```bash
#!/bin/bash
set -e

cd /etc/openvpn/easy-rsa/
cp config.template /tmp/$1.ovpn
echo "<ca>" >> /tmp/$1.ovpn
cat keys/ca.crt | grep -A 100 "BEGIN CERTIFICATE" | grep -B 100 "END CERTIFICATE" >> /tmp/$1.ovpn
echo "</ca>" >> /tmp/$1.ovpn
echo "<cert>" >> /tmp/$1.ovpn
cat keys/$1.crt | grep -A 100 "BEGIN CERTIFICATE" | grep -B 100 "END CERTIFICATE" >> /tmp/$1.ovpn
echo "</cert>" >> /tmp/$1.ovpn
echo "<key>" >> /tmp/$1.ovpn
cat keys/$1.key | grep -A 100 "BEGIN PRIVATE KEY" | grep -B 100 "END PRIVATE KEY" >> /tmp/$1.ovpn
echo "</key>" >> /tmp/$1.ovpn
```

**Comment by ecrist** [comment]
There’s another project, ssl-admin, that can do this.

**Comment by AndersBillLinden** [comment]
Why do you have a script that adds together an ovpn file instead of just showing what the ovpn file will look like?

**Comment by TinCanTech** [comment]
Also, EasyRSA has an inline function now.  

Also, [Easy-TLS](https://github.com/TinCanTech/easy-tls) has enhanced inlining to cover all TLS keys. Check it out !

**Comment by TinCanTech** [comment]
> It would be nice if the tool could embed the config and the certificates as a single file

@bogdanr Above, you use **EasyRSA version 2.**

You could have submitted your code as a PR.

**Comment by TinCanTech** [comment]
No feedback in over half a decade.
