### ISSUE TITLE
keypairs and request signing ?

### ISSUE THREAD

**Issue by SheepDomination** [OpenVPN/easy-rsa#1230]
I don't quite understand this; I've read some of the advanced guide but don't understand ?
As well, how do I sign a request ?

> Ideally you should never generate entity keypairs for a client or server in a PKI you are using for your CA. It is best to separate this process and generate keypairs only on the systems you plan to use them

**Comment by TinCanTech** [comment]
> how do I sign a request ?

Please see `help`.
