### ISSUE TITLE
`easyrsa gen-crl` does not honour `openssl-easyrsa.cnf` CRL location/filename configuration

### ISSUE THREAD

**Issue by dvanzuijlekom** [OpenVPN/easy-rsa#1232]
`openssl-easyrsa.cnf` has the following configuration variable:

```bash
crl             = $dir/crl.pem          # The current CRL
```
However, changing this to a different value has no effect, as `easyrsa` has the following hardcoded in the `gen_crl` function:

```bash
# gen-crl backend
gen_crl() {
        out_file="$EASYRSA_PKI/crl.pem"
        out_der="$EASYRSA_PKI/crl.der"
```

In my opinion, `easyrsa` should either honour the configuration variable in the OpenSSL config file, or it should be removed from the template config file (or perhaps being marked as having no effect)?

Thank you for this awesome project :heart:

**Comment by TinCanTech** [comment]
This, and other settings in `openssl-easyrsa.cnf`, have never been honored and there is no intention for that to change, at least for the foreseeable future.

It is more likely that parameters in `openssl-easyrsa.cnf`, which are not honored, will be removed from that configuration file.
