### ISSUE TITLE
Development snapshots should be marked as prereleases

### ISSUE THREAD

**Issue by numinit** [OpenVPN/easy-rsa#1239]
Hey there,

I noticed that https://github.com/OpenVPN/easy-rsa/releases/tag/v3.2.0 got released, and this dutifully triggered our tools in nixpkgs:

https://github.com/NixOS/nixpkgs/pull/312649

However, this release, despite being marked with "NOTICE: EasyRSA version 3.2.0 is a development snapshot." on the GH release, was not marked as a prerelease. So our update scripts pushed an unstable version out.

Regardless, it's fixed now, but I'd suggest marking GH dev releases as prereleases in the future.

Thanks!

**Comment by TinCanTech** [comment]
Yes, `3.2.0` should have been more clearly marked as a _development snapshot_. Sorry about that.
