### ISSUE TITLE
Passphrases with quotes don't work

### ISSUE THREAD

**Issue by artyom-razinov** [OpenVPN/easy-rsa#1256]
Steps to reproduce:

1. `./easyrsa init-pki && ./easyrsa build-ca`

2. Enter `abc"` (see double quote in the end)

Actual result:

3. `Enter New CA Key Passphrase: ./easyrsa: 1: eval: Syntax error: Unterminated quoted string`

Expected result:

3. no syntax error

Environment:
`./easyrsa --version`: 3.1.7

There's `eval` in the code without escaping.

This can help to fix it: https://stackoverflow.com/questions/70822095/bash-equivalent-of-pythons-shlex-quote

Feel free to close the issue as I can do fix myself, but I'm basically to lazy to do it, because it's much easier for me to just not use `"` in passphrase than to contribute to 4K+ lines bash script

**Comment by TinCanTech** [comment]
@artyom-razinov Easy-RSA is `sh` not `bash` ...

Anyhow, if you take a look at `./easyrsa help build-ca`, you will find details specifically pertaining to your issue.

Please close this, once you are satisfied.

**Comment by artyom-razinov** [comment]
I believe you were talking about this:

```
      * raw-ca  - ONLY use SSL binary to input CA password
        raw       (Equivalent to global option '--raw-ca')
```

(I'm just keeping it here if someone search for this issue)

Sorry for taking your time and have a nice day.

**Comment by TinCanTech** [comment]
Alternatively, you can automate this with use of EasyRSA options `--passin` and `--passout`.
