### ISSUE TITLE
Certificates are rejected by Chrome 58

### ISSUE THREAD

**Issue by rfjakob** [OpenVPN/easy-rsa#126]
> Since version 58, Chrome requires SSL certificates to use SAN (Subject Alternative Name) instead of the popular Common Name (CN), thus CN support has been removed.

![screen shot 2017-05-02 at 07 42 49](https://cloud.githubusercontent.com/assets/286847/25612122/c5151218-2f29-11e7-927f-0616b4e709b3.jpeg)

easy-rsa should include a subject alternative name by default. For now, you can do it manually using something like this:

    HOSTNAME=myserver.example
    ./easyrsa --subject-alt-name="DNS:$HOSTNAME" build-server-full $HOSTNAME nopass

**Comment by ecrist** [comment]
This is a change that I will make now, and something that is much newer than the 3.0.1 release from 2015.  I'll add this to 3.0.2.

**Comment by ecrist** [comment]
I will point out that this is already supported in 3.0, by passing --subject-alt-name=SAN-STRING.  Since this is the case, I'm going to push this automatic detail to 3.1.
