### ISSUE TITLE
Static key generation (tls-auth)

### ISSUE THREAD

**Issue by Diaoul** [OpenVPN/easy-rsa#127]
Since it is possible to perform ["Hardening OpenVPN Security"](https://openvpn.net/index.php/open-source/documentation/howto.html) it would be a nice addition to have the equivalent of `openvpn --genkey --secret ta.key` built-in easy-rsa.

**Comment by ecrist** [comment]
Why do you need/want EasyRSA to do this, when OpenVPN can do it already?

**Comment by kobuki** [comment]
I know 2 good reasons:
* better streamlining/batch scripting/automation using a single tool
* often times the key generation is done on a completely different server or desktop PC than the one OpenVPN is running on - actually this should be recommended

**Comment by guyinsb** [comment]
Static keys may be of interest to those wishing to create a VPN with minimal effort.
My two cents on the simplest way to get openvpn on a Mac:  install Tunnelblick.

**Comment by kobuki** [comment]
The ta.key is not about static access certs/keys. It's about additional TLS authentication. It should always be used, whatever user auth is in place.

**Comment by guyinsb** [comment]
Sorry, I misinterpreted the point of your initial post; but your follow on post clarified the intent.  My post targets for those searching for the bare minimum effort to establish a "road warrior" VPN from a MacBook to a home network (possibly served by a Shibby router).

**Comment by ecrist** [comment]
This is more an OpenVPN issue, not EasyRSA.  Rejecting, for now.
