### ISSUE TITLE
"maybe wrong password" on ./easyrsa build-server-full server nopass - strange behaviour

### ISSUE THREAD

**Issue by nocarea** [OpenVPN/easy-rsa#1276]
Hey, so I'm setting up my certificates and I encounter a strange behaviour.
What I did so far:
```
cp -r /usr/share/easy-rsa /etc/
cd /etc/easy-rsa/
./easyrsa init-pki
./easyrsa build-ca
```
Now, I generate a password "WZoJrte4XlZN!-Wkl" for the CA cert, another one for the PEM and I continue.
```
./easyrsa gen-dh
./easyrsa build-server-full server nopass
```
I confirm with yes and enter the password and I am met with the following error:

```Could not read CA private key from /etc/easy-rsa/pki/private/ca.key
80FBCC0EE97F0000:error:1608010C:STORE routines:ossl_store_handle_load_result:unsupported:../crypto/store/store_result.c:151:
80FBCC0EE97F0000:error:1C800064:Provider routines:ossl_cipher_unpadblock:bad decrypt:../providers/implementations/ciphers/ciphercommon_block.c:124:
80FBCC0EE97F0000:error:11800074:PKCS12 routines:PKCS12_pbe_crypt_ex:pkcs12 cipherfinal error:../crypto/pkcs12/p12_decr.c:86:maybe wrong password
```
"[...]maybe wrong password"

Weird, so I verify, for sure am using the right password.
So I try shortening it to "WZoJrte4XlZN", to see if special characters or length are the issue, but ..same issue.
"123456", works fine so numbers only works. "123456789012", works, also length of 12 confirmed, works.
"asdfghjklzxcvbnm", works fine. All lowercase letters - works, also length of 16 - not an issue.
Is it the uppercase letters ? "W1234wR", works fine.
I try the old one again, maybe I had a typo after all, it doesn't work.
Am I missing something here ?
I'm out of guesses and would appreciate help.

(Debian 12 VPS)
easy-rsa stable 3.1.0-1
openvpn stable 2.6.3-1+deb12u2 amd64

**Comment by nocarea** [comment]
Ok nevermind, I am a donkey. Closing

**Comment by TinCanTech** [comment]
@nocarea Hi.

Not sure what went wrong ?

Also, perhaps `easyrsa --raw-ca build-ca` will help.

**Comment by TinCanTech** [comment]
Thanks for your explanation.

**Comment by nocarea** [comment]
Appreciate you asking ! :-)
