### ISSUE TITLE
Incorrect invocation of "openssl rand"

### ISSUE THREAD

**Issue by uwehermann** [OpenVPN/easy-rsa#138]
I've noticed the following error message recently: "rand: Use -help for summary.":

```
$ ./easyrsa build-client-full test
Generating a 2048 bit RSA private key
...................+++
.............+++
writing new private key to '[...]/easyrsa3/pki/private/test.key.PCGwePrAbV'
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
-----
rand: Use -help for summary.
Using configuration from ./openssl-1.0.cnf
Enter pass phrase for [...]/easy-rsa/easyrsa3/pki/private/ca.key:
Can't open [...]/easy-rsa/easyrsa3/pki/index.txt.attr for reading, No such file or directory
140301176214784:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:74:fopen('[...]/easy-rsa/easyrsa3/pki/index.txt.attr','r')
140301176214784:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:81:
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'test'
Certificate is to be certified until Aug 15 17:26:49 2027 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated
```

Indeed it seems that the call of "openssl rand ..." is using an incorrect parameter order:

```
$ openssl rand -hex 16 -out foo
rand: Use -help for summary.
$ cat foo
cat: foo: No such file or directory
$ openssl rand -hex -out foo 16
$ cat foo
0688a1682bbe18fd0adf61fec65dfeac
```

This is with OpenSSL 1.1.0f. I haven't checked whether this has been changed at some point in upstream openssl or whether this was always the case.

Anyway, after the parameter ordering change I now have 16-byte serial numbers like "0688a1682bbe18fd0adf61fec65dfeac" as it was probably intended to be (?) Before that, I was getting serial numbers like 01, 02, 03 and such, which probably was more or a lucky coincidence(?)

Random other note: There are also a few other errors/warnings in the log:
```
Can't open [...]/easy-rsa/easyrsa3/pki/index.txt.attr for reading, No such file or directory
140301176214784:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:74:fopen('[...]/easy-rsa/easyrsa3/pki/index.txt.attr','r')
140301176214784:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:81:
```

No idea whether those are harmless or not, maybe that's another bug?

**Comment by danhunsaker** [comment]
The first issue looks like a bug.

The other log entries are harmless - it's trying to look up which serials have already been issued, but when none have, that file won't exist yet. It would be nice if upstream would suppress that error in that scenario, but ... Oh well.

**Comment by ecrist** [comment]
Easy-RSA currently supports OpenSSL 1.0x, not OpenSSL 1.1.  We should do some additional version checking, but 1.1 is causing all sorts of problems so I'm going to sit and wait until things settle.

**Comment by uwehermann** [comment]
Just tested an openssl 1.0.1f, that one actually accepts both versions just fine.

**Comment by ecrist** [comment]
I did some testing as well.  I've merged your pull request.  Thanks for the patch!
