### ISSUE TITLE
I didn`t get how to use this utility on the Windows 10. Documents needs to be clarified. 

### ISSUE THREAD

**Issue by aPSopt** [OpenVPN/easy-rsa#140]
I download sources. Go to the "distro\windows", lauch EasyRSA-Start.bat and see error that "bin\sh.exe" is not a internal or external command.
It is possible to use this utility on the Windows 10? If so, could you clarify what I must to do for it usage?

**Comment by TinCanTech** [comment]
The only version of Easy-rsa-3x which has the required binaries is:
https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.0-rc2/EasyRSA-3.0.0-rc2.zip

**Comment by ecrist** [comment]
I will build a new release this evening with the missing binary. 

Eric Crist

**Comment by aPSopt** [comment]
Thx, Eric!

2017-08-21 23:31 GMT+03:00 Eric Crist <notifications@github.com>:

> I will build a new release this evening with the missing binary.
>
> Eric Crist
>
