### ISSUE TITLE
3.0.3 release seems to be a copy of the 3.0.2 release

### ISSUE THREAD

**Issue by djsly** [OpenVPN/easy-rsa#146]
The binary is dated august 21, while it should be august 22. 

Also the Change log was not updated.

**Comment by ecrist** [comment]
You're right, the ChangeLog wasn't updated.  I'll update it in v3.0.4 or whatever comes next.  The v.3.0.2 and v3.0.3 release are in fact different (not every update changes the easyrsa script, but may change the supporting files).

In the case of v3.0.3, a mktemp.exe was included for the benefit of Windows users.

**Comment by djsly** [comment]
I'm looking for the bash of format issue fix "[[ " which I taught was fixed in 3.0.3.  I guess. It was in a previous release and it still present in 3.0.3.  

I tried with master and I was getting the other error that you seemed to have fix today.

**Comment by ecrist** [comment]
What fox are you trying to get?  3.0.3 only released the mktemp binary for Windows. 

Eric Crist

**Comment by ecrist** [comment]
The double square braces fix will be in 3.0.4 I think.   That change was in 4ba461d, after 3.0.3 was published. 

See changes since 3.0.3 here: https://github.com/OpenVPN/easy-rsa/compare/v3.0.3...master

Eric Crist

**Comment by djsly** [comment]
Ok. Thanks. I know where I got confused.  The release pages shows a link with all commits after the release. I though it was all the commits for that release. 

I'll wait for 3.0.4

Thanks
