### ISSUE TITLE
OpenVPN on the Raspberry PI 3 Error | Help

### ISSUE THREAD

**Issue by nt91** [OpenVPN/easy-rsa#147]
Whilst attempting to install OpenVPN on the RPI3 i get the below error which follows by generating.

Im very new to this all so im not 100% what this mean however i understand that much the errors are due to the file not existing or theres no directory as such.

if anyone has any info i would appriciate the help :)
  

-

writing new private key to '/etc/openvpn/easy-rsa/pki/private/ca.key.JStIn6wiNV'
-----

::: CA Complete.

Note: using Easy-RSA configuration from: ./vars
rand: Use -help for summary.
Generating a 2048 bit RSA private key
..................................+++
..........................................................................................................+++
writing new private key to '/etc/openvpn/easy-rsa/pki/private/server.key.pWOV1ZBVBT'
-----
Using configuration from /etc/openvpn/easy-rsa/openssl-1.0.cnf
Can't open /etc/openvpn/easy-rsa/pki/index.txt.attr for reading, No such file or directory
1995675040:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:74:fopen('/etc/openvpn/easy-rsa/pki/index.txt.attr','r')
1995675040:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:81:
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'server'
Certificate is to be certified until Aug 31 18:29:25 2027 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated

Note: using Easy-RSA configuration from: ./vars
Generating DH parameters, 2048 bit long safe prime, generator 2
This is going to take a long time

**Comment by danhunsaker** [comment]
You can ignore that error. The file isn't supposed to exist on first run.

Also, when posting console output on GitHub, you can avoid weird output by wrapping it in triple backticks (```).

**Comment by nt91** [comment]
Thank you for your response, I have successfully created a working VPN connection.

I have another problem where i have generated a .ovpn file this works completely fine on the laptop through tunnelblick however when the cerfticate is imported onto my IOS Device (IPhone 7 Plus, IOS 10.3.3 i get the following error on my iphone; 

OpenVPN Error : PolarSSL: error parsing config private : PKCS5 - Requested encryption or digest alg not available. 

Any suggestion what the problem maybe, The same certificate connects fine as previously mentioned on a Apple Laptop through Tunnelblick.

Once again i would appriciate any help provided.

**Comment by danhunsaker** [comment]
What app are you using to connect?

**Comment by nt91** [comment]
openVPN Application from the Appstore.

**Comment by danhunsaker** [comment]
Right, but is that it's actual title? The only supported one is OpenVPN Connect Client...

**Comment by nt91** [comment]
It's called OpenVPN Connect so I'm guessing you are referring to the same one.

**Comment by danhunsaker** [comment]
Ok, that's good, then. I'm also going to just go ahead and guess you have the latest version installed.

Based on the error message, your certificate is embedded in the config, and is in a format the app doesn't understand.

**Comment by ecrist** [comment]
You need to use the OpenVPN support systems for this troubleshooting. Your question at this point is not about EasyRSA. 

Eric Crist

**Comment by jkbullard** [comment]
On Sat, Sep 2, 2017 at 10:49 PM, nt91 <notifications@github.com> wrote:
>
> I have another problem where i have generated a .ovpn file this works completely fine on the laptop through tunnelblick however when the cerfticate is imported onto my IOS Device (IPhone 7 Plus, IOS 10.3.3 i get the following error on my iphone;
>
> OpenVPN Error : PolarSSL: error parsing config private : PKCS5 - Requested encryption or digest alg not available.

On Sat, Sep 2, 2017 at 11:30 PM, Daniel Hunsaker <notifications@github.com> wrote:
>
> Based on the error message, your certificate is embedded in the config, and is in a format the app doesn't understand.

Tunneblick (I'm the developer) uses the OpenSSL library for encryption and OpenVPN Connect uses a different library, PolarSSL, now known as mBed TLS. OpenSSL suports PKCS#5, PolarSSL doesn't.

If you want to use a configuration on both an iOS device and a Mac, you must use something that is supported by the client software on both devices (and on the server, too, of course).

I'm not familiar enough with OpenVPN Connect to help further. I suggest you ask for advice on the OpenVPN **Users** Mailing List at https://sourceforge.net/p/openvpn/mailman.
