### ISSUE TITLE
easyrsa for Windows can no longer find openssl

### ISSUE THREAD

**Issue by TinCanTech** [OpenVPN/easy-rsa#148]
**openvpn-build** commit https://github.com/OpenVPN/openvpn-build/commit/cb9a523be4df5e5b6ee788bae1315bbfd0e2d9ef breaks all easyrsa on Windows because openvpn binaries (including openssl) are no longer added to PATH during install.

**Comment by ecrist** [comment]
This doesn't seem like an EasyRSA problem, but actually a problem with how OpenVPN is packaging and installing the software.

**Comment by mattock** [comment]
@TinCanTech : good catch. I believe a typical way to handle this is to have "EasyRSA command-prompt" shortcut in the Start menu with the correct PATH. That way system path does not have to be modified.

**Comment by TinCanTech** [comment]
As there is some debate as to who this problem belongs to it seems only sensible to keep further discussion in this thread https://github.com/OpenVPN/openvpn-build/pull/103
If/when a solution is found then this EasyRSA issue #148 can be closed.

**Comment by mattock** [comment]
FYI: proposed fix for easy-rsa-old: https://github.com/OpenVPN/easy-rsa-old/pull/5

**Comment by mattock** [comment]
@TinCanTech : care to review the [proposed fix](https://github.com/OpenVPN/easy-rsa-old/pull/5) for easy-rsa-old? I need to build Windows installers tomorrow and would like to have someone review and test the changes before I merge them. And time is running short as I have to build new Windows installers tomorrow.

**Comment by nim** [comment]
I have this problem in openvpn-install-2.4.6-I602 ...

**Comment by Romancha** [comment]
same issue on openvpn-install-2.4.7-I607

**Comment by ecrist** [comment]
This is an issue with the OpenVPN installer, not EasyRSA
