### ISSUE TITLE
breaking change to default values in bugfix releases

### ISSUE THREAD

**Issue by majewsky** [OpenVPN/easy-rsa#152]
In 534f67345997603e3b1fbf6b673bbaa65937019e, the default value for the `EASYRSA` variable was changed from `$PWD` to the directory containing the `easyrsa` binary, usually `/usr/bin`. This breaks a lot of other assumptions in my workflow, for example `$EASYRSA/openssl-1.0.cnf` used to work when `EASYRSA` defaulted to `$PWD` (which is `/etc/easy-rsa` for me). Now it's looking for `/usr/bin/openssl-1.0.cnf` which is nonsensical.

Of course I can easily work around this by `export EASYRSA=/etc/easy-rsa`, but there's a lot that's unprofessional about what happened:

1. Changes like this should be announced as backwards-incompatible in the changelog and the release notes.
2. Changes like this should never happen in bugfix releases. Even if you don't follow semver.org, having a breaking change in a bugfix release is extremely surprising and unexpected.

As a result of this issue, I'd like:

1. clear documentation in the changelog about what was changed and why, and
2. optionally, a discussion whether this change should stay in or be reverted.

**Comment by ecrist** [comment]
I will investigate this further. I didn't see a breakage by accepting this fix, so any breakage was unintended. 

Updates to the change log will become more consistent and verbose.

I'm not familiar with semver.org and don't/won't promise following their standard. I won't make promises on your demands, but endeavor to improve updates and releases in the future. 

Eric Crist

**Comment by majewsky** [comment]
Thanks for your swift and professional reply.
