### ISSUE TITLE
easyrsa init subcommand failed on macOS high sierra.

### ISSUE THREAD

**Issue by hiroyuki-sato** [OpenVPN/easy-rsa#155]
Hello, maintainers. 

`easyrsa init` command failed on macOS high sierra.

## Reproduce step

```
git clone https://github.com/OpenVPN/easy-rsa.git
```

* id: c75e74a6972864557e6f4bd2e79a74b0b3196951

```
cd easy-rsa/easyrsa3
./easyrsa init-pki
140736139559816:error:0E065068:configuration file routines:STR_COPY:variable has no value:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/conf/conf_def.c:573:line 3

Easy-RSA error:

Missing or invalid OpenSSL
Expected to find openssl command at: openssl
```

## Workaround

It works fine with OpenSSL

Use /usr/local/Cellar/openssl/1.0.2l/bin/openssl 

```
you may now create a CA or requests.
Your newly created PKI dir is: /tmp/easy-rsa/easyrsa3/pki
```

## Additional info

Simply the following command reproduce this issue.

```
cd easy-rsa/easyrsa3
env OPENSSL_CONF=./openssl-1.0.cnf openssl version
140736139559816:error:0E065068:configuration file routines:STR_COPY:variable has no value:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/conf/conf_def.c:573:line 3
```

macOS high sierra use LibreSSL.

```
openssl version
LibreSSL 2.2.7
```

Best regards.

**Comment by hiroyuki-sato** [comment]
Duplicate #7478

**Comment by alexstaj** [comment]
I did brew install openssl but eas-rsa is still trying to use the libressl included in high sierra.  how did you change this?

**Comment by hiroyuki-sato** [comment]
Hello, @alexstaj 

Set `EASYRSA_OPENSSL` environment variable explicitly. 
https://github.com/OpenVPN/easy-rsa/issues/74#issuecomment-334691069

**Comment by bhall7** [comment]
The only problem is that /usr/local/Cellar/openssl/1.0.2l/bin/openssl doesn't seem to exist (nor does the folder /usr/local/Cellar on my machine, for that matter, running macOS 10.13.4).

**Comment by hiroyuki-sato** [comment]
Hello, @bhall7 

The built-in `/usr/bin/openssl` is LibreSSL not OpenSSL.
I installed OpenSSL with [homebrew](https://brew.sh)

**Comment by ecrist** [comment]
EasyRSA 3 does not support LibreSSL at this time due to LibreSSL removing support for generating certificates using environment variables.   This is on my list of things to fix, but will be part of v3.1.0, and not part of v3.0.5.

**Comment by ecrist** [comment]
For my own sanity, here's another project that had to fix a similar issue:

- https://jira.opencord.org/browse/CORD-2350
- https://gerrit.opencord.org/#/c/7497/

**Comment by bhall7** [comment]
In hindsight, I should've attempted to install OpenSSL via homebrew. Shamefully, what I ended up doing was launching a Windows VM on Mac, installing Cygwin (with OpenSSL), and running it from there. (facepalm)

**Comment by bhall7** [comment]
Yeah, understood. I wasn't able to get OpenSSL installed for some reason after multiple attempts--so I assumed that Apple just didn't want OpenSSL installed, because each time I tried the install steps, it still only stayed with LibreSSL. I should've used Homebrew. But, the Cygwin workaround worked for me. Hopefully Easy RSA will work with LibreSSL soon. Appreciate all you do!

**Comment by SundialServices** [comment]
Eric, it’s a critical show-stopper for me that EasyRSA doesn’t work on High Sierra. Any idea when it will be ready?

**Comment by ecrist** [comment]
I haven’t had time to look at this but I will try to tomorrow.  Ping me tomorrow with an Gary emoji to motivate me. 🤠

Eric Crist
