### ISSUE TITLE
README-Windows.txt should have 0x0d 0x0a line breaks instead of just 0x0a.

### ISSUE THREAD

**Issue by morrisalex** [OpenVPN/easy-rsa#156]
The default Windows text editor is Notepad, which doesn't cope with 0x0a line breaks. All of the text runs together.

A user would need either to use WordPad (assuming the user is aware that WordPad is included with Windows) or install a third-party text editor (e.g. Notepad++) to read the file.

It would be better if the Windows readme had line breaks already suitable for Notepad, i.e. 0x0d 0x0a.

**Comment by ecrist** [comment]
I agree. There is already a tool that should be converting these in the release packages. Is it not doing that?

Eric Crist

**Comment by ecrist** [comment]
Fixed in fe7cbae.
