### ISSUE TITLE
Gen-crl doesn't support --days option

### ISSUE THREAD

**Issue by jellemdekker** [OpenVPN/easy-rsa#158]
For the PiVPN project, I'm [currently trying to implement](https://github.com/pivpn/pivpn/pull/378) that the certificate revocation list (CRL) expires 10 years from now. I have successfully used `EASYRSA_CRL_DAYS=3650 ./easyrsa gen-crl` to achieve this. I also happened to come across the [`--days=` option](https://github.com/OpenVPN/easy-rsa/blob/c75e74a6972864557e6f4bd2e79a74b0b3196951/easyrsa3/easyrsa#L1125) which seems to modify this variable as well. However, when executing `./easyrsa gen-crl --days=3650`, the `Next Update:` for the CRL is still only 180 days from now. Is this intended behavior? If so, would it be nice to add support for the `--days` option for `gen-crl`? Or is there a better way to achieve my desired behavior?

**Comment by davidh83110** [comment]
To be clarify, the soluction was `EASYRSA_CRL_DAYS=3650 ./easyrsa gen-crl`.

It works, Thanks.

**Comment by amishmm** [comment]
Setting it as environment variable is one time solution and you always need to remember to set it.

More accurate solution would be to put this is `vars` file: (located under `pki` directory)

```set_var EASYRSA_CRL_DAYS 3650```

This will make sure that even in future it will remain so.
