### ISSUE TITLE
openssl-1.1.0.cnf is missing

### ISSUE THREAD

**Issue by ThomasLeister** [OpenVPN/easy-rsa#159]
There is no configuration for openssl 1.1.0, which leads to error messages:

http://forums.debian.net/viewtopic.php?f=3&t=134378

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851059

Users are not sure if the old 1.0 configuration can be used. Please clarify the situation.

**Comment by euphoria360** [comment]
What happened to this issue? I have this problem and i dont think using openssl 1.0.0.cnf is a good idea

**Comment by tsirolnik** [comment]
Currently having this issue
