### ISSUE TITLE
PKI conversion tool for v2 to v3

### ISSUE THREAD

**Issue by QueuingKoala** [OpenVPN/easy-rsa#16]
It would be nice to have a tool script to convert a v2 PKI layout to a v3 layout in a new dir for users wishing to upgrade.

**Comment by roehling** [comment]
+1

**Comment by ecrist** [comment]
The goal is to have this for the 3.0 release, but I don't consider it a blocker.  This might be a 3.0.1 or a 3.1 feature.

**Comment by sargue** [comment]
Now that Debian 10 has switched to easy-rsa 3 this would really be useful.

Please.

**Comment by TinCanTech** [comment]
Please see https://github.com/OpenVPN/easy-rsa/commit/07ec923be13d45d1592e93f08a0157dbc7ed3b4c
Not released yet but imminent. 
All questions and feedback welcome. Please test if you can.
