### ISSUE TITLE
Connecting DB remotely using VPN for .NET Application

### ISSUE THREAD

**Issue by Saeedtalib** [OpenVPN/easy-rsa#163]
I  have a local Database installed at my organization. I want the Outer Clients connectivity to this local DB using Remotely by VPN Techniques. 
Please guide me how should i use some Relevant API to access this functionality , Also recommend me some of the best Free VPN's for this purpose.

Your Help would be highly appreciated..

**Comment by ecrist** [comment]
You'll need to find a suitable advice/support forum. This ticketing queue is for issues identified in EasyRSA.
