### ISSUE TITLE
Stable releases

### ISSUE THREAD

**Issue by szepeviktor** [OpenVPN/easy-rsa#166]
Please consider adding - at least basic - functional tests.

For example:

- ./easyrsa init-pki
- ./easyrsa build-ca nopass
- ./easyrsa build-server-full noapp

Then test the certs!

**Comment by ecrist** [comment]
Some automated testing is in order. I plan on implementing this in the future.  Thanks for creating the ticket. 

Eric Crist

**Comment by TinCanTech** [comment]
hold my beer ..

**Comment by szepeviktor** [comment]
holding....

:)

**Comment by ecrist** [comment]
We have automated testing at this point, so I'll close this ticket.  :)
