### ISSUE TITLE
missing dependencies in easyrsa script

### ISSUE THREAD

**Issue by amkhlv** [OpenVPN/easy-rsa#167]
line 963:  `type="$1" name="$2" in_file format'

--- my computer does not recognize the command `in_file` , where does it come from?

similarly, in line 62:  `text opts`  

--- is `text` a command?

I am getting error messages such as `./easyrsa: 62: ./easyrsa: text: not found`

**Comment by ecrist** [comment]
You're using master, which is in development.

**Comment by amkhlv** [comment]
Yes, thank you! I guess I was confused by having to BOTH `git checkout v3.0.3` and pass `--version=3.0.3` to `build/build-dist.sh` (why?)

**Comment by sunshineco** [comment]
Commit 384d407 neglected to fix the other problem reported here:

```
 cmd_help() {
 -	local text opts
 +	text opts
 ```

Which, of course, bogusly attempts to invoke a program named `text` with argument `opts`.

**Comment by ecrist** [comment]
Dammit. You're right.

**Comment by bjoernv** [comment]
The fix is incomplete. This patch is needed too:

```
diff --git a/easyrsa3/easyrsa b/easyrsa3/easyrsa
index 5023ee5..78a45e6 100755
--- a/easyrsa3/easyrsa
+++ b/easyrsa3/easyrsa
@@ -968,7 +968,7 @@ verify_file() {
 # show-* command backend
 # Prints req/cert details in a readable format
 show() {
-       type="$1" name="$2" in_file format
+       type="$1" name="$2"
        [ -n "$name" ] || die "\
 Missing expected filename_base argument.
 Run easyrsa without commands for usage help."
````

**Comment by ecrist** [comment]
I’ve made a commit that should resolve this.  Hoping for a release soon.

Eric
