### ISSUE TITLE
bashisms in easyrsa v3.0.3

### ISSUE THREAD

**Issue by amkhlv** [OpenVPN/easy-rsa#169]
The `easyrsa` script in v3.0.3 has `/bin/sh` shebang, yet it uses bash test `[[ ]]` on line 644.
This is fixed in `master` but not in release. 
Please, prepare a release fixing this problem.

**Comment by ecrist** [comment]
There will be a release when the current code base is stable in master.  Should be soon.

Unless you intend on helping, such direction is not appreciated.

Thanks,

Eric
