### ISSUE TITLE
`nopass` not honored anymore

### ISSUE THREAD

**Issue by calve** [OpenVPN/easy-rsa#176]
Hi, not quite sure but it looks like 7f2dda12c232620eb0a2fbf3320b83574c576c3b introduced a bug where the `nopass` option is not honored anymore.

```
$ ./easyrsa build-ca nopass
Enter New CA Key Passphrase: 
Re-Enter New CA Key Passphrase: 

Easy-RSA error:

Passphrases do not match.
```

As you can see, the script ask for a Passphrase despite the `nopass` option. 

Please let me know if I can provide any extra information

**Comment by ecrist** [comment]
Gah, that's an error on my part.

**Comment by calve** [comment]
On another hand, I would suggest to add support for openssl `-passin argument` options, which would allow administrators to batch password generation. `-passin` allow passphrase to be set by a command line argument, external file, environment variable, or stdin.

I can provide a patch if needed

**Comment by windyboy** [comment]
got same problem on my debian 9 server

**Comment by mistriel** [comment]
Last time i checked,
if you in `--batch` mode `nopass` works fine.

**Comment by MrKroo** [comment]
Not for me, `EASYRSA_BATCH` set to "yes" and `nopass` and not honored.
