### ISSUE TITLE
Randomize Serial number in sign_req() breaks previous behavior

### ISSUE THREAD

**Issue by jamesyonan** [OpenVPN/easy-rsa#177]
A recent patch to sign_req() unconditionally randomizes the serial number which breaks use cases that expect the serial number to increment sequentially.

**Comment by ecrist** [comment]
What version of EasyRSA are you comparing this to?

**Comment by jamesyonan** [comment]
This merge changed the behavior from a linear incrementing serial number to randomization.  This breaks a lot of our use cases including those that require an incrementing serial number (as was the behavior of easy-rsa since the time I originally developed it) as well as those that require the serial number to fit in a uint64 type.

commit f480de2b7772817bb7196c6be66e2b20af8bb7f1
Merge: 5a429d2 e9e8e27
Author: Eric Crist <ecrist@secure-computing.net>
Date:   Fri Jun 30 18:09:53 2017 -0500

    Merge pull request #133 from mschmitt/no-smime
    
    Default SAN in server certs, serial randomization

commit e9e8e272e0eb5225ecfb0d8a0953a5b480c5e85d
Author: Martin Schmitt <mas@scsy.de>
Date:   Fri Jun 30 17:04:31 2017 +0200

    Moved @ValdikSS's serial randomization to sign_req

**Comment by ecrist** [comment]
alright, I've added EASYRSA_RAND_SN to vars which defaults to "yes".  Setting this to "no" changes the behavior back to the old method.  This can also be set in the environment.  It is possible to switch back and forth between random and incremental, but the increments will start from the most recent serial number, regardless of format:

```
V	220501114230Z		01	unknown	/CN=client1
V	220501114237Z		02	unknown	/CN=client2
V	220501114241Z		03	unknown	/CN=client3
V	220501114307Z		2BAA5F8CB0A303DE2E20585C5C2C333F	unknown	/CN=client4
V	220501114326Z		2BAA5F8CB0A303DE2E20585C5C2C3340	unknown	/CN=client5
V	220501114431Z		2BAA5F8CB0A303DE2E20585C5C2C3341	unknown	/CN=client6
V	220501114506Z		F0A22B904510942731D6963F98813A0E	unknown	/CN=client7
V	220501114517Z		9D6E9411674E7CF88B467841B76352FB	unknown	/CN=client8
V	220501114521Z		570D5C69E0D54CA13282F8ABD1F2C926	unknown	/CN=client9
V	220501114530Z		570D5C69E0D54CA13282F8ABD1F2C927	unknown	/CN=client10
```

In the above I started with EASYRSA_RAND_SN set to no and created the first three certificates.  Then I set EASYRSA_RAND_SN to yes and generated a fourth.  I switched back to incremental and generated the fifth and sixth certificates, no increments in hex.  I generated a couple more random serials, then generated a couple more incremental serials.
