### ISSUE TITLE
Alternative passphrase input support

### ISSUE THREAD

**Issue by QueuingKoala** [OpenVPN/easy-rsa#18]
OpenSSL supports multiple input methods for passwords, such as stdin, files, pipes, etc. This feature can offer improved flexibility and allow batching multiple operations requiring passphrase input.

**Comment by mbainter** [comment]
Any reason not to just allow people to pass extra options on the command line to be passed directly to the command?

**Comment by ecrist** [comment]
Passing a passphrase on the command line is inherently insecure as anyone with shell access, or access to list running processes, could retrieve the list of command line options, which would include the passphrase.  A file or stdin is are better alternatives.

**Comment by dx9** [comment]
+1

**Comment by hugoduncan** [comment]
Alllowing extra options to be passed to the openssl command would allow a passphrase to be passed as a file, via stdin or via an env var (as well as directly).

**Comment by ecrist** [comment]
> On Oct 5, 2015, at 13:11:41, Hugo Duncan <notifications@github.com> wrote:
> 
> Alllowing extra options to be passed to the openssl command would allow a passphrase to be passed as a file, via stdin or via an env var (as well as directly).
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenVPN/easy-rsa/issues/18#issuecomment-145619403>.
> 

I’m concerned with overall support for such a feature.  It sounds simple, but making sure things continue to work with new options and via automation is difficult.  If you are to the level of passing options to openssl directly, why are you even using a project like EasyRSA to manage your PKI?

-----
Eric F Crist

**Comment by hugoduncan** [comment]
>  If you are to the level of passing options to openssl directly, why are you even using a project like EasyRSA to manage your PKI?

In my case, some of the PKI is maintained by automation, but I would like to use EasyRSA to allow simple admin of the PKI by others.

**Comment by TinCanTech** [comment]
Eight year old issue that has been solved.

Please re-open if the problem persists.
