### ISSUE TITLE
Self-Signed certificate file lacks certificate details

### ISSUE THREAD

**Issue by mistriel** [OpenVPN/easy-rsa#180]
I can see some inconsistency with certificate files produced with easy-rsa:
Root CA certificate structure `ca.crt` is a PEM file without any certificate details appended,
whereas subordinate CA's certificates issued as well as generated certificates for server/client are PEM files prefixed by their certificate details.

Is it by design ?
Why ?

**Comment by ecrist** [comment]
I believe this is the default behavior for OpenSSL.  Looking at the source, I'm not seeing anything options added between the CA generation routines compared to the normal request signing code that would change the output format.

You can get the certificate details by simply running an OpenSSL command manually:

openssl x509 -noout -text -in ca.crt

**Comment by ecrist** [comment]
I will close this issue after March 1st if there's no reply.

**Comment by TinCanTech** [comment]
At least partially addressed by https://github.com/OpenVPN/easy-rsa/pull/118

**Comment by TinCanTech** [comment]
In fact, a `sub-ca` is created without the certificate text. Only after being signed is the test prepended.
