### ISSUE TITLE
`build-ca` fails (silently) with passwords containing '%' characters

### ISSUE THREAD

**Issue by Antagonym** [OpenVPN/easy-rsa#181]
When using a password containing one or more '%' characters during the `build-ca` command, the following error message appears (assuming the character directly following the '%' was a '~'):

    ./easyrsa: 482: printf: %~: invalid directive

The root certificate generation then proceeds normally and *seems* to succeed, except the resulting certificate does not have the expected password, which becomes apparent when attempting to sign a CSR with it.

This is likely due to the following code line:

    L482: printf "$kpass" > "$out_key_pass_tmp

`printf` tries to '%' for substitution, which is not desirable in this case.

**Comment by ecrist** [comment]
I’m not handling the input correctly here. Will fix this tonight.
