### ISSUE TITLE
Separate key/request generation

### ISSUE THREAD

**Issue by QueuingKoala** [OpenVPN/easy-rsa#19]
Separating the backend process of key and request generation allows additional flexibility and workflows.

De-coupling these steps allows more abstraction in how each one is performed. In particular, this may be a benefit with future PKCS11 smart card integration or other advanced workflows. Another possible use-case is creating an updated request from an existing keypair.

**Comment by TinCanTech** [comment]
This is no longer a viable concern for Easy-RSA.
