### ISSUE TITLE
Create client from intermediate?

### ISSUE THREAD

**Issue by PermaNulled** [OpenVPN/easy-rsa#190]
I see no option to create a client based on an intermediate CA? Is this a feature that's lacking or am I missing something?

**Comment by PermaNulled** [comment]
So I've noticed build-ca has "nopass" and "subca" but if you try to use either of these options they appear to do nothing currently, nopass I still get prompted for a password and was able to confirm the private key was still exported with a password.

subca and you get told the ca already exists.

**Comment by kaspergrubbe** [comment]
Please update here if you manage to find a solution to this.

**Comment by PermaNulled** [comment]
The solution I found was basically generating an root creating a signing request and signing it as an intermediate, moving the pki folder to root_pki, reinitiating an root (initpki) and then copying the newly signed intermediate into the new pki folder and signing a client cert under it.

**Comment by saissemet** [comment]
Hello @viharm, did that really work? Could that depend on the version in use?

I tried to follow your steps one by one. Here's what I did:

**[Root CA]
./easy-rsa init-pki
./easy-rsa build-ca nopass**

**[Intermediate CA]
./easy-rsa initi-pki
./easy-rsa build-ca nopass subca**

At first, I tried to import the **ca.req** using scp, but then I realized that easy-rsa comes with an "import-req" option. So I tried to do that:

**[Root CA]
./easy-rsa [Intermediate CA IP]:/path/pki/reqs/ca.req ca**

**Output: The input file does not appear to be a certificate request. Aborting import..
Offending file: [Intermediate CA IP]:/path/pki/reqs/ca.req ca**

I'm not quite sure if I'm doing this right or missing some obvious part.. Thanks!
