### ISSUE TITLE
some Variables in "Vars" get ignored in Version 3.0.5 

### ISSUE THREAD

**Issue by Linklon** [OpenVPN/easy-rsa#193]
In Version 3.0.5
When i was changing the set_var EASYRSA_KEY_SIZE to 4096 in the vars file this did not work. Even forcing the bithlength to 4096 with the command  "./easyrsa --keysize=4096 build-ca" had no effect and the default bitlength of 2048 has been taken.
In Version 3.0.4 seems everything to work

**Comment by Antagonym** [comment]
I have a pending PR (#186) that should fix this issue among other things.

**Comment by ecrist** [comment]
This should be resolved now since 6e35636.
