### ISSUE TITLE
Client generated has incorrect purpose settings

### ISSUE THREAD

**Issue by yookoala** [OpenVPN/easy-rsa#201]
The [easyrsa3/x509-types/client](https://github.com/OpenVPN/easy-rsa/blob/ff07d754f54c83787cd3e8179c89c762178d16f6/easyrsa3/x509-types/client) file has no `nsCertType` definition. When the generated client certificate (with command `easyrsa gen-req client nopass`) is using in openvpn, server would have problem verifying the certificate:

```
VERIFY ERROR: depth=0, error=unsupported certificate purpose: CN=client
```

You can read a more detailed description of the issue [here](https://serverfault.com/questions/905712/openvpn-client-certificate-error-with-unsupported-purpose).

After adding this line to the `client` config file:

```
nsCertType = client
```
`easyrsa` will generate correct certificate for openvpn to use.

**Comment by TinCanTech** [comment]
Are you aware of the `vars` file element:
```
# Support deprecated "Netscape" extensions? (choices "yes" or "no".) The default
# is "no" to discourage use of deprecated extensions. If you require this
# feature to use with --ns-cert-type, set this to "yes" here. This support
# should be replaced with the more modern --remote-cert-tls feature.  If you do
# not use --ns-cert-type in your configs, it is safe (and recommended) to leave
# this defined to "no".  When set to "yes", server-signed certs get the
# nsCertType=server attribute, and also get any NS_COMMENT defined below in the
# nsComment field.

#set_var EASYRSA_NS_SUPPORT	"no"
 set_var EASYRSA_NS_SUPPORT	"yes"
```

The subsequent certificate has the following purpose:
```
            X509v3 Extended Key Usage: 
                TLS Web Client Authentication
            X509v3 Key Usage: 
                Digital Signature
            Netscape Comment: 
                Easy-RSA Generated Certificate
            Netscape Cert Type: 
                SSL Client
```

**Comment by yookoala** [comment]
Thanks.

The package from my distro (Fedora 27) did not include the vars.example file thus I didn't know about it.

Will close this issue now.

**Comment by TinCanTech** [comment]
I would have reported the missing file but according to this:
https://fedora.pkgs.org/27/fedora-updates-i386/easy-rsa-3.0.3-1.fc27.noarch.rpm.html
-- `vars.example` is included in the package.

**Comment by TinCanTech** [comment]
Also, an up-vote on Serverfault for the correct answer would be highly appreciated.

**Comment by yookoala** [comment]
The example is in `/usr/share/doc/easy-rsa/vars.example`, while the wiki told us to use files in `/usr/share/easy-rsa/`...

Classic "your princess is in another castle" situation XD.
