### ISSUE TITLE
Error in build-key-server in openvpn 2.4.5 in Windows 10 x64

### ISSUE THREAD

**Issue by 1Jesper1** [OpenVPN/easy-rsa#206]
_Using configuration from openssl-1.0.0.cnf
Loading 'screen' into random state - done
default is an unsupported message digest type
8164:error:02001002:system library:fopen:No such file or directory:.\crypto\bio\bss_file.c:172:fopen('keys/index.txt.attr','rb')
8164:error:2006D080:BIO routines:BIO_new_file:no such file:.\crypto\bio\bss_file.c:175:
8164:error:0E078072:configuration file routines:DEF_LOAD:no such file:.\crypto\conf\conf_def.c:195:
Could Not Find C:\Program Files\OpenVPN\easy-rsa\keys\*.old_

Fix was to change:
default_md = default to **md5**

**Comment by Jacksonong2011** [comment]
Hi Jesper, 

I have the same problem. did you managed to solve this? I am trying to setup a home vpn. 

Thanks

**Comment by 1Jesper1** [comment]
@Jacksonong2011 use `default_md  = sha256    `

**Comment by Jacksonong2011** [comment]
Hi thanks got it. work prefectly now. :)
