### ISSUE TITLE
openvpn-install-2.4.6-I602 openssl is not exsist

### ISSUE THREAD

**Issue by MBurtsev** [OpenVPN/easy-rsa#207]
After install lasteted version i try run build-ca.bat where i get exception lack of openssl. In the end, I installed a program that does not work. Not surprisingly, OpenVpn has such a weak usage in the world.

**Comment by ecrist** [comment]
What is the error you are seeing?

**Comment by nim** [comment]
Openssl is not recognized as an internal or external command, an executable program or a batch file.

**Comment by ecrist** [comment]
This is a problem with the OpenVPN installer not delivering the OpenSSL binary. Did you use default settings when installing?  This is not a problem or bug is EasyRSA. 

Eric Crist

**Comment by ecrist** [comment]
My previous comment is not quite correct.  This issue is manifested when LibreSSL is present instead of OpenSSL.  LibreSSL does not allow the use of environment variables to pass data to the certificate routines.

This change is going to require some core changes to how EasyRSA processes variables.

**Comment by TinCanTech** [comment]
> After install lasteted version i try run **build-ca.bat** 

Not Easyrsa v3
