### ISSUE TITLE
Running build-server-full on a filename_base with spaces leads to errors 

### ISSUE THREAD

**Issue by BastiPaeltz** [OpenVPN/easy-rsa#208]
Hey,

I think this only happens in v3.0.4 .
If you run `./easyrsa build-server-full 'server@Company Foo Limited.com' nopass` it will subsequently error because of [this](https://github.com/OpenVPN/easy-rsa/blob/v3.0.4/easyrsa3/easyrsa#L660) line.
The filename is not quoted so only a part of it is passed to the function.

**Comment by ecrist** [comment]
This issue is already resolved in the v3.0.5 branch, which will be released soon.
