### ISSUE TITLE
"the displayed note  when source vars" should be removed

### ISSUE THREAD

**Issue by angelgjj1987** [OpenVPN/easy-rsa#209]
Once I need to revoke a former colleague's vpn certificate, and before I do the revoke option, I need to source the vars, but a note given by system like this,

[ NOTE: If you run ./clean-all, I will be doing a rm -rf on /home/keyservice/easyrsa/keys" ]

I would not run that ./clean-all option if I didn't notice that note,but after the note came up,I really did that naturally while without thinking carefully, and ... oops :(  That command help delete the ca.crt, I can't sign vpn keys for others anymore which brings lots of trouble.

So, to avoid more mistakes , I think this note is unnecessary ,should be removed here.

When somebody does run the command "./clean-all" ,and we can give note "Please be sure very careful  with the ./clean-all option,or else you will delete the ca.crt which makes you can't sign up vpn keys for others "  

Appreciate if you the great maintainer can see this and wish you can take it into account.

**Comment by ecrist** [comment]
What version of EasyRSA are you using?  The 3.x version does not require you to source your vars file any longer.  We are not making changes to the 2.x version.

**Comment by angelgjj1987** [comment]
@ecrist  Oh,you are right, it is really 2.7 version, so I got it ,and appreciate your reply.  
^_^
