### ISSUE TITLE
How to create certificate interactively?

### ISSUE THREAD

**Issue by MatthiasLohr** [OpenVPN/easy-rsa#216]
Hello,

When using the mode "org" instead of "cn_only" - is it possible to interactively give all the certificate details? Currently it's filled with my default values defined in vars, but I would like to define them individually for every certificate I create. Is there any option I missed?

Best regards
Matthias

**Comment by ThomasCr** [comment]
did you try to not set the defaults?

**Comment by TinCanTech** [comment]
> When using the mode "org" instead of "cn_only" - is it possible to interactively give all the certificate details? Currently it's filled with my default values defined in vars, but **I would like to define them individually for every certificate I create**.

You can define them.

>  Is there any option I missed?

No.

**Comment by MatthiasLohr** [comment]
Not sure what I did wrong, now it works.
