### ISSUE TITLE
gen-req server/client/ca options

### ISSUE THREAD

**Issue by eugene-bright** [OpenVPN/easy-rsa#217]
I've examined the code and now I can see that proper key usage is set only on the `sign-req` step.
I have external CA and need proper request file with all extensions set.

Could you consider extending `gen-req` in such a way to accept `crt_type` option?

**Comment by TinCanTech** [comment]
> Could you consider extending `gen-req` in such a way to accept `crt_type` option?

That would be the **opposite** of how Easy-RSA works.
