### ISSUE TITLE
Cannot sign server crt on Windows

### ISSUE THREAD

**Issue by Anvolne** [OpenVPN/easy-rsa#224]
When I try to sign a server crt with easyrsa on windows, it just errors out on the 'basename' and 'cut' commands. There are no excecutables in the \bin folder with this name.

Also there is a 'No such file or directory' error with 'index.txt.attr'

Console output:

> Type the word 'yes' to continue, or any other input to abort.
  Confirm request details: yes
C:/Program Files/OpenVPN/EasyRSA-3.0.4/easyrsa[1277]: basename: not found
C:/Program Files/OpenVPN/EasyRSA-3.0.4/easyrsa[1277]: cut: not found
req: Cannot open input file C:/Program, No such file or directory
req: Use -help for summary.
path = C:/Program Files/OpenVPN/EasyRSA-3.0.4/pki/issued/asus_server.crt.XXXXXXXXXX
lpPathBuffer = C:\Users\atill\AppData\Local\Temp\
szTempName = C:\Users\atill\AppData\Local\Temp\tmp5523.tmp
path = C:\Users\atill\AppData\Local\Temp\tmp5523.tmp
fd = 3
Using configuration from C:/Program Files/OpenVPN/EasyRSA-3.0.4/openssl-easyrsa.cnf
Can't open C:/Program Files/OpenVPN/EasyRSA-3.0.4/pki/index.txt.attr for reading, No such file or directory
30724:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:74:fopen('C:/Program Files/OpenVPN/EasyRSA-3.0.4/pki/index.txt.attr','r')
30724:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:81:
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'ASUS Router'
ERROR: adding extensions in section default
30724:error:2206D06D:X509 V3 routines:X509V3_parse_list:invalid null value:crypto/x509v3/v3_utl.c:352:
30724:error:22097069:X509 V3 routines:do_ext_nconf:invalid extension string:crypto/x509v3/v3_conf.c:93:name=subjectAltName,section=DNS:
30724:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:crypto/x509v3/v3_conf.c:47:name=subjectAltName, value=DNS:
Easy-RSA error:
signing failed (openssl output above may have more detail)

**Comment by Anvolne** [comment]
Okay, so I fixed the problem by:
1. going to [http://gnuwin32.sourceforge.net/packages/coreutils.htm](url) and downloading the **Binaries** and **Dependencies** (the 2 Zip archives, and not the Setup)
2. unzipping the basename.exe and cut.exe from the Binaries Zip into the /bin directory
3. unzipping the 2 DLLs from the Dependencies Zip into the /bin directory
4. modifying the easyrsa file in the "root" directory (in my case the "EasyRSA-3.0.4" directory) at:
line 660: `	default_server_san $req_in` to `default_server_san "$req_in"` (notice the quotes)

**Comment by ecrist** [comment]
If you had to download the dependencies, this should remain open until we can investigate it further.

**Comment by Anvolne** [comment]
The line that causes the error is number 657 in the file easyrsa:
`sname=$(basename $req_in | cut -d. -f1)`
because the shell does not find the basename and cut commands, it errors out

**Comment by ecrist** [comment]
I'm going to close this.  We don't use basename in the v3.0.5 branch.
