### ISSUE TITLE
TLS 1.3

### ISSUE THREAD

**Issue by obendev** [OpenVPN/easy-rsa#228]
Hey, I'm not quite sure if openvpn itself needs to be updated or if we can generate the certificates with easy-rsa, so OpenVPN will use TLS 1.3.

But since TLSv1.3 has a [RFC doc](https://tools.ietf.org/html/rfc8446) now and openssl released version 1.1.1 with TLS 1.3 support, will easy-rsa also get TLS 1.3 use the new openssl Version?

I'm not able to make an issue in the OpenVPN repo so I will ask this here as well:
OpenVPN has the `tls-version-min` option, does this also relay on the global installed openssl version on your system or does OpenVPN needs to be updated to support TLS 1.3?

**Comment by ecrist** [comment]
There is no updated to EasyRSA required.  EasyRSA only handles certificate management, and not the TLS protocol itself.  The protocol is handled by the library OpenVPN uses, so an update would be necessary to OpenVPN and to the library (OpenSSL or LibreSSL).

A request for support of TLS 1.3 is already in the OpenVPN bug tracker here: https://community.openvpn.net/openvpn/ticket/1080 <https://community.openvpn.net/openvpn/ticket/1080>

-----
Eric F Crist
Sr Integration Engineer
Author: Troubleshooting OpenVPN
Co-Author: Mastering OpenVPN

**Comment by obendev** [comment]
Oh okay, thank you for the quick and detailed information!
I'm really not an expert on this topic.

I saw this ticket before, but it is closed. Now openssl 1.1.1 got released and I'm not sure if it does make sense to open a new ticket by myself?
Last comment was

> I'm closing this ticket because it works fine if you recompile. If anyone wants to further investigate run time checks, feel free to open a feature request ticket.

Does that mean I can open a new ticket with TLS 1.3 request (bco openssl 1.1.1 release) without making anyone angry bco "double posting"?

**Comment by ecrist** [comment]
Looking at that comment, it appears that if you compile with a library that supports TLS 1.3, it should work.  That does mean both the client and server need to support the protocol, as it will always be negotiated down to the least capable endpoint.

-----
Eric F Crist
Sr Integration Engineer
Author: Troubleshooting OpenVPN
Co-Author: Mastering OpenVPN

**Comment by obendev** [comment]
Okay. So there are yet no plans for OpenVPN to be updated to openssl 1.1.1?

**Comment by ecrist** [comment]
That’s an entirely different question.  Have you looked in the issue tracker for anything related to OpenSSL 1.1.1?  Have you tried compiling OpenVPN against OpenSSL 1.1.1?

-----
Eric F Crist
Sr Integration Engineer
Author: Troubleshooting OpenVPN
Co-Author: Mastering OpenVPN

**Comment by obendev** [comment]
Okay, I get your point.
Well maybe I will open a ticket for OpenVPN to ask about openssl support.
I think I'm not able to compile OpenVPN all by myself so thats all I can do right now.
