### ISSUE TITLE
stty not supported by supplied win32 shell

### ISSUE THREAD

**Issue by lvogt** [OpenVPN/easy-rsa#230]
While building a new CA ,the passphrase is read in using read. Since 3.0.5 the output is suppressed using "stty -echo". 

However the supplied win32 shell does not support this command resulting in error messages and visible output of the supplied passphrase.

Before switching to stty, "read -s varName" was used, which also does not suppress the output, but at least does not spam additional error messages...

**Comment by ecrist** [comment]
This is a problem and I'll work on getting it fixed in v3.0.6.
