### ISSUE TITLE
Possible to use SHA3?

### ISSUE THREAD

**Issue by eccgecko** [OpenVPN/easy-rsa#235]
Would it be possible to use some of the new SHA3 signing algorithms when using easy-rsa against OpenSSL 1.1.1? I tried changing `set_var EASYRSA_DIGEST` to sha3-256 but it was unable to build the CA. How would I go about using SHA3 algorithms? Would I need to edit the openssl-easyrsa.cnf file?

**Comment by ecrist** [comment]
There are no current plans to build support for sha3 into EasyRSA.  Not to say it won't happen in the future, but see [this Stack Exchange answer](https://security.stackexchange.com/questions/152360/should-we-be-using-sha3-2017/153058#153058) for more details.
