### ISSUE TITLE
Set default branch to master

### ISSUE THREAD

**Issue by luizluca** [OpenVPN/easy-rsa#237]
As master should be the default target for PR, it should be project default branch. Currently, a PR will use by default 3.0.6 branch.

**Comment by ecrist** [comment]
No.

master, at times, is very broken.  Lots of users clone master and my email inbox is destroyed.  This was tactical on my part.  Open to other suggestions, or how I can better manage my branches and tags, however.

**Comment by luizluca** [comment]
Yes @ecrist , I have a suggestion. It's based on how I saw easy-rsa development works and from what I see in other OSS projects.

Git makes branching too easy to develop directly in master branch. Normally you would dev in a different "feature' branch and merge into master once it does not break anything. If something is broken in master, fix it as a bug before any new change is introduced. Never keep it intentionally broken.

It looks like easy-rsa have only 2 real release banches (1.x and 2.x). It does not make sense to have a "dot release" branch like 3.0.5 because, once release, it does not receive more commits. It is more likely to be a tag in a branch. You could have a 3.0 branch but it does not seem to be how easy-rsa is developed. What looks like is that easy-rsa is develop in a mix of temporary 3.0.x branch and master, which exchange patches from and to. It will only make things more complex. BTW, it is currently unsynchronized.

My suggestion:

1) get rid of "dot release branches". Use only tag.
2) make master the default branch. Eventually tag a commit as a 3.0.x release.
3) create unstable or "feature xyz" branch(es) for experimental stuff. It does not even need to be in easy-rsa project. It could be in your personal github fork.
4) once a version turn into "maintanance mode", branch it. I would use branch names like 'easy-rsa-3.0' and not 'release/1.x'. Only fixes get into this branch. Eventually tag a commit as a release.
