### ISSUE TITLE
Travis is broken during shellcheck installation

### ISSUE THREAD

**Issue by luizluca** [OpenVPN/easy-rsa#239]
I might be an easy fix, like changing the debian version or changing it to ubuntu.
Shellcheck can also be directly downloaded. No need for a package.

**Comment by luizluca** [comment]
Travis use probably never took off because easyrsa wasn't scriptable.
I'm already using #242 for some batch testing and it works very well.

Testing compatibility with Windows and FreeBSD is still an issue. Besides bash, ash could also be easily used for compatibility test. Travis can also test on MacOSX. Is FreeBSD Bourne shell-compatible sh available there?

**Comment by ecrist** [comment]
Travis use hasn’t taken off because I was having problems getting shellcheck working correctly.

-----
Eric F Crist
Sr Integration Engineer
Author: Troubleshooting OpenVPN
Co-Author: Mastering OpenVPN

**Comment by TinCanTech** [comment]
Can we close this please ?

**Comment by ecrist** [comment]
Yeah, closing.  Travis has been working well for a while now.
