### ISSUE TITLE
Can I specify expiration date for a client?

### ISSUE THREAD

**Issue by jalalsfs** [OpenVPN/easy-rsa#252]
Hello there,
When I create any client/user, the default expiration date for them is 3650 days,
I tried searching, I found that I can do
```
export KEY_EXPIRE=30
./easyrsa build-client-full user1
```
but it doesn't work,
Any way to do it with easyrsa tool?

**Comment by jalalsfs** [comment]
From IRC channel, Ecrist, give the solution by these steps:
```
export EASYRSA_CERT_EXPIRE=30
./easyrsa build-client-full user10
```
With this example the validation date of the user certificate is 30 days.

**Comment by nlee88** [comment]
Is there a easyRSA command to revoke a client cert for ovpn?

**Comment by ecrist** [comment]
Specific to OpenVPN, no. You can revoke it and then give the CRL to OpenVPN to handle. Alternatively you can create a current config directory and disable the specific client. This is out of scope for EasyRSA.

Eric F Crist
________________________________
