### ISSUE TITLE
./easyrsa build-ca can't set ca serial

### ISSUE THREAD

**Issue by lijk8090** [OpenVPN/easy-rsa#256]
serial file can't set ca SN
i want to set CA cert SN to 16 byte
but failed

**Comment by chn475111** [comment]
"$EASYRSA_OPENSSL" rand 16 -hex -out "$EASYRSA_PKI/serial"
use this cmd
but ca serial can't work

**Comment by chn475111** [comment]
需要修改openssl apps/ca.c的源码
CA证书的序列号是在源码内伪随机生成的
