### ISSUE TITLE
Install directory no longer immutable.

### ISSUE THREAD

**Issue by chrisgavin** [OpenVPN/easy-rsa#259]
Hi,

Since #220 was merged, it appears that the installation directory of easy-rsa is no longer immutable. This makes it impossible to do things like extracting it to `/usr/share/easy-rsa/` so it can be used by every user on the system. It now fails with the error `can't create /usr/share/easyrsa/safessl-easyrsa.cnf: Permission denied`. I think this also affects the thread-safety of operations using the same copy easy-rsa on multiple PKI directories.

Is this an expected change?

Thanks,
Chris

**Comment by ecrist** [comment]
What do you mean that it’s not longer possible to extract it to another directory?  We ship a simple zip file that can be placed anywhere you like.  Maybe I’m missing something obvious, but I don’t see how #220 changes installation path in any remarkable way.

Eric F Crist

**Comment by chrisgavin** [comment]
It makes it so files (specifically `safessl-easyrsa.cnf) are written to the installation directory. If you install easy-rsa to `/usr/share/easy-rsa/`, then you either need to be root in order to use it or you have to make the directory writable by all users; neither are really reasonable from a security standpoint.

**Comment by ecrist** [comment]
Not exactly, if you read lines 1183 - 1189 (pasted below), you’ll see that the configuration files in the PKI path are preferred over the non-PKI (aka install) path.

	# Detect openssl config, preferring EASYRSA_PKI over EASYRSA
	if [ -f "$EASYRSA_PKI/openssl-easyrsa.cnf" ]; then
		set_var EASYRSA_SSL_CONF	"$EASYRSA_PKI/openssl-easyrsa.cnf"
		set_var EASYRSA_SAFE_CONF	"$EASYRSA_PKI/safessl-easyrsa.cnf"
	else	set_var EASYRSA_SSL_CONF	"$EASYRSA/openssl-easyrsa.cnf"
		set_var EASYRSA_SAFE_CONF	"$EASYRSA/safessl-easyrsa.cnf"
	fi


Eric F Crist

**Comment by darkmattercoder** [comment]
I experience a problem here, too. I have two likely identical setups, one containing easyrsa from oct 2017, one containing easyrsa from sep 2018. On the older one i can issue 

`easyrsa --days=1 build-client-full client4 nopass` and get a new client

On the younger one, I get

```
 easyrsa --days=1 build-client-full client4 nopass
/usr/local/bin/easyrsa: line 292: can't create /usr/share/easy-rsa/safessl-easyrsa.cnf: Permission denied

Easy-RSA error:

Failed to update /usr/share/easy-rsa/safessl-easyrsa.cnf
```
Both times I use a non-root user to do this.

**Comment by sdellenb** [comment]
I get that error, _even as root_.
```
[root@host EasyRSA-v3.0.6]# ./easyrsa show-ca

Note: using Easy-RSA configuration from: ./vars
sed: can't read /root/install/EasyRSA-v3.0.6/pki/openssl-easyrsa.cnf: No such file or directory

Easy-RSA error:

Failed to update /root/install/EasyRSA-v3.0.6/pki/safessl-easyrsa.cnf
```
If `safessl-easyrsa.cnf` exists in directory `pki`, **_it is truncated_**.
I failed to move my existing PKI from 3.0.5 to 3.0.6.

**Comment by ecrist** [comment]
We're still working on a proper upgrade mechanism from 3.0.5 to 3.0.6.  There were changes made that we didn't consider impacted upgrade.  All our tests were from a clean/empty pki path.

**Comment by sergiomb2** [comment]
Hello
I use epel7 in Centos 7 we got one update from 3.0.3-1.el7 to 3.0.6-1.el7 .

So I moved my existing PKI from 3.0.3 to 3.0.6 and

    sed: can't read./pki/openssl-easyrsa.cnf: No such file or directory
    Failed to update ./pki/safessl-easyrsa.cnf

 Downgrade to 3.0.3 , fix the issue

**Comment by TinCanTech** [comment]
Dragons be here
and Tin Cans too ..)
The question is:
what can _you_ do ?

**Comment by TinCanTech** [comment]
Updates ?

**Comment by sergiomb2** [comment]
> We're still working on a proper upgrade mechanism from 3.0.5 to 3.0.6. There were changes made that we didn't consider impacted upgrade. All our tests were from a clean/empty pki path.

any update ?

**Comment by darkmattercoder** [comment]
Well, the issue has been around for about eight months. Any information when to expect a fix on that?

**Comment by ecrist** [comment]
We haven’t gotten around to it yet.

**Comment by gregbert42** [comment]
Still ??? is there a work around where I dont have to regenerate all my keys?

**Comment by ecrist** [comment]
Why would you have to regenerate all your keys?  This isn't a high priority at the moment.  We'll get to it when we can.  When I say we, it's mostly me and a couple others.

**Comment by ecrist** [comment]
There is an upgrade mechanism in place and available in the v3.0.7 release.

**Comment by jiang-wei** [comment]
> There is an upgrade mechanism in place and available in the v3.0.7 release.

YES
I just upgraded from v3.0.6 to v3.0.8 and forgot to run `easyrsa upgrade pki` under v3.0.7. See error messages above

Returns to v3.0.7, execute the upgrade

Then it's working under v3.0.8

**Comment by TinCanTech** [comment]
Linking #499

**Comment by TinCanTech** [comment]
Commit https://github.com/OpenVPN/easy-rsa/commit/3222d17b5effcb829089a6a35da749c41e6600a7 should fix this in most cases.

Please re-open if the problem persists.
