### ISSUE TITLE
sign a wildcast certificate

### ISSUE THREAD

**Issue by deisi** [OpenVPN/easy-rsa#260]
Hey,

I try to use easyrsa to generate and sign a wildcast certificate for a local web server, but I cant get it to work.

What I did:
- Created a CA as described in the quick start tutorial. 
- Create a request and for the `ComonName` I use a wildcast name as `*.heim`
- Send the Request to my CA
- Sign the request and send it back to my server

The problem now is, I made the serve reachable under the domain `mopidy.heim` but the certificate for `*.heim` isn't valid for `mopidy.heim`. I see:

`mopidy.heim uses an invalid security certificate. The certificate is only valid for *.heim. Error code: SSL_ERROR_BAD_CERT_DOMAIN`

This makes me belief easyrsa cant be used to sign wildcast certificates or there is a special option of openssl that has to be set. However I cant seem to find it. Any suggestion where to search for it.

**Comment by chrisgavin** [comment]
Firefox (and indeed most clients) will not accept wildcard certificates for things that look like top level domains. There must be at least two components following the `*`.

https://hg.mozilla.org/mozilla-central/file/4530482cc605/security/pkix/lib/pkixnames.cpp#l1699

**Comment by ecrist** [comment]
This makes sense, since most "people" don't control an entire TLD.  I don't see a point in supporting it in EasyRSA.

**Comment by deisi** [comment]
Ah okay, then I know what I need to do. Thx
