### ISSUE TITLE
"nopass" option for export-p12?

### ISSUE THREAD

**Issue by billbaird3** [OpenVPN/easy-rsa#265]
Hi,

I was hoping to use the "nopass" option when exporting a p12 with this command:

`./easyrsa export-p12 ittest123 nopass`

I get an error like this:

`Ignoring unknown command option: 'nopass'`

Is this supposed to work? I use it with the "build-client-full" option and it works well.

Thanks!

**Comment by videoman** [comment]
Any updates if this will come back to this command? Why was this functionality removed?

**Comment by TinCanTech** [comment]
`export-p*` has never supported `nopass`.

**Comment by ecrist** [comment]
I don't believe p12 supports nopass at all.  This [stackexchange](https://stackoverflow.com/questions/27497723/export-a-pkcs12-file-without-an-export-password) article has more detail.

At the core:

> This is a static static variable and when stored to a pointer, this pointer cannot be NULL. There is no other code that ever assigns a different value to cpass, so cpass can be an empty string but it can certainly not be NULL and thus no PKCS#12 file that OpenSSL will ever create on command line as no password. It may have an empty password but it certainly has a password.

**Comment by videoman** [comment]
I have a script that I created that indeed does use the 'nopass' option to export pkcs12 files for automation. I mean, I guess I can just use openssl to do the same thing- but I was hoping to keep using this tool chain.

**Comment by ecrist** [comment]
Care to share that script?  Maybe you know something I do not?

**Comment by itaru2622** [comment]
@ecrist 

please refer my branch at https://github.com/itaru2622/easy-rsa/tree/exportp12-nopass
which  can archive:  
  easyrsa export-p12 EntryName nopass 

I can send PR if you re-open this issue.

openssl pkcs12 -export  has  -password option, and empty password is accepted on the test.
i.e:  openssl pkcs12 -export -password pass:  ...
refer manuals for detail (pkcs12, openssl).

**Comment by clandestinenetworks** [comment]
sux
