### ISSUE TITLE
Plans for PKCS#11 smartcard support?

### ISSUE THREAD

**Issue by graffen** [OpenVPN/easy-rsa#268]
I have a couple of Nitrokey HSMs, and I can see in different places that Easy-RSA does not support PKCS#11 smartcards. In other places it says "planned for a future point release". Are there any specific plans to implement support for this type of device?

**Comment by ecrist** [comment]
In all honesty, there is no current plan to implement this.  Not because I don't think it's worthwhile, more I don't have the time to do the work.

**Comment by Abdulmanahtalib** [comment]
Thankyou for support

**Comment by Abdulmanahtalib** [comment]
Support pkfc#11

**Comment by 0xdecaf** [comment]
I've added a version of PKCS#11 support via https://github.com/OpenVPN/easy-rsa/pull/332 and would love any feedback!  It's only tested with SoftHSM but over the next week or so I'll be testing and documenting usage on a YubiKey NEO 4.

**Comment by TinCanTech** [comment]
Follow-up: #689
