### ISSUE TITLE
How can I verify the release archive?

### ISSUE THREAD

**Issue by hanyuwei70** [OpenVPN/easy-rsa#27]
I tried to download the release 2.2.2 and gpg sign key. But I can't find the public key.
Where is it? I have tried key 0x606fd463. It didn't match!

**Comment by Vi-vi-Vi** [comment]
EasyRSA 3.x is now release, where could we find the information about how verifying the archive signature?
Especially how to avoid the warning:
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.

**Comment by ecrist** [comment]
Go to [the release page](https://github.com/OpenVPN/easy-rsa/releases) and you can see signature information there.  The warning you are seeing is a simple GPG warning.  To get rid of that you need to add and trust the signature used to sign the releases.
