### ISSUE TITLE
Release signature for Source code ?

### ISSUE THREAD

**Issue by computersalat** [OpenVPN/easy-rsa#270]
Hi,
you provide special Assets for `nix/windows` and `signature` files for those.
Is it possible to also provide `signatures` for the `Source code` `zip/tarball` ?

Thank you :-)

**Comment by ecrist** [comment]
No, I cannot.  As I stated in #269, those files are auto-generated from GitHub.

**Comment by computersalat** [comment]
https://wiki.debian.org/Creating%20signed%20GitHub%20releases
