### ISSUE TITLE
EASYRSA_REQ_CN var not honoured when creating CA

### ISSUE THREAD

**Issue by RWF-N** [OpenVPN/easy-rsa#275]
When a CA is created, the EASYRSA_REQ_CN variable is not honoured when set in the vars file. The CA's CN always is "Easy-RSA CA".

Rel: EasyRSA-nix-3.0.5

The problem seems to be the following code in build_ca():

```
***************
*** 492,498 ****
  
  	# Default CN only when not in global EASYRSA_BATCH mode:
  	# shellcheck disable=SC2015
! 	[ "$EASYRSA_BATCH" ] && opts="$opts -batch" || export EASYRSA_REQ_CN="Easy-RSA CA"
  
  	out_key_tmp="$(mktemp "$out_key.XXXXXXXXXX")"; EASYRSA_TEMP_FILE_2="$out_key_tmp"
  	out_file_tmp="$(mktemp "$out_file.XXXXXXXXXX")"; EASYRSA_TEMP_FILE_3="$out_file_tmp"
--- 492,498 ----
  
  	# Default CN only when not in global EASYRSA_BATCH mode:
  	# shellcheck disable=SC2015
! 	[ "$EASYRSA_BATCH" ] && opts="$opts -batch" || export EASYRSA_REQ_CN="${EASYRSA_REQ_CN:-Easy-RSA CA}"
  
  	out_key_tmp="$(mktemp "$out_key.XXXXXXXXXX")"; EASYRSA_TEMP_FILE_2="$out_key_tmp"
  	out_file_tmp="$(mktemp "$out_file.XXXXXXXXXX")"; EASYRSA_TEMP_FILE_3="$out_file_tmp"
```

If EASYRSA_REQ_CN is already set, it should not be set to "Easy-RSA CA".

**Comment by TinCanTech** [comment]
Are you proposing a change to the code ?
eg `export EASYRSA_REQ_CN="${EASYRSA_REQ_CN:-Easy-RSA CA}"`

**Comment by RWF-N** [comment]
Hi Richard,

I would say suggest, rather than propose. I made the change, and it worked for me. But I did not test exhaustively.

Roger

**Comment by TinCanTech** [comment]
It looks like a bug in `easyrsa` and testing your "suggestion" reveals that yours is probably the intended behaviour.

**Comment by TinCanTech** [comment]
For future ref. also see #100

**Comment by DRN88** [comment]
+1

**Comment by ecrist** [comment]
This is related to #363 I think.  It's being worked on in that ticket.  Please make further comments there.

**Comment by TinCanTech** [comment]
> When a CA is created, the EASYRSA_REQ_CN variable is not honoured when set in the vars file. The CA's CN always is "Easy-RSA CA".

Use `--batch` mode.
