### ISSUE TITLE
certificate not correctly signed by the trusted ca

### ISSUE THREAD

**Issue by covici** [OpenVPN/easy-rsa#301]
Hi.  I used easyrsa to create a certificate on my server and several client certificates.  I did the ./easyrsa3/easyrsa init-pki and then did the gen-dh.  Then I did  server-full vpn-server4.covici.com nopass .  Then I did several build-client-full covici-s... nopass.  One of then was covicis-iphone .  I then copied it and changed the name to .OpenVPN rather than .conf and inserted the ca, certificate and private key at the end of the file, using <ca>, </ca> and <cert> and <key> .  But the ios client would not connect to the server with the above error.

On the server I have 2.4.7 and the latest IOS client.

How can I fix or did I do something wrong?

**Comment by ecrist** [comment]
This isn't an issue with EasyRSA.  Please use the OpenVPN support channel on IRC (Freenode #openvpn) or the forums at https://forums.openvpnn.net

**Comment by covici** [comment]
Here is the ios logs.

**Comment by covici** [comment]
Did I do the easyrsa steps correctly?  I will go to their forums and
send them the log, but I want to make sure I generated a proper cert.

On Fri, 01 Mar 2019 14:09:33 -0500,
Eric Crist wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> [2  <text/html; UTF-8 (7bit)>]
> This isn't an issue with EasyRSA. Please use the OpenVPN support channel on IRC (Freenode #openvpn) or the forums at https://forums.openvpnn.net
> 
> ―
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici wb2una
         covici@ccs.covici.com
