### ISSUE TITLE
System was unable to find the specified registry key or value

### ISSUE THREAD

**Issue by mrjohnr** [OpenVPN/easy-rsa#304]
I've installed (as Admin) latest version of OpenVPN (2.4.7-I603) on Windows 2012 x64. I've checked on installer EasyRSA 2. Then trying to generate the certificate go in path ..\program files\OpenVPN\easy-rsa\ open command prompt(as Admin) run
` init-config.bat`
got :

> 1 file copied

then I run `vars.bat` and got: 

> system was unable to find the specified registry key or value

thanks for any help

**Comment by TinCanTech** [comment]
`vars.bat` is trying to find registry key `HKEY_LOCAL_MACHINE\SOFTWARE\OpenVPN` key:`default` which ought to be `C:\Program Files\OpenVPN`
Make sure this exists in the registry.

**Comment by TinCanTech** [comment]
Alternatively, you can consider upgrading easyrsa to version 3, we can help with that.  Before you make any changes please backup your current easyrsa PKI.

**Comment by TinCanTech** [comment]
The correct repo to report this issue is: https://github.com/OpenVPN/easy-rsa-old

**Comment by ecrist** [comment]
Closing, legacy code, use 3.x.
