### ISSUE TITLE
Time for a 3.0.7 release?

### ISSUE THREAD

**Issue by luizluca** [OpenVPN/easy-rsa#313]
@ecrist ,

There are plenty of new stuff in current master. Maybe it is time for a release. What is your plan here? Branch master for fix-only or commits, beta/RC release or a direct 3.0.8 release?

**Comment by ecrist** [comment]
We’ll fix everything in master, then cut a release from that.  I need to set aside some time to look at your fix for windows, then I think we should be able to cut a release.

Eric

**Comment by ecrist** [comment]
Working on it now, but it'll be release v3.0.7, not v3.0.8.

**Comment by luizluca** [comment]
Fixed the tittle ;-)

**Comment by luizluca** [comment]
v3.0.6 is already one year old 🎂

**Comment by pschiffe** [comment]
It would be great to have a new release for me as well, I'm currently facing #308 which is almost a year old.

**Comment by ecrist** [comment]
Released today. :)
