### ISSUE TITLE
Switch to build CAs with larger keys?

### ISSUE THREAD

**Issue by tromlet** [OpenVPN/easy-rsa#323]
Hey all -

I was wondering if it would be possible to add a bit length flag to the `build-ca` command that would allow us to specify the key size, if we wanted it to be different from the rest. Specifically, I like to use 2048 bits for most client and server keys, but the paranoia in me likes to use 4096 bits for root CAs and such. Would it be possible to add such a flag?

**Comment by evitalis** [comment]
I would also like to see this. Possibly also an option for EC root CA keys to go with this?

**Comment by ecrist** [comment]
EC root CA keys are already included in master (v3.0.8 will have them, to be released soon).  You can see the key size for certain types of keys in the openssl-easyrsa.cnf file already.  Closing.
