### ISSUE TITLE
$EASYRSA_EXT_DIR not set correctly

### ISSUE THREAD

**Issue by z3rone** [OpenVPN/easy-rsa#324]
In `easyrsa` file in line 1520 the function `set_var()` does not set the variable `$EASYRSA_EXT_DIR` correctly.

Value of `$EASYRSA_EXT_DIR` is `/x509-types` befor line 1520 and also afterwards, but should be `./x509-types` as `$EASYRSA` has value `'.'`.

This leads to error `Unknown cert type 'server'` when signing requests.

Code:
```
1515	# Same as above for the x509-types extensions dir
1516	if [ -d "$EASYRSA_PKI/x509-types" ]; then
1517		set_var EASYRSA_EXT_DIR		"$EASYRSA_PKI/x509-types"
1518	else	
1519		#TODO: This should be removed.  Not really suitable for packaging.
1520		set_var EASYRSA_EXT_DIR		"$EASYRSA/x509-types"
1521	fi
```

EasyRSA version: 3.0.6

**Comment by ecrist** [comment]
I think this is related to #363.  Work is being done there.

**Comment by TinCanTech** [comment]
Closed via https://github.com/OpenVPN/easy-rsa/commit/3222d17b5effcb829089a6a35da749c41e6600a7

@z3rone  Please re-open if the problem persists.
