### ISSUE TITLE
Clarify what to use as CA bundle/root cert for web servers?

### ISSUE THREAD

**Issue by evitalis** [OpenVPN/easy-rsa#325]
The documentation is not clear on what certificate should be imported into a user's web browser to allow them to properly check web server certs. Is this the same as the CA certificate created when running `easyrsa build-ca` or something else?

Also when checking the output certificate the entire details about the certificate are present in addition to the certificate itself. This is surprising as most certificates don't have this information within the same file. I was surprised nginx didn't complain about this but it could be due to how OpenSSL outputs the certificate from easyrsa.

**Comment by ecrist** [comment]
This isn't really an Easy-RSA issue.  You need to include the root CA, which is in pki/ca.crt by default, as well as the server certificate.  If you have intermediate certificates, you need to include those CAs as well.
