### ISSUE TITLE
Allow simple global configuration directory

### ISSUE THREAD

**Issue by ghost** [OpenVPN/easy-rsa#326]
Is it possible for easy-rsa to use a global configuration set in say /etc/easyrsa without needing to constantly change environment variables or set command line options? I was attempting to package this until I realized the script expects everything in the same directory, though I could be missing an option somewhere.

**Comment by luizluca** [comment]
@evitalis , it looks like easyrsa was built with multiple instances in mind. I don't know if a global config would be welcome.

Anyway, while packaging it, I normally use /etc/profile.d/easyrsa.sh to set a default directory.

**Comment by TinCanTech** [comment]
if `easyrsa` is in your `PATH` and you use it thus:
```
easyrsa --pki-dir=/path/to/pki build-something
```
does it not work ?

Possibly, make a copy of `vars` in your `$EASYRSA_PKI`.

**Comment by TinCanTech** [comment]
Linking: #348
