### ISSUE TITLE
Would it make sense to drop the default cert expiration from 1080 to 824?

### ISSUE THREAD

**Issue by mikewerwin** [OpenVPN/easy-rsa#328]
According to this note regarding iOS 13, Apple is now enforcing timeframes on certificates being presented:
https://support.apple.com/en-us/HT210176

A possible adjustment here could save people a lot of log crawling:
https://github.com/OpenVPN/easy-rsa/blob/57ef07f133e4f0351595795126680e983172c0eb/easyrsa3/easyrsa#L1573

**Comment by ecrist** [comment]
We are currently defaulting to 825 days.
