### ISSUE TITLE
Server Certificates Should Only Be Valid for 825 Days

### ISSUE THREAD

**Issue by shawnweeks** [OpenVPN/easy-rsa#333]
MacOS and Chrome have reduced the max server certificate lifetime to no more than 825 days. We should probably change the default. See https://support.apple.com/en-us/HT210176, https://github.com/FiloSottile/mkcert/issues/174 and https://github.com/symfony/cli/issues/146.

**Comment by ecrist** [comment]
I put 52, but this is resolved in 7f727b7

**Comment by ohiogeek8215** [comment]
Agree and no code of conduct or security 
Lock it down

**Comment by ecrist** [comment]
> Agree and no code of conduct or security
> Lock it down

What does this mean?
