### ISSUE TITLE
Feature request EASYRSA_CERT_EXPIRE

### ISSUE THREAD

**Issue by samuraiii** [OpenVPN/easy-rsa#334]
Hello,
I would like to first thank you for great work.
Second I have one feature request:
What about to implement EASYRSA_CERT_EXPIRE value which would tell easy-rsa that I would like to generate client certificate with validity period same as the CA (to the EOL of the CA).

Something like EASYRSA_CERT_EXPIRE=ca-lifetime.
So we do not have to update EASYRSA_CERT_EXPIRE in a way to keep client certs with shorter validity than the CA.

Cheers 
S

**Comment by TinCanTech** [comment]
https://github.com/OpenVPN/easy-rsa/blob/7e741a5a11ea67175d499bbf2b07f10ad3cd83d0/easyrsa3/vars.example#L128

**Comment by ecrist** [comment]
Closing this.  Nothing to do.

**Comment by samuraiii** [comment]
Hi,
I know about EASYRSA_CERT_EXPIRE...
But you need to adjust it manually.
I will try to provide example to describe my proposition more clearly:

You create new CA with validity of a one year.
On same day you issue few certificates with same validity period of a one year.
So far so good certificates are valid for roughly period as CA.
But now lets move for some (eg. 11) to future.
You still have same configuration in config files.
CA validity one year (now - 11 days) and you need to manually adjust validity for a new certificate to 354 days, to keep valid for similar time as CA.

My proposition was to have a switch (eg EASYRSA_CERT_EXPIRE_NO_LONGER_THAN_CA) which would effectively cap cert validity by CAs validity...

We now do it by quite complex shell script to issue certs not valid logner than CA (becuse some people in our company are not that good to debug problems, and would complian that "My cert is still valid why can't I connect?"

But if it is too complex I can take rejection :)

Anyway I also want to thank all of you for nice tool.

We
