### ISSUE TITLE
sign-req Unknown cert type 'server'

### ISSUE THREAD

**Issue by RdL87** [OpenVPN/easy-rsa#335]
Hi,
i'm facing this issue on the following stack:

- CentOS Linux release 7.7.1908 (Core)
- OpenVPN 2.4.7 x86_64-redhat-linux-gnu
- Easy-RSA 3.0.6
```

[centos@openvpn 3]$ sudo ./easyrsa init-pki
[centos@openvpn 3]$ sudo ./easyrsa build-ca
[centos@openvpn 3]$ sudo ./easyrsa gen-req pippo-server nopass
[centos@openvpn 3]$ sudo ./easyrsa sign-req server pippo-server

Note: using Easy-RSA configuration from: ./vars

Using SSL: openssl OpenSSL 1.0.2k-fips  26 Jan 2017

Easy-RSA error:

Unknown cert type 'server'

```

**Comment by TinCanTech** [comment]
Your previous question has the answer:
https://github.com/OpenVPN/easy-rsa/issues/93#issuecomment-547844835

**Comment by RdL87** [comment]
My previos question says also that the answer provided above does not work for me.
