### ISSUE TITLE
Run all scripts through ShellCheck for better compatibility

### ISSUE THREAD

**Issue by a1346054** [OpenVPN/easy-rsa#336]
All scripts included with easy-rsa should be run through [ShellCheck](https://www.shellcheck.net/) for better compatibility with various shells, and as another code checker for bugs.

Currently, there are a few issues revealed by ShellCheck that might be worth having a look at.

For example, there are a few cases of these in the easy-rsa code:

https://github.com/koalaman/shellcheck/wiki/SC2086
https://github.com/koalaman/shellcheck/wiki/SC2181
https://github.com/koalaman/shellcheck/wiki/SC2230
https://github.com/koalaman/shellcheck/wiki/SC2235

**Comment by ecrist** [comment]
We actually *do* run all our code through shellcheck.  Take a look at our other repo [easy-rsa-unit-tests](https://github.com/OpenVPN/easyrsa-unit-tests) and make suggestions there.  Also check out our [Travis-CI](https://travis-ci.org/OpenVPN/easy-rsa) build history.
