### ISSUE TITLE
unexpected EOF caused by unsupported quotation in vars file

### ISSUE THREAD

**Issue by ojkastl** [OpenVPN/easy-rsa#34]
Hi,

using easy-rsa3 on OSX 10.9.x (with bash from macports) I get this error when using init-pki:

```
$easyrsa init-pki
./easyrsa: eval: line 1046: unexpected EOF while looking for matching `''
./easyrsa: eval: line 1047: syntax error: unexpected end of file
```

The directory pki seems to be created, along with the directories reqs and private, but I do not know if something goes wrong 'underneath'.

```
$bash -version:
GNU bash, Version 4.3.11(1)-release (x86_64-apple-darwin13.1.0)
```

I do not see this error on linux, and I wonder why. Please ask for any pieces of information you might need...

**Comment by brother-bernard** [comment]
I use Mac OS 10.9.5. I am up-to-date for github branch v3.0.5 and I still get the same error:
```
developpement:easyrsa3 bern$ ./easyrsa build-client-full viator4@xxxxx.com
./easyrsa: eval: line 1172: unexpected EOF while looking for matching `''
./easyrsa: eval: line 1173: syntax error: unexpected end of file
```

**Comment by brother-bernard** [comment]
Solved! When a single quote is present inside a string, the above issue is displayed.
For instance, I have changed in the province variable "Provence-Alpes-Côte d'Azur" by "Provence-Alpes-Côte d Azur" and the error has gone away! That confirm the comment of ojkastl on Jul 28, 2014.

**Comment by ecrist** [comment]
Looks like we need to do some better escaping if that variable. 

Eric Crist

**Comment by TinCanTech** [comment]
@brother-bernard OpenSSL and LibreSSL don't respect the use of apostrophe in those fields.  Thus: "Provence-Alpes-Côte d'Azur" becomes "Provence-Alpes-Côte dAzur" (no space) when the certificate is created.

**Comment by TinCanTech** [comment]
I have wasted enough time on this.

IMHO, it is simply not worth the effort to support single quote marks `'`.
