### ISSUE TITLE
Bug: export-p12

### ISSUE THREAD

**Issue by chriskacerguis** [OpenVPN/easy-rsa#342]
Hello,

I'm seeing the following error, when running the command:

`# ./easyrsa export-p12 user@domain.com`

Note: `EASYRSA_PASSIN` and `EASYRSA_PASSOUT` are NOT set.

Output: 
```sh
Using SSL: openssl LibreSSL 2.8.3
Usage: pkcs12 [options]
where options are
[TRUNCATED OPTIONS]
Easy-RSA error:

Export of p12 failed: see above for related openssl errors.
``` 

I'm running the latest "master".
```sh
# git rev-parse HEAD        
7f727b791b76147f97bfae2a152f57ad94240106
```

Setting `EASYRSA_PASSIN` and `EASYRSA_PASSOUT` has no effect in resolving this error.

Running this command works as expected:

```sh
openssl pkcs12 \
-in "pki/issued/user@domain.com.crt" \
-inkey "pki/private/user@domain.com.key" \
-passout pass:chang3m3 \
-export \
-out "/tmp/user@domain.com.p12"
```

**Comment by ecrist** [comment]
Can you verify with v3.0.7 or an update from master?  This seems to work fine for me on macOS with LibreSSL:

```
ecrist@marvin:~/easy-rsa/easyrsa3-> ./easyrsa export-p12 ed25519-fixed
Using SSL: openssl LibreSSL 2.8.3
Enter Export Password:
Verifying - Enter Export Password:

Successful export of p12 file. Your exported file is at the following
location: /Users/ecrist/easy-rsa/easyrsa3/pki/private/ed25519-fixed.p12
```

**Comment by justfly1111** [comment]
i have same issue when attempting  o export p12 see bellow

root@freya:/usr/local/git/easy-rsa/easyrsa3 # ./easyrsa export-p12 nginx-client 

Note: using Easy-RSA configuration from: /usr/local/git/easy-rsa/easyrsa3/vars
Using SSL: /usr/local/bin/openssl OpenSSL 3.0.0-alpha6 6 Aug 2020 (Library: OpenSSL 3.0.0-alpha6 6 Aug 2020)
Enter Export Password:
Verifying - Enter Export Password:
0020E10008000000:error::digital envelope routines:evp_generic_fetch:fetch failed:crypto/evp/evp_fetch.c:318:Global default library context, Algorithm (RC2-40-CBC), Properties ()
0020E10008000000:error::digital envelope routines:EVP_CipherInit_ex:initialization error:crypto/evp/evp_enc.c:179:
0020E10008000000:error::digital envelope routines:EVP_PBE_CipherInit:keygen failure:crypto/evp/evp_pbe.c:132:
0020E10008000000:error::PKCS12 routines:PKCS12_pbe_crypt:pkcs12 algor cipherinit error:crypto/pkcs12/p12_decr.c:37:
0020E10008000000:error::PKCS12 routines:PKCS12_item_i2d_encrypt:encrypt error:crypto/pkcs12/p12_decr.c:133:
0020E10008000000:error::PKCS12 routines:PKCS12_pack_p7encdata:encrypt error:crypto/pkcs12/p12_add.c:119:

Easy-RSA error:

Export of p12 failed: see above for related openssl errors.


and just like above the following command to openssl directly worked perfectly 

root@freya:/usr/local/etc/ssl/CA/pki # openssl pkcs12 \
? -in "issued/nginx-client.crt" \
? -inkey "private/nginx-client.key" \
? -passout pass:09LoveYou2392 \
? -export \
? -out "issued/nginx-client.p12"
root@freya:/usr/local/etc/ssl/CA/pki # ls issued
nginx-client.crt        nginx-client.p12        nginx-server.crt
root@freya:/usr/local/etc/ssl/CA/pki # 


so id assume theres something either in the environment or bug in the actual wrapper script  causing this

**Comment by TinCanTech** [comment]
> Using SSL: /usr/local/bin/openssl **OpenSSL 3.0.0-alpha6**

@justfly1111   That is why it does not work.

**Comment by TinCanTech** [comment]
> ./easyrsa export-p12 **user@domain.com**

Required: `<FILE_NAME_BASE>`
