### ISSUE TITLE
Can't open /pki/private/ca.key for reading

### ISSUE THREAD

**Issue by jeh1138** [OpenVPN/easy-rsa#343]
I'm very new to this.  I was walking through the documentation to set up key for AWS VPN connectivity.  I was able to generate the pki/ca.cert and pki/private/ca.key files from the command:

```
$ ./easyrsa build-ca nopass
Using SSL: openssl OpenSSL 1.1.1d  10 Sep 2019
Generating RSA private key, 2048 bit long modulus (2 primes)
.........................................+++++
......+++++
e is 65537 (0x010001)
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.

Common Name (eg: your user, host, or server name) [Easy-RSA CA]:CaCert

CA creation complete and you may now import and sign cert requests.
Your new CA certificate file for publishing is at:
/c/Users/UserName/Documents/GitHub/easy-rsa/easyrsa3/pki/ca.crt
```

But then when I tried to generate the server I got this error:

```
$ ./easyrsa build-server-full server nopass
Using SSL: openssl OpenSSL 1.1.1d  10 Sep 2019
Generating a RSA private key
.......................................................................................+++++
................+++++
writing new private key to 'C:/Users/UserName/Documents/GitHub/easy-rsa/easyrsa3/pki/easy-rsa-1637.0cW49K/tmp.aXbXnh'

Using configuration from C:/Users/UserName/Documents/GitHub/easy-rsa/easyrsa3/pki/easy-rsa-1637.0cW49K/tmp.F6XL0C
Can't open /c/Users/UserName/Documents/GitHub/easy-rsa/easyrsa3/pki/private/ca.key for reading, No such file or directory
19016:error:02001003:system library:fopen:No such process:../openssl-1.1.1d/crypto/bio/bss_file.c:69:fopen('/c/Users/UserName/Documents/GitHub/easy-rsa/easyrsa3/pki/private/ca.key','r')
19016:error:2006D080:BIO routines:BIO_new_file:no such file:../openssl-1.1.1d/crypto/bio/bss_file.c:76:
unable to load CA private key

Easy-RSA error:

signing failed (openssl output above may have more detail)

Easy-RSA error:

Failed to sign 'server'
```

I found an article on the AWS forums where the workaround was to use a Linux box to run the command.  I'm not sure if I need to install/setup anything special on my Windows 10 box to get this to run correctly.

[https://forums.aws.amazon.com/thread.jspa?threadID=308532]

Any help is appreciated.  I'm a n00b with OpenVPN and easy-rsa.  The files are definitely in the target folders and I have full administrative access.  I even ran Git Bash as an administrator so I'm guessing it's not a permissions issue.

--j

**Comment by TinCanTech** [comment]
It looks like you have cloned EasyRSA3 git-master to a Windows machine.
This not a supported installation option for Windows.
Please try using the Windows ready installation options here:
https://github.com/OpenVPN/easy-rsa/releases v306 is suitable.

**Comment by SAkagiI** [comment]
I occur same problem.

## My Environment
 - git version 2.25.0.windows.1
 - OpenSSL 1.1.1d
 - EasyRSA-3.0.5, EasyRSA-3.0.6

## Error Message

```
$ ./easyrsa sign-req server server

Using SSL: openssl OpenSSL 1.1.1d  10 Sep 2019


You are about to sign the following certificate.
Please check over the details shown below for accuracy. Note that this request
has not been cryptographically verified. Please be sure it came from a trusted
source or that you have verified the request checksum with the sender.

Request subject, to be signed as a server certificate for 1080 days:

subject=
    commonName                = server


Type the word 'yes' to continue, or any other input to abort.
  Confirm request details: yes
Using configuration from ./safessl-easyrsa.cnf
Can't load /c/easyrsa/EasyRSA-Windows-3.0.5/EasyRSA-3.0.5/pki/.rnd into RNG
16336:error:2406F079:random number generator:RAND_load_file:Cannot open file:../openssl-1.1.1d/crypto/rand/randfile.c:98:Filename=/c/easyrsa/EasyRSA-Windows-3.0.5/EasyRSA-3.0.5/pki/.rnd
Can't open /c/easyrsa/EasyRSA-Windows-3.0.5/EasyRSA-3.0.5/pki/private/ca.key for reading, No such file or directory
16336:error:02001003:system library:fopen:No such process:../openssl-1.1.1d/crypto/bio/bss_file.c:69:fopen('/c/easyrsa/EasyRSA-Windows-3.0.5/EasyRSA-3.0.5/pki/private/ca.key','r')
16336:error:2006D080:BIO routines:BIO_new_file:no such file:../openssl-1.1.1d/crypto/bio/bss_file.c:76:
unable to load CA private key
Cannot write random bytes:
16336:error:24070079:random number generator:RAND_write_file:Cannot open file:../openssl-1.1.1d/crypto/rand/randfile.c:233:Filename=/c/easyrsa/EasyRSA-Windows-3.0.5/EasyRSA-3.0.5/pki/.rnd

Easy-RSA error:

signing failed (openssl output above may have more detail)
```

## My Solution

However EasyRSA-3.0.4 doesn't occur same problem, and successfully finish.

```
$ ./easyrsa build-server-full server nopass
Generating a RSA private key
........................................................................................+++++
....................................................................................................................+++++
writing new private key to 'C:/easyrsa/EasyRSA-3.0.4/EasyRSA-3.0.4/pki/private/server.key.BhKPLLJauT'
-----
Using configuration from ./openssl-easyrsa.cnf
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'server'
Certificate is to be certified until Feb 14 07:56:06 2030 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated

$ ls pki/issued/
server.crt
```

**Comment by ecrist** [comment]
Does this still occur in v3.0.7 or master?

**Comment by Tulskie** [comment]
I have the same problem.
v3.0.8
$ ./easyrsa sign-req server server

Note: using Easy-RSA configuration from: /c/xampp/htdocs/easy-rsa/easyrsa3/vars
Using SSL: openssl OpenSSL 1.1.1g  21 Apr 2020


You are about to sign the following certificate.
Please check over the details shown below for accuracy. Note that this request
has not been cryptographically verified. Please be sure it came from a trusted
source or that you have verified the request checksum with the sender.

Request subject, to be signed as a server certificate for 825 days:

subject=
    commonName                = server


Type the word 'yes' to continue, or any other input to abort.
  Confirm request details: yes
                              Using configuration from C:/xampp/htdocs/easy-rsa/easyrsa3/pki/easy-rsa-2056.sA4wMj/tmp.1kojG0
Can't open /c/xampp/htdocs/easy-rsa/easyrsa3/pki/private/ca.key for reading, No such file or directory
12448:error:02001003:system library:fopen:No such process:../openssl-1.1.1g/crypto/bio/bss_file.c:69:fopen('/c/xampp/htdocs/easy-rsa/easyrsa3/pki/private/ca.key','r')
12448:error:2006D080:BIO routines:BIO_new_file:no such file:../openssl-1.1.1g/crypto/bio/bss_file.c:76:
unable to load CA private key

Easy-RSA error:

signing failed (openssl output above may have more detail)

Does anyone have a solution?

**Comment by dredwolff** [comment]
I found a workaround, you can pass in the pki-dir option as a windows-style directory and things seem to work:
./easyrsa3/easyrsa --pki-dir="C:/Users/<username here>/IdeaProjects/easy-rsa/pki" build-server-full server nopass

**Comment by DmitriyBobrovskiy** [comment]
Thank you @dredwolff it works, I had the same problem with `sign-req` but your solution helps!

**Comment by hiddeneyes02** [comment]
> Thank you @dredwolff it works, I had the same problem with `sign-req` but your solution helps!

@DmitriyBobrovskiy Can you please tell me how did you resolve that using `sign-req` ?

**Comment by DmitriyBobrovskiy** [comment]
> @DmitriyBobrovskiy Can you please tell me how did you resolve that using `sign-req` ?

I used the solution provided by @abstractBoyd (probably he was a @dredwolff before):
```bash
./easyrsa --pki-dir="c:/Users/username/EasyRSA-3.0.8/pki/" sign-req client client1
```

**Comment by TinCanTech** [comment]
Please ignore the Mention above, that was an error.

**Comment by TinCanTech** [comment]
This appears to be a Windowz problem.  

Windowz is creating file names in the following format:
`/c/xampp/htdocs/easy-rsa/easyrsa3/pki/private/ca.key`

EasyRSA Windows tool-chain does not recognise that file-name.

**Comment by TinCanTech** [comment]
The first requirement to solving this, is to establish the Windows environment that `easyrsa` is being run by.

For starters, the version of Windows.

**For the record**, `easyrsa` does **not work correctly** using `git-bash` for Windowz.

**Comment by TinCanTech** [comment]
However, this `file-name` problem can be solved.

**Comment by TinCanTech** [comment]
This is probably related to #467

**Comment by imbajibabu** [comment]
./easyrsa --pki-dir="D:/easy-rsa/easyrsa3/pki" build-server-full server nopass

**Comment by TinCanTech** [comment]
Please reopen if not fixed via https://github.com/OpenVPN/easy-rsa/pull/528
