### ISSUE TITLE
Support for multiple CAs

### ISSUE THREAD

**Issue by ecrist** [OpenVPN/easy-rsa#348]
Would like to support multiple CAs and/or sub-CAs.

Basically, we'd have a root path, and sub paths for each subsequent CA/sub-CA in a directory structure, kinda like this:

`/home/ecrist/easy-rsa
   |--example.org
   |----vpn-subca
   |----web-subca
   |--example2.org
`

This would generate a menu, if opted, or expect a CA nickname as an argument to proceed.  EasyRSA could know it was in such a place through the presence of a .easyrsa-root file (empty).  The presence of this file would activate logic that caused EasyRSA to look above for the .easyrsa-root, and in subdirectories directly below.

A simple change of the config file active would enable the use.

Thoughts?

**Comment by TinCanTech** [comment]
Easyrsa3 could also `inline` the certificates correctly for use with openvpn.

**Comment by TinCanTech** [comment]
`easyrsa` can now be successfully used from PATH and all data-files will be placed in the current PKI.

The only exception being `vars`, due to user expectations.

**Comment by TinCanTech** [comment]
All user data files now belong in the PKI or system shared areas.

`easyrsa` can be run from `$PATH` with `--pki-dir`, which means you could do:
```
$ easyrsa --pki-dir=/home/tct/easy-rsa/family init-pki
$ easyrsa --pki-dir=/home/tct/easy-rsa/friends init-pki
etc...
```

**Comment by viharm** [comment]
This is awesome! However, I was wondering how we can avoid the failure mode where the user utilizes the root CA instead of sub-CA. I am aware that this is user error, but is this in scope?

**Comment by TinCanTech** [comment]
@viharm I do not understand your question.

Please start a new issue with **full details**.

**Comment by viharm** [comment]
> @viharm I do not understand your question.
> 
> Please start a new issue with **full details**.

OK, sure. I'll start a new issue, but since it's related to multiple PKIs/CAs, I wanted to understand if it is in scope to protect the user from making a wrong decision of using the incorrect PKI/CA - only a query.

**Comment by TinCanTech** [comment]
Your question is **not** related to this issue.

**Comment by TinCanTech** [comment]
This is already possible and simple. Even Sub-CA support.

Closing
