### ISSUE TITLE
Support for providing additional RDN information for root CA and intermediate CA certificates

### ISSUE THREAD

**Issue by siddharths2710** [OpenVPN/easy-rsa#352]
At present the `easyrsa build-ca` command prompts us to fill the content of only one RDN as part of the Distinguished Name info, i.e the _Common Name_ RDN which is part of the **Subject** field of the X.509 certificate.
```
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Common Name (eg: your user, host, or server name) [Easy-RSA CA]:

CA creation complete and you may now import and sign cert requests.
Your new CA certificate file for publishing is at:
../../pki/ca.crt
```
It would be ideal if the prompt provided initializing other RDNs like `OU`, `C`, `O` etc. as well.

**Comment by TinCanTech** [comment]
Please read your `./vars` file: 
https://github.com/OpenVPN/easy-rsa/blob/e59911a474f5a0b9f5ac98b1ca304b2069c3a14f/easyrsa3/vars.example#L78

**Comment by siddharths2710** [comment]
Closing this issue as it is solved using the vars file.
