### ISSUE TITLE
Batch mode breaks gen_csr

### ISSUE THREAD

**Issue by awienecke** [OpenVPN/easy-rsa#357]
line 710
[ ! "$EASYRSA_BATCH" ] && EASYRSA_REQ_CN="$1"
when using gen-csr option, it fails to set the DN becuase of the failed line, I removed the first failing part, and it now functions as expected.

Seriously, what was the purpose of this. No amount of setting the variable anywhere worked.

**Comment by ecrist** [comment]
Can you elaborate?  Not much detail here, just sounds like you're frustrated and lashing out...

**Comment by awienecke** [comment]
Not lashing out so much as questioning why it was put in there? Maybe a touch frustrated... 
I honestly didn't have time to dig into it too deeply, however, when EASYRSA_BATCH is set to true in the config, gen-csr fails to generate a valid CSR.

Commenting out that code seemed to resolve it, though I've since moved to manually generating a CSR because it seems to fail to set other flags as well, and it was easier to automate an openssl line in this case.

**Comment by ecrist** [comment]
If you can give me a concrete example (command line and sample config) it will allow me to speed up troubleshooting this.  Without that, I'll still try to figure out the issue, but it'll take longer and I might fix something else that doesn't address your problem.

**Comment by awienecke** [comment]
options set:
set_var EASYRSA_DN      "org"
set_var EASYRSA_REQ_COUNTRY ... etc are set
set_var EASYRSA_KEY_SIZE        2048
set_var EASYRSA_CA_EXPIRE       3650
set_var EASYRSA_CERT_EXPIRE     397
set_var EASYRSA_BATCH           "yes"

Everything else is default/commented out, I then run the following:

./easyrsa gen-req example.dom nopass

This generated a bad cert with the latest I was using at the time (over a month ago.)

**Comment by TinCanTech** [comment]
`EASYRSA_BATCH=1` not `yes` .. I suspect this is a problem of inadequate variable quoting in the source.

**Comment by TinCanTech** [comment]
Recent changes appear to have fixed what-ever the issue here was.

Closing - Please reopen if the problem persists.
