### ISSUE TITLE
allow external EASYRSA_PASSIN and EASYRSA_PASSOUT env vars

### ISSUE THREAD

**Issue by pschiffe** [OpenVPN/easy-rsa#365]
Hi @luizluca ,

thank you for your awesome PR #242 , it makes a lot of things easier. However I'm wondering, why did you forbid the external source for the `EASYRSA_PASSIN` and `EASYRSA_PASSOUT` variables? See https://github.com/OpenVPN/easy-rsa/blob/master/easyrsa3/easyrsa#L2303

I think allowing those env vars could provide additional flexibility, for example in situations, when the control of command line options is difficult.

Thanks for considering this request.

peter

**Comment by luizluca** [comment]
In this case, EASYRSA_PASSIN and EASYRSA_PASSOUT variables are like 'private variables', only touched by --passin and --passout args.

My concern was that someone could set those vars outside easyrsa in an unintentionally innocent way (like a script calling easyrsa3) or by a malicious agent trying to read sneakily password info or writing data (password) to any location easyrsa could write to.

However, I do not have a strong argument against removing that limitation. All uses of EASYRSA_PASSIN and EASYRSA_PASSOUT prefixes the call with -passin/out and it also protects the content with double quotes. So, it should not be able to use them to add extra arguments but those available for openssl -passin/out.

You can create a PR and let the maintainer decide (with my neutral option about it).
