### ISSUE TITLE
easyrsa ignores crl_dir and crl form openssl-easyrsa.cnf

### ISSUE THREAD

**Issue by tobox** [OpenVPN/easy-rsa#367]
I changed `$crl_dir` and `$crl` in `openssl-easyrsa.cnf` but `easyrsa gen-crl` seems to ignore the settings. Since the CRL needs to be access while openvpn is running as nobody, it is often required to put the CRL in a different position than the other certifcates (which a imported at startup with root privileges)

Relevant section of easyrsa seems to be here:
https://github.com/OpenVPN/easy-rsa/blob/master/easyrsa3/easyrsa#L1260

**Comment by ecrist** [comment]
This is actually an extension of the bug reported in #363.  Closing as duplicate.
