### ISSUE TITLE
[Enhancement] allow parameter keysize= for gen-dh

### ISSUE THREAD

**Issue by htcfreek** [OpenVPN/easy-rsa#369]
Hello.

Please allow the common parameter 
keysize for the function gen-dh.

Then users can generate dh-parameters with other keysize than used for the rsa keys. For example with 4096 bit.

**Comment by TinCanTech** [comment]
@htcfreek did you see `easyrsa help options`

**Comment by htcfreek** [comment]
@TinCanTech, yes did. But the parameter didn't work for gen-dh command.

**Comment by TinCanTech** [comment]
```
tct@home:~/git/easy-rsa/EasyRSA-3.0.7$ ./easyrsa --keysize=64 gen-dh

Note: using Easy-RSA configuration from: /home/tct/git/easy-rsa/EasyRSA-3.0.7/vars
Using SSL: openssl OpenSSL 1.1.1  11 Sep 2018
Generating DH parameters, 64 bit long safe prime, generator 2
This is going to take a long time
....+.+....++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*

DH parameters of size 64 created at /home/tct/git/easy-rsa/EasyRSA-3.0.7/pki/dh.pem
```

**Comment by htcfreek** [comment]
I can't test it anymore. But i didn't get that work.

One thing I have to mention: I didn't create/use the vars file.

**Comment by ecrist** [comment]
As @TinCanTech stated, the --keysize value works on the command line.  Closing.
