### ISSUE TITLE
vars.example : the var "EASYRSA_CRL_DAYS" is written in the false line

### ISSUE THREAD

**Issue by htcfreek** [OpenVPN/easy-rsa#370]
Hello.

In the file vars.example the text `#set_var EASYRSA_CRL_DAYS	180` is written in the false line. At the moment it is written in line 38. But it must be written in line 33/34.

![IMG_20200323_210827](https://user-images.githubusercontent.com/61519853/77358643-7ff52080-6d4a-11ea-8cac-1a7de11b3f24.png)

**Comment by ecrist** [comment]
I'm not understanding what you're trying to report here...

**Comment by htcfreek** [comment]
Hello @ecrist .

> I'm not understanding what you're trying to report here...

I reporting the issue that there is a failur in the structure of vars.example.

**What I did mean:**
I think the variable for 'crl expiration' must be wirtten directly under the explaination for it and not under the explanation and variable for 'cert renewal'.
![image](https://user-images.githubusercontent.com/61519853/78012040-b7645e00-7344-11ea-8fd9-a254cc1c468b.png)
