### ISSUE TITLE
OpenVPM 3.0.6 - Can't load /etc/openvpn/server/easy-rsa/pki/.rnd into RNG 

### ISSUE THREAD

**Issue by rwillett** [OpenVPN/easy-rsa#371]
Hi, 

I came here as I have the same issues with the error generating the .rnd file as 

#261 (and what appears to be a few others)
```
Can't load /etc/openvpn/server/easy-rsa/pki/.rnd into RNG
```

using the 3.0.6 release of OpenVPN. 

I note (with some bemusement) that everybody who has written about installing OpenVPN puts up screenshots showing this error occurring but nobody has picked up on this or commented on this.

I do not have the expertise to know if this error/warning/information is important or not. From what I can understand, it helps provide more entropy to certificates which sounds like it's kinda important, specifically when you are using a security based system such as OpenVPN. 

1. Can somebody comment on whether this problem is serious, or I could ignore it or should 

2. Is the 3.0.7. release imminent now? 

Never sure if I should hijack an existing thread or create a new issue. I normally get it wrong :)

Many thanks for the work thats gone into this.

Rob

**Comment by ecrist** [comment]
This appears to actually be a feature/bug in OpenSSL 1.1.1a.  It's non-consequential, it seems.  

https://github.com/openssl/openssl/issues/7754
