### ISSUE TITLE
[Enhancement] add version info to easyrsa-script

### ISSUE THREAD

**Issue by htcfreek** [OpenVPN/easy-rsa#372]
### Idea
Is it possible to add a version info into the easyrsa script 'easyrsa'?

### Details
At the moment I find no solution to get the exact version of the used easyrsa script.
Most of the docs for openvpn say that I should copy easyrsa into ./etc/openvpn. After a few months it is not possible to find the exact version of the easyrsa script.

Because of that it would be nice to have version information into the script.

### Technical details
I find the following useful:
1. Having a comment at the biginning of the script code: tool name, version, author, link to github repository
2. Parameter 'version' which shows the following text at the shell: tool name, version, author, link to github repository

```
$> ./easyrsa --version
easy-yrsa 3
version: 3.0.6
author: <name>
more details on Github: https://github.com/OpenVPN/easy-rsa
```

**Comment by TinCanTech** [comment]
Something like this: https://github.com/TinCanTech/easy-tls/blob/6033ee8e98fd15c74cd8b4158f30be2f6143429f/easytls#L1085

**Comment by ecrist** [comment]
Great idea. We will make it happen.
