### ISSUE TITLE
easy-rsa building client fails without useful error output

### ISSUE THREAD

**Issue by ashu-savani** [OpenVPN/easy-rsa#375]
Hi, 

I'm trying to create a new client for the OpenVPN server. It appears that the easy-rsa build client command does not execute successfully

```
root@IP-ADDRESS:/etc/openvpn/easy-rsa# ./easyrsa build-client-full 'client' nopass
Using SSL: openssl OpenSSL 1.1.1f  31 Mar 2020
Generating a RSA private key
....................................+++++
.......................+++++
writing new private key to '/etc/openvpn/easy-rsa/pki/easy-rsa-10842.0O0Cdh/tmp.g2jy4j'
-----
Using configuration from /etc/openvpn/easy-rsa/pki/easy-rsa-10842.0O0Cdh/tmp.Fnhlh2

Easy-RSA error:

signing failed (openssl output above may have more detail)

Easy-RSA error:

Failed to sign 'client'
```

It is worth noting that this randomly occurs after multiple clients have been created successful. 

The machine information is as follows
```
Linux ip-10-0-0-20 4.15.0-1045-aws #47-Ubuntu SMP Fri Aug 2 13:50:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ecrist** [comment]
What version of EasyRSA are you using?

Eric Crist

**Comment by ashu-savani** [comment]
v3.0.4

**Comment by ecrist** [comment]
Can you see if you run into the same issue with v3.0.7?

Eric Crist

**Comment by ashu-savani** [comment]
Apologies for the delayed response - using v3.0.7 also doesn't show any useful output
```
ubuntu@IP-ADDRESS:/etc/openvpn/easy-rsa$ sudo ./easyrsa build-client-full 'FILENAME' nopass
Using SSL: openssl OpenSSL 1.1.1  11 Sep 2018
Generating a RSA private key
.............................................+++++
..............................................................................................+++++
writing new private key to '/etc/openvpn/easy-rsa/pki/easy-rsa-24266.Ey3A3M/tmp.mg1fav'
-----
Using configuration from /etc/openvpn/easy-rsa/pki/easy-rsa-24266.Ey3A3M/tmp.iR7yhk

Easy-RSA error:

signing failed (openssl output above may have more detail)

Easy-RSA error:

Failed to sign 'FILENAME'
```

**Comment by ecrist** [comment]
Can you re-execute the script, but call it like below?  DO NOT include anything you want to keep secret.  Why are you enclosing the client name in single quotes? 

`sudo sh -x ./easyrsa build-client-full 'FILENAME' nopass`

**Comment by bradleysmith** [comment]
The OP has failed to respond to the last request but I have the exact same issue and am happy to provide the requested information if that's still valid?

Basically this did work, and then some time later (machine will have rebooted at least once I believe) requests to build a new client stops working. This has happened twice now on two different installations although IIRC it was on Ubuntu 20.04 both times.

**Comment by ecrist** [comment]
By all means, if you have debug info, please share.

**Comment by bradleysmith** [comment]
[easyrsa-build-client-full-output.txt](https://github.com/OpenVPN/easy-rsa/files/5622106/easyrsa-build-client-full-output.txt)
Output attached

**Comment by ashu-savani** [comment]
Apologies for the delay on here. The reason I was not responding is because I came up with a (temporary) solution for the issue. 

I noticed that the `index.txt` file located at `/etc/openvpn/easy-rsa/pki/` would contain some characters at the end of the file. The last time I had this issue, the file contained `.` or `...`

We use an API to generate OpenVPN configuration files and I assume that the `index.txt` file would be written to multiple times hence the discrepancy with the random characters occurring at the end of the file. 

I solve the issue by removing the the random characters at the end of the file.

I currently do not have the full set of files/output as this issue has not occurred for a while so it may take some time to dig through backups to check for these files.

I hope this was helpful.

**Comment by TinCanTech** [comment]
> I noticed that the `index.txt` file located at `/etc/openvpn/easy-rsa/pki/` would contain some characters at the end of the file. The last time I had this issue, the file contained `.` or `...`

That must be an `openssl` bug.

**Comment by TinCanTech** [comment]
> To get my system working again I put a new install somewhere, copy over my vars, run init-pki and the ca generation, copy over the ca cert and key and then I'm up and running again.

Which cannot be reproduced.

**Comment by gelin** [comment]
> I noticed that the `index.txt` file located at `/etc/openvpn/easy-rsa/pki/` would contain some characters at the end of the file. The last time I had this issue, the file contained `.` or `...`

Got the same issue. There was an occasional empty line (two new line chars) at the end of `index.txt`, it was edited manually before.

**Comment by TinCanTech** [comment]
Reliably reproduce the problem and I'll take a look.
