### ISSUE TITLE
v2 to v3 upgrade ignores code / keys separated setup

### ISSUE THREAD

**Issue by monsterry** [OpenVPN/easy-rsa#377]
At the moment we are using a setup like this to support multiple CAs with only one easyrsa installation:

* easyrsav2 installed via deb-packages lying in `/usr/share/easyrsa`
* Multiple PKI infrastructures under `/etc/openvpn/server/ca1` to `caX` containing
  *  a `vars` file with `EASY_RSA` set to `/usr/share/easyrsa` and `KEY_DIR` set to `/etc/openvpn/server/caX/keys`
  * a `keys` directory containing the certs

Execution is possible via sourcing the `vars` file and executing `$EASY_RSA/easy_rsa ...`. I tried to continue this sort of setup with easyrsav3 and installed the github release into `/opt/easyrsa`.

Unfortunately executing the migration script fails with no error message. I examined the script and found that in the code below `$vars` should be populated

```
vars_setup() {
        # Try to locate a 'vars' file in order of location preference.
        # If one is found, source it
        vars=

        # set up program path
        prog_file="$0"
        prog_file2="$(which -- "$prog_file" 2>/dev/null)" && prog_file="$prog_file2"
        prog_file2="$(readlink -f "$prog_file" 2>/dev/null)" && prog_file="$prog_file2"
        prog_dir="${prog_file%/*}"
        prog_vars="${prog_dir}/vars"
        # set up PKI path
        pki_vars="${EASYRSA_PKI:-$PWD/pki}/vars"


        # command-line path:
        if [ ! -z "$EASYRSA_VARS_FILE" ]; then
          if [ ! -f "$EASYRSA_VARS_FILE" ]; then
                  # If the --vars option does not point to a file, show helpful error.
                        die "The file '$EASYRSA_VARS_FILE' was not found."
                fi
                vars="$EASYRSA_VARS_FILE"
        # PKI location, if present:
        elif [ -f "$pki_vars" ]; then
                vars="$pki_vars"
        # EASYRSA, if defined:
        elif [ -n "$EASYRSA" ] && [ -f "$EASYRSA/vars" ]; then
                vars="$EASYRSA/vars"
        # program location:
        elif [ -f "$prog_vars" ]; then
                vars="$prog_vars"
        fi
```

and `up23_manage_upgrade_23` depends on it, exiting without an error message:

```
up23_manage_upgrade_23 ()
{
        EASYRSA_UPGRADE_VERSION="v1.0a (2020/01/08)"
        EASYRSA_UPGRADE_TYPE="$1"

        # Verify all existing versions of vars/vars.bat
        if [ -f "$vars" ]
        then
                if grep -q 'Complain if a user tries to do this:' "$vars"
                then
                        EASYRSA_FOUND_VARS=1
                        EASYRSA_VARS_IS_VER3=1
                fi

                # Easyrsa v3 does not use NOR allow use of `export`.
                if grep -q 'export' "$vars"
                then
                        EASYRSA_FOUND_VARS=1
                        EASYRSA_VARS_IS_VER2=1
                        EASYRSA_VER2_VARSFILE="$vars"
                        EASYRSA_TARGET_VARSFILE="$vars"
                fi
        fi
...
        [ "$EASYRSA_FOUND_VARS" ] || return 0
```

IMHO two improvements should be made:
* `vars_setup()` should check `./vars` or `KEY_DIR/vars` allowing to find old separated vars files
* `up23_manage_upgrade()` should exit with a solid error message and not silently

**Comment by monsterry** [comment]
I just found, that executing easyrsa with `$EASYRSA_VARS_FILE` set, is sufficient for me. The error message should be fixed nevertheless.

```
EASYRSA_VARS_FILE=./vars /opt/easyrsa/easyrsa upgrade pki
```

**Comment by TinCanTech** [comment]
I believe the root cause is that `easyrsa` does not find `./vars` when the script is not located in the current directory.

**Comment by TinCanTech** [comment]
I already suggested a fix but it was rejected
