### ISSUE TITLE
No easyrsa script under folder easy-rsa after installing easy-rsa using sudo apt-get install easy-rsa

### ISSUE THREAD

**Issue by chdharm** [OpenVPN/easy-rsa#378]
I am installing open vpn server with easy-rsa.

While I am running few commands using ./easyrsa , I am getting the error that this is not found.

I searched under the easy-rsa folder and there was no ./easyrsa script.

**Comment by ecrist** [comment]
You need to look at the documentation for the package maintainer.  We do not maintain the packages that provide for any particular distribution.
