### ISSUE TITLE
EASYRSA_ALGO=ec, EASYRSA_KEY_SIZE=521 does not use secp521r1 curve

### ISSUE THREAD

**Issue by kyanha** [OpenVPN/easy-rsa#380]
When setting `EASYRSA_ALGO=ec` and `EASYRSA_KEY_SIZE=521`, easyrsa silently uses the secp384r1 curve (which limits the key bits to 384).

When setting `EASYRSA_ALGO=ec` and `EASYRSA_KEY_SIZE=256`, easyrsa silently uses the secp384r1 curve when secp256k1 or prime256v1 would be sufficient.

Expected behavior: easyrsa would automatically use the curve size large enough for the key size without using a curve larger than necessary and without having to muck around with the `openssl ecparam -list_curves` command or set the `EASYRSA_CURVE` variable.  Or, failing that, identify that the default curve would not be large enough for the number of bits requested, and display a warning.

**Comment by ecrist** [comment]
I thought I could add multiple milestones.  Guess not.

**Comment by edwardxia** [comment]
You need to set `EASYRSA_CURVE` instead of `EASYRSA_KEY_SIZE`.

`EASYRSA_CURVE` is for ECDSA and EdDSA, `EASYRSA_KEY_SIZE` is for RSA. Those are different systems.

**Comment by TinCanTech** [comment]
EasyRSA `--keysize` does not apply to elliptic curves.
