### ISSUE TITLE
how to use AES-256-CBC ?

### ISSUE THREAD

**Issue by kforner** [OpenVPN/easy-rsa#387]
Hello,

Very naive question: the default openvpn on ubuntu 16.04 does not seem to support AES-256-GCM.
Is is possible to use `easy-rsa` to configure the certificates for `AES-256-CBC` ?

Thanks!

**Comment by TinCanTech** [comment]
Given that AES-256-GCM is a cipher which is used by OpenVPN, you probably have an old version of OpenVPN.  See this for help:
https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos

**Comment by kforner** [comment]
> you probably have an old version of OpenVPN.

Yes that's true. We also have bunch of users. That's why I was looking for a way to use AES-256-CBC instead so that we do not have to reach out to all user and ask them to update their openvpn version. 
Does it make sense ? 

Thanks for your quick reply!

**Comment by TinCanTech** [comment]
Why are you asking on Easy-RSA bug tracker ?

**Comment by kforner** [comment]
I apologize for my poor understanding on that matter.
Here's what I understood:
- we setup an AWS VPN (for which we use the openvpn client) 
- the certificates for this VPN have been generated by `easy-rsa`, as recommenced by aws
- this vpn requires `AES-256-GCM`

I assumed that this `AES-256-GCM` requirement was induced by the certificates generated by `easy-rsa`, so I was trying to see if it was possible to set `easy-rsa` to use `AES-256-CBC` instead.

**Comment by TinCanTech** [comment]
> I assumed that this AES-256-GCM requirement was induced by the certificates generated by easy-rsa

Your assumption is incorrect.

Please start here:
https://forums.openvpn.net/viewtopic.php?f=30&t=22603

**Comment by kforner** [comment]
Thanks a lot. This was really helpful!
