### ISSUE TITLE
Need a way to import a certificate

### ISSUE THREAD

**Issue by lyoungstratus** [OpenVPN/easy-rsa#388]
Consider the case where two certificates are created in two different copies of a PKI directory. This could arise, for example, if the PKI directory is kept in a Git repository. Now after realizing that this fork has occurred, we would like to revoke both certificates. Without a way to import an existing certificate into a PKI, I don't see how to generate a CRL that covers both certificates.

**Comment by ecrist** [comment]
I won't say this is an invalid request, but this really dives into an oddball corner case.  Really, importing the certificate isn't necessary, it just needs to be placed in the right path within the pki dir for easy-rsa to find it.

I'll leave this open for now, but I'm not sure we'll ever actually do anything to support an import mechanism.

**Comment by lyoungstratus** [comment]
I thought it also needs an entry in the  index file.  I did have occasion to figure out what I had to do to satisfy the revocation function, and it turned out to be easy enough.

**Comment by TinCanTech** [comment]
What did you _figure out_ ?

**Comment by TinCanTech** [comment]
EasyRSA should not be responsible for how you screw up your PKI.
