### ISSUE TITLE
export-zip

### ISSUE THREAD

**Issue by jrocha** [OpenVPN/easy-rsa#392]
Would it be ok to write a patch for a feature to export required files for client (ca.crt, client-key.crt, client-key.key) to zip file?

I'm planning to add something like `./easyrsa export-zip client-key`

**Comment by TinCanTech** [comment]
Possible candidate for https://github.com/TinCanTech/easy-tls ?

**Comment by ecrist** [comment]
This would be possible, and a good candidate for acceptance into the code base.

**Comment by ecrist** [comment]
> Possible candidate for https://github.com/TinCanTech/easy-tls ?

That particular bit of code isn't yet included in the base EasyRSA distribution.  We're happy to accept it on another PR if it meets project requirements.

**Comment by TinCanTech** [comment]
In my personal opinion, the compression of an inline file is as good as pointless. Distributing an inline file verses a compressed file makes no significant difference.
