### ISSUE TITLE
Easy-RSA no access to CRL.pem by nobody:nogroop

### ISSUE THREAD

**Issue by hellkaim** [OpenVPN/easy-rsa#393]
Hi,
According to the line below
https://github.com/OpenVPN/easy-rsa/blob/e68faed0a3832028ed2e9999cd2013d9664bd067/easyrsa3/easyrsa#L1309

Easy-RSA is generating a file in a directory OpenVPN will not be able to access at all as it mostly run under nobody:nogroup credentials.
Please mention somewhere in the Doc's that it should be copied in an appropriate location or otherwise made accessible to nobody user or let's create a workaround like adding a line before
https://github.com/OpenVPN/easy-rsa/blob/e68faed0a3832028ed2e9999cd2013d9664bd067/easyrsa3/easyrsa#L1314
with something like `cp and chown`.
The only issue I can see here is as Easy-RSA is a platform agnostic there will be a headache to define a proper location.

**Comment by ecrist** [comment]
This isn't really an EasyRSA issue, as it's just permissioning on your system, and how you're deploying the CRL.  What you could do in your case is have a cron job that runs periodically to copy the file and change ownership/permissions for your OpenVPN process.
