### ISSUE TITLE
"Extra Arguments Given" when using build-ca

### ISSUE THREAD

**Issue by tgross35** [OpenVPN/easy-rsa#395]
Running `./easyrsa build-ca` from mksh asks for a password, then always says:

```
Enter New CA Key Passphrase:
Re-Enter New CA Key Passphrase:
Extra arguments given.
genrsa: Use -help for summary.

Easy-RSA error:

Failed create CA private key
```

This happens even when the passwords are identical.

Running with the nopass option completes successfully

Windows 10, EasyRSA-3.0.7

**Comment by ecrist** [comment]
There are some special characters that cannot be escaped. Can you confirm with a simple password or let us know what the special character is?

Eric Crist

**Comment by tgross35** [comment]
I originally tried it with special character passwords including * or @, but later I tested with just "1234" and it still refused to work. I will have to try again starting from scratch

**Comment by Saicopate** [comment]
Same problem here.

**Comment by node13h** [comment]
This issue might be caused by spaces in the path easy-rsa is installed in. It derives temporary directory path from it's own by default and passes it to `openssl` unquoted. A workaround for this is to set the `EASYRSA_TEMP_DIR` to a path without spaces (please make sure the path is secured and cannot be accessed by other users as this path is used to temporarily store secrets.

**Comment by GMasta2000** [comment]
In easyrsa script for rsa on line 672, insert code
```
            elif [ "rsa" = "$EASYRSA_ALGO" ]; then
                crypto_opts="$crypto_opts -passout file:$out_key_pass_tmp"
```

Result
```
        crypto_opts="$crypto"
        if [ -z "$EASYRSA_PASSOUT" ]; then
            if [ "ed" = "$EASYRSA_ALGO" ]; then
                crypto_opts="$crypto_opts -pass file:$out_key_pass_tmp"
            elif [ "rsa" = "$EASYRSA_ALGO" ]; then
                crypto_opts="$crypto_opts -passout file:$out_key_pass_tmp"
            else
                crypto_opts="$crypto_opts -passin file:$out_key_pass_tmp"
            fi
        fi
```

openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017

No -passin option
"-passout arg    output file pass phrase source"
Sorry for my English!

**Comment by steffenfrederiksen** [comment]
> This issue might be caused by spaces in the path easy-rsa is installed in. It derives temporary directory path from it's own by default and passes it to `openssl` unquoted. A workaround for this is to set the `EASYRSA_TEMP_DIR` in the `vars` file to a path without spaces (please make sure the path is secured and cannot be accessed by other users as this path is used to temporarily store secrets.

I can confirm this is still an issue if the path to easy-rsa contains spaces, for exsample. C:\Program Files\OpenVPN\EasyRSA-3.0.8
If easy rsa is locate in a path without any spaces, then no problem.

**Comment by jasenmoloy** [comment]
+1 to @steffenfrederiksen's comment. Ran into the same issue, moved the easy-rsa folder to a path without `Program Files` in the path, and it was successful.

**Comment by TinCanTech** [comment]
Please try again with current `git/master`

**Comment by mcdado** [comment]
> Please try again with current `git/master`

I guess I'm just a little bit too early for a packaged Windows build 😄 

I just installed OpenVPN 2.5.6 on Windows Server 2019, and had to reinstall in "C:\OpenVPN" instead of "C:\Program Files\OpenVPN" because of this problem. Thanks for the solution 🙂

**Comment by TinCanTech** [comment]
The version packaged with Windows has not been updated.

**Comment by mcdado** [comment]
BTW, I was looking for a place to report a minor inconvenience, but couldn't find it: the sample config files in the Windows release seem to suffer from a bad conversion of line endings, resulting in neither LF nor CRLF, but CRCRLF, which Notepad, Notepad++ (and I suspect other editors) identify as Macintosh (Classic) and display an empty line every other one.

**Comment by TinCanTech** [comment]
> I was looking for a place to report a minor inconvenience, but couldn't find it

How about: https://github.com/OpenVPN/easy-rsa/issues

I've just tested this and the files are all `LF` only.

**Comment by mcdado** [comment]
> > I was looking for a place to report a minor inconvenience, but couldn't find it
> 
> How about: https://github.com/OpenVPN/easy-rsa/issues
> 
> I've just tested this and the files are all `LF` only.

That didn't seem right because I imagine this is about OpenVPN daemon and not the easy-rsa scripts, and [openvpn/openvpn](https://github.com/OpenVPN/openvpn) doesn't have Issues turned on.

I'm referring to server.ovpn and client.ovpn in the sample-config directory in OpenVPN for Windows:
![Screenshot 2022-04-06 at 17 17 37](https://user-images.githubusercontent.com/898057/162009927-3e83235a-de88-4135-86f3-e77f2606de29.png)

I also just checked in a Debian installation under `/usr/share/doc/openvpn/examples/sample-config-files` and indeed the file has LF line endings. As I said before, my best guess is that when the Windows package gets compiled, there's a bad conversion of lines ending 🤔

**Comment by ValerioParisMitritsakis** [comment]
On Windows one quick-and-dirty fix is to use subst to assign a drive letter to the path as follows:

subst x:  C:\Program Files\OpenVPN\easy-rsa

Then switch to drive letter X and run it from there. Make sure the drive letter X is not in use on your computer. If it is just use a different drive letter. Once you are done just run subst x: /D to delete the substitution.

Hope it helps.

**Comment by TinCanTech** [comment]
For the record: Easy-RSA, from version 3.0.8 onward, should no longer have problems with spaces in the PATH.  If anybody finds that is not the case then please open a new issue here.

**Comment by kimboslice99** [comment]
This is still an issue, fresh install has 3.0.8

Takes 5 minutes to identify yourself

```iwr https://swupdate.openvpn.org/community/releases/OpenVPN-2.5.8-I604-amd64.msi -Outfile '.\OpenVPN-2.5.8-I604-amd64.msi'```

Install, then

```
cd 'C:\Program Files\OpenVPN\easy-rsa'
.\EasyRSA-Start.bat
./easyrsa init-pki
./easyrsa build-ca
```
At the very least, there should be a resolution in the readme

**Comment by TinCanTech** [comment]
@kimboslice99 Which version of **OpenSSL** do you have installed ?

**Comment by ecrist** [comment]
Also, v3.0.8 isn't current.

Eric Crist

On Dec 3, 2022, at 06:34, TinCanTech ***@***.***> wrote:

﻿

@kimboslice99<https://github.com/kimboslice99> Which version of OpenSSL do you have installed ?

**Comment by kimboslice99** [comment]
```
# ./easyrsa version
EasyRSA Version Information
Version:     3.0.8
Generated:   Wed Sep 16 07:52:24 CDT 2020
SSL Lib:     OpenSSL 1.1.1s  1 Nov 2022
Git Commit:  a9cecc747c419197d9540ccd46259559e271788a
Source Repo: https://github.com/OpenVPN/easy-rsa
```
I'm using the included OpenSSL

Setup was just in a development VM, so I used the nopass option to dodge this issue

**Comment by TinCanTech** [comment]
> @TinCanTech
> 
> This is still an issue, fresh install has 3.0.8
> 
> Takes 5 minutes to identify yourself
> 
> `iwr https://swupdate.openvpn.org/community/releases/OpenVPN-2.5.8-I604-amd64.msi -Outfile '.\OpenVPN-2.5.8-I604-amd64.msi'`
> 
> Install, then
> 
> ```
> cd 'C:\Program Files\OpenVPN\easy-rsa'
> .\EasyRSA-Start.bat
> ./easyrsa init-pki
> ./easyrsa build-ca
> ```
> 
> At the very least, there should be a resolution in the readme

_There should be_ more detail here. **eg**: command output.

**Comment by M2000h** [comment]
I had the same problem. Your password should start with "pass:". For exemple, for password "1234" give "pass:1234" to easyrsa. This works for me.
