### ISSUE TITLE
"genrsa: Unrecognized flag passin" when using build-ca

### ISSUE THREAD

**Issue by ZOOUQinn** [OpenVPN/easy-rsa#400]
Get message bellow, running ./easyrsa build-ca

```
$ ./easyrsa build-ca
Using SSL: openssl OpenSSL 1.1.1g FIPS  21 Apr 2020

Enter New CA Key Passphrase:
Re-Enter New CA Key Passphrase:
genrsa: Unrecognized flag passin

Easy-RSA error:

Failed create CA private key
```

Are there anyone can figure it out?

By the way, the OS is Ubuntu.

**Comment by ecrist** [comment]
What version of EasyRSA?

Eric Crist

**Comment by ZOOUQinn** [comment]
Easy-RSA 3

In fact, I followed steps in [Easy-RSA 3 Quickstart README](https://github.com/OpenVPN/easy-rsa/blob/master/README.quickstart.md)

**Comment by ZOOUQinn** [comment]
> What version of EasyRSA? Eric Crist
> […](#)
> On Aug 29, 2020, at 5:21 AM, ZOOU Qinn ***@***.***> wrote: ﻿ Get message bellow, running ./easyrsa build-ca $ ./easyrsa build-ca Using SSL: openssl OpenSSL 1.1.1g FIPS 21 Apr 2020 Enter New CA Key Passphrase: Re-Enter New CA Key Passphrase: genrsa: Unrecognized flag passin Easy-RSA error: Failed create CA private key Are there anyone can figure it out? By the way, the OS is Ubuntu. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Easy-RSA 3

In fact, I followed steps in [Easy-RSA 3 Quickstart README](https://github.com/OpenVPN/easy-rsa/blob/master/README.quickstart.md)

**Comment by ZOOUQinn** [comment]
> Get message bellow, running ./easyrsa build-ca
> 
> ```
> $ ./easyrsa build-ca
> Using SSL: openssl OpenSSL 1.1.1g FIPS  21 Apr 2020
> 
> Enter New CA Key Passphrase:
> Re-Enter New CA Key Passphrase:
> genrsa: Unrecognized flag passin
> 
> Easy-RSA error:
> 
> Failed create CA private key
> ```
> 
> Are there anyone can figure it out?
> 
> By the way, the OS is Ubuntu.

Well, the issue will not occur if I download ver3.0.7 from releases page instead of 'git clone' one.

**Comment by ZOOUQinn** [comment]
> What version of EasyRSA? Eric Crist
> […](#)
> On Aug 29, 2020, at 5:21 AM, ZOOU Qinn ***@***.***> wrote: ﻿ Get message bellow, running ./easyrsa build-ca $ ./easyrsa build-ca Using SSL: openssl OpenSSL 1.1.1g FIPS 21 Apr 2020 Enter New CA Key Passphrase: Re-Enter New CA Key Passphrase: genrsa: Unrecognized flag passin Easy-RSA error: Failed create CA private key Are there anyone can figure it out? By the way, the OS is Ubuntu. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks for your reminding, I figure it out that I used wrong version.
