### ISSUE TITLE
genrsa: Unrecognized flag passin

### ISSUE THREAD

**Issue by ionred** [OpenVPN/easy-rsa#403]
Recent builds are returning this error. 
____
root@SYSNAME:/mnt/VPN/easy-rsa/easyrsa3# easyrsa build-ca
Using SSL: openssl OpenSSL 1.1.1g  21 Apr 2020

Enter New CA Key Passphrase:
Re-Enter New CA Key Passphrase:
**genrsa: Unrecognized flag passin**

Easy-RSA error:

Failed create CA private key
____

Perhaps related to commit 768b66cfdd26b510e04686776e28368b02072aac ?

**Comment by katherine-curtis** [comment]
This appears related to https://github.com/OpenVPN/easy-rsa/pull/399/files#diff-231cb43897d7aa2a98dfda5720c2b40fR673
