### ISSUE TITLE
easy-rsa upgrade - documentation

### ISSUE THREAD

**Issue by dsommers** [OpenVPN/easy-rsa#406]
We want to include the latest easy-rsa 3 release in the soon coming OpenVPN 2.5 release, where it is bundled in the Windows installer.

From a quick glance, it seems there is missing some documentation *how* to perform upgrade from prior easy-rsa 2 releases.  A quick howto which we can include in the bundle and/or point at somewhere would be appreciated.

The OpenVPN 2.5_rc1 release is currently scheduled to Monday September 21, 2020.  We can probably do that release without docs if we have a guarantee the docs will arrive in time for the final 2.5.0 release.

**Comment by TinCanTech** [comment]
https://community.openvpn.net/openvpn/wiki/easyrsa-upgrade

**Comment by ecrist** [comment]
I also need to push an update for v3.0.9 that either downgrades OpenSSL or fixes the bug 1.1.1g is causing.  I’ll try to get to that tonight.

Eric F Crist
Mobile: 612-998-3588

**Comment by dsommers** [comment]
@mattock Any issues with just pointing at the URL from @TinCanTech ?

**Comment by ecrist** [comment]
I’ve re-released the v3.0.8 packages for Windows and this appears to be working now with the older OpenSSL library and binaries.

Eric F Crist

**Comment by TinCanTech** [comment]
@dsommers the link above was something i put together while working on the upgrade.

It could do with improvement, which is why it is on the wiki, so that i can edit it at will.

**Comment by dsommers** [comment]
> @dsommers the link above was something i put together while working on the upgrade.
> 
> It could do with improvement, which is why it is on the wiki, so that i can edit it at will.

Alright, would you be willing to whip together something we can ship in the 2.5 release, based on that wiki page?

**Comment by TinCanTech** [comment]
Sorry, I would **not** _be willing to whip together something_ -- I will edit the wiki as needed.

Personally, I do not believe EasyRSA-3 is entirely ready for _mass deployment_.

**Comment by ecrist** [comment]
I can put something together in the official docs based on what is in the wiki. Give me a day or two.
