### ISSUE TITLE
OpenSSL 3.0.2 - OpenSSL 1.1.1n

### ISSUE THREAD

**Issue by Neustradamus** [OpenVPN/easy-rsa#407]
EDIT: At this date: 2022-03-15:
OpenSSL 3.0.2 and OpenSSL 1.1.1n out:
- https://www.openssl.org/

Time to update in this repo:
- https://github.com/OpenVPN/easy-rsa/search?p=1&q=openssl

**Comment by TinCanTech** [comment]
Thanks!

**Comment by Neustradamus** [comment]
@TinCanTech: It is not solved...

Currently:
- 14-Dec-2021: OpenSSL 3.0.1 is now available, including bug and security fixes
- 14-Dec-2021: OpenSSL 1.1.1m is now available, including bug fixes

**Comment by TinCanTech** [comment]
EasyRSA has made no commitment (at this time) to provide support for OpenSSL 3.0.1 - That will come in time.

EasyRSA ought not be distributing OpenSSL binaries at all - So this is currently unclear.

**Comment by TinCanTech** [comment]
This issue can be followed here: #489

**Comment by Neustradamus** [comment]
@TinCanTech: Can you remove all OpenSSL binaries because there are?
- https://github.com/OpenVPN/easy-rsa/tree/master/distro/windows

**Comment by ecrist** [comment]
The ticket here just states versions of OpenSSL. What is the desired goal?

An update to 1.1.1m our support for 3.x?

**Comment by TinCanTech** [comment]
My reason to re-open this is because #489 is resolved but this one is left hanging .. a decision would be appreciated here because I do not fully understand the reason EasyRSA distributes OpenSSL.  I leave that in your hands.

**Comment by Neustradamus** [comment]
Note: Announcement from yesterday:
- 15-Mar-2022: OpenSSL 3.0.2 is now available, including bug and security fixes
- 15-Mar-2022: OpenSSL 1.1.1n is now available, including bug and security fixes

**Comment by TinCanTech** [comment]
https://github.com/OpenVPN/easy-rsa/commit/2155d2c95c60bbf1442b177aceb3556f5b3b66a7

OpenSSL 1.1.1m also fails on actions.

**Comment by TinCanTech** [comment]
EasyRSA built OpenSSL 1.1.1m does not work.

**Comment by TinCanTech** [comment]
https://github.com/OpenVPN/easy-rsa/commit/ed67df9578dedec4af818941582f91486999489a
