### ISSUE TITLE
ECDH under Windows in latest version

### ISSUE THREAD

**Issue by joksik** [OpenVPN/easy-rsa#408]
Hello i download latest version easy-rsa for Windows EasyRSA-3.0.8 x64

after i rename file vars.example to vars and edit vars file with this change:
set_var EASYRSA_ALGO		ec
set_var EASYRSA_CURVE		secp384r1

i do:
cd C:\Program Files\OpenVPN\easy-rsa\
.\EasyRSA-Start.bat
./easyrsa init-pki
./easyrsa build-ca nopass
./easyrsa gen-req Myserver nopass

and in last command gen-reg i have error:
Easy-RSA error:
Failed to generate request

when i change again set_var EASYRSA_ALGO from "ec" to "rsa" last command 
./easyrsa gen-req Myserver nopass 
works with no error.
what i do wrong or what i miss when i want use ec ?

**Comment by joksik** [comment]
weird.
 today i accidentally moved the whole easy-rsa folder from C:\Program Files\OpenVPN\easy-rsa to my download folder and in another folder I can sucesfull generate ec certificate. 
So I have given full permissions to C:\Program Files\OpenVPN\ but unfortunately when generating the ec certificate from Program Files I cannot however from any other location like Downloads or Desktop i can really weird

**Comment by TinCanTech** [comment]
Perhaps the space in `\Program Files` is confusing EasyRSA 3.0.8 somehow ?

**Comment by joksik** [comment]
Maybe first I installed openvpn 2.5 rc1 then openvpn 2.5 rc2 also couldn't generate ec keys (with rsa 
I had no problem) so i try the latest version easy-rsa from github and after unpack put into "Program Files" like openvpn installer does by default.

if someone tells me how to provide more logs under Windows I will be happy to help

**Comment by gilbertosilvaoliv** [comment]
> weird.
> today i accidentally moved the whole easy-rsa folder from C:\Program Files\OpenVPN\easy-rsa to my download folder and in another folder I can sucesfull generate ec certificate with gen-req command.
> So I have given full permissions to C:\Program Files\OpenVPN\ but unfortunately when generating the ec certificate from Program Files I cannot however from any other location like Downloads or Desktop i can really weird

This works for me, Thank you!
May be the space on path "program files".

**Comment by TinCanTech** [comment]
Please test again with current `git/master`

**Comment by TinCanTech** [comment]
#412

**Comment by TinCanTech** [comment]
Follow up set to #412 - Closing.
