### ISSUE TITLE
Allow the CA to be inspected by  easyrsa show-cert

### ISSUE THREAD

**Issue by jaydub** [OpenVPN/easy-rsa#41]
The show-cert command only allows inspection of cerificates under pki/issued, so to inspect the CA certificate, it needs to be linked or copied into pki/issued at creation time.

(Given that it's possible to include a directory separator (ie '\', '/') in the free form distinguished name of the CA, it might be best to just link or copy to "ca.crt" or "CA.crt".)

**Comment by mistriel** [comment]
@jaydub  I'm also into that issue exactly, while its feasible to query the CA certificate using openSSL : 
```sh
openssl x509 -in <YourCAdir>/ca.crt -text -noout
```
its not possible to use the same `show-cert` command : 

```sh
 easyrsa --pki-dir=<YourCAdir>  show-cert ca.crt full
```

**Comment by TinCanTech** [comment]
Closed via https://github.com/OpenVPN/easy-rsa/commit/087d36a0d8b42eda48af596df5abf1c41065c279
