### ISSUE TITLE
Unable to get private keys in RSA form

### ISSUE THREAD

**Issue by ipalazzi** [OpenVPN/easy-rsa#410]
After creating a CA key-pair, when I request a new entity certificate using the gen-req function I see that private key is generated in PEM instead of RSA. I noticed this reading the key file that starts with `-----BEGIN PRIVATE KEY-----` instead of `-----BEGIN RSA PRIVATE KEY-----`.

Consider that the variable `EASYRSA_ALGO` is set to `rsa` (`set_var EASYRSA_ALGO rsa`).

Am I missing something?

**Comment by TinCanTech** [comment]
> I see that private key is generated in PEM instead of RSA

You misunderstand.

All certificates and keys generated by EasyRSA are in Private Email (PEM) format.

The certificate shows: `Signature Algorithm: sha256WithRSAEncryption` - **RSAEncryption**

OpenSSL decides which details to add to the `BEGIN`/`END` markers.
