### ISSUE TITLE
Spaces in PATH

### ISSUE THREAD

**Issue by TinCanTech** [OpenVPN/easy-rsa#412]
_Originally posted by @node13h in https://github.com/OpenVPN/easy-rsa/issues/395#issuecomment-674069768_

The comment above is probably correct.  

I used EasyRSA from **OpenVPN-2.5-rc3-I601-x86.msi** which ships with patch https://github.com/OpenVPN/easy-rsa/commit/1e98ba808c9c90629595827773a66b59f8c9b927 applied.

`build-ca` fails with the OpenSSL message `Extra arguments given`.

**Workaround**: create a directory with no spaces in the name, eg. `C:\temp`
In EasyRSA `vars` use `set_var EASYRSA_TEMP_DIR	"/temp"`
and run `build-ca` again .. which now works.

**Comment by TinCanTech** [comment]
For debugging; using `build-ca`, this is the command which fails:
```
Enter New CA Key Passphrase:
Re-Enter New CA Key Passphrase:
openssl genrsa -out C:/Program Files/OpenVPN/easy-rsa/pki/easy-rsa-3156.a00300/t
mp.a03980 -aes256 -passout file:C:/Program Files/OpenVPN/easy-rsa/pki/easy-rsa-3
156.a00300/tmp.a03612  2048
Extra arguments given.
genrsa: Use -help for summary.
```

**Comment by BlackFIlms** [comment]
Same issue. =/

**Comment by y0y0z** [comment]
```shell
export EASYRSA_TEMP_DIR="/temp"
./easyrsa build-ca
````

worked  for me

**Comment by oistri** [comment]
> still happens for `OpenVPN-2.5.0-I601-amd64.msi`
> 
> ```shell
> export EASYRSA_TEMP_DIR="/temp"
> ./easyrsa build-ca
> ```
> 
> worked for me


i use OpenVPN-2.5.3-I601-amd64.msi
i was getting error: "Extra arguments given." when OpenVPN was installed to C:/Program Files/OpenVPN
i re-installed to C:\openvpn\ and was getting error: "Error reading password from BIO"

And Your line "export EASYRSA_TEMP_DIR="/temp"" helped! 
Thank you!

**Comment by TinCanTech** [comment]
https://github.com/OpenVPN/easy-rsa/commit/8e7bac695df546189c447b66b1a95c1de36919cf

**Comment by TinCanTech** [comment]
Closed via https://github.com/OpenVPN/easy-rsa/commit/73e674a5eaaa697180e6e0f9d7597695fc3d2707

And other patches for 'spaces in path'.
