### ISSUE TITLE
How to run easy-rsa beautifully

### ISSUE THREAD

**Issue by XIYO** [OpenVPN/easy-rsa#415]
Ubuntu 20.04 LTS

I'm not good at English, so I used a translator.

I installed easy-rsa via apt to make an openvpn server.
I tried easy-rsa to run this, but nothing came out.
I tried 
>easyrsa, man easy-rsa, man easyrsa

but nothing happened.
So I found the location with 
>find / -name easy-rsa 

and ran it directly.
I think this is not a beautiful way. Is there a cooler way?

**Comment by Alexhha** [comment]
I checked in docker
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

# dpkg -L easy-rsa
/.
/usr
/usr/bin
/usr/bin/make-cadir
/usr/share
/usr/share/doc
/usr/share/doc/easy-rsa
/usr/share/doc/easy-rsa/NEWS.Debian.gz
...
...
...
/usr/share/easy-rsa/x509-types/code-signing
/usr/share/easy-rsa/x509-types/server
/usr/share/easy-rsa/x509-types/serverClient
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/make-cadir.1.gz
```

It should be located in `/usr/share/easy-rsa`
```
# cd /usr/share/easy-rsa/
# ./easy-rsa init-pki
# ./easy-rsa build-ca nopass
...
...
...
```

**Comment by XIYO** [comment]
I used Google Translator.
If it is a polite sentence or the grammar is strange, please mess with it.
I will fix it. Thank you.

Thanks for the answer.
That's not what I want.
Because it looks for the file location exactly like "find".

What I'm looking for is a way to use it like "make-cadir".
(I found this command on the web.)
I read the quick guide and searched for references.
But I couldn't find anything describing the command for "make-cadir". (Is it something I couldn't find?)

What I want is a command like "make-cadir",
Installed with package manager,
If you are new to easy-rsa, where can you find the "make-cadir" command?

Thanks in advance to those who help.

**Comment by Alexhha** [comment]
> What I'm looking for is a way to use it like "make-cadir".

not sure what do you mean. make-cadir it's a bash script that shipped with easy-rsa package. There is no point to call it directly. You should use /usr/share/easy-rsa/easyrsa

> If you are new to easy-rsa, where can you find the "make-cadir" command?
```
# dpkg -L easy-rsa | grep make-cadir$
/usr/bin/make-cadir
```

**Comment by ecrist** [comment]
I'm closing this.  The real question is for the package maintainer, who I have no contact/relationship with.
