### ISSUE TITLE
$EASYRSA_OPENSSL is ignored on Mac

### ISSUE THREAD

**Issue by ChrisBaker97** [OpenVPN/easy-rsa#416]
I'm using macOS 14.6. I've installed OpenSSL with [Homebrew](https://github.com/Homebrew), which links it into `/usr/local/opt/openssl@1.1/bin/openssl` to prevent conflicts with the system LibreSSL at `/usr/bin/openssl`:

```sh
$ type openssl
openssl is /usr/bin/openssl
$ openssl version
LibreSSL 2.6.5
$ /usr/bin/openssl version
LibreSSL 2.6.5
$ /usr/local/opt/openssl@1.1/bin/openssl version
OpenSSL 1.1.1h  22 Sep 2020
```

I've renamed `vars.example` to `vars` and edited it to include:
```
set_var EASYRSA_OPENSSL	"/usr/local/opt/openssl@1.1/bin/openssl"
```

I've also defined `$EASYRSA` to point to the location of the `vars` file, and other configuration options specified in there seem to be getting read:
```
$ echo $EASYRSA
/usr/local/opt/easy-rsa/share
$ grep EASYRSA_OPENSSL $EASYRSA/vars
set_var EASYRSA_OPENSSL	"/usr/local/opt/openssl@1.1/bin/openssl"
#set_var EASYRSA_OPENSSL	"C:/Program Files/OpenSSL-Win32/bin/openssl.exe"
```

However, `easyrsa` seems to be using the system's LibreSSL rather than Homebrew's OpenSSL, unless I explicitly place OpenSSL at the front of my path:
```
$ easyrsa --version
EasyRSA Version Information
Version:     ~VER~
Generated:   ~DATE~
SSL Lib:     LibreSSL 2.6.5
Git Commit:  ~GITHEAD~
Source Repo: https://github.com/OpenVPN/easy-rsa
$ EASYRSA_OPENSSL="/usr/local/opt/openssl@1.1/bin/openssl" easyrsa --version
...
SSL Lib:     LibreSSL 2.6.5
...
$ OPENSSL="/usr/local/opt/openssl@1.1/bin/openssl" easyrsa --version
...
SSL Lib:     LibreSSL 2.6.5
...
$ PATH="/usr/local/opt/openssl@1.1/bin:$PATH" easyrsa --version
...
SSL Lib:     OpenSSL 1.1.1h  22 Sep 2020
...
```

Am I doing something wrong here, or is there a bug that's causing `easyrsa` to ignore both the `vars` configured and environment set `$EASYRSA_OPENSSL`?

**Comment by TinCanTech** [comment]
> is there a bug that's causing `easyrsa` to ignore both the `vars` configured and environment set `$EASYRSA_OPENSSL`?

Yes, there is a bug.

The `print_version()` function implicitly uses `$PATH` not `$EASYRSA_OPENSSL` to call `openssl` binary.

**Comment by ChrisBaker97** [comment]
Thanks. Does this only affect `easyrsa --version`? In other words, everything else will use what's specified in `$EASYRSA_OPENSSL`?

**Comment by ecrist** [comment]
Only affects the —version argument.  I’ll push a patch for this.

Eric F Crist
Mobile: 612-998-3588

**Comment by ChrisBaker97** [comment]
Thanks, @ecrist. I tested this, and it does seem to work if the `$EASYRSA_OPENSSL` environment variable is set:
```
$ EASYRSA_OPENSSL="/usr/local/opt/openssl/bin/openssl" easyrsa --version                                              ✔  11:38:35 
EasyRSA Version Information
Version:     ~VER~
Generated:   ~DATE~
SSL Lib:     OpenSSL 1.1.1h  22 Sep 2020
Git Commit:  ~GITHEAD~
Source Repo: https://github.com/OpenVPN/easy-rsa
```
but not if it's only set in `vars`:
```
$ echo $EASYRSA
/usr/local/opt/easy-rsa/share
$ grep EASYRSA_OPENSSL $EASYRSA/vars
set_var EASYRSA_OPENSSL	"/usr/local/opt/openssl@1.1/bin/openssl"
#set_var EASYRSA_OPENSSL	"C:/Program Files/OpenSSL-Win32/bin/openssl.exe"
$ easyrsa --version
/usr/local/bin/easyrsa: line 2376: version: command not found
EasyRSA Version Information
Version:     ~VER~
Generated:   ~DATE~
SSL Lib:
Git Commit:  ~GITHEAD~
Source Repo: https://github.com/OpenVPN/easy-rsa
```

**Comment by ecrist** [comment]
Don't use the -- in front of the option. 

Eric Crist

**Comment by ChrisBaker97** [comment]
Hmm. Okay, that works. I don't understand why `--version` works if `$EASYRSA_OPENSSL` isn't defined in `vars` or if it's overridden by the environment, but I guess it doesn't matter.
