### ISSUE TITLE
 EASYRSA_REQ_CN/--req-cn not used

### ISSUE THREAD

**Issue by sbstnmrwld** [OpenVPN/easy-rsa#420]
Hello,

when I `easyrsa --dn-mode="org" --req-cn="MY CN" gen-req test nopass`, the default CN is always the NameOfRequest

```
Country Name (2 letter code) [US]:
State or Province Name (full name) [California]:
Locality Name (eg, city) [San Francisco]:
Organization Name (eg, company) [Copyleft Certificate Co]:
Organizational Unit Name (eg, section) [My Organizational Unit]:
Common Name (eg: your user, host, or server name) [test]:
```

It is the same behaviour when I use `build-client-full` and `--batch`.

I need to have different CN and NameOfRequest.

Regards

Edit:
I think that the problem was addressed in the following PR: https://github.com/OpenVPN/easy-rsa/pull/227

**Comment by TinCanTech** [comment]
Linking: #456
