### ISSUE TITLE
Question: After revoking a cert, what needs to be kept around?

### ISSUE THREAD

**Issue by sebrandon1** [OpenVPN/easy-rsa#421]
Hello!  I just have a quick question about what needs to be kept around after revoking a cert.

After revoking a cert using `easyrsa revoke`, then running `easyrsa gen-crl` which generates/updates the `crl.pem` file, the revoked cert is listed with an "R" in pki/index.txt and the leftover `<ID>.pem` file is left in `certs_by_serial`.

Since the referenced revoked cert is listed in the `crl.pem`, am I good to remove the `<ID>.pem` file in `certs_by_serial`?  

Just trying to figure out what needs to be kept around after the revocation process.

Thanks!

**Comment by sebrandon1** [comment]
Just digging through some previously written issues, [this one](https://github.com/OpenVPN/easy-rsa/issues/104) seems close to what I'm asking but doesn't quite touch on what happens if I remove `/pki/certs_by_serial/<ID>.pem` after it has been revoked.

**Comment by sebrandon1** [comment]
@QueuingKoala seems like you were the last one to touch that section of the documentation.  Do you happen to know?  I know that was like 7 years ago so it's a bit of stretch.

**Comment by ecrist** [comment]
I will look at this tonight or tomorrow.

**Comment by sebrandon1** [comment]
@ecrist Any updates?  Just want to know what is good to "throw away" when done issuing the revoke.

**Comment by ecrist** [comment]
Sorry for the delay.  You *really* don't have to keep anything around.  If you want to reissue a similar certificate it can be useful to keep the CSR around, but that's not required.

EasyRSA uses the certificate itself to revoke it, but once it's been revoked, you don't need anything.  In most PKI setups where the "P" really means public, the CSR is the only thing the CA receives from the user to generate a certificate.  The private key is typically not shared with the CA.  In corporate environments, though, the CA (corporation) usually does the whole thing (generate key, build CSR, sign CSR, issue certificate).

I hope this clears things up.

**Comment by sebrandon1** [comment]
No worries!  This is good to know.  Thanks!

**Comment by sebrandon1** [comment]
@ecrist One more question, what does `update-db` have to do with any of this revoking of certificates?

Does it have to be issued for the revoke to become "official" or does `update-db` just update the index.txt with an updated timestamp?  Trying to figure out what the doc is talking about.

https://www.sbarjatiya.com/notes_wiki/index.php/Easy-rsa

Thanks!

**Comment by ecrist** [comment]
A revocaion is really only "valid" if it's present in the CRL file, and that CRL is referenced by consumers.  If nobody is looking at the CRL file, then there isn't any such thing as a revoked certificate.

You can set a timestamp for next CRL update, and then you're expected to update the CRL before then, even if the contents are the same.  If the CRL isn't updated, and a consumer references it, they will refuse to honor the CRL.

**Comment by pedrevans** [comment]
If the CRL has expired, not only will it not be honoured, but everybody else will be shut out from the VPN too, even if their profiles are valid. As we manage our profiles and the CRL on a machine separate from the VPN server this is a bit of a pain, so in the `vars` file we set the expiration date of the CRL far in the future.

    set_var EASYRSA_CRL_DAYS 10000
