### ISSUE TITLE
missing windows batch files

### ISSUE THREAD

**Issue by lazna** [OpenVPN/easy-rsa#422]
Just upgrade OpenVPN to ver 2.5 and it seems switch from EasyRSA 2.x to 3.x where most of batch files (i am use) missing. Is there any recomended method to create a new PKI infrastructure in windows environment in ver 3?

Second question:

Trying to automatize creation of users certificate in the environment of windows batch scripting. Have three command derived from previously present EasyRSA bat files:
```
rem creating request for new certificate
"%HOME%\..\bin\openssl.exe" req -days 3650 -nodes -new -keyout "%USER_DIR%\\%NAME_CN%.key" -out "%USER_DIR%\\%NAME_CN%.csr"  -subj "/C=%KEY_COUNTRY%/ST=%KEY_PROVINCE%/L=%KEY_CITY%/O=%KEY_ORG%/OU=%KEY_OU%/CN=%NAME_CN%"

rem signing request by certification authority key, creating cert/key pair
"%HOME%\..\bin\openssl.exe" ca -days 3650 -cert "-out "%USER_DIR%\\%NAME_CN%.crt" -in "%USER_DIR%\\%NAME_CN%.csr" -batch

rem check if created client certificate is valid
"%HOME%\..\bin\openssl.exe" verify -CAfile "%HOME%\\%CA_KEYS%\\%CA_CRT%.crt" -purpose sslclient "%USER_DIR%\\%NAME_CN%.crt" 
```
is it possible to add some command line parameters to '-config' option to avoid using .cfg file? I have the translating of .cfg file into command line parameters is possible  but do not found any examples.

OpenVPN documentation still EasyRSA 2.x oriented :-/

https://openvpn.net/community-resources/how-to/#setting-up-your-own-certificate-authority-ca-and-generating-certificates-and-keys-for-an-openvpn-server-and-multiple-clients

**Comment by ecrist** [comment]
EasyRSA has changed considerably in 3.x.  You should just see EasyRSA-start.bat, which sets up the environment.  From there, all other commands are run just like like they'll would be on Linux.

Eric F Crist
Mobile: 612-998-3588

**Comment by lazna** [comment]
> EasyRSA has changed considerably in 3.x. You should just see EasyRSA-start.bat, which sets up the environment. From there, all other commands are run just like like they'll would be on Linux.

Thanks for reply. I saw the EasyRSA-start.bat and as far as I understand, it just read path to openvpn form registry and start linux shell. So whole easyrsa is now big linux shell script, windows batch files are no more supported right? But I see there only windows openssl binaries, so the shell script finaly produce parameters to openssl.exe and run it? If my theory is right, it should be possible to assemble command line parameters for openssl.exe manually, without linux shell intermediate layer, am I thinking in right direction??

**Comment by ecrist** [comment]
You are thinking somewhat correct but if you do that you're just rewriting EasyRSA. 

Eric Crist

**Comment by lazna** [comment]
> You are thinking somewhat correct but if you do that you're just rewriting EasyRSA. Eric Crist

Not really, just trying to create single-purpose three-commands script in windows native scripting enviromment. I am able to do windows scripting, but unable to read linux script :-/

Do you know why linux scripting was choosed for windows distributions of EasyRSA? Wasnt possible to use windows native scripting?

**Comment by ecrist** [comment]
Sure, it was possible but then we would have to maintain two versions of EasyRSA. 

Eric Crist

**Comment by lazna** [comment]
> Sure, it was possible but then we would have to maintain two versions of EasyRSA. Eric Crist

Understand now

About my second question: could you sugest me what parameters missing in my commands. Googling for a long time but have no found any examples how to create client certificate without an EasyRSA config file. 

In the meantime found the add parameter 'rsa:2048' to command line avoid one error line in first command, but have no idea what more missing. Expecting each error line

`3296:error:0E065068:configuration file routines:str_copy:variable has no value:crypto/conf/conf_def.c:624:line 10`

under the command, mean one missing parameter in command line?

**Comment by ecrist** [comment]
If you are going to use EasyRSA, you need to edit the configuration file and set the appropriate variables.

**Comment by ecrist** [comment]
This isn't an EasyRSA issue, rather a user support issue.  Closing.
