### ISSUE TITLE
unable to write 'random state'

### ISSUE THREAD

**Issue by mbressman** [OpenVPN/easy-rsa#428]
Noticed I was getting this error (unable to write 'random state') when running EasyRSA commands on my CA computer.  I think maybe this is because I didn't run EasyRSA as a local administrator (it's running on a Win10 computer), but not sure.  Either way, any thoughts on this issue, and also whether this is a concern and I need to recreate the .ovpn accounts I've alreaddy created using EasyRSA?

Thanks!

**Comment by TinCanTech** [comment]
I believe this was fixed in version 3.0.7
#261

**Comment by mbressman** [comment]
Guess I'll need to remember to update next time I need to create or revoke VPN accounts.  Are there any security issues with the current accounts I've created based on this issue?  Thanks!

**Comment by TinCanTech** [comment]
I don't know how old your accounts are (not very old, considering when you reported this) but `unable to write 'random state'` should not compromise your security.

It was something that OpenSSL took care of some time ago.

**Comment by mbressman** [comment]
Awesome - I feel better knowing that.  Thanks for the info!
