### ISSUE TITLE
`easyrsa -install`

### ISSUE THREAD

**Issue by kousu** [OpenVPN/easy-rsa#434]
https://github.com/FiloSottile/mkcert has a great feature which is `mkcert -install`. It installs the CA it generates in your cert stores:

- Edge on Windows
- nss (i.e. firefox) on mac and windows and unix
- /etc/ssl on linux
- etc
- it even does android? I think? If you plug it in over `adb`?

I'm a bit hazy on how it does this; I think it shells out to https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Tools/certutil?

It would good to match this feature in easy-rsa. mkcert is great and all but it's really meant for devs: it can't handle cert requests, it is limited in what kinds of keys it can use, and it depends on golang. For sysadminning I would rather use easy-rsa, but actually installing the certs is always hard for me to remember how to do.

**Comment by TinCanTech** [comment]
Sorry .. this is completely unsuitable for Easy-RSA.

There is a well told mantra: Do one job and do it right.
