### ISSUE TITLE
Request - show-crl

### ISSUE THREAD

**Issue by tranzitwww** [OpenVPN/easy-rsa#436]
Hi,
Can you please include a function to read the crl file from easyrsa

I do it manually using this command.
openssl crl -inform PEM -in X:/PKI/EasyRSA/pki/crl.pem -text -noout

Best regards,
Ninel

**Comment by tranzitwww** [comment]
Also will be nice to have a list-certs with a search filter. ;)

**Comment by tranzitwww** [comment]
Also please force replace the crl file. Now you must confirm that all the time 

[easyrsa]
# gen-crl backend
-	mv "$out_file_tmp" "$out_file"
+	mv -f "$out_file_tmp" "$out_file"

**Comment by TinCanTech** [comment]
Reading and writing a CRL can be improved. 

If you want to write something like `./easyrsa status` then listing certificates could also be possible.

**Comment by TinCanTech** [comment]
Closed via https://github.com/OpenVPN/easy-rsa/commit/d1993892178c5219f4a38d50db3b53d1a972b36c

Testing welcome.
