### ISSUE TITLE
Windows issue with build-ca when easy-rsa is installed to a path with spaces

### ISSUE THREAD

**Issue by peg-leg** [OpenVPN/easy-rsa#437]
build-ca fails when running easy-rsa from a path that has spaces in it on Windows (easy-rsa ver 3.0.8)

**Comment by TinCanTech** [comment]
See #412

**Comment by peg-leg** [comment]
My solution which also worked was to change the installation folder for the Easy-RSA scripts to c:\easy-rsa.

**Comment by TinCanTech** [comment]
https://github.com/OpenVPN/easy-rsa/commit/8e7bac695df546189c447b66b1a95c1de36919cf

**Comment by TinCanTech** [comment]
Follow up set to #412 - Closing.
