### ISSUE TITLE
Subject Alternative Names are not in signed cert using Openssl 1.1.1

### ISSUE THREAD

**Issue by faxm0dem** [OpenVPN/easy-rsa#445]
Something changed in OpenSSL (I haven't bisected yet) between 1.0.2k and 1.1.1g that strips the SANs in the signed certificate.
I tracked this down to the `display_san()` function. For some reason the `openssl req` command emits an empty output and the `$san` variable is empty. When running the exact same command interactively, it works. I suspect there's something happening behind the scenes with the tty, maybe openssl now checks for tty presence, and if absent just stays silent

**Comment by faxm0dem** [comment]
I narrowed this down between 1.1.1d and 1.1.1e

**Comment by faxm0dem** [comment]
This commit broke it for me: https://github.com/openssl/openssl/commit/5fe82100857ff194e5728bafe9af1a27c9d5475c

**Comment by faxm0dem** [comment]
It turns out this problem disappears when using the provided `openssl-easyrsa.cnf`.
I actually never used that before. Now I know I should have :-D

**Comment by PikuZheng** [comment]
same problem here. reset openssl-easyrsa.cnf not work. any details, please?
