### ISSUE TITLE
SANs are not copied from the CSR for client certificates

### ISSUE THREAD

**Issue by gbrdead** [OpenVPN/easy-rsa#447]
Client certificates may also have subject alternative names, e.g. e-mail addresses. They should be copied to the certificate. Here is a proposal for the fix:

```
                echo "$EASYRSA_EXTRA_EXTS" | grep -q subjectAltName
                if [ $? -ne 0 ];
                then
                        san=$(display_san req "$req_in")

                        # If type is server and no subjectAltName was requested,
                        # add one to the extensions file
                        if [ "$crt_type" = 'server' ] || [ "$crt_type" = 'serverClient' ];
                        then
                                if [ -z "$san" ];
                                then
                                        default_server_san "$req_in"
                                fi
                        fi

                        if [ -n "$san" ];
                        then
                                print "subjectAltName = $san"
                        fi
                fi
```

**Comment by TinCanTech** [comment]
Looks simple .. but the signing agent needs authority.

The current approach is **nothing is copied by default** then the signing agent has the authority to put the SAN in place.

An improvement could be to add a `--copy-san` flag to `sign-req`, to save some time.

**Comment by TinCanTech** [comment]
#88

**Comment by TinCanTech** [comment]
`easyrsa --subject-alt-name=DNS:foo sign-req client bar`

**Comment by mercury46dev** [comment]
`./easyrsa sign-req client test --copy-ext`
Works as expected when adding `copy_extensions = copy` to the `openssl-easyrsa.cnf` file of the pki.
