### ISSUE TITLE
openssl binary assumed in path - security issue

### ISSUE THREAD

**Issue by coldBug** [OpenVPN/easy-rsa#451]
Hi, 
maybe not the most critical problem, but: "openssl" is assumed to be on the env PATH and accessed with relative PATH location.

This makes it susceptible for "path injection" attacks if run with SUID flags or other means to run it as a normal user with higher privileges. It should always be preferred (default) to run external binaries with absolute path for security means.

**Comment by TinCanTech** [comment]
The `vars` file allows for users to specify the **exact** location of `openssl`.

**Comment by ecrist** [comment]
This isn't a real vulnerability.  You're ALWAYS subject to path injection in some manner.  Also, we cannot expect to know where to find the openssl binary on every system we use.
