### ISSUE TITLE
In gen-req --batch option generates request with "subject=CN = ChangeMe"

### ISSUE THREAD

**Issue by tik806** [OpenVPN/easy-rsa#456]
To reproduce:
`easyrsa --batch gen-req CertName nopass`
and look at it:
`openssl req -in CertName.req -noout -subject`

But 
`easyrsa gen-req CertName nopass batch`
works fine

**Comment by u0m3** [comment]
You can work around that with something like:
```bash
declare -a certnames
certnames=( 'cert1' 'cert2' 'cert3 )

for certname in ${certnames[@]}; do
    ./easyrsa --batch --req-cn=${certname} gen-req ${certname} nopass
    ./easyrsa --batch --req-cn=${certname} sign-req client ${certname} nopass
done
```

Also +1 for the
```bash
easyrsa gen-req CertName nopass batch
```
version of the command. I had no idea it of it's existence.

**Comment by ecrist** [comment]
This is a bug for sure.  We'll try to address this in v3.0.9.

**Comment by TinCanTech** [comment]
This comment is completely wrong:
```
# gen-req backend:
gen_req() {
	# pull filename base and use as default interactive CommonName:
```
This is what actually happens:
```
# gen-req backend:
gen_req() {
	# pull filename base and use as default non-interactive CommonName:
```
This is another case of abusing `EASYRSA_BATCH`.
