### ISSUE TITLE
Option to specify --hours=# instead of --days

### ISSUE THREAD

**Issue by anhoxa** [OpenVPN/easy-rsa#457]
For the purpose of software development testing with respect to how it behaves when a certificate expires, it would be useful to be able to  specify the validity period in time units less than a day, otherwise testing edge cases takes long time, and clock shifting gets messy.

**Comment by trasherdk** [comment]
What prevents you from using a already expired certificate for this test?

**Comment by anhoxa** [comment]
Want to be able to ensure connectivity before expiry followed by behaviour after expiry.  The setup on embedded devices can be tricky and time consuming.

**Comment by trasherdk** [comment]
How about
```
 -startdate YYMMDDHHMMSSZ  - certificate validity notBefore
 -enddate YYMMDDHHMMSSZ    - certificate validity notAfter (overrides -days)
```

**Comment by TinCanTech** [comment]
It would be interesting to see a one minute valid certificate, if anybody wants to write the necessary code ..
