### ISSUE TITLE
Gen-Req: Setting commonname using batch

### ISSUE THREAD

**Issue by Deantwo** [OpenVPN/easy-rsa#461]
I was having trouble generating a certificate request using the `--batch` option. The CN (commonname) of the certificate didn't 
```
sudo /etc/openvpn/easy-rsa/easyrsa --batch --passout=pass:***** gen-req MyCert
```
Will create a certificate with the default CN specified in the `vars` file, which by default is "ChangeMe".
This is of course not what I wanted, I wanted the CN to be "MyCert" like the name of the resulting file.

The solution I found by looking in the source code and noticed what I think is a mistake, but it fixes my issue anyway.
Using the `batch` option that is specific to the `gen-req` command causes it to use the file name as the CN.
```
sudo /etc/openvpn/easy-rsa/easyrsa --passout=pass:***** gen-req MyCert batch
```

This happens because when `--batch` is not set, the CN is set to the file name, otherwise the default is used.
https://github.com/OpenVPN/easy-rsa/blob/6c5753348df959259314967a92d96f7a9376a083/easyrsa3/easyrsa#L758
I would suggest this be made more standard so they both behave the same way, unless you are trying to preserve backwards-compatibility.

**Comment by Deantwo** [comment]
Duplicate of #456

**Comment by ecrist** [comment]
Closing this for #456 duplicate.  Will handle there.
