### ISSUE TITLE
try to understand the batch mode

### ISSUE THREAD

**Issue by tlsalex** [OpenVPN/easy-rsa#465]
I want to specify Organizational DN options in command line (like below code)when I create CA/normal certification, but I found it doesn't work as I can't see the DN information when I check issued CA certification detail.

I don't want to specify DN option in "var" file , what's the correct way to do that in command line , we use the same way to do that no mater we create CA or normal certification ? or how to disable batch mode which use a interactive mode , and also give a chance to specify a SAN for certification.
`
./easyrsa --batch --days=3650 --req-c=CN --req-st=aa --req-city=bb --req-org=cc.org --req-email=mail@cc.org --req-ou=IT --req-cn=ca.cc.org build-ca`

PS:  I use easy-rsa Version:     3.0.8

**Comment by TinCanTech** [comment]
Are you looking for `./easyrsa help options` ?

**Comment by tlsalex** [comment]
I have checked ./easyrsa help options, just don't know how to use them

**Comment by TinCanTech** [comment]
You appear to need:
```
--subject-alt-name : Add a subjectAltName. For more info and syntax, see:
                     ./easyrsa help altname
```

**Comment by tlsalex** [comment]
Thanks @TinCanTech , I have also checked ./easyrsa help altname, and you are correct, I do want to get a SAN certificate, but I also want to set DN options like country code, city name when I create a certificate, I don't see some useful examples in Read.me file, I hope someone can give me some examples on that

**Comment by TinCanTech** [comment]
My crystal ball is showing me:
```
--dn-mode=MODE  : DN mode to use (cn_only or org)
```
I believe you need `org`

**Comment by tlsalex** [comment]
@TinCanTech  thanks , it does work with --dn-mode , but for the --subject-alt-name part ,I still can't make it work with below code, I also tried to keep --subject-alt-name only (remove --req-cn), but the CN will become "ChangeMe" in the created certification, do I miss something again?
`./easyrsa --batch --days=3650 --dn-mode=org --req-cn=vpn.alex.org --subject-alt-name=DNS:vpn.alex.org,DNS:primary.alex.org --req-c=ZZ --req-st=AA --req-city=BB --req-org=ALEX.ORG --req-email=mail@alex.org --req-ou=IT build-ca`

**Comment by TinCanTech** [comment]
A CA does not have SAN field.
