### ISSUE TITLE
Unable to determine version

### ISSUE THREAD

**Issue by g0lgs** [OpenVPN/easy-rsa#469]
Earlier today I was trying to fathom out which version I had and discovered that the version from the Ubuntu 20.04 repo is not current (I failed to ascertain what version it was).

Having removed the Ubuntu version and cloned the latest from github I find the it still does not given me the version information.

./easyrsa3/easyrsa --version
./easyrsa3/easyrsa: 2380: version: not found
EasyRSA Version Information
Version:     ~VER~
Generated:   ~DATE~
SSL Lib:     
Git Commit:  ~GITHEAD~
Source Repo: https://github.com/OpenVPN/easy-rsa

./easyrsa3/easyrsa version
EasyRSA Version Information
Version:     ~VER~
Generated:   ~DATE~
SSL Lib:     OpenSSL 1.1.1f  31 Mar 2020
Git Commit:  ~GITHEAD~
Source Repo: https://github.com/OpenVPN/easy-rsa

**Comment by ecrist** [comment]
So this *does* work when released.  If you run this straight out of a cloned repo, you end up with some placeholder values that aren't defined until a release is built.

Check out built/Building.md for information.

Since there isn't a way to do commit triggers to update thing, we have to kind of do it manually.  This isn't a bug, just the way it works when you're not really building something.

**Comment by ecrist** [comment]
```
ecrist@terrance:~/easy-rsa-> build/build-dist.sh 
Remove existing DIST_ROOT at: 'dist-staging' ? y/n: y
build-dist NOTE: tarball created at: dist-staging/EasyRSA-git-development.tgz
build-dist NOTE: zip file created at: dist-staging/EasyRSA-git-development-win32.zip
build-dist NOTE: zip file created at: dist-staging/EasyRSA-git-development-win64.zip
ecrist@terrance:~/easy-rsa-> cd ../
ecrist@terrance:~-> tar -xzvf easy-rsa/dist-staging/EasyRSA-git-development.tgz	
x EasyRSA-git-development/
x EasyRSA-git-development/easyrsa
x EasyRSA-git-development/openssl-easyrsa.cnf
x EasyRSA-git-development/vars.example
x EasyRSA-git-development/x509-types/
x EasyRSA-git-development/gpl-2.0.txt
x EasyRSA-git-development/mktemp.txt
x EasyRSA-git-development/COPYING.md
x EasyRSA-git-development/ChangeLog
x EasyRSA-git-development/README.md
x EasyRSA-git-development/README.quickstart.md
x EasyRSA-git-development/doc/
x EasyRSA-git-development/doc/EasyRSA-Advanced.md
x EasyRSA-git-development/doc/EasyRSA-Readme.md
x EasyRSA-git-development/doc/EasyRSA-Upgrade-Notes.md
x EasyRSA-git-development/doc/Hacking.md
x EasyRSA-git-development/doc/Intro-To-PKI.md
x EasyRSA-git-development/x509-types/COMMON
x EasyRSA-git-development/x509-types/ca
x EasyRSA-git-development/x509-types/client
x EasyRSA-git-development/x509-types/code-signing
x EasyRSA-git-development/x509-types/email
x EasyRSA-git-development/x509-types/kdc
x EasyRSA-git-development/x509-types/server
x EasyRSA-git-development/x509-types/serverClient
ecrist@terrance:~-> cd EasyRSA-git-development/
ecrist@terrance:~/EasyRSA-git-development-> ./easyrsa version
EasyRSA Version Information
Version:     git-development
Generated:   Tue Mar 15 21:47:15 CDT 2022
SSL Lib:     OpenSSL 1.1.1h-freebsd  22 Sep 2020
Git Commit:  ce8f1847f1c6439c9c130ecfaa0633ebb54689ee
Source Repo: https://github.com/OpenVPN/easy-rsa
```

**Comment by ecrist** [comment]
On some systems you may be missing some python libraries, so you can skip the windows build.  Here it is on macOS:

```
ecrist@marvin:~/easy-rsa-> build/build-dist.sh --no-windows
Remove existing DIST_ROOT at: 'dist-staging' ? y/n: y
build-dist NOTE: tarball created at: dist-staging/EasyRSA-git-development.tgz
ecrist@marvin:~/easy-rsa-> cd ..
ecrist@marvin:~-> tar -xzf easy-rsa/dist-staging/EasyRSA-git-development.tgz 
ecrist@marvin:~-> cd EasyRSA-git-development/
ecrist@marvin:~/EasyRSA-git-development-> ./easyrsa version
WARNING: can't open config file: /Users/ecrist/EasyRSA-git-development/pki/safessl-easyrsa.cnf
EasyRSA Version Information
Version:     git-development
Generated:   Tue Mar 15 21:50:44 CDT 2022
SSL Lib:     LibreSSL 3.3.5
Git Commit:  6ac2705eb4ebf020990ba24eb91d5a9a52764c19
Source Repo: https://github.com/OpenVPN/easy-rsa
```

**Comment by g0lgs** [comment]
I eventually fathomed out that I had missed something and found the Building.md file.

It would have been easier if the README.md had something that made it clearer how it was supposed to be built / installed.

**Comment by viharm** [comment]
> I eventually fathomed out that I had missed something and found the Building.md file.
> 
> It would have been easier if the README.md had something that made it clearer how it was supposed to be built / installed.

What did you find? I couldn't really flesh out the answer from the Building.md file :-(

**Comment by ecrist** [comment]
You are not supposed to run easy-rsa from a git clone, that's not how it's designed.  You should be running a release version. If you run from git clone, you're left on your own to figure it out.
