### ISSUE TITLE
EasyRSA-Readme.md missing command for Signing a request

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [OpenVPN/easy-rsa#47]
sign-req <type> <filename_base> is not listed under https://github.com/OpenVPN/easy-rsa/blob/master/doc/EasyRSA-Readme.md#signing-a-request

**Comment by TinCanTech** [comment]
This appears to be fixed. https://github.com/OpenVPN/easy-rsa/commit/7f2936caf9511ecbf614613f9fdb9e73b6454789
