### ISSUE TITLE
2-way-tls

### ISSUE THREAD

**Issue by chillriver** [OpenVPN/easy-rsa#470]
Hello,

I have a simple question. It is possible to use easy-rsa to generate and manage certs for 2-way-tls - clientauthentification with webserver?

https://linuxconfig.org/apache-web-server-ssl-authentication

Thanks for answer.

**Comment by TinCanTech** [comment]
It looks to be fairly standard X509, so, Easy-RSA can _probably_ generate compatible certificates.

**Comment by chillriver** [comment]
yes I can confirm your answer. Yesterday I find out the solution with easy-rsa and can use pki to manage 2-way-ssl.

Thanks for your feedback.
