### ISSUE TITLE
Define Distribution point for CRLs

### ISSUE THREAD

**Issue by GiannisStasinakis82** [OpenVPN/easy-rsa#472]
Hello ! Is there a way to define a CDP instead of sending the CRL to all entities of my chain of trust ? I am using the latest version of EasyRsa on Ubuntu 20.04.
Thanks in advance

**Comment by Du-St** [comment]
@GiannisStasinakis82 

Hi,

I solved this need using the file "x509-types/COMMON" containing this line:

crlDistributionPoints   = URI:<path to CRL file, e.g. http://host/file.crl>
