### ISSUE TITLE
 index.txt too long lead to client.crt not created

### ISSUE THREAD

**Issue by linxingyang** [OpenVPN/easy-rsa#473]
Hi.
I'm using easyrsa to create client crt and key in my shell script. but recently i found that the client.crt is not create correctly while the client.key is created. 
finally i got the point, the `easyrsa3/pki/index.txt` file has more than 70K+ lines,  and the client.crt is create normally when i clean this file.

for now i clean this file in my shell script when it has 10K lines. 
but i think the clean job should add to easyrsa script,  clean it or backup index.txt to index.txt.1 when it's too large.

linxingyang.

**Comment by TinCanTech** [comment]
What do you mean by "clean the file" ?

Why do you think the file is too large ?

**Comment by linxingyang** [comment]
Over 76K lines and 5.8M(not very large), in this case create client.crt fail.
```shell
# cat easy-rsa/easyrsa3/pki/index.txt | wc -l
76673

# ll -h easy-rsa/easyrsa3/pki/index.txt
-rw------- 1 root root 5.8M Jan 11 14:22 easy-rsa/easyrsa3/pki/index.txt
```

clean the file means clean the index.txt file.
```shell
cat /dev/null > easy-rsa/easyrsa3/pki/index.txt
# or rollover index.txt
# index.txt -> index.txt.1
```

**Comment by TinCanTech** [comment]
> Over 76K lines and 5.8M(not very large), in this case create client.crt fail

What is the output from `easyrsa` and `openssl` ?

**Comment by TinCanTech** [comment]
If you have 76 thousand odd clients then you should know how to use OpenSSL.
