### ISSUE TITLE
easyrsa upgrade pki errors

### ISSUE THREAD

**Issue by vazhnov** [OpenVPN/easy-rsa#474]
Hello!
Thank you for great project!

I tried to migrate my old project, created with easy-rsa v2, into new format easy-rsa v3, with a command `./easyrsa upgrade pki`.

I use Devuan GNU/Linux 4 (chimaera) (based on Debian 11 Bullseye), package `easy-rsa` v3.0.8-1.

First, I created empty directory: `make-cadir test1`.

Second, I copied whole content of old directory into new one. File `vars` was rewritten.

Next:
```
 % ./easyrsa upgrade pki

Easy-RSA error:

echo
./easyrsa: 274: exit: Illegal number: vars file not found
```

I found an argument `--vars`, so now my command is `./easyrsa --vars=./vars upgrade pki`.

Next error:

```
mkdir: cannot create directory ‘/usr/share/easy-rsa/VERY-SAFE-PKI’: Permission denied
```

Why is it trying to create a dir into system directory?

I replaced `EASYRSA_SAFE_PKI="$EASYRSA/VERY-SAFE-PKI"` with `EASYRSA_SAFE_PKI="$PWD/VERY-SAFE-PKI"`.

Next error:
```
ERROR: Failed to create /usr/share/easy-rsa/vars-v3.wrn.easyrsa-upgrade-23
```

Again, why system directory?

Here I decided to change `$EASYRSA`, which is a base for other variables. Replaced: `set_var EASYRSA		"$prog_dir"` with `set_var EASYRSA		"$PWD"`.

Next error:

```
ERROR: cannot find /home/user/vpn-keys/keys/test1/vars.example
```
Ok, take example from system directory: replace `EASYRSA_VARSV3_EXMP="$EASYRSA/vars.example"` with `EASYRSA_VARSV3_EXMP="$prog_dir/vars.example`.

Finally, script works!

```
./easyrsa --vars=./vars upgrade pki
…
Your settings and PKI have been successfully upgraded to EasyRSA version3
…
                   * UPGRADE COMPLETED SUCCESSFULLY *
```

I will create a merge request, if my changes are not so bad…

**Comment by TinCanTech** [comment]
Where do you have `./easyrsa` located ?

**Comment by vazhnov** [comment]
Inside `test1` directory, which was created by `make-cadir test1` (by fresh `easy-rsa`).

**Comment by TinCanTech** [comment]
1. What is `make-cadir` ?
2. Where do you have the script `./easyrsa` located ?

**Comment by vazhnov** [comment]
`/usr/bin/make-cadir` is a script, which is included into Debian/Devuan/Ubuntu `easy-rsa` packages. I didn't think it is not an original part of `easy-rsa` project. The script is pretty simple:

```shell
#!/bin/sh

# This script creates a new directory in order to be used
# with the tools from the easy-rsa project.
#
# Copyright (C) 2012 Alberto Gonzalez Iniesta
#               2018 Pierre-Elliott Bécue
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

set -e

usage() {
	echo "Usage: $0 DIRECTORY"
	echo "Creates a *new* directory and prepares it to be used as a (CA) key management directory (to create and store keys and certificates)."
	exit 1
}

[ "$#" -ne 1 ] && usage
[ -e "$1" ] && { echo "$1 exists. Aborting." ; usage ; }

mkdir -m 700 -p "$1"
ln -s /usr/share/easy-rsa/easyrsa "$1"
ln -s /usr/share/easy-rsa/x509-types "$1"
cp /usr/share/easy-rsa/openssl-easyrsa.cnf "$1"
cp /usr/share/easy-rsa/vars.example "$1/vars"
```

Command `make-cadir test1` creates that structure:
```console
 % make-cadir test1
 % ls -lAF test1
total 20
lrwxrwxrwx 1 user user   27 Jan 29 01:28 easyrsa -> /usr/share/easy-rsa/easyrsa*
-rw-r--r-- 1 user user 4616 Jan 29 01:28 openssl-easyrsa.cnf
-rw-r--r-- 1 user user 8925 Jan 29 01:28 vars
lrwxrwxrwx 1 user user   30 Jan 29 01:28 x509-types -> /usr/share/easy-rsa/x509-types/
```

`easyrsa` script is located in `/usr/share/easy-rsa/easyrsa`.

**Comment by TinCanTech** [comment]
In order to use the **upgrade** facility, you require an **Easy-RSA version 2** generated PKI. You do not need to initialise a new PKI.

**Comment by vazhnov** [comment]
Ok, I think I understand the idea. I shouldn't use `make-cadir` to prepare for upgrade.

Steps to confirm that all works fine:
* I created empty directory with `mkdir -pv test1`,
* `cd test1`
* `rsync -a ~/vpn-keys/my-old-keys-v2/ .`
* `cp -pv /usr/share/easy-rsa/easyrsa .`
* `cp -pv /usr/share/easy-rsa/openssl-easyrsa.cnf .`
* `cp -pv /usr/share/easy-rsa/vars.example .`

Now the structure is:
```console
 % ls -lAF
total 228
-rwxr-xr-x 1 user user   119 Apr 27  2011 build-ca*
-rwxr-xr-x 1 user user   352 Apr 27  2011 build-dh*
-rwxr-xr-x 1 user user   188 Apr 27  2011 build-inter*
-rwxr-xr-x 1 user user   163 Apr 27  2011 build-key*
-rwxr-xr-x 1 user user   157 Apr 27  2011 build-key-pass*
-rwxr-xr-x 1 user user   249 Apr 27  2011 build-key-pkcs12*
-rwxr-xr-x 1 user user   268 Apr 27  2011 build-key-server*
-rwxr-xr-x 1 user user   213 Apr 27  2011 build-req*
-rwxr-xr-x 1 user user   158 Apr 27  2011 build-req-pass*
-rwxr-xr-x 1 user user   428 Apr 27  2011 clean-all*
-rwxr-xr-x 1 user user 76946 Sep  9  2020 easyrsa*
-rwxr-xr-x 1 user user  1457 Apr 27  2011 inherit-inter*
drwx------ 2 user user  2920 Sep 29  2018 keys/
-rwxr-xr-x 1 user user   295 Apr 27  2011 list-crl*
-rw-r--r-- 1 user user   413 Jul  1  2011 Makefile
-rw-r--r-- 1 user user  7768 Oct 21  2010 openssl-0.9.6.cnf
-rw-r--r-- 1 user user  8325 Jul  1  2011 openssl-0.9.8.cnf
-rw-r--r-- 1 user user  8222 Jul  1  2011 openssl-1.0.0.cnf
-rw-r--r-- 1 user user  8224 Jun 23  2011 openssl-1.0.0.cnf-old-copy
-rw-r--r-- 1 user user  4616 Sep  9  2020 openssl-easyrsa.cnf
-rwxr-xr-x 1 user user 12675 Apr 27  2011 pkitool*
-rw-r--r-- 1 user user  3757 Jul  1  2011 README.gz
-rwxr-xr-x 1 user user   918 Apr 27  2011 revoke-full*
-rwxr-xr-x 1 user user   178 Apr 27  2011 sign-req*
-rw-r--r-- 1 user user  1877 May  8  2014 vars
-rw-r--r-- 1 user user  8925 Sep  9  2020 vars.example
-rwxr-xr-x 1 user user   715 Mar 14  2014 whichopensslcnf*
```

And now `easyrsa` works without patching (and patched version works too):
```shell
./easyrsa upgrade pki
```

```console
 % ls -lAF
total 128
-rwxr-xr-x 1 user user 76946 Sep  9  2020 easyrsa*
drwx------ 2 user user  2920 Sep 29  2018 keys/
-rw-r--r-- 1 user user   413 Jul  1  2011 Makefile
-rw-r--r-- 1 user user  8224 Jun 23  2011 openssl-1.0.0.cnf-old-copy
-rw-r--r-- 1 user user  4616 Sep  9  2020 openssl-easyrsa.cnf
drwx------ 6 user user   240 Jan 29 13:53 pki/
-rw-r--r-- 1 user user  3757 Jul  1  2011 README.gz
-rw------- 1 user user  9643 Jan 29 13:53 vars
-rw-r--r-- 1 user user  8925 Sep  9  2020 vars.example
drwx------ 3 user user   460 Jan 29 13:53 VERY-SAFE-PKI/
```

I will try to update https://community.openvpn.net/openvpn/wiki/easyrsa-upgrade with a note for Debian/Devuan/Ubuntu users.

**Comment by vazhnov** [comment]
Created a new chapter: https://community.openvpn.net/openvpn/wiki/easyrsa-upgrade#ersa-up23-debian

**Comment by vazhnov** [comment]
But anyway, even now, when I know how `upgrade` should work, I think these changes in #475 are good.

I downloaded https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.8/EasyRSA-3.0.8.tgz , unpacked it, and I see `openssl-easyrsa.cnf` and `vars.example` are in the same directory, as script `easyrsa`. So, it is better to create anything in current directory `$PWD` (but not where the script is), and take files `openssl-easyrsa.cnf` and `vars.example` from the directory with script `$prog_dir`. So it is possible to create symlinks from a multiple EasyRSA key directories to one script, which can be installed with package manager somewhere into `/usr/…` The script can be automatically updated in case of security issues, for example.

And in this case, we don't need any special documentation notes for Debian-based distros.

**Comment by TinCanTech** [comment]
Regarding your [patch](https://github.com/OpenVPN/easy-rsa/pull/475), personally, Nack. Changing `$EASYRSA` is too intrusive.

Your wiki update is ok.

**Comment by vazhnov** [comment]
@TinCanTech, thank you for a help!

**Comment by TinCanTech** [comment]
@vazhnov This would be the function to take a look at:
https://github.com/OpenVPN/easy-rsa/blob/243bb708b02897c563631ce62633d90ae80c82ff/easyrsa3/easyrsa#L1661

That is where `$prog_dir` and `$EASYRSA` are evaluated.
