### ISSUE TITLE
Revoke Certtificates

### ISSUE THREAD

**Issue by Sjk-Lacoste** [OpenVPN/easy-rsa#477]
There is currently no way the revoking of users can be automated as it requires user interaction. I discovered this recently when we wanted to automate this process of revoking user and wanted to add a flag option on the command to auto-confirm on the prompt where we have to type yes.

The example should be as follows:
```bash
./easyrsa revoke "{{username}}" -y
```
or
```bash
./easyrsa revoke "{{username}}" --yes
```

May this feature please be added.

**Comment by TinCanTech** [comment]
The option you require can be found by reading `help options`.

**Comment by TinCanTech** [comment]
Please see `--batch` in `./easyrsa help options`
