### ISSUE TITLE
Use of mktemp is not POSIX compliant – script failure.

### ISSUE THREAD

**Issue by Tokarak** [OpenVPN/easy-rsa#478]
Running EasyRSA in a freshly unzipped 3.0.8 distribution on a linux system. I checked, and mktemp is no longer posix compliant. If it means anything, I am running on Asuswrt-merlin – this might just turn out to be an issue specific to that.

Even though it is not technically POSIX compliant, it is still a highly portable command. 

<details>
<summary>Test results</summary>
<br>

`./easyrsa` :

```
./easyrsa: line 1: mktemp: not found

Easy-RSA 3 usage and overview
[...]
```

`./easyrsa init-pki`:
```
./easyrsa: line 1: mktemp: not found

Easy-RSA error:

EASYRSA_TEMP_DIR_session not initialized!

Easy-RSA error:

Failed to create temporary file
```
However, the pki folder is created, and it contains the correct files.

`./easyrsa build-ca`:
```
./easyrsa: line 1: mktemp: not found
Using SSL: openssl OpenSSL 1.1.1l  24 Aug 2021

Easy-RSA error:

EASYRSA_TEMP_DIR_session not initialized!

Easy-RSA error:

Failed to create temporary file
```

Some files are created (eg index.txt, revoked), but is notably missing ca.crt.
</details>

Upon installing "coreutils-mktemp" from my package manager, the script works as intended.

To fix this issue, here are the options, ordered from best to worst:

- Add a clear error message, prompting the user to install mktemp + note this dependency in the ReadMe (Technically breaks strict POSIX compliance, but that is not a big problem considering I am the first to complain about this in ages.)
- Switch to a different POSIX command of similar functionality (Although none of the alternatives I found were installed on my system either, including mkstemp)
- Write the mktemp function from the ground up  (A good self-built function can also remove the need for the crude Windows workarounds)
- Bundle mktemp with the program (A considerable option, as long as it is shortened to just a few lines.)

This issue had some discussion in #84.

**Comment by TinCanTech** [comment]
Personally, I would prefer Easy-RSA to offer a `mktemp` and a `non-mktemp` version .. or at least to determine if `mktemp` is available and work without it, when necessary.  Discussion and PRs on the subject are certainly welcome.

**Comment by trasherdk** [comment]
`echo "/tmp/tmp.easyrsa.$(date +%s)"` :smile:

**Comment by ecrist** [comment]
Actually, a bit easier:

`tmpfile=/tmp/tmp.easyrsa.$(openssl rand -hex 3)`

I'll work on adding this to easyrsa tonight.  Pulling dependency of an external non-POSIX mktemp is a good move.
