### ISSUE TITLE
Easy-RSA error: Failed create CA private key - SSL FIPS Mode

### ISSUE THREAD

**Issue by chckfrmn** [OpenVPN/easy-rsa#479]
Using AlamaLinux 8.5 (RedHat clone) installed in FIPS mode, EasyRSA 3.0.8

     [cfreeman@localhost easy-rsa]$ **fips-mode-setup --check FIPS mode is enabled.**
     [cfreeman@localhost easy-rsa] Linux localhost.localdomain 4.18.0-348.12.2.el8_5.x86_64 #1 SMP Wed Jan 19 14:35:04 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

Following instructions at (https://vitux.com/how-to-install-openvpn-on-almalinux-8-centos-8-or-rocky-linux-8/)

Using SSL: openssl OpenSSL 1.1.1k  FIPS 25 Mar 2021

Enter New CA Key Passphrase: 
Re-Enter New CA Key Passphrase: 
Generating RSA private key, 2048 bit long modulus (2 primes)
**************************************************************************************************************************************************************************************************************+++++
**********************************************************************************+++++
e is 65537 (0x010001)
139680079726400:error:060800C8:digital envelope routines:EVP_DigestInit_ex:disabled for FIPS:crypto/evp/digest.c:135:

Easy-RSA error:

Failed create CA private key

Looking for some help :)

**Comment by TinCanTech** [comment]
> digital envelope routines:EVP_DigestInit_ex:**disabled for FIPS**:crypto/evp/digest.c:135:

I guess Easy-RSA-3, with your settings, is not FIPS compatible ..

**Comment by TinCanTech** [comment]
It would be interesting to understand which **digest** FIPS finds to be unacceptable .. do you have any ideas ? Perhaps an old MD5 hash ?
