### ISSUE TITLE
Easy-RSA failed to create temporary file

### ISSUE THREAD

**Issue by Gilgamesh0028** [OpenVPN/easy-rsa#482]
![image](https://user-images.githubusercontent.com/98428877/155061182-ddfaa9bb-a538-4838-ab16-15c180af7ed3.png)

It fails on install, using latest version of everything, and up to date windows install.

**Comment by TinCanTech** [comment]
You probably need to be using an administrator account.

**Comment by Gilgamesh0028** [comment]
EDIT: It turns out its a permissions error as C:\Program Files\OpenVPN\ is unable to be edited unless you grant 'user' the permissions to modify and edit the folder

@TinCanTech  yeah, I tried using the Administrator account, this was the only way.

**Comment by TinCanTech** [comment]
The error with the temporary folder does need to be addressed.

Because you are running windows, I invite you to help us test some changes that are being made.

**Comment by Gilgamesh0028** [comment]
Sure, I'd be glad to help test this out. BTW this is also happening:
![image](https://user-images.githubusercontent.com/98428877/155069014-13137ba5-3809-4dd4-a8ce-ef9a9eb4679b.png)

**Comment by amoncer** [comment]
Hi i'm facing the same issue, is there any solution ??

![easyrsa_error](https://user-images.githubusercontent.com/6735457/229761676-54dc6709-e538-4d74-bf07-e9bce9d4d8ed.png)

**Comment by Gilgamesh0028** [comment]
@amoncer 
The short answer is, no.

The long answer, is that I had to re-image my machine, and uninstall some wack windows feature update in order to get it to work.
This was several months ago though, so I don't remember which feature update had to be uninstalled.

**Comment by TinCanTech** [comment]
If this is a problem with `easyrsa` then it can be reopened.

I do not have access to Windows 11 so I cannot test, however, there is probably a simple work around:

- Copy `C:\Program Files\Openvpn\easy-rsa` to your user home directory and run it from there, where permissions should not be an issue.
- Also, **take note**: If your PKI is `C:\Program Files\Openvpn\easy-rsa\pki` then your private `ca.key` (The corner stone of security for your entire PKI) is **World** readable.  Running `easyrsa` from your home directory is **more secure**.

**Comment by TinCanTech** [comment]
@kthamel **All** programs that write data to _Windows System Folders_ **require** administrator privileges, This is not a bug in EasyRSA or any other program.

However, storing your Easy-RSA PKI in _Windows System Folders_ is **insecure**, because these folders are **World Readable**, by default.

In future, Easyrsa may even prohibit the use of _Windows System Folders_, in favor of _Windows User Folders_, which are only readable by the User or privileged user accounts.

I **strongly** suggest that you copy `easy-rsa` to your `$HOME` folder and create your PKI there.

Or define your PKI with command line option:
- `--pki-dir=C:/Users/<Your-user-name>/easy-rsa/pki`

**Comment by nicky1038** [comment]
> However, storing your Easy-RSA PKI in _Windows System Folders_ is **insecure**, because these folders are **World Readable**, by default.

@TinCanTech Hello there! Could you please explain more verbose what does "World Readable" mean and why is it so?

At first glance at this phrase there becomes an impression that anyone in the world can read any content of Windows system folders of any computer in the world, seems to be a very bold statement

**Comment by TinCanTech** [comment]
> At first glance

Is your issue with _my comment above_ **or** _the code_ ?

**Comment by nicky1038** [comment]
> > At first glance
> 
> Is your issue with _my comment above_ **or** _the code_ ?
> 
> 

Regarding the information in your comment stating that storing PKI inside the OpenVPN installation folder in Program Files is insecure. Sorry for ambiguity

**Comment by TinCanTech** [comment]
> storing PKI inside the OpenVPN installation folder in Program Files is insecure

It is less than optimal.

**Comment by nicky1038** [comment]
> > storing PKI inside the OpenVPN installation folder in Program Files is insecure
> 
> It is less than optimal.

I agree it is _not optimal_, but you stated that it's _World Readable_ and added the same information message to EasyRSA.
Could you please tell more about what "World Readable" means and why is it so?

**Comment by TinCanTech** [comment]
I could disable the warning.

Considering the minority that this may effect, I'm still good with it.

Operating system security is a separate challenge.

**Comment by ecrist** [comment]
Keep the warnimg for any world readable path.

Eric F Crist
________________________________

**Comment by TinCanTech** [comment]
I will disable`[patch]` that message.

**Comment by nicky1038** [comment]
@TinCanTech I have to apologize, I didn't know the term "World readable" before and didn't find something about it on the Internet before asking my question here.

Now I understand the idea. It is actually a good point to log the message with recommendations to move pki to some user folder.

The only thing that could be optionally done is to make the explanation a bit clearer for people like me 😅

**Comment by TinCanTech** [comment]
Disabled the warning via #1033
