### ISSUE TITLE
Use external / remote database

### ISSUE THREAD

**Issue by mmigliari** [OpenVPN/easy-rsa#484]
It would be great if easy-rsa could have the option of storing keys, requests, certificates and everything needed to control the CA, revoking certs and so forth in an external, remote database, such as Postgres or MySQL

You would configure the database credentials and store them in a dot file or suchlike, and the entire easy-rsa service would query these databases.

This would allow for more flexible use of easy-rsa, as I could for example, create a pipeline in bitbucket or gitlab to create a new user for my organization and have easy-rsa run inside an efemeral docker image in one of the pipeline steps.

The issue is, today you need to store all your certs within the easy-rsa directory in order to properly manage revocations and generate the CRL.

**Comment by TinCanTech** [comment]
It's a nice idea, have you started any coding ?

But for the record: _easy-rsa - **Simple** shell based CA utility_

It is very unlikely your idea will ever take shape, unless you start it.

I leave this for you to decide.

**Comment by ecrist** [comment]
The real backend to EasyRSA is openssl or libressl - how those tools store the files and databases is entirely up to them.  EasyRSA is really just a shell wrapper for the command line tools - not a reimplementation of the underlying libraries.
