### ISSUE TITLE
Running easyrsa from a symlink or PATH

### ISSUE THREAD

**Issue by TinCanTech** [OpenVPN/easy-rsa#499]
This issue is here to discuss how to simplify and resolve the problems related to:
- _where `easyrsa` is located_ **verses**
- _the current directory_, where `easyrsa` was called.

When running `easyrsa` from the same directory as the location of the PKI, things generally work.

When `easyrsa` is **not** located in `$PWD` then things go wrong:
- `$EASYRSA` is evaluated to the script directory not the working directory.

While it is a very simple fix, #475 changes this behavior by explicitly setting `$EASYRSA` to `$PWD`.

This is a binary choice; **Either `easyrsa` is in `$PWD` or it is not**.
- If `$0` points to `$PWD` then `easyrsa` is here. Normal functions resumed..
- **Otherwise**, it is somewhere else. _Good luck_..

This seems to be a far simpler choice than the `if/elif/else` _maze_ to be found in `vars_setup()`. If **otherwise** then simple measures can be put in place for that specific situation.

Comments welcome.

**Comment by TinCanTech** [comment]
A special approach could be, to deliberately run `easyrsa` from within your chosen PKI.

**Comment by TinCanTech** [comment]
I am tempted to include all the data files as `heredoc`s inside `easyrsa`.

**Comment by TinCanTech** [comment]
### BUG:

If `easyrsa` is in your path and **not** in the current-directory then it will always fail to find `openssl-easyrsa.cnf`.  This is due to the current mess found in `vars_setup()`.

**Comment by TinCanTech** [comment]
In order to de-couple the requirement for `easyrsa` to be in the same location as the data files, `EASYRSA` should be `$PWD`.

`prog_dir` can be used to look for data files, they _might_ be present ..

**Comment by TinCanTech** [comment]
Because finding the data files is **critical** for `easyrsa`, the best location for them is: `/etc/easyrsa`

**Comment by TinCanTech** [comment]
Because the `x509-types` and data-files are intended to be edited by users, they need to be per PKI.

It makes sense for `init-pki` to copy the `x509-types` and data-files **from** `/etc/easyrsa` **to** the newly created PKI.

And then present **help** to editing those files on completing `init--pki`.

**Comment by Prouflon** [comment]
So to keep track, `init-pki` should copy the following files into a new PKI directory:
- `openssl-easyrsa.cnf`
- (`safessl-easyrsa.cnf` is automatically generated)
- `vars`
- `x509-types/`

It could be required for future versions of easyrsa that those files are in either `~/.config/easy-rsa` or `/etc/easy-rsa`.
As you mentioned they are critical.

**Comment by TinCanTech** [comment]
There is one question:
- Where should `vars` belong ?

It is customary to find `vars` in the parent folder to the PKI.

This can be copied/moved to the PKI folder but it MUST be very visible to users that behavior has (will) change.

**Comment by TinCanTech** [comment]
@Prouflon **any** feedback regarding https://github.com/OpenVPN/easy-rsa/pull/508 is most welcome.

**Comment by TinCanTech** [comment]
I need the output to this on Windows 11 with and without WSL:
```
$ readlink -f ./easyrsa
$ echo "$PWD"
$ set
```

**Comment by dariosusman** [comment]
Glad this was taken up. I was unable to articulate the problem. :)

I don't have a Windows 11 to assist with. 

But I do have this issue with Debian 11. The vars file in /opt/easyrsa is not honoured completely. Specifically in regards to the EASYRSA_CRL_DAYS variable

I have to set it manually:

```
root@corpapse2a-vpn01:~# ls -l /opt/
total 4
drwx------ 3 root root 4096 Apr 27 08:58 easyrsa
root@corpapse2a-vpn01:~# ls -l /opt/easyrsa/
total 24
lrwxrwxrwx 1 root root   27 Oct 27 14:43 easyrsa -> /usr/share/easy-rsa/easyrsa
-rw-r--r-- 1 root root 4616 Oct 27 15:30 openssl-easyrsa.cnf
drwx------ 8 root root 4096 Apr 27 08:58 pki
-rw-r--r-- 1 root root 8895 Oct 27 15:58 vars
lrwxrwxrwx 1 root root   30 Oct 27 14:43 x509-types -> /usr/share/easy-rsa/x509-types
root@corpapse2a-vpn01:~# cd /opt/easyrsa/
root@corpapse2a-vpn01:/opt/easyrsa# ./easyrsa version
EasyRSA Version Information
Version:     3.0.8
Generated:   Wed Sep  9 15:59:45 CDT 2020
SSL Lib:     OpenSSL 1.1.1n  15 Mar 2022
Git Commit:  f12e00e53b4f486ce3d119ca429198780fa694ac
Source Repo: https://github.com/OpenVPN/easy-rsa
```
I have to run it like this:
`EASYRSA_CRL_DAYS=3650 ./easyrsa  gen-crl` for the variable to be taken in. I've realised the issue seemed that it took the enviroment from  in /usr/share/easy-rsa, which has no vars file. So openssl-easyrsa.cnf defaults from /usr/share/easy-rsa are taken?

The vars file, in my opinion, should be taken from where the make-cadir script creates the easyrsa+PKI dirs. 

Thank you!

Cheers, 
Dario Susman

**Comment by TinCanTech** [comment]
Please try with current `git/master`.

**Comment by dariosusman** [comment]
Well, I've given it a try on my testing server.

It didn't appear to like it very much and it appears to expect it under the pki dir.
And, as you can see, even on the same directory, it thinks there's a conflict when there's none. It's the same directory.

```
root@warpcore:/etc/openvpn/ca# ./easyrsa gen-crl
Found: /etc/openvpn/ca/vars
Found: ./vars

Easy-RSA error:

Conflicting 'vars' files found.

Priority should be given to your PKI vars file:
* /etc/openvpn/ca/pki/vars


Host: nix | Linux | /bin/bash


root@warpcore:/etc/openvpn/ca#
root@warpcore:/etc/openvpn/ca# ls -tlrah
total 32K
lrwxrwxrwx 1 openvpn nogroup   30 Nov 23  2020 x509-types -> /usr/share/easy-rsa/x509-types
lrwxrwxrwx 1 root    root      27 Feb 17 23:38 easyrsa -> /usr/share/easy-rsa/easyrsa
-rw-r--r-- 1 openvpn nogroup 4.6K Feb 18 00:04 openssl-easyrsa.cnf
-rw-r--r-- 1 openvpn nogroup 8.5K Feb 18 00:14 vars
drwx------ 3 openvpn nogroup 4.0K Feb 18 00:14 .
drwxr-xr-x 5 openvpn nogroup 4.0K Mar 23 14:40 ..
drwx------ 8 openvpn nogroup 4.0K Apr 29 12:30 pki
root@warpcore:/etc/openvpn/ca# ls -tlrah pki/vars
ls: cannot access 'pki/vars': No such file or directory
root@warpcore:/etc/openvpn/ca# 

```

**Comment by TinCanTech** [comment]
I believe this is all essentially fixed, so changing milestone.

**Comment by dariosusman** [comment]
If the move forward is to have the vars file within the PKI dir, sure.

Thanks!

Cheers,
Dario Susman

**Comment by TinCanTech** [comment]
> If the move forward is to have the vars file within the PKI dir, sure.

It is not a hard requirement but it is heavily biased.

You can over-ride by using `--vars=your-vars`, as documented.

**Comment by dariosusman** [comment]
Gotcha. Thank you :)

Cheers,

Dario Susman

**Comment by TinCanTech** [comment]
I have been running `easyrsa` from `usr/local/sbin` and a `symlink` for 6+ months with no issie.
