### ISSUE TITLE
EasyRSA with LbreSSL (2.8.3) on MacOS

### ISSUE THREAD

**Issue by mbeekman** [OpenVPN/easy-rsa#504]
The additions in line 455-461 do not work on the MacOS version of LibreSSL as it looks like you might be missing a "2" case.

https://github.com/OpenVPN/easy-rsa/commit/a0dbc346bd92088ee481f5488ac53a7537b32073

We get this error:
"Unsupported SSL library: 2"

for an openssl version:
"LibreSSL 2.8.3"

Which should be supported? no?

We changed our library to OpenSSL 3 and move forward ... could also remove 455-461 from the script once it is dowloaded. 

But have to believe we are not the only ones experiencing this who might not have posted the issue.

Please let us know if you make the update and/or if we are missing something. 
Thanks in advance ... we appreciate your work.

**Comment by TinCanTech** [comment]
@mbeekman Thanks for your report.

This is a bug in `easyrsa`, LibreSSL is meant to be supported.

**Comment by mbeekman** [comment]
Hello I can clone the repo, but which repo? did you check that in to main already? ... or did I miss the link

**Comment by TinCanTech** [comment]
Ooops, sorry, I have not added the changes, so it would make no difference and would fail.

It is now a priority and will be patch later today.

FYI: The correct way to run the test is:
- `git clone https://github.com/OpenVPN/easy-rsa.git easy-rsa`
- `cd easy-rsa`
- `./op_test.sh -v`

**Comment by TinCanTech** [comment]
@mbeekman Changes applied, you can test if you have time `;-)`

**Comment by mbeekman** [comment]
hello ... we got farther ... but hit bump in 358-368 
"Unsupported openssl version: 2"

looks like that needs a 2) case as well

**Comment by TinCanTech** [comment]
@mbeekman Thank you very much for testing!

I'll send another patch to correct this bug, soon.
