### ISSUE TITLE
Bug: export-p12 failing on Windows

### ISSUE THREAD

**Issue by ben-reitz** [OpenVPN/easy-rsa#531]
Hey, I'm trying to run `export-p12` and am getting the following error on Windows:
```
EasyRSA Shell
# ./easyrsa export-p12 ben

Note: using Easy-RSA configuration from: ./vars
Using SSL: openssl OpenSSL 1.1.1n  15 Mar 2022
pkcs12: Use -help for summary.

Easy-RSA error:

Export of p12 failed: see above for related openssl errors.
```

Running this seems to succeed however:
```
# openssl pkcs12 \
> -in "pki/issued/ben.crt" \
> -inkey "pki/private/ben.key" \
> -passout pass:XXXXXX \
> -export \
> -out "/temp/ben.p12"
```

This is running from the easy-rsa bundled with the latest version of OpenVPN (2.5.6) after successfully running the following commands already
```
build-ca
build-server-full
build-client-full
gen-dh
```

`export-p8 ben` also seems to work fine

**Comment by TinCanTech** [comment]
@ben-reitz it works OK for me.

Could you please try again using [`easyrsa git/master`](https://github.com/OpenVPN/easy-rsa/blob/master/easyrsa3/easyrsa)

**Comment by ben-reitz** [comment]
Cool - tried that and it revealed a different error which was fortunately easy to fix

```bash
EasyRSA Shell
# ./easyrsa export-p12 ben
Found: C:/Program Files/OpenVPN/easy-rsa/vars
Found: ./vars

Easy-RSA error:

Conflicting 'vars' files found.

Priority should be given to your PKI vars file:

* C:/Program Files/OpenVPN/easy-rsa/pki/vars
```

That made it easy enough to know to copy my `vars` file from `/easy-rsa` to `/easy-rsa/pki` which fixed the issue.

Massive thanks for your help!!!

**Comment by TinCanTech** [comment]
@ben-reitz Thanks for your help testing :sunglasses: :cake: :beer:
