### ISSUE TITLE
How to find EasyRSA version?

### ISSUE THREAD

**Issue by viharm** [OpenVPN/easy-rsa#539]
I'm sorry if this is obvious, but I couldn't find any way to check what version of EasyRSA I'm running. I tried the following

```
./easyrsa version
./easyrsa --version
./easyrsa --version show-ca
./easyrsa show-ca --version
```

I also couldn't find any reference on the _Github_ repo.

Again, sorry if this is obvious, but any pointers will help very much, as I'd like to be on the latest version.

**Comment by viharm** [comment]
Also, I found a related issue #469 , but can't really find the outcome :-(

**Comment by TinCanTech** [comment]
`easyrsa version`

If that does not work then update your copy.

**Comment by WayneSallee** [comment]
I had the same question. And this page is at the top of the search results. And the other search results were not giving me the answer.
cd /etc/openvpn/easy-rsa
./easyrsa version
