### ISSUE TITLE
EASYRSA_EXTRA_EXTS ignored build build-ca

### ISSUE THREAD

**Issue by ptman** [OpenVPN/easy-rsa#54]
```
EASYRSA_EXTRA_EXTS='nameConstraints=permitted;DNS:example.com' ./easyrsa build-ca nopass
```

creates a ca.crt that doesn't include the nameConstraints extension. The only way I found to add name constraints to the CA was to edit `openssl-1.0.cnf`, adding the contents of `EASYRSA_EXTRA_EXTS` under `[ easyrsa_ca ]`

**Comment by QueuingKoala** [comment]
Good point, thanks for the report.

I think the way to resolve this is to use the already-existing x509-types/ dir layout (which defaults to the currently supplied options in the .cnf file for the 'ca' type) and use the -extfile flag to the x509 command. The idea here is to make the CA signing process more like how sign_req() works currently, supporting both x509-types/ and env-var additions to the certificate extensions.

For sites that wish to use different options for a self-signed CA verses signing other sub-CA requests, the default 'ca' file under x509-types/ can be copied to a sub_ca extensions file, or the equivalent approach used with env-vars.

**Comment by TinCanTech** [comment]
This essentially boils down to `build-ca` supporting `EASYRSA_EXTRA_EXTS`.

Linking: #525

**Comment by TinCanTech** [comment]
There is also another problem:
https://github.com/OpenVPN/easy-rsa/blob/9970d626c17a4f2c439ab34eba8b18f35fe40871/easyrsa3/easyrsa#L379-L388

`req_extensions` do not _fly_ for CAs.

**Comment by TinCanTech** [comment]
The **bottom_line** is:
- `EASYRSA_EXTRA_EXTS` is **not** the variable to use for CA extensions.

Suitable PRs welcome.

**Comment by TinCanTech** [comment]
Feedback welcome.
