### ISSUE TITLE
'build-ca nopass' incorrectly prompts for password - OpenSSL version 3

### ISSUE THREAD

**Issue by filipvh-sentia** [OpenVPN/easy-rsa#554]
Hello,

The current release of easyrsa prompts for a PEM password, even when using the `nopass` argument and setting the `EASYRSA_BATCH` environment variable.

OpenSSL: OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
easyrsa: easyrsa 3.0.8
System: Ubuntu 22.04

# Example
```
export EASYRSA_BATCH=1
export EASYRSA_CERT_EXPIRE=2048

./easyrsa init-pki
./easyrsa build-ca nopass
```
# Output:
```
Using SSL: openssl OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
Enter PEM pass phrase:
```
# Expected output:
None

# Fix

It seems you've already fixed the bug in the current master branch between the latest version ( 3.0.8 ) and master.
I'd rather not reference master in my automation scripts to avoid getting unexpected results.

Any ETA when a new version will be released/tagged?
I'll run tests against a specific commit and use that in the meantime.

Example of the execution against master.
```
./easyrsa init-pki
./easyrsa build-ca nopass
Using configuration from /tmp/<omitted>/easy-rsa/easyrsa3/pki/bfe59f7e/temp.f82e23a0
.....+...+....+.........+.....+.+...+...+............+...........+.......+...+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+.+..+....+...+.....+.+.....+......+...+......+.+......+.....+....+...+...........+......+....+..+....+...+..+....+.........+.....+......+.......+........+.........+.+..+..........+..+.......+..............+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.......+...+.......+.........+...........+......+...+....+..+.+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
..+.....+......+.......+......+..+.......+..+....+.........+..+...+.+...............+..+....+.....+.+..+.......+.....+.+..+...+....+...........+..........+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+...+..................+..+.+..+...+.........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..........+....+...............+..+...+.......+.........+...+..+......+...+.......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
```

**Comment by TinCanTech** [comment]
EasyRSA version 3.0.8 does not support OpenSSL version 3.x

Currently, only `easyrsa git/master` supports OpenSSL v3.x and it is still a _work in progress_.

**Comment by filipvh-sentia** [comment]
Thanks for the answer @TinCanTech  !
In that case I might hold off on using a specific commit from master in that case.

**Comment by TinCanTech** [comment]
Re-opening for others to report related problems.

**Comment by TinCanTech** [comment]
The release schedule for EasyRSA is as follows:
- Version 3.0.9 - Unknown
- Version 3.1.0 - Scheduled for 2022-05-13, but that will probably not be met.

**Comment by TinCanTech** [comment]
@ecrist Release time .. ?

**Comment by ecrist** [comment]
Yes. I can push v3.0.9 out this week.

Eric Crist

On May 4, 2022, at 6:23 AM, TinCanTech ***@***.***> wrote:

﻿

@ecrist<https://github.com/ecrist> Release time .. ?

**Comment by TinCanTech** [comment]
OpenSSL version 3 is now supported by EasyRSA version 3.0.9 and 3.1.x
