### ISSUE TITLE
date function for Darwin is incorrect

### ISSUE THREAD

**Issue by TinCanTech** [OpenVPN/easy-rsa#559]
https://github.com/OpenVPN/easy-rsa/runs/6336081225?check_suite_focus=true

Let's see the queue of Mac users breaking down the door to help .. *yawn*

**Comment by ecrist** [comment]
I'm not seeing anything useful in that log. Maybe mobile sucks. I can fix date on Darwin tomorrow.

Eric Crist

On May 7, 2022, at 1:48 PM, TinCanTech ***@***.***> wrote:

﻿

https://github.com/OpenVPN/easy-rsa/runs/6336081225?check_suite_focus=true

Let's see the queue of Mac users breaking down the door to help .. yawn

**Comment by TinCanTech** [comment]
The log doesn't have anything useful.

This is the code in question:
https://github.com/OpenVPN/easy-rsa/blob/af4120c50ea1379274839d8ef6cb0b8dce73028f/easyrsa3/easyrsa#L1651-L1659

**Comment by TinCanTech** [comment]
Following a minor unit-test change, it is apparent that the failed command if the first one: ` 	expire_date="$(date -j -f '%b %d %T %Y %Z' "$crt_not_after" +%s)" `

**Comment by TinCanTech** [comment]
> I can fix date on Darwin **tomorrow**.

Breath held ...

**Comment by mandree** [comment]
It's very simple. POSIX date only supports the -u option and +"FORMAT"

**Comment by ecrist** [comment]
This is a red herring.

I need to know information on how to reproduce - the op-test.sh script dies early due to missing support for ed25519 in LibreSSL, nothing to do with the date command.

I’m open to a discussion, but I’m thinking of dropping the “POSIX” standard claim in light of a BSD/GNU happy-medium claim.  I’ll open a new issue to discuss that.

Eric

**Comment by TinCanTech** [comment]
Run the unit test like so:
```
LIBRESSL_LIMIT=1 sh op-test.sh -vv
```

**Comment by TinCanTech** [comment]
I do not agree to "dropping POSIX claim".

**Comment by ecrist** [comment]
I think this is an error in the upstream unit tests:

|| :: ***** /Users/ecrist/ersa-release/easy-rsa/easyrsa3/easyrsa  build-server-full s01 nopass inline
Generating a 1024 bit RSA private key
............................++++++
.......................++++++
writing new private key to '/Users/ecrist/ersa-release/easy-rsa/easyrsa3/unit tests/pki-sys ssl-rsa/a1845ce5/temp.70e0c66f'
-----
date: illegal time format
usage: date [-jnRu] [-r seconds|file] [-v[+|-]val[ymwdHMS]]
            [-I[date | hours | minutes | seconds]]
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]

Easy-RSA error:

Undefined: 1652052143, 14083200


Note the Undefined at the end.  date was fed something empty.

Eric

**Comment by TinCanTech** [comment]
I guess this is a **Darwin** issue. github runner `macos-latest` maybe too up to date.

Manual test succeeds, with:
`
Darwin wiscii-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
`

```
wiscii@wiscii-MacBook-Pro easyrsa3 % openssl version
LibreSSL 2.8.3
```

**Comment by TinCanTech** [comment]
```
wiscii@wiscii-MacBook-Pro easyrsa3 % ./easyrsa init-pki                                        

WARNING!!!

You are about to remove the EASYRSA_PKI at:
* /Users/wiscii/git/easy-rsa/easyrsa3/pki

and initialize a fresh PKI here.

Type the word 'yes' to continue, or any other input to abort.
  Confirm removal: yes

* Notice:

  init-pki complete; you may now create a CA or requests.

  Your newly created PKI dir is:
  * /Users/wiscii/git/easy-rsa/easyrsa3/pki

  IMPORTANT: Easy-RSA 'vars' file has now been moved to your PKI above.


wiscii@wiscii-MacBook-Pro easyrsa3 % ./easyrsa build-ca nopass                                 
* Notice:
Using Easy-RSA configuration from: /Users/wiscii/git/easy-rsa/easyrsa3/pki/vars

* Notice:
Using SSL: openssl LibreSSL 2.8.3

...............+++
.......................................................................................+++
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Common Name (eg: your user, host, or server name) [Easy-RSA CA]:

* Notice:

CA creation complete and you may now import and sign cert requests.
Your new CA certificate file for publishing is at:
/Users/wiscii/git/easy-rsa/easyrsa3/pki/ca.crt


wiscii@wiscii-MacBook-Pro easyrsa3 % ./easyrsa build-server-full s1 nopass
* Notice:
Using Easy-RSA configuration from: /Users/wiscii/git/easy-rsa/easyrsa3/pki/vars

* Notice:
Using SSL: openssl LibreSSL 2.8.3

Generating a 2048 bit RSA private key
..................................................................+++
...........+++
writing new private key to '/Users/wiscii/git/easy-rsa/easyrsa3/pki/153692f4/temp.37f39c00'
-----
* Notice:

Keypair and certificate request completed. Your files are:
req: /Users/wiscii/git/easy-rsa/easyrsa3/pki/reqs/s1.req
key: /Users/wiscii/git/easy-rsa/easyrsa3/pki/private/s1.key

Using configuration from /Users/wiscii/git/easy-rsa/easyrsa3/pki/153692f4/temp.7237aeb6
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'s1'
Certificate is to be certified until Aug 11 00:53:33 2024 GMT (825 days)

Write out database with 1 new entries
Data Base Updated

* Notice:
Certificate created at: /Users/wiscii/git/easy-rsa/easyrsa3/pki/issued/s1.crt


```

**Comment by ecrist** [comment]
So, might be a test/expectation issue?

bash-3.2$ openssl version
LibreSSL 2.8.3

Eric

**Comment by ecrist** [comment]
I don't think date on darwin is a problem at all.

Eric Crist

On May 9, 2022, at 7:56 AM, TinCanTech ***@***.***> wrote:

﻿

Further investigation indicates that start_fix_sec is probably the problem:
https://github.com/OpenVPN/easy-rsa/blob/85b35cccb86f9f8ca1d79b0816ef2ef6bd574ae2/easyrsa3/easyrsa#L1654-L1660

**Comment by mandree** [comment]
> I guess this is a **Darwin** issue. github runner `macos-latest` maybe too up to date.
> 
> Manual test succeeds, with: `Darwin wiscii-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64`
> 
> ```
> wiscii@wiscii-MacBook-Pro easyrsa3 % openssl version
> LibreSSL 2.8.3
> ```

I do not buy "too up to date" unless there is some irony I were missing. That version of LibreSSL is pretty stale and has diverted from OpenSSL pretty early. About the date, see https://www.libressl.org/releases.html - Dec 2018 - so why waste time with it? 

Require a supported version of OpenSSL (meaning in the 1.1.1 or 3.0 tracks) and let the LibreSSL zealots deal with it. I understand why LibreSSL was forked, but essentially is has fallen so far behind it's not worth the efforts. And even OpenBSD offers ports of OpenSSL...

**Comment by mandree** [comment]
No objection against running on Macs, but developing new code against an outdated LibreSSL version seems pretty far off.

**Comment by TinCanTech** [comment]
@mandree can you please try running:
```
LIBRESSL_LIMIT=1 sh op-test.sh -vv
```

**Comment by TinCanTech** [comment]
LGTM
