### ISSUE TITLE
Wouldn't work with latest Ubuntu LTS release ( 22.04 )

### ISSUE THREAD

**Issue by ayanamidev** [OpenVPN/easy-rsa#560]
As per mentioned by https://askubuntu.com/questions/1403837/how-do-i-use-openssl-1-1-1-in-ubuntu-22-04, 

The latest LTS release of Ubuntu is shipped with openssl version 3,

So EasyRSA wouldn't work with the latest version of Ubuntu LTS without supporting the latest openssl version as well.

**Comment by TinCanTech** [comment]
Easy-RSA does not support OpenSSL version 3 at this time.

Ubuntu is not ready for OpenSSL version 3 either.

**Comment by ayanamidev** [comment]
> Ubuntu is not ready for OpenSSL version 3, either.

Well, they weren't ready for Python 3 as well

https://askubuntu.com/questions/1232812/whats-the-default-python-version-in-ubuntu-20-04

For every new LTS version releases, I think they enjoy packaging new toolchains that aren't actually not ready.

**Comment by ayanamidev** [comment]
@TinCanTech When would the EasyRSA be compatible with openssl version 3?

Maybe the community should submit the pull request for it?

**Comment by ayanamidev** [comment]
@TinCanTech BTW, could you ask anyone from OpenVPN about the deb file shipment for 22.04 as well? https://build.openvpn.net/debian/openvpn/testing/dists/ 

https://github.com/OpenVPN/openvpn/commit/baa1e67f310b1db3c5b7b9b9f12867a86c947648

I think someone has already started testing builds, so maybe soon?

**Comment by TinCanTech** [comment]
This is not a general support channel.
