### ISSUE TITLE
"The file is not a valid request." when there are multiple IP addresses in SAN

### ISSUE THREAD

**Issue by quonb** [OpenVPN/easy-rsa#564]
https://github.com/OpenVPN/easy-rsa/blob/20d2bedaedec5398d37225c4fe95924a27489270/easyrsa3/easyrsa#L1858
It should be `s/IP Address:/IP:/g`, with **g** flag to deal with multiple IP addresses in Subject Alternative Name field,
like in
https://github.com/OpenVPN/easy-rsa/blob/20d2bedaedec5398d37225c4fe95924a27489270/easyrsa3/easyrsa#L2403

**Comment by TinCanTech** [comment]
This would be more suitable as a PR.
