### ISSUE TITLE
Default to issuing under 36 month certificates

### ISSUE THREAD

**Issue by ptman** [OpenVPN/easy-rsa#57]
https://support.servertastic.com/neterr_cert_validity_too_long-the-server-certificate-has-a-validity-period-that-is-too-long/

**Comment by QueuingKoala** [comment]
I'll put some thought into this.

Really what this boils down to is people being aware of what the purpose and lifetime of the certificates they're issuing are. In terms of Easy-RSA, this is already easy to configure. However, this also has implications for use-cases signing sub-CAs, which presumably should default to the much longer period for CAs, not a fairly short recent new requirement from a standards-group for one particular usage of TLS/X.509.

Also, remember that Easy-RSA isn't just used to issue internal web server X.509 certs, but also for VPNs, 802.1X auth, and other implementations for which a 3-year max validity period may be far too small. It may make sense to require these users to increase their own validity periods, or possibly warn if the option is left unconfigured, encouraging users to set their own value, even if it's just confirming the built-in default.

**Comment by ptman** [comment]
I totally agree with your points. I gave this some thought myself, but I think that changing the default would result in fewer suprises. The default could be limited only for server certificates, but that increases complexity.

**Comment by ecrist** [comment]
Should be resolved in 93b0f2e74bb600c7f05c20eaa97f7b12fb7ba670
