### ISSUE TITLE
New renewal mechanism is not backward compatible

### ISSUE THREAD

**Issue by TinCanTech** [OpenVPN/easy-rsa#578]
Commit ef22701878bb10df567d60f2ac50dce52a82c9ee introduced a new renewal mechanism:
- Allows renewed certificates to be revoked by name not serial number.
- Stores renewed certificates by name not serial number.
- Store directories are **not** called `foo_by_serial` they are only `foo`
  eg. `renewed/certs_by_serial` is not used, `renewed/issued` is used.

The root cause of this incompatibility is that `renew` was a _half-baked-hack_ when it was first merged.

The final result of the new mechanism is that any renewed files which are stored by serial number are effectively lost to `eaasyrsa`, as it currently stands.

PRs solving this problem are welcome.

**Comment by ecrist** [comment]
The fix should be backported to v3.0.9 as well.

**Comment by TinCanTech** [comment]
What fix ?

**Comment by TinCanTech** [comment]
Could this also be included into v3.1.0 ?

**Comment by ecrist** [comment]
It could be in v3.1.1 but the v3.1.0 ship has already sailed.

Eric Crist

On May 22, 2022, at 11:37 AM, TinCanTech ***@***.***> wrote:

﻿

Could this also be included into v3.1.0 ?

**Comment by TinCanTech** [comment]
Perhaps, adjust [Milestone v3.1.1](https://github.com/OpenVPN/easy-rsa/milestone/13) ?

**Comment by TinCanTech** [comment]
> the v3.1.0 ship has already sailed

as has v3.0.9

**Comment by TinCanTech** [comment]
Summary of changes for resolution:

**Re-write `renew`** - This was complicated.
- Essential commit: https://github.com/OpenVPN/easy-rsa/commit/ac12dad0285a4c472d7c1eaed5548d6af2166051
- No longer renames files to the certificate `serialNumber`.
-  Moves files by `commonName` to mirror image directories under the `pki/renewed` directory.
  eg. Certificates - From: `pki/issued`, to `pki/renewed/issued`
- These files can then be targeted by `revoke-renewed commonName`.

**Introduce `revoke-renewed`** - https://github.com/OpenVPN/easy-rsa/commit/ef22701878bb10df567d60f2ac50dce52a82c9ee
- This revokes certificates which have been renewed, via the _new method_, and moves all associated files to the `revoked` DIR, where they are stored by `serialNumber`.

**Introduce `rewind-renw`** - #579
- This moves renewed files from `renewed/(foo)_by_serial` DIRs, to the mirrored DIRs mentioned above. It also renames the files from `serialNumber`, to `commonName`

**Notes**:
- All **revoked** certificates are stored in the `revoked` DIRs by `serialNumber`.
- Certificates can only be **renewed** **one time**, until they are **revoked** via `revoke-renewed`. They can be renewed indefinitely, provided that the preceding certificate is revoked first.
- Given enough time, `rewind-renew` will no longer be required because all renewals will have been done via the _new `renew` method_.
