### ISSUE TITLE
These characters are not supported: (') (&) (`) ($) (#)

### ISSUE THREAD

**Issue by jasonhe54** [OpenVPN/easy-rsa#582]
So I've been using EasyRSA on Ubuntu, but wanted to move it to Windows instead of on a VM.

Moving over, I have `set_var EASYRSA_EXT_DIR	"$EASYRSA/x509-types"` set in the vars files, but when running `easyrsa build-ca`, it returns "These characters are not supported: (') (&) (`) ($) (#)" and after entering a password to secure the RootCA Private Key, it just fails.

Any ideas?

Also, any suggestions about moving from Ubuntu to Windows...? Can I just move the files over? I'm guessing no, but what's the easiest way to go about it?

In case it helps, this is what it says after it fails 

> Could not open file or uri for loading private key from E://pki/f763005a/temp.2572bfab
B0340000:error:16000069:STORE routines:ossl_store_get0_loader_int:unregistered scheme:crypto/store/store_register.c:237:scheme=E
B0340000:error:1608010C:STORE routines:inner_loader_fetch:unsupported:crypto/store/store_meth.c:359:No store loader found. For standard store loaders you need at least one of the default or base providers available. Did you forget to load them? Info: Global default library context, Scheme (E : 0), Properties (<null>)

**Comment by TinCanTech** [comment]
> "These characters are not supported: (') (&) (`) ($) (#)"

Simply remove this: 

`set_var EASYRSA_EXT_DIR "$EASYRSA/x509-types"`



> moving from Ubuntu to Windows...? Can I just move the files over?

Yes you can.   If you installed Easy-RSA from the OpenVPN Windows installer then all you need to copy is your PKI folder.

**Comment by TinCanTech** [comment]
After **very much** testing, the characters which EasyRSA cannot support are:
```
1. Backtick (`) - Incompatible with easyrsa_openssl()
2. Open curly brace { - Have fun testing.
3. Close curly brace } - Have fun testing.
4. Double quote " - Have fun testing.

These characters either __will not__ (1)
or __can not__ (2,3,4) be fixed.
