### ISSUE TITLE
`date -j` fails on MacOS if MacPorts' `coreutils` installed 

### ISSUE THREAD

**Issue by frspackager** [OpenVPN/easy-rsa#583]
Use of `date -j` fails on MacOS when MacPorts `coreutils` package is installed and if `/opt/local/libexec/gnubin` is in and has priority in `$PATH` order over `/bin`.

Hardcoding `/bin/date` fixes the issue of course but there might be a more elegant wait to check at runtime and adjust arguments to use Linux style.

*Just a minor inconvenience is this great package.*

**Comment by TinCanTech** [comment]
The correct syntax for MacPorts `coreutils` `date` would be _more elegant_.

PRs welcome. :+1:

**Comment by frspackager** [comment]
I gave it a try and added a PR. Hope it helps.

**Comment by TinCanTech** [comment]
@frspackager could you please paste the output of `man date` from your system ?

**Comment by frspackager** [comment]
Sure, in the meantime, I thought about how I wrote the test, maybe I should add last resort default to MacOS' `/bin/date` if all else fails.

```console
$ date --version
date (GNU coreutils) 8.32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David MacKenzie.
```

```console
$ man date
DATE(1)                           User Commands                          DATE(1)

NAME
       date - print or set the system date and time

SYNOPSIS
       date [OPTION]... [+FORMAT]
       date [-u|--utc|--universal] [MMDDhhmm[[CC]YY][.ss]]

DESCRIPTION
       Display the current time in the given FORMAT, or set the system date.

       Mandatory arguments to long options are mandatory for short options too.

       -d, --date=STRING
              display time described by STRING, not 'now'

       --debug
              annotate the parsed date, and warn about questionable usage to
              stderr

       -f, --file=DATEFILE
              like --date; once for each line of DATEFILE

       -I[FMT], --iso-8601[=FMT]
              output date/time in ISO 8601 format.  FMT='date' for date only
              (the default), 'hours', 'minutes', 'seconds', or 'ns' for date and
              time to the indicated precision.  Example:
              2006-08-14T02:34:56-06:00

       -R, --rfc-email
              output date and time in RFC 5322 format.  Example: Mon, 14 Aug
              2006 02:34:56 -0600

       --rfc-3339=FMT
              output date/time in RFC 3339 format.  FMT='date', 'seconds', or
              'ns' for date and time to the indicated precision.  Example:
              2006-08-14 02:34:56-06:00

       -r, --reference=FILE
              display the last modification time of FILE

       -s, --set=STRING
              set time described by STRING

       -u, --utc, --universal
              print or set Coordinated Universal Time (UTC)

       --help display this help and exit

       --version
              output version information and exit

       FORMAT controls the output.  Interpreted sequences are:

       %%     a literal %
       %a     locale's abbreviated weekday name (e.g., Sun)
       %A     locale's full weekday name (e.g., Sunday)
       %b     locale's abbreviated month name (e.g., Jan)
       %B     locale's full month name (e.g., January)
       %c     locale's date and time (e.g., Thu Mar  3 23:05:25 2005)
       %C     century; like %Y, except omit last two digits (e.g., 20)
       %d     day of month (e.g., 01)
       %D     date; same as %m/%d/%y
       %e     day of month, space padded; same as %_d
       %F     full date; like %+4Y-%m-%d
       %g     last two digits of year of ISO week number (see %G)
       %G     year of ISO week number (see %V); normally useful only with %V
       %h     same as %b
       %H     hour (00..23)
       %I     hour (01..12)
       %j     day of year (001..366)
       %k     hour, space padded ( 0..23); same as %_H
       %l     hour, space padded ( 1..12); same as %_I
       %m     month (01..12)
       %M     minute (00..59)
       %n     a newline
       %N     nanoseconds (000000000..999999999)
       %p     locale's equivalent of either AM or PM; blank if not known
       %P     like %p, but lower case
       %q     quarter of year (1..4)
       %r     locale's 12-hour clock time (e.g., 11:11:04 PM)
       %R     24-hour hour and minute; same as %H:%M
       %s     seconds since 1970-01-01 00:00:00 UTC
       %S     second (00..60)
       %t     a tab
       %T     time; same as %H:%M:%S
       %u     day of week (1..7); 1 is Monday
       %U     week number of year, with Sunday as first day of week (00..53)
       %V     ISO week number, with Monday as first day of week (01..53)
       %w     day of week (0..6); 0 is Sunday
       %W     week number of year, with Monday as first day of week (00..53)
       %x     locale's date representation (e.g., 12/31/99)
       %X     locale's time representation (e.g., 23:13:48)
       %y     last two digits of year (00..99)
       %Y     year
       %z     +hhmm numeric time zone (e.g., -0400)
       %:z    +hh:mm numeric time zone (e.g., -04:00)
       %::z   +hh:mm:ss numeric time zone (e.g., -04:00:00)
       %:::z  numeric time zone with : to necessary precision (e.g., -04,
              +05:30)
       %Z     alphabetic time zone abbreviation (e.g., EDT)

       By default, date pads numeric fields with zeroes.  The following optional
       flags may follow '%':

       -      (hyphen) do not pad the field
       _      (underscore) pad with spaces
       0      (zero) pad with zeros
       +      pad with zeros, and put '+' before future years with >4 digits
       ^      use upper case if possible
       #      use opposite case if possible

       After any flags comes an optional field width, as a decimal number; then
       an optional modifier, which is either E to use the locale's alternate
       representations if available, or O to use the locale's alternate numeric
       symbols if available.

EXAMPLES
       Convert seconds since the epoch (1970-01-01 UTC) to a date

              $ date --date='@2147483647'

       Show the time on the west coast of the US (use tzselect(1) to find TZ)

              $ TZ='America/Los_Angeles' date

       Show the local time for 9AM next Friday on the west coast of the US

              $ date --date='TZ="America/Los_Angeles" 09:00 next Fri'

DATE STRING
       The --date=STRING is a mostly free format human readable date string such
       as "Sun, 29 Feb 2004 16:21:42 -0800" or "2004-02-29 16:21:42" or even
       "next Thursday".  A date string may contain items indicating calendar
       date, time of day, time zone, day of week, relative time, relative date,
       and numbers.  An empty string indicates the beginning of the day.  The
       date string format is more complex than is easily documented here but is
       fully described in the info documentation.

AUTHOR
       Written by David MacKenzie.

REPORTING BUGS
       GNU coreutils online help: <https://www.gnu.org/software/coreutils/>
       Report any translation bugs to <https://translationproject.org/team/>

COPYRIGHT
       Copyright © 2020 Free Software Foundation, Inc.  License GPLv3+: GNU GPL
       version 3 or later <https://gnu.org/licenses/gpl.html>.
       This is free software: you are free to change and redistribute it.  There
       is NO WARRANTY, to the extent permitted by law.

SEE ALSO
       Full documentation <https://www.gnu.org/software/coreutils/date>
       or available locally via: info '(coreutils) date invocation'


GNU coreutils 8.32                 March 2020                            DATE(1)
```

**Comment by TinCanTech** [comment]
> maybe I should add last resort default to MacOS

I was thinking the same `;-)`

Thanks for the man page, I'll take a closer look.

**Comment by frspackager** [comment]
Understood, I have the revised PR ready if you want to look at it anyway. GNU `date` (coreutils) seems to be common to most recent Linux distributions not based on `busybox`.

**Comment by TinCanTech** [comment]
Linking #593

**Comment by TinCanTech** [comment]
This has been addressed by #595 

Testing and feedback is welcome.

**Comment by frspackager** [comment]
@TinCanTech, did quite some extended testing and dates manipulation seem to work fine. However I do see other issues around conflicting behaviors with GNU tools like `grep` for RegExp (`vars` parsing for instance) when I play around between native MacOS and GNU equivalents from MacPorts. I need to do more exhaustive test and revert with proper diagnostics.

**Comment by TinCanTech** [comment]
To be honest, the intention to support multiple versions of these tools has not been put in writing. It is a simple _best guess effort_, to date.

You are welcome to raise multiple issues detailing all the problems that you find for MacPorts, or any other OS.

You are welcome to send pull requests dealing with these issues.

I am happy to help by reviewing and testing.  I'll even help to guide your effort, if I can.

There is no overt rush for any further changes, so you can work at your leisure or even not at all .. enjoy the summer starlight  `;-)`

**Comment by frspackager** [comment]
I totally understand. I will for now restrict testing to vanilla MacOS environment. Seems the `grep` issue on `vars` parsing is an issue irrespective of the tool used and would need a `-F` flag to disable regex matching which seems enabled by default. I will propose PR when I'm done with proper testing.

Thanks for your support.

**Comment by ecrist** [comment]
Please keep in mind these issues affect other non-GNU based systems. We cannot support every possible customization of every OS out there.

Eric Crist

On Jun 17, 2022, at 2:29 PM, FRS Packager ***@***.***> wrote:

﻿

I totally understand. I will for now restrict testing to vanilla MacOS environment. Seems the grep issue on vars parsing is an issue irrespective of the tool used and would need a -F flag to disable regex matching which seems enabled by default. I will propose PR when I'm done with proper testing.

Thanks for your support.

**Comment by frspackager** [comment]
@ecrist understood and no worries, the reason I raised an issue and started investigating is that MacPorts is the solution I use to transform a non-GNU system (MacOS) into GNU System and that was interfering with some of the tests in easyrsa. I will revert to a GNU-Linux usage in the future.

**Comment by ecrist** [comment]
Understood. But you see how that's just a bastardization right?

It's not reasonable to support this, really. We have to support 8^9000 combinations of things. If you want a GNU system, use one. Don't take a BSD system, abuse it to GNU, and expect everything to work.

This gets into all the embedded stuff, BusyBox, FreeNAS, etc etc etc.

I do not support this ticket or any patches to resolve it as it is a slippery slope.

Eric Crist

On Jun 18, 2022, at 7:34 PM, FRS Packager ***@***.***> wrote:

﻿

@ecrist<https://github.com/ecrist> understood and no worries, the reason I raised an issue and started investigating is that MacPorts is the solution I use to transform a non-GNU system (MacOS) into GNU System and that was interfering with some of the tests in easyrsa. I will revert to a GNU-Linux usage in the future.

**Comment by TinCanTech** [comment]
FTR: `busybox date` _is now supported and is preferred_.

Where available, `busybox date` can be installed without conflicting with whatever `date` is installed.  It is also very simple to use and fits EasyRSA requirements well.

**Comment by ecrist** [comment]
What I was really trying to say is that it is a slippery slope to try and support everyone's customization of their operating system.

Eric Crist

On Jun 19, 2022, at 5:26 AM, TinCanTech ***@***.***> wrote:

﻿

FTR: busybox date is now supported and is preferred.

Where available, busybox date can be installed without conflicting with whatever date is installed. It is also very simple to use and fits EasyRSA requirements well.
