### ISSUE TITLE
regression report 3.1.0 (since 3.0.8): vars handling

### ISSUE THREAD

**Issue by mandree** [OpenVPN/easy-rsa#589]
Greetings, I am the packager of the Easy-RSA package for FreeBSD. In our post-install scripot, we install the .example files for openssl-easyrsa.cnf and vars into /usr/local/share/easy-rsa (= $DATADIR), and install a wrapper that defines EASYRSA.

#! /bin/sh
: ${EASYRSA:="/usr/local/share/easy-rsa"}
export EASYRSA
exec "/usr/local/share/easy-rsa/easyrsa.real" "$@"

This apparently used to work nicely in 3.0.8 (no bug reports in months),
we now received a report about a 3.0.8 -> 3.1.0 upgrade breaking this, please see 
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=264415 for details.

**Comment by TinCanTech** [comment]
I believe that the correct solution, in this case, is for the packaging to **not** create the `vars` file.

`easyrsa` will create the `vars` file from the same source, `vars.example`, in the defined PKI at `init-pki`.

The script now heavily favors `vars` to be found in the PKI **only**.
If multiple viable `vars` files are found then this is considered to be an **error**.

If only one `vars` file is found and this is `init-pki` then that found `vars` file will be moved to the PKI automatically and a user message is issued (No message in batch mode).

If only one `vars` file is found but this is **not** `init-pki` then a warning is issued to move `vars` to the PKI , no further action is taken.

This is current and moving forward with version 3.1.x

**Comment by TinCanTech** [comment]
To be absolutely specific, in the case of the bug report:

`/usr/local/share/easy-rsa/vars` should **never** exist.

**Comment by mandree** [comment]
Thank you. Fixed in FreeBSD's port as of version 3.1.0_1, which no longer creates this file and only installs .../share/easy-rsa/vars.example, and ships with a post-install message to explain what needs to be done and that init-pki is a dangerous beast.

**Comment by TinCanTech** [comment]
Linking #566

**Comment by FireEmerald** [comment]
> A `vars` file should **not** exist until the PKI does AND the `vars` should **only** exist in the PKI.
> 
> **Feedback welcome**

@TinCanTech Please explain the purpose of the `set_var EASYRSA_PKI		"$PWD/custom/pki"` line inside a `vars` file, when a `vars` file should be **only** exist after creating that directory? The `EASYRSA_PKI` does not make any sense then.

**Comment by TinCanTech** [comment]
@FireEmerald Having a `vars` file which is external to the PKI in Easy-RSA version 3.1x is considered to be DEPRECATED.

These lines should really be removed from `vars.example`:
```
# Edit this variable to point to your soon-to-be-created key directory.  By
# default, this will be "$PWD/pki" (i.e. the "pki" subdirectory of the
# directory you are currently in).
#
# WARNING: init-pki will do a rm -rf on this directory so make sure you define
# it correctly! (Interactive mode will prompt before acting.)

#set_var EASYRSA_PKI		"$PWD/pki"

# Define directory for temporary subdirectories.

#set_var EASYRSA_TEMP_DIR	"$EASYRSA_PKI"
```
However, they remain for the time being.

**Comment by TinCanTech** [comment]
Commit https://github.com/OpenVPN/easy-rsa/commit/f4a604438d3ce5fe67a1f4db956dc42fc4ae5588 now allows the **vars** file to remain in the PKI parent folder, much like the old behavior.

  It also allows for a user defined **vars** file, option `--vars=foo`, to remain in place, provided that it is always called via `--vars=foo`

I am personally convinced that this is the correct way for `easyrsa` to behave .. but I've been wrong before.

@mandree  (And others) I would appreciate your thoughts and will do my best to answer any questions.

I am not in a rush to close this, simply looking to _drum up_ some interest in a _sticky wicket_.

**Comment by TinCanTech** [comment]
FTR: The changes made so far do _prefer_ **vars** to be found in the PKI .. but those changes have _essentially_ reverted back to previous behavior. I hope to find a middle ground for all, or, at least, most. `:-)`

**Comment by TinCanTech** [comment]
Linking #651
