### ISSUE TITLE
cert signed by easyrsa3 seems missed SAN in original request

### ISSUE THREAD

**Issue by yf13** [OpenVPN/easy-rsa#60]
Hi,

I have a cert request which contains the subjectAltName (SAN) extension, which is visible to the easyrsa3 tool:

```
[u@ubuntu:~/ca]$ easyrsa show-req qpidd.221

Showing req details for 'qpidd.221'.
This file is stored at:
/home/u/ca/pki/reqs/qpidd.221.req

Certificate Request:
    Data:
        Version: 0 (0x0)
        Subject:
            countryName               = cn
            commonName                = 10.69.6.90
        Attributes:
        Requested Extensions:
            X509v3 Subject Alternative Name:
                DNS:ubuntu-12, DNS:10.69.6.90
```

I can sign this as "server" type without issue, However, when I checked the output .crt file, it has no SAN extensions:

```
[u@ubuntu:~/ca]$ easyrsa show-cert qpidd.221

Showing cert details for 'qpidd.221'.
This file is stored at:
/home/u/ca/pki/issued/qpidd.221.crt

Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 16 (0x10)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer:
            commonName                = yf test ca
        Validity
            Not Before: May 12 22:00:52 2015 GMT
            Not After : May  9 22:00:52 2025 GMT
        Subject:
            countryName               = cn
            commonName                = 10.69.6.90
        X509v3 extensions:
            X509v3 Basic Constraints:
                CA:FALSE
            X509v3 Subject Key Identifier:
                18:53:A5:B8:68:A4:42:31:03:FB:CA:02:C8:41:96:60:02:C4:2B:17
            X509v3 Authority Key Identifier:
                keyid:7B:5B:2C:13:83:C0:C4:2D:0D:95:C9:F9:0B:C1:70:B3:F6:65:0E:AA
                DirName:/CN=yf test ca
                serial:FF:47:28:66:2F:DD:53:C5

            X509v3 Extended Key Usage:
                TLS Web Server Authentication
            X509v3 Key Usage:
                Digital Signature, Key Encipherment
```

When I applied this as a SSL server, and used the SAN to address it, client complains that server subject doesn't match host-name.

Can you give some hints?

Regards,
yf

**Comment by aiwilliams** [comment]
@yf13 I have run into this also. The only solution is providing the same `--subject-alt-name="DNS:www.example.net,DNS:secure.example.net"` option:
```
easyrsa --req-cn=*.example.net --subject-alt-name=DNS:example.net gen-req example.com.csr nopass
easyrsa --subject-alt-name=DNS:example.net sign-req server example.com.csr
```

This is made clear by reviewing the code. It generates a temporary openssl configuration file. If the option is not provided when signing the request, the configuration will not include the extensions in the generated configuration.

**Comment by mbruzek** [comment]
I am also encountering this issue where the signed certificate does not have SANs.  The workaround that @aiwilliams mentions is not possible because the master server is signing requests and does not know all the SAN values from the requesting server (its public, and private address, dns values etc).  

Is it possible to use easyrsa to print the SANs found in the request out in a format that we can send back to easyrsa when the request is signed?

**Comment by chuckbutler** [comment]
I've discovered a working work-around to this issue

If you update the shipping openssl configuring, eg: easy-rsa/easyrsa3/openssl-1.0.cnf

and place under the CA_default directive

```
[ CA_default ]
copy_extensions = copy
```

Incoming CSR's will have their SubjectAltNames preserved. However I'm not 100% clear on the implications of this approach.

**Comment by ecrist** [comment]
Doing this would allow a CSR to contain any SubjectAltNames the 
requestor desired, and have those automatically applied to the 
certificate upon signing.  I don't think it's a good default, but if you 
want to provide a patch that indicated the option, and what its use case 
is, I'm happy to integrate it.

Eric

**Comment by webdawg** [comment]
Is this patched or is this expected behaviour?

**Comment by webdawg** [comment]
is this patched or is this expected behaviour?

**Comment by ecrist** [comment]
This has not been patched yet.

Eric

**Comment by dreua** [comment]
Unrelated information for people landing here searching for why their created certificates lack subject fields:
Just edit your `vars` to include `set_var EASYRSA_DN	"org"`
