### ISSUE TITLE
X509-types files code-signing, email, and kdc serve no-purpose

### ISSUE THREAD

**Issue by TinCanTech** [OpenVPN/easy-rsa#607]
`X509-types` files: `code-signing`, `email`, and `kdc` are **never** used by `easyrsa` .. 

**Purge them all**.

**Comment by TinCanTech** [comment]
Linking #608

**Comment by dekeonus** [comment]
I will note that I've used `code-signing` and `email` however removing them won't really affect me (as I've already got those in my existing pkis)

**Comment by TinCanTech** [comment]
@dekeonus Please explain **_how_** you used them.

**Comment by dekeonus** [comment]
@TinCanTech for `code-signing` I've used a cert to sign a Windows installer for distribution of my CA and subCA certs. I've used a different cert to sign a Windows driver for a personal project I'm working on (chaining to the rootCA installed by the above).

For `email` I needed to sign a document for an educational institution I was at during the height of the pandemic. The institution did not provide certs to students, I also noted that the document management system (on site) was indicating that those staff certs were not signed by a trusted root. I extracted one of those certs to examine the kU and eKU and noted that it matched the `email` type.
While I didn't get the fancy image of signature + crypto signature (ie just the crypto signature) the document was regarded as signed by institution and the process for which the document was needed, did continue (without me having to organise a visit to the admin centre with their skeleton crew).

**Comment by TinCanTech** [comment]
The question remains: **_How_** did you use them ?

I have no interest in why/where you used them.

**Comment by dekeonus** [comment]
huh? perhaps in my weakened state I'm not understanding the question:
`easyrsa --days=1825 sign-req code-signing cert_dist`
this with a 2.?? series
`easyrsa sign-req code-signing dek_dev`
this with the 3.0.8 release

**Comment by TinCanTech** [comment]
> perhaps in my weakened state I'm not understanding the question:
> `easyrsa --days=1825 sign-req code-signing cert_dist`

That is exactly what I needed to see, thanks. :+1:

**Comment by TinCanTech** [comment]
@dekeonus Thank you for your feedback here.

Closing this PR as an incorrect assumption.
