### ISSUE TITLE
EasyRSA 'renew' does NOT renew, it builds a new certificate *and* key

### ISSUE THREAD

**Issue by TinCanTech** [OpenVPN/easy-rsa#609]
For **true** certificate _renewal_ the original key MUST be used.

I intend to **remake** Easy-RSA **_`renew`_**, as it _should have been done in the first place_.

**`renew` sucks .. don't use it.** -- Until further notice.

If you **already did** use **_`renew`_** then you can use `rewind-renew <serial-number>` to undo the damage caused. (Version 3.1x only)

**Comment by ecrist** [comment]
So, there's a few things to consider here that aren't currently well supported in EasyRSA:

1. There is not a canonical renew function that uses the old key.
2. Support for signing a naked CSR not generated by EasyRSA is not present
3. CA/sub-CA should be handled different from regular certificates

These three things should be addressed in an update to the renew function.  In reality, there really is no "renew" concept, you're just signing a new CSR with the CA/sub-CA.  

The private key used MAY NOT be present if there is support for #2 above.  This needs to be possible if we are to accept externally provided certificate signing requests.  It is best practice that the certificate authority NOT have access to the private key.

Finally, with changes to policy on lifetimes of certificates that are not CA/sub-CA certs, there are different requirements for lifetime, how we handle CRL, etc.  Yes, these are "just" certificates, but there is additional data to consider in this case.

Changes to the existing behavior of "renew" function in EasyRSA should not be made until the 3.2.x branch.  3.1.x should retain existing behavior sans bug fixes.

**Comment by TinCanTech** [comment]
> 1. There is not a canonical renew function that uses the old key

I have a patch which introduces `req-renew`, which creates a new request with the original key.

> Support for signing a naked CSR not generated by EasyRSA

I don't believe EasyRSA is the right tool for signing requests from unknown sources.

> CA/sub-CA should be handled different from regular certificates

Renewing a CA/Sub-CA leaves the user with the same problems as creating a completely new PKI; That is the problem of distributing the new CA certificate to all nodes.  IMPO, CA renewal offers almost no advantage over complete PKI recreation.

> Changes to the existing behavior of "renew" function in EasyRSA should not be made until the 3.2.x branch

Having created `req-renew`, `renew` can remain more-or-less as-is, see below.
(Although, I would prefer that `renew` be renamed to `rebuild` for semantic accuracy)

> 3.1.x should retain existing behavior sans bug fixes

One improvement which I intend to make to `renew` is the use of `nopass` option.

The simple change is:
- Issue a confirmation that `nopass` **has/has not** been used correctly for this renewal, prior to rebuilding the cert/key pair.

This is better than forgetting to use `nopass` and then breaking out of the script when prompted for an unwanted password.  Breaking out of the script at this point leaves the PKI in an undefined state, requiring manual intervention.

Also, it may not possible for `easyrsa` to determine if the new key should be encrypted because the original key may not be present. It may also be that the new key _encrypted state_ is different to the original.

**Comment by dsommers** [comment]
> > Support for signing a naked CSR not generated by EasyRSA
> 
> I don't believe EasyRSA is the right tool for signing requests from unknown sources.

That is not correct.  Any CA should be able to sign any CSR.  The CSR may for security reasons be created on a host not accessible to EasyRSA, where the intention is to not share the private key with anyone else. This may even include private keys stored on Yubikeys or Nitrokeys.  In these cases, the client provides the CSR to the CA maintainer, which can use EasyRSA to sign the request and return a signed certificate to be used by the client.

This is essentially the core concept of how any commercial CA operates today.

**Comment by dewydex** [comment]
> > CA/sub-CA should be handled different from regular certificates
> 
> Renewing a CA/Sub-CA leaves the user with the same problems as creating a completely new PKI; That is the problem of distributing the new CA certificate to all nodes. IMPO, CA renewal offers almost no advantage over complete PKI recreation.

There's possibly some confusion here regarding especially sub-CA operations. When Easy-RSA (or any CA) issues a subordinate/intermediary CA certificate, it's creating a chain of authority by granting permission for this sub-CA to issue certificates that will be trusted by entities which trust the root CA certificate (such as a root generated by Easy-RSA).

Whereas it is true that these sub-CA certificates need distributed, that distribution can then be "bundled" with other intermediary or leaf certificates (maintaining a "chain"). The issue being hinted at is less about distribution and more about trust, and the key takeaway is that these subordinate\intermediary certificates do not need to be specifically added to trust-stores\registries (the problem with "a completely new PKI"). They are distributed and trusted as part of other certificates in the chain (which may begin with Easy-RSA), and "renewal" in this case pertains to when\where\how these sub-CA's (which may not be Easy-RSA) are allowed to issue new certificates in the chain that will be trusted. 

This concept becomes one of Easy-RSA's strengths in general-purpose as having an "offline" CA used exclusively for the creation (and then ideally "renewal") of subordinate\intermediary CA's (which can then be operated in more timely, online, interactive manners) approaches the pinnacle of the use-cases and problem-sets certificate authorities were designed to handle in the larger landscape of diverse technology.

This might border the more "advanced" uses and configurations of Easy-RSA, but this software can and has been used for that exact purpose (quite effectively) in earlier versions. How those use-cases become reflected in future developments may well be in discussion, but the "possibility" of this type of configuration (as an offline root CA) is a notable part of the program's legacy.

**Comment by ecrist** [comment]
There are assumptions made with "simple" setups and use of EasyRSA that are not going to be true in more advanced deployments.  Namely that the CSR comes from the admin signing the certificate, and as an extension, the private key is available.  We **must** assume the we may only have a CSR and no private key.  A private key is not needed if we're provided a CSR.

Also, with regard to CA/sub-CA certificates, we need to ensure we aren't signing certificates that are valid longer than the CA doing the signing.  It's not up to EasyRSA to be concerned with deployment of CAs and sub-CAs - that's left to the admin.

Finally, there really is no such thing as an actual renewal in PKI - you're just generating a new certificate with the same CN.   There are artificial restrictions on duplicate CN within a validity window, but holding on to the idea that we must use the same key isn't how the real world does it.

**Comment by TinCanTech** [comment]
Re-opening for follow up discussion regarding `renew-req` command.

**Comment by dekeonus** [comment]
I have patched 3.0.8 (was looking at migrating this forward to 3.1.0) for more robust ANY cert type (well not the kdc type) renewals based just upon the existing csr (I put subjAltNames in the csr, and extract SAN for all but kdc type csr),  using some awk magic (looking over that awk code I'd say some chaos magic ... was avoiding using Gnu extensions to awk).

The awk compared the  extendedKeyUsage and keyUsage for the csr with the x509-types/ and IFF there was one match renewed the cert as that match if there was more than one match it printed the matches and directed the user to rerun as renewas <type> <filename_base> [ cmd-opts ]

**Comment by dekeonus** [comment]
example of the code (for basicConstraints)
```

	# FIXME: these awk scripts need to be updated as openssl changes/adds strings
# awk script to sort x509-type basicConstraints from pki/x509-types
	awk_s_type_bc='function arrsort(Z, x,y,z){ x=length(Z)
do { z=""; for(y=1;y<x;y++) { if(Z[y]>Z[y+1]) {
z=Z[y]; Z[y]=Z[y+1]; Z[y+1]=z } } } while(z!="")}

/^ ?#/ {next};
/basicConstraints/ {sub(/ ?basicConstraints ?= ?/,"");
gsub(/ /,""); split($0,W,","); asort(W); o="";
for(i in W) {o=o","W[i]} sub(/^,/,"",o); print toupper(o)}'

# awk script to convert/sort cert basicConstraints from openssl x509
	awk_s_crt_bc='function arrsort(Z, x,y,z){ x=length(Z)
do { z=""; for(y=1;y<x;y++) { if(Z[y]>Z[y+1]) {
z=Z[y]; Z[y]=Z[y+1]; Z[y+1]=z } } } while(z!="")}

{s=(NR==1?s:s ",")$0}END{
sub(/X509v3 Basic Constraints:/,"",s);
gsub(/ /,"",s); {split(s,W,","); arrsort(W); o="";
for(i in W) {o=o","W[i]} sub(/^,+/,"",o); print toupper(o)} }'

	# extract the basicConstraints, keyUsage, and extendedKeyUsage from cert
	crt_bc="$($EASYRSA_OPENSSL x509 -in $crt_in -noout -ext basicConstraints |awk "$awk_s_crt_bc")"



	x509_type_match=""
	# match the cert x509 extensions against each cert-type definition
	# FIXME should exclude COMMON? -won't match anyway
	for x509_type in $(ls $EASYRSA_EXT_DIR) ; do
		x509_type_bc="$(awk "$awk_s_type_bc" "$EASYRSA_EXT_DIR/$x509_type")"

```

**Comment by dekeonus** [comment]
including the keyUsage from openssl x509 as the substitution for basicConstraints may have been less than clear

```
# awk script to convert/sort cert keyUsage from openssl x509
	awk_s_crt_ku='function arrsort(Z, x,y,z){ x=length(Z)
do { z=""; for(y=1;y<x;y++) { if(Z[y]>Z[y+1]) {
z=Z[y]; Z[y]=Z[y+1]; Z[y+1]=z } } } while(z!="")}

{s=(NR==1?s:s ",")$0}END{
sub(/X509v3 Key Usage:/,"",s);
sub(/Digital Signature/,"digitalSignature",s);
sub(/Non Repudiation/,"nonRepudiation",s);
sub(/Key Encipherment/,"keyEncipherment",s);
sub(/Data Encipherment/,"dataEncipherment",s);
sub(/Key Agreement/,"keyAgreement",s);
sub(/Certificate Sign/,"keyCertSign",s);
sub(/CRL Sign/,"cRLSign",s);
sub(/Encipher Only/,"encipherOnly",s);
sub(/Decipher Only/,"decipherOnly",s);
gsub(/ /,"",s);
{split(s,W,","); arrsort(W); o="";
for(i in W) {o=o","W[i]} sub(/^,+/,"",o); print toupper(o)} }'

```

**Comment by TinCanTech** [comment]
@dekeonus Your comments do not belong on this thread.

Please start a new issue.

Your comments here **will be deleted**.

**Comment by dekeonus** [comment]
@TinCanTech fair enough, delete away. The gist of my comments are relevant to this this thread: A means to renew based upon the existing CSR.
I am curious to the reasoning behind requiring generation of a new CSR if the contents will match the old CSR.

**Comment by TinCanTech** [comment]
@dekeonus Please start your thread and refer to it here as a linked URL.

Then please, stop bombing other issues.

If you wish to discuss other options then we are available on IRC.

**Comment by TinCanTech** [comment]
@dekeonus  You can open as many **_new_ issues** as you need to. 

__

**Comment by TinCanTech** [comment]
Summary:
- `renew` builds a new certificate and key, this will not change.
- `renew-req` creates a new request from an existing key. `v3.1.1+` only.

**Comment by hyacin75** [comment]
This looks like it was added... and then, removed?

Can anyone shed any light on what happened here?

I'm in the same boat (and from a quick search online, so are many others) ... I can't update all my client certs, especially that they're now disconnected since my server cert expired ... I need to generate a new cert they'll accept and I thought this was the way :-/

**Comment by TinCanTech** [comment]
This _issue_ has been resolved.

EasyRSA command `renew` will correctly **renew** a certificate.

**Comment by dekeonus** [comment]
@hyacin75 
>
> Can anyone shed any light on what happened here?
> 

The original implementation did not _renew_ rather it created an entirely new private + public keypair & CSR & Cert (this functionality, if desired, is still available as `rebuild`) .
The old implementation was less than ideal in cases where users of EasyRSA were generating the CSR outside of the CA (or subCA) working directory (for example using EasyRSA on a target server to generate CSR and importing that CSR into a separate machine running an EasyRSA CA).

The current `renew` is a renew using the existing (possibly previously imported) CSR.
