### ISSUE TITLE
Improve debuggability by adding option to not remove temporary openssl config files

### ISSUE THREAD

**Issue by Yannik** [OpenVPN/easy-rsa#610]
In https://github.com/OpenVPN/easy-rsa/issues/596#issuecomment-1153923680, I suggested adding an option to not remove the temporary openssl config/extfile to improve debuggability.

Currently, this can only be achieved by commenting out
```
[ -z "$EASYRSA_TEMP_DIR_session" ] || rm -rf "$EASYRSA_TEMP_DIR_session"
```

and

```
rm -f "$easyrsa_openssl_conf"
rm -f "$easyrsa_extra_exts"
```

**Comment by TinCanTech** [comment]
This is not a complete solution.

There is no other way to do this, other than to keep the temporary config file for verification.

Example: This string is **not** expanded by `easyrsa`,  `x509-types/kdc`:
- `${ENV::EASYRSA_KDC_REALM}`

**Comment by TinCanTech** [comment]
Testing welcome. #667
