### ISSUE TITLE
'rewind-renew' needs to make 'renewed/issued' folder

### ISSUE THREAD

**Issue by TinCanTech** [OpenVPN/easy-rsa#612]
`rewind-renew` target `out` folder _should be_ `pki/renewed/issued` not `pki/issued`.  This is because the `renew` has already taken place and new certificate/key/req files already exist in the live PKI, thus `rewind-renew` wants to over-write the new files. [Bug]

`rewind-renew` is **not** intended to _undo_ a certificate renewal, it is meant to pull the file based on serial number from the `renewed/cert-by-serial` folder back into the `renewed/issued` folder, where it _regains_ its original filename, the `commonName`.  From there it can subsequently be revoked and moved to the `revoked/cert_by_serial` folder, never to return.

There is, however, a slight glitch. 

If `renew` is used without the option `nopass` when `nopass` was intended and is stopped midway via `Ctrl-C`then the old `renew` (which `rewind-renew` is there to undo) is not recovered by the script.. 

And `rewind-renew` is unable to help, even though the name suggests it _should_ work..

The bug here is that old `renew` was utterly broken. There is only so much that can be done (and I've done enough) to undo the damage caused..

**Comment by TinCanTech** [comment]
`rewind-renew` must ensure the `renewed/issued` (etc) folders exist.

Currently, only the target-out file-names are checked for not the folders themselves, which will be missing if `rewind-renew` is tried first.

**Comment by dsommers** [comment]
What is the use case for this feature?

**Comment by TinCanTech** [comment]
If you mean "what does `rewind-renew` do ?

**Answer**: Previous versions of `easyrsa` move the old cert/key/req to sub-folders in subfolder `pki/renewed`. The files are renamed to the serial number of the certificate .`crt`, `.key` and `.req`.

The problem then is that revoking the old certificate could not be done by `easyrsa`, because the code did not exist.

`rewind-renew` pulls the serial-numbered files from those old folders and renames them back to the original CN and places them into `renewed/issued`, `renewed/private` and `renewed/req`.

Now the old certificate can be revoked by using `revoke-renewed commonName`.
And the revoked files are all sent to the `revoked/` folder, the same as all other revoked certificates.

Without `rewind-renew` the old certificates which have been renewed are not in the right place for revocation.

Eventually `rewind-renew` will not be needed because the new version of `renew` does not rename the old files to their serial number.

Note: Only one cert/key/req of one `commonName` can exist in the `renewed` folder at any one time.  So, if you try to renew a certificate which has been renewed previously but not yet revoked then the second renew will fail, with the explanation why.

**Comment by dsommers** [comment]
You are answering "what does it do", not "when do I need to use this feature" (aka: use case).

**Comment by TinCanTech** [comment]
You always need `rewind-renew`, if you have used an older version of `easyrsa` to `renew` a certificate.

**Comment by dsommers** [comment]
> It is required to align files moved by the **old version** of `renew` to be inline with the new version.

Then I am again at loss at the use case.  When is it needed to run this `rewind-renew`, how will it be run and how often?  There is a lot of ambiguity here.  I see a lot of explanation of why things are wrong and how this feature will work.   But not the context it is to be used in.

If this is a one-time operation fixing the outcome of the old behavior, then this should be named something with "migrate", like `migrate-old-renewals` where it restores things as need to be with the new version of easyrsa.  If there are files missing or it can't do it correctly, this should be properly logged.  The `rewind-renew` doesn't really say much about the use case for this feature.

**Comment by TinCanTech** [comment]
I am certainly happy to rename the command for semantic accuracy but `migrate-` would be inaccurate. This is not a migration, this is undoing what has been changed by old `renew`.

The use-case is as I have explained, it is only required if a certificate has been renewed by the old(current release) version of `renew`.

The **new** version of `renew` also comes with `revoke-renewed`, which is required to revoke certificates in the `renewed` folder.

The old version of `renew` left these files, named by serial number, with no code to complete a revocation. In **Limbo**.

Unless you expect users to unpick the result of current `renew` then a programmatic solution is required to `rewind` those files into a working framework. IE. `rewind-renew`.

**Comment by dsommers** [comment]
I still do not have a full understanding, which is rooted in this question - in particular the last part of the second question.

>  When is it needed to run this rewind-renew, how will it be run and how often? 

With your last comment, I also just got even more questions:

* Is this run for each single certificate which for some reason can't be renewed without this?
* If yes, why can't this be implemented as a migration feature instead running it once after upgrading?

These are the questions related to use case.  You have provided comments with lot of details, but there are many gaps where I don't fully understand the problem you try to solve.

Basically, don't go low-level into how things are done yet. A use case is not about the technical implementation.  A very quick overview of a use case description:

1. Define the overall goal first, like "The user should be able to renew certificates issued by older EasyRSA releases". This should be short and concise without describing any problems itself:  "User wants to do X and need to do Y to achieve the goal".
2. Define the issue with current public releases: "To achieve X, there is a problem Z" ... Also short and concise what the high-level problem is - avoid technical and implementation details as much as possible. (like, "prior versions moved certificate files around to different directories", maybe with some more high-level explanation of why the situation is like this.)
3. Define who this use case affects (like, "users who did $OPERATION in prior releases are affected, because of $WHAT_HAPPENED_IN_PRIOR_RELEASES").
4. Define a possible solution to solve the goal in step 1: "The user should in normal situations run `$COMMAND` to renew a certificate, but due to $PROBLEM this is not possible unless $REQUIREMENT_TO_PERFORM_TASK. To solve this, one solution can be $DESCRIBE_SOLUTION". The core implementation details of the fix is normally not needed; this step needs to define in which state the "system" (EasyRSA) need to be in to solve the task and the overall, higher-level idea of changes needed so the "system" is in the proper state to perform the operation.  And this solution description needs to point back at what has been described in prior steps.

You might have explained a lot of this already in various bits and comments - and I probably have a vague idea of several of these points, but your information too unstructured for me to fully see and grasp the core of problem and why your proposal is the right solution.

This resource might help in regards to writing use cases: https://www.wikihow.com/Write-a-Use-Case

**Comment by TinCanTech** [comment]
Easy-RSA version 3.0.8, which stood as release version since **16 Sep 2020**, has no way to revoke a certificate once it has been renewed.  IMHO, a considerable security flaw, which stood for two years and should never have been released in the first place.

v308 Demonstration:
```
tct@home:~/git/easy-rsa/test/installed$ easyrsa init-pki

Note: using Easy-RSA configuration from: /home/tct/git/easy-rsa/test/installed/pki/vars


WARNING!!!

You are about to remove the EASYRSA_PKI at: /home/tct/git/easy-rsa/test/installed/pki
and initialize a fresh PKI here.

Type the word 'yes' to continue, or any other input to abort.
  Confirm removal: yes

init-pki complete; you may now create a CA or requests.
Your newly created PKI dir is: /home/tct/git/easy-rsa/test/installed/pki


tct@home:~/git/easy-rsa/test/installed$ easyrsa build-ca nopass
Using SSL: openssl OpenSSL 1.1.1f  31 Mar 2020
Generating RSA private key, 2048 bit long modulus (2 primes)
..........................................................+++++
...................................................................................+++++
e is 65537 (0x010001)
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Common Name (eg: your user, host, or server name) [Easy-RSA CA]:

CA creation complete and you may now import and sign cert requests.
Your new CA certificate file for publishing is at:
/home/tct/git/easy-rsa/test/installed/pki/ca.crt


tct@home:~/git/easy-rsa/test/installed$ easyrsa build-client-full c1 nopass
Using SSL: openssl OpenSSL 1.1.1f  31 Mar 2020
Generating a RSA private key
.................................................+++++
...................+++++
writing new private key to '/home/tct/git/easy-rsa/test/installed/pki/easy-rsa-573961.BAnRcM/tmp.N6ynAz'
-----
Using configuration from /home/tct/git/easy-rsa/test/installed/pki/easy-rsa-573961.BAnRcM/tmp.BKTo7m
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'c1'
Certificate is to be certified until Sep 29 10:04:11 2024 GMT (825 days)

Write out database with 1 new entries
Data Base Updated

tct@home:~/git/easy-rsa/test/installed$ EASYRSA_CERT_RENEW=900 easyrsa renew c1 nopass
Using SSL: openssl OpenSSL 1.1.1f  31 Mar 2020


Please confirm you wish to renew the certificate with the following subject:

subject=
    commonName                = c1


Type the word 'yes' to continue, or any other input to abort.
  Continue with renew: yes
Generating a RSA private key
......................................+++++
...................+++++
writing new private key to '/home/tct/git/easy-rsa/test/installed/pki/easy-rsa-574019.EE9g0h/tmp.yiDu3q'
-----
Using configuration from /home/tct/git/easy-rsa/test/installed/pki/easy-rsa-574019.EE9g0h/tmp.FJbvYs
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'c1'
Certificate is to be certified until Sep 29 10:04:26 2024 GMT (825 days)

Write out database with 1 new entries
Data Base Updated
```

Resulting PKI:
```
pki
├── ca.crt
├── certs_by_serial
│   └── 03E70958E3A48D142DC2FF8663AA5785.pem
├── index.txt
├── index.txt.attr
├── index.txt.attr.old
├── index.txt.old
├── issued
│   └── c1.crt
├── openssl-easyrsa.cnf
├── private
│   ├── c1.key
│   └── ca.key
├── renewed
│   ├── certs_by_serial
│   │   └── 97CB97049A5D25B2757773385E619617.crt
│   ├── private_by_serial
│   │   └── 97CB97049A5D25B2757773385E619617.key
│   └── reqs_by_serial
│       └── 97CB97049A5D25B2757773385E619617.req
├── reqs
│   └── c1.req
├── revoked
│   ├── certs_by_serial
│   ├── private_by_serial
│   └── reqs_by_serial
├── safessl-easyrsa.cnf
├── serial
└── serial.old

12 directories, 17 files
```
`easyrsa` **cannot** `revoke` certificate `c1`.

**Comment by TinCanTech** [comment]
I wrote a **vastly** improved version of `renew`, which can revoke a renewed certificate. But it cannot revoke a certificate which was renewed by v308 without preparing those certificates in advance. That is `rewind-renew`.

It also logically controls how a user can use `renew`. By only allowing one unique-by-commonName certificate to exist in the renewed storage area.  If a user wants to renew another certificate for a specific commonName then they MUST revoke the previous one first.

All revoked certificates etc end up in the revoked storage area, regardless of renewal or not.

The issue is that v308 `renew` is incompatible with v309+, so a mechanism to recover those renewed-by-serialNumber certificates was required.  This is the function of `rewind-renew`.

As for how I chose to accomplish this task, that is intrinsically linked to the mess which v308 left behind in its wake and the subsequent issues which were raised.

**Comment by TinCanTech** [comment]
> 1. Define the overall goal first, like "The user should be able to renew certificates issued by older EasyRSA releases". This should be short and concise without describing any problems itself:  "User wants to do X and need to do Y to achieve the goal".

The user wants to revoke certificates which have been renewed.  This is not possible with Easy-RSA v308.  There is no "solution Y" to this problem.

In order to revoke the certificate the user must use raw `openssl` command and input raw certificate file.  If the user then wants those revoked certificates to be placed in the revoked storage area they must do so manually.

**Comment by TinCanTech** [comment]
> 2\. Define the issue with current public releases: "To achieve X, there is a problem Z" ... Also short and concise what the high-level problem is - avoid technical and implementation details as much as possible. (like, "prior versions moved certificate files around to different directories", maybe with some more high-level explanation of why the situation is like this.)

With v308 there is no way to revoke a renewed certificate.  It has to be done manually, as described above.

The situation is like this because the original version of `renew` was incomplete. There was never a way to revoke a renewed certificate, except manually, as decribed above.

**Comment by TinCanTech** [comment]
> 3\. Define who this use case affects (like, "users who did $OPERATION in prior releases are affected, because of $WHAT_HAPPENED_IN_PRIOR_RELEASES").

Every certificate that has been renewed, since v306. #286

**Comment by TinCanTech** [comment]
> 4\. Define a possible solution to solve the goal in step 1: "The user should in normal situations run `$COMMAND` to renew a certificate, but due to $PROBLEM this is not possible unless $REQUIREMENT_TO_PERFORM_TASK. To solve this, one solution can be $DESCRIBE_SOLUTION". The core implementation details of the fix is normally not needed; this step needs to define in which state the "system" (EasyRSA) need to be in to solve the task and the overall, higher-level idea of changes needed so the "system" is in the proper state to perform the operation.  And this solution description needs to point back at what has been described in prior steps.

There was no solution provided by EasyRSA.  There were no proposals and no PRs.

Since the introduction of `renew`, old cert/key/req files were moved out of the way, unnecessarily. Not only were they moved beyond the reach of the script, they were also renamed to the serial number of the x509 cert.  Only ONE of these acts is necessary:
- Either move the file out of the way to another folder
- **OR** rename it and leave it where it is.

Had the file been moved and not renamed then the situation would be as I have created.

Had the file been renamed to the cert serial number ONLY then it could have been revoked by serial number, with existing code.

The step of `rewind-renew` is to align the old renewed files with the new renewed system, so that they can be revoked.

So, the question is: Why was incomplete and broken `renew` code merged in the first place ?

**Comment by TinCanTech** [comment]
WRT **the question of** _The way in which `renew` is currently broken_:

Currently, the expectation on the user is that they should either:
- Keep an **external record** of All certificate `commonName` to `serialNumber`.
- OR **Fish** through the currently `renew`ed certificate files, _listed by `serialNumber` ONLY_, looking for the `commonName` of the certificate they wish to `revoke`.

**This is the expectation of EasyRSA v308.**

**Comment by TinCanTech** [comment]
> With your last comment, I also just got even more questions:
> 
>     * Is this run for each single certificate which for some reason can't be renewed without this?
> 
>     * If yes, why can't this be implemented as a migration feature instead running it once after upgrading?

Just to address these two questions:
1. Yes, `rewind-renew` must be run for each individual certificate which has been renewed with Easy-RSA v306 - v308.
2. This cannot be implemented as a migrate feature for all certificates which have been renewed because there could be certs which will resolve to the same `commonName`. IE. The same `cert/key/req` file-names in the same folders.

There may be different ways to achieve the same goal but is it worth the effort when `rewind-renew` and `revoke-renewed` are technically sound ?

Regarding my earlier _speculation_, I retract that comment. However, I have spent **many hours** considering this problem and my solution and .. **I am only human** ..

**Comment by TinCanTech** [comment]
Regarding your reply:


> Speculations why things are done in certain ways will never be a fruitful path to walk down. And that will not and should not be answered

You will choose your path and I will choose mine.

I will ALWAYS ask.

Your choice is: How you answer.  

Censorship is NEVER a good or popular choice, as an answer.
