### ISSUE TITLE
Command 'renew' should not use option 'nopass'

### ISSUE THREAD

**Issue by TinCanTech** [OpenVPN/easy-rsa#613]
Command `renew` should be aware of a password requirement or not.

When creating a new certificate it is easy to make a mistake and do it again.

When _renewing_ a certificate it is easy to make a mistake and `easyrsa` chokes if you do make a mistake and try to `break` out of it.

**Comment by dsommers** [comment]
This needs more explanation.  If a certificate is _renewed_, it should to use the already existing private key to generate the signing request. And it can use the existing certificate as a "template" for the renewal.  If the private key is password protected, that password need to be processed in the process.

      $ openssl x509 -x509toreq -in test-cert.pem -signkey test-key.pem > test-csr.pem

**Comment by TinCanTech** [comment]
> If a certificate is _renewed_, it should to use the already existing private key to generate the signing request.

The current version of `renew` does **not** use the existing key, both cert and key are built from scratch.  This is why I objected to calling it `renew` in the very first place, over a year ago.  This version of `renew` should be called `rebuild` ..

**Comment by dsommers** [comment]
well, I was quite a bit unclear. Sorry about that.

When you use the approach above (`openssl x509 -x509toreq` feature), what essentially happens is that it extracts all the certificate details and generates a new CSR from scratch and signs it with the local private key.

Creating a new private key sounds a bit too invasive, as that means two components needs to be replaced instead of just the certificate part.

**Comment by ecrist** [comment]
If we can use the existing key, we should.  But, not doing so isn't "broken" per se.  Referring to it as broken or "damaged" is an opinion that has little technical merit.

I support improvement here, but calling everything before broken, and treating it as such, is not productive and potentially introduces confusion.

**Comment by TinCanTech** [comment]
I found a better solution:

If `renew` is interrupted by the user then do a clear-up by calling `renew_restore_move()` from `clear_up()`, which is called by `trap` for `Ctrl-C` break.
