### ISSUE TITLE
Upgrade EasyRSA v2.x to v3.x PKI stops working from v3.0.9-rc1 onward

### ISSUE THREAD

**Issue by amerello** [OpenVPN/easy-rsa#622]
The command `easyrsa upgrade pki` stops working in accordance with this [guide](https://community.openvpn.net/openvpn/wiki/easyrsa-upgrade) starting on v3.0.9-rc1.
With Version 3.0.7 and 3.0.8 the upgrade works as expected and the v2.x vars are upgraded to the v3 equivalent.
Starting from 3.0.9-rc1 the following error occurs:
```bash
$ ./easyrsa upgrade pki
Found: /home/dev/src/pki_test/EasyRSA-v3.0.9-rc1/vars
Found: ./vars

Easy-RSA error:

Conflicting 'vars' files found.

Priority should be given to your PKI vars file:
* /home/dev/src/pki_test/EasyRSA-v3.0.9-rc1/pki/vars


Host: nix | Linux | /bin/bash

```
After which the upgrade process is aborted. 
I believe this is related to [issue 589](https://github.com/OpenVPN/easy-rsa/issues/589)

**Comment by TinCanTech** [comment]
The problem here is that `easyrsa` has found two different `vars` files and does not know which one to use for the upgrade.

@amerello can you confirm which of the two `vars` files is the correct one in this case ?

**Comment by amerello** [comment]
@TinCanTech both `vars` referenced are the same file, one is the relative path (./vars) and the other the absolute path (/home/dev/src/pki_test/EasyRSA-v3.0.9-rc1/vars) in this case.
The guide requests in step 2 to copy the old files: 

> Copy your existing EasyRSA version 2 files and directories into ./easyrsa3

This includes the old vars version with `export`, which at least on version 3.0.7 and 3.0.8 are replaced with the new format `set_var`

**Comment by TinCanTech** [comment]
> both `vars` referenced are the same file, one is the relative path (./vars) and the other the absolute path (/home/dev/src/pki_test/EasyRSA-v3.0.9-rc1/vars) in this case.

Thanks.

In this case, I believe I have resolved that particular circumstance in a later patch, I will search and update here when I have confirmed.

For the time being I cannot offer a resolution to this particular problem.

**Comment by amerello** [comment]
> Thanks.

@TinCanTech thank you for looking into this!

**Comment by TinCanTech** [comment]
The code to detect the duplicate `./vars` verses the `/full/path/vars` file was introduced here: https://github.com/OpenVPN/easy-rsa/commit/26b7247f708f2b895c289aefaab9b99023aa7860#diff-facbd438107d2ef365738070a1bd97ab30395e1e821eec939bd766b8a73b9464R2975

**Comment by amerello** [comment]
@TinCanTech  running the upgrade from `git/master` ([e5ec1ab](https://github.com/OpenVPN/easy-rsa/commit/e5ec1ab7718ac6dac4138745c997a8ae64ef0832)) I don't experience the vars error that aborts the process at the beginning. 

After the existing certificate verification I see the following output though:

```bash
Found current CA at: /home/dev/src/pki_test/easy-rsa/easyrsa3/keys/ca.crt

Type the word 'yes' to continue, or any other input to abort.
  * Confirm CA shown above is correct: yes


Easy-RSA error:

Non-existant temporary session: 

Easy-RSA error:

easyrsa_openssl - Failed to create temporary file (1)
EasyRSA Version Information
Version:     ~VER~
Generated:   ~DATE~
SSL Lib:     OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
Git Commit:  ~GITHEAD~
Source Repo: https://github.com/OpenVPN/easy-rsa
Version: dev | nix | Linux | /bin/bash | ssl_lib not set
```

So the upgrade isn't successful, like up to 3.0.8, but this seems to be a different issue than the `vars` one. Do you have an idea what could be the problem here?

Thanks again for taking the time to look into this

**Comment by TinCanTech** [comment]
@amerello I cannot replicate your problem.

For starters, the output above is incomplete, there should be warnings prior to verifying your CA.

This is what I expect to see:
```
tct@home:~/git/easy-rsa/easy-rsa-v2-test$ ./easyrsa upgrade pki
NOTE: If you run ./clean-all, I will be doing a rm -rf on /home/tct/git/easy-rsa/easy-rsa-v2-test/keys
NOTE: If you run ./clean-all, I will be doing a rm -rf on /home/tct/git/easy-rsa/easy-rsa-v2-test/keys
* Using Easy-RSA configuration from: /home/tct/git/easy-rsa/easy-rsa-v2-test/vars

WARNING
=======
Move your vars file to your PKI folder, where it is safe!


WARNING
=======

=========================================================================

                           * WARNING *

Found settings from EasyRSA-v2 which are not compatible with EasyRSA-v3.
Before you can continue, EasyRSA must upgrade your settings and PKI.
* Found EASYRSA and vars file:
  /home/tct/git/easy-rsa/easy-rsa-v2-test
  /home/tct/git/easy-rsa/easy-rsa-v2-test/vars :

Further info:
* https://community.openvpn.net/openvpn/wiki/easyrsa-upgrade

Easyrsa upgrade version: v1.0a (2020/01/08)
=========================================================================




This upgrade will TEST that the upgrade works BEFORE making any changes.

Type the word 'yes' to continue, or any other input to abort.
  * EasyRSA **TEST** upgrade (Changes will NOT be written): yes

-------------------------------------------------------------------------
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            7a:38:ac:cd:e4:cb:aa:30:e2:2e:4a:c4:08:fb:6f:f8:9f:64:b2:be
        Signature Algorithm: sha256WithRSAEncryption
        Issuer:
            countryName               = US
            stateOrProvinceName       = CA
            localityName              = SanFrancisco
            organizationName          = Fort-Funston
            organizationalUnitName    = changeme
            commonName                = changeme
            name                      = changeme
            emailAddress              = mail@host.domain
        Validity
            Not Before: Jul 29 18:02:05 2022 GMT
            Not After : Jul 26 18:02:05 2032 GMT
        Subject:
            countryName               = US
            stateOrProvinceName       = CA
            localityName              = SanFrancisco
            organizationName          = Fort-Funston
            organizationalUnitName    = changeme
            commonName                = changeme
            name                      = changeme
            emailAddress              = mail@host.domain
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                32:98:62:4D:E7:84:62:3D:F3:F8:D7:4D:7D:7F:C4:6C:02:BC:27:87
            X509v3 Authority Key Identifier: 
                keyid:32:98:62:4D:E7:84:62:3D:F3:F8:D7:4D:7D:7F:C4:6C:02:BC:27:87
                DirName:/C=US/ST=CA/L=SanFrancisco/O=Fort-Funston/OU=changeme/CN=changeme/name=changeme/emailAddress=mail@host.domain
                serial:7A:38:AC:CD:E4:CB:AA:30:E2:2E:4A:C4:08:FB:6F:F8:9F:64:B2:BE

            X509v3 Basic Constraints: 
                CA:TRUE
-------------------------------------------------------------------------

Found current CA at: /home/tct/git/easy-rsa/easy-rsa-v2-test/keys/ca.crt

Type the word 'yes' to continue, or any other input to abort.
  * Confirm CA shown above is correct: yes

cp: cannot stat '/home/tct/git/easy-rsa/easy-rsa-v2-test/keys/index.txt.attr': No such file or directory

Notice
------

============================================================================
The update has failed but NOTHING has been lost.

ERROR: Failed to copy /home/tct/git/easy-rsa/easy-rsa-v2-test/keys/index.txt.attr to /home/tct/git/easy-rsa/easy-rsa-v2-test/pki
----------------------------------------------------------------------------

Further info:
* https://community.openvpn.net/openvpn/wiki/easyrsa-upgrade#ersa-up23-fails

Easyrsa3 upgrade FAILED
============================================================================

```

**Comment by amerello** [comment]
@TinCanTech i should have mentioned that i removed all the output from my previous message until after the certificate information is printed out, because it contains sensitive information

**Comment by TinCanTech** [comment]
Can you post the complete output with redacted certificate data please.

**Comment by TinCanTech** [comment]
@amerello I have **solved** this, so you do not need to post any further output.

**Comment by TinCanTech** [comment]
@amerello can you please confirm that this works for you.

**Comment by amerello** [comment]
@TinCanTech I just was able to get back to this. Running from `git/master` [bee93cf8692c3ff52c6256960d59ce5f07d8bc3c](https://github.com/OpenVPN/easy-rsa/commit/bee93cf8692c3ff52c6256960d59ce5f07d8bc3c)
Upgrade still fails with the following output:

```bash
NOTE: If you run ./clean-all, I will be doing a rm -rf on /home/dev/src/pki_test/easy-rsa/easyrsa3/keys
NOTE: If you run ./clean-all, I will be doing a rm -rf on /home/dev/src/pki_test/easy-rsa/easyrsa3/keys
* Using Easy-RSA configuration from: /home/dev/src/pki_test/easy-rsa/easyrsa3/vars

WARNING
=======
Move your vars file to your PKI folder, where it is safe!

* Using SSL: openssl OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

WARNING
=======

=========================================================================

                           * WARNING *

Found settings from EasyRSA-v2 which are not compatible with EasyRSA-v3.
Before you can continue, EasyRSA must upgrade your settings and PKI.
* Found EASYRSA and vars file:
  /home/dev/src/pki_test/easy-rsa/easyrsa3
  /home/dev/src/pki_test/easy-rsa/easyrsa3/vars :

Further info:
* https://community.openvpn.net/openvpn/wiki/easyrsa-upgrade

Easyrsa upgrade version: v1.0a (2020/01/08)
=========================================================================




This upgrade will TEST that the upgrade works BEFORE making any changes.

Type the word 'yes' to continue, or any other input to abort.
  * EasyRSA **TEST** upgrade (Changes will NOT be written): yes


Notice
------

============================================================================
The update has failed but NOTHING has been lost.

ERROR: DEFAULT NEW PKI exists: /home/dev/src/pki_test/easy-rsa/easyrsa3/pki
----------------------------------------------------------------------------

Further info:
* https://community.openvpn.net/openvpn/wiki/easyrsa-upgrade#ersa-up23-fails

Easyrsa3 upgrade FAILED
============================================================================

```

Could we reopen this ticket, or did I choose the wrong branch?

**Comment by TinCanTech** [comment]
Thank you very much for thoroughly testing and feeding back your experience.

**Comment by mohag** [comment]
Mainly notes for someone else trying to upgrade:

I found that the easiest way to get a 2 to 3 upgrade done is to use 3.0.7 (and maybe 3.0.8, I did not test that, but 3.0.9 was failing with the error from this issue) - latest 3.1 fails the vars file since it does 3.x checks on the 2.x vars file (it complains that "export" is not allowed or if those are removed it gets the "conflicting vars file" or if `--vars=./vars` is given `vars file not found`)

(I don't know if some intermediate 3.1 versions worked as well, this issues appears to imply that they did)

After that migration, upgrading to latest 3.1 works.

If the upgrade fails with `CA certificate does not match vars/vars.bat file settings`, run `sh -x easyrsa upgrade pki` to see which checks fail... (No idea how the Windows version works)

The [OpenVPN wiki page](https://community.openvpn.net/openvpn/wiki/easyrsa-upgrade) was used as a base for the upgrade.
