### ISSUE TITLE
install_data_to_pki() /usr/local/share/easy-rsa should come before /usr/share/easy-rsa

### ISSUE THREAD

**Issue by dekeonus** [OpenVPN/easy-rsa#627]
https://github.com/OpenVPN/easy-rsa/blob/7b4d2fb23e50bc645132ffb392bc4201a2332857/easyrsa3/easyrsa#L1036-L1043

Take this hypothetical:
User's package manager has installed easy-rsa, but has not populated /etc/easy-rsa (only /usr/share/easy-rsa).
The user installs locally a newer easy-rsa (for some bugfix or feature).
For most systems /usr/local/bin is on the path before /usr/bin, ergo one would expect the easyrsa running from /usr/local/bin to pickup the vars.example from /usr/local/share/easy-rsa (especially pertinent if the reason for the local install was a new feature).

**Comment by TinCanTech** [comment]
Ref: install_data_to_pki() /usr/local/share/easy-rsa **should come before** /usr/share/easy-rsa

You are obviously correct. 

This must be fixed.

**Comment by TinCanTech** [comment]
@dekeonus would you also expect `/etc/easy-rsa` to be third ?

eg:
```
	for area in \
		'/usr/local/share/easy-rsa' \
		'/usr/share/easy-rsa' \
		'/etc/easy-rsa' \
		"$PWD" \
		"${0%/*}" \
		# EOL - # Add more distros here

```

**Comment by dekeonus** [comment]
At first thought no I'd expect `/etc/easy-rsa` to be first in the list. However I'm not sure what package maintainers in other distributions are doing RE user changes to files in /etc.
So I'm not sure if it should be first or second (with `/usr/local/share/easy-rsa` first).

I would hope that package maintainers are honouring changes by the local admin, but in the past I have been caught out by some package or other not providing a `dpkg reconfigure` for some conf file that got overwritten.

**Comment by TinCanTech** [comment]
Due to your original point:


> The user installs locally a newer easy-rsa (for some bugfix or feature).
> For most systems /usr/local/bin is on the path before /usr/bin, ergo one would expect the easyrsa running from /usr/local/bin to pickup the vars.example from /usr/local/share/easy-rsa (especially pertinent if the reason for the local install was a new feature).

I am considering dropping `/etc/easy-rsa` as a source for these data files.

**Comment by dekeonus** [comment]
I'd consider that the correct thing to do: from discussion in #589 vars is supposed to be a per pki config, not a global config.

I suppose users wanting a shared vars could just use symlinks, though Windows users might have some issues RE whether mksh can use ntfs symlinks (provided the user knew how to make them).

**Comment by TinCanTech** [comment]
Linking #635 20f7aaa - Keep `/etc/easy-rsa` as a source but make it permanently last place.

**Comment by TinCanTech** [comment]
Closed via https://github.com/OpenVPN/easy-rsa/commit/20f7aaa9c6727389c40970cd0e6ca28bd05f306a
