### ISSUE TITLE
`sign-req` does not check for an existing certificate

### ISSUE THREAD

**Issue by TinCanTech** [OpenVPN/easy-rsa#629]
Easy to reproduce:
- Create a PKI and CA certificate.
- Build a new client: `build-client-full client-1 nopass`
- Try to build another new client named `client-1`,
  This will correctly fail.
- Use `sign-req client client-1`
  This will over-write the existing certificate, **without warning**.
  It will also add **another** record to `index.txt` for `client-1`.

**Comment by TinCanTech** [comment]
> Verified :-)

What did you verify, the bug or the fix ?

**Comment by tecoboot** [comment]
The fix works well.

**Comment by TinCanTech** [comment]
This must to go into release.

**Comment by TinCanTech** [comment]
Closed via https://github.com/OpenVPN/easy-rsa/commit/5b4fd2b484adc6e2f506b62eb54fc38adc802766

Labeled for version 3.0.x port.
