### ISSUE TITLE
Is it possible to assign many SANs to a certificate?

### ISSUE THREAD

**Issue by ComptonAlvaro** [OpenVPN/easy-rsa#643]
I am using easy-rsa 3 to create certificates and I need, in the server certificate, set the SAN. It is for a gRPC service.

When I try to connect, I get the error that there is not assigned any IP to the SAN, so I guess that I need to set the IP in this field, but I don't know how could I do that.

It seems that with OpenSsl it is possible, and how easy-rsa use OpenSsl, I would like to know if it is possible to do it with this tool.

Thanks.

**Comment by TinCanTech** [comment]
Yes, it is possible.  The best explanation can be found with command:
- `easyrsa help san`

**Comment by ComptonAlvaro** [comment]
I am in windows and I start the shell:

`easyrsa-start.bat`

Then I use the ask for help:

`easyrsa help san`

The help that I get is this:

```
Note: using Easy-RSA configuration from: D:/temp/easy-rsa3/vars

  --subject-alt-name=SAN_FORMAT_STRING
      This global option adds a subjectAltName to the request or issued
      certificate. It MUST be in a valid format accepted by openssl or
      req/cert generation will fail. Note that including multiple such names
      requires them to be comma-separated; further invocations of this
      option will REPLACE the value.

      Examples of the SAN_FORMAT_STRING shown below:
        DNS:alternate.example.net
        DNS:primary.example.net,DNS:alternate.example.net
        IP:203.0.113.29
        email:alternate@example.net
```

Then I try to create a server certificate:

`easyrsa build-server-full Server2 nopass --subject-alt-name=IP:192.168.1.200`

But the SAN is not set. The information of the certificate is:

```
        Validity
            Not Before: Aug 19 09:07:46 2022 GMT
            Not After : Dec 20 09:07:46 3021 GMT
        Subject: CN=Server4
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (4096 bit)

        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Subject Key Identifier: 
                AF:8A:4F:0F:C9:02:7
            X509v3 Authority Key Identifier: 
                keyid:65:86:27:B8:D
                DirName:/CN=CA
                serial:29:A7:C4:27:

            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
            X509v3 Key Usage: 
                Digital Signature, Key Encipherment
            X509v3 Subject Alternative Name: 
                DNS:Server4
```

In fact, if I use a wrong parameter, I don't get any error and the certificate is created anyway. For example a command like that:

`easyrsa build-server-full Server2 nopass --subject-alt-n`

So it seems that if I use the script the parameter is ignored.

**Comment by ComptonAlvaro** [comment]
I have found this issue: https://github.com/OpenVPN/easy-rsa/issues/576

It is said that if I use the command:

`easyrsa build-server-full 1.2.3.4 nopass`

I should get this result:

```
 X509v3 Extended Key Usage: 
                TLS Web Server Authentication
            X509v3 Key Usage: 
                Digital Signature, Key Encipherment
            X509v3 Subject Alternative Name: 
                IP Address:1.2.3.4
```

But in my case I get: 

```
X509v3 Extended Key Usage: 
                TLS Web Server Authentication
            X509v3 Key Usage: 
                Digital Signature, Key Encipherment
            X509v3 Subject Alternative Name: 
                DNS:192.168.1.200
```

It is set as DNS, not as IP like in your example.

**Comment by TinCanTech** [comment]
The order of the command is vital:
- `easyrsa --san=DNS:primary.example.net,DNS:alternate.example.net buils-server-full server nopass`

**Comment by ComptonAlvaro** [comment]
Thanks so much.

Also i have tried the new version 3.1.0 and with the simply command build-server-full 192.168.1.200 nopass it assign IP instead of DNS and it works too.

But thanks for the correct command, because I was interesting to assing various SAN values.

**Comment by TinCanTech** [comment]
> command build-server-full 192.168.1.200 nopass it assign IP instead of DNS and it works too.

I believe there is an issue related to that: #576 

I have not decided how to handle such a case.

**Comment by ComptonAlvaro** [comment]
I guess it was solved in e version after 3.0.8 because in the new 3.1.0, the same command assign IP address instead of DNS.

**Comment by TinCanTech** [comment]
I would **not** call it **_solved_**.

For example:
- `easyrsa build-server-full b01d:face::1`
  will have SAN `DNS:b01d:face::1`

It is inconsistent behavior, based on flawed logic.

**Comment by TinCanTech** [comment]
I would **not** call it **_solved_**.

For example:
- `easyrsa build-server-full b01d:face::1`

Will have SAN `DNS:b01d:face::1`

It is inconsistent behavior, based on flawed logic.

**Comment by ComptonAlvaro** [comment]
Right, in this case it doesn't work, so it is inconsistent as you tell, but at least for IPv4 it works.

Thanks for the comment.

**Comment by TinCanTech** [comment]
I woul not agree that it works for IPv4, either.
- `build-server-full 1.1.1.1`

Will have SAN `IP:1.1.1.1` but `commonName` `1.1.1.1` .. the default SAN should be `DNS:1.1.1.1`, after all, that is the given name.  If I want SAN `IP:1.1.1.1` then I should use the `--san` option.

**Comment by ComptonAlvaro** [comment]
Yes, I think the best option it is to use the --san parameter to set explicitly the desired SANs.
