### ISSUE TITLE
Easy-RSA RHEL 9 EPEL nopass bug

### ISSUE THREAD

**Issue by magsdev** [OpenVPN/easy-rsa#648]
Hi,
I just moved from Ubuntu 20.04 LTS (where the exact command works fine and does not prompt for pass phrase) to Red Hat Enterprise Linux 9 and installed Easy-RSA via EPEL.

When I run ./easyrsa build-ca nopass as root, it still prompts for PEM pass phrase:

```
# ./easyrsa build-ca nopass
Using SSL: openssl OpenSSL 3.0.1 14 Dec 2021 (Library: OpenSSL 3.0.1 14 Dec 2021)
Enter PEM pass phrase:
Enter PEM pass phrase:
Enter PEM pass phrase:
Enter PEM pass phrase:
80DB8DBF7D7F0000:error:0480006D:PEM routines:PEM_def_callback:problems getting password:crypto/pem/pem_lib.c:62:
80DB8DBF7D7F0000:error:07880109:common libcrypto routines:do_ui_passphrase:interrupted or cancelled:crypto/passphrase.c:175:
80DB8DBF7D7F0000:error:1C80009F:Provider routines:p8info_to_encp8:unable to get passphrase:providers/implementations/encode_decode/encode_key2any.c:116:

```

```
# ./easyrsa --version
EasyRSA Version Information
Version:     3.0.8
Generated:   Wed Sep  9 15:59:45 CDT 2020
SSL Lib:     OpenSSL 3.0.1 14 Dec 2021 (Library: OpenSSL 3.0.1 14 Dec 2021)
Git Commit:  f12e00e53b4f486ce3d119ca429198780fa694ac
Source Repo: https://github.com/OpenVPN/easy-rsa


```
```
# ls -l
total 8
lrwxrwxrwx 1 root root   29 Aug 17 18:56 easyrsa -> /usr/share/easy-rsa/3/easyrsa
lrwxrwxrwx 1 root root   41 Aug 17 18:56 openssl-easyrsa.cnf -> /usr/share/easy-rsa/3/openssl-easyrsa.cnf
drwx------ 9 root root 4096 Aug 17 20:10 pki
-rw-r--r-- 1 root root  332 Aug 17 18:56 vars
lrwxrwxrwx 1 root root   36 Aug 17 18:56 vars.example -> /usr/share/doc/easy-rsa/vars.example
lrwxrwxrwx 1 root root   32 Aug 17 18:56 x509-types -> /usr/share/easy-rsa/3/x509-types


```
```
# cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="9.0 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.0"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.0 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/9/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.0
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.0"


```
```
# dnf repolist
Updating Subscription Management repositories.
repo id                                                                    repo name
codeready-builder-for-rhel-9-x86_64-rpms                                   Red Hat CodeReady Linux Builder for RHEL 9 x86_64 (RPMs)
epel                                                                       Extra Packages for Enterprise Linux 9 - x86_64
rhel-9-for-x86_64-appstream-rpms                                           Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)
rhel-9-for-x86_64-baseos-rpms                                              Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)


```
```
# getenforce
Disabled


```
```
# uname -a
Linux test 5.14.0-70.22.1.el9_0.x86_64 #1 SMP PREEMPT Tue Aug 2 10:02:12 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux


```
Let me know if you need additional information.

Thanks,
Magnus

**Comment by TinCanTech** [comment]
The problem here is that EasyRSA version `3.0.8` does **not** support OpenSSL version 3.x.x

You **must** move to EasyRSA version `3.0.9` or 3.1.1-git/master`. You can try EasyRSA version `3.1.0` but it is a `.0` release with known issues.

And for the record, you should not be using OpenSSL version `3.0.1` but I suspect that is a RedHat patched version, so I don't know ..

**Comment by TinCanTech** [comment]
Either upgrade `easyrsa` or, if you have the inclination, you can edit `easyrsa` source.

You need to replace the `nopass` value of `-nodes` with `-noenc`, for `build-ca` and `build_full()`.  I don't have a patch for that because EasyRSA version `3.0.8` does **not** support OpenSSL version `3.x.x`.

**Comment by magsdev** [comment]
This has to be fixed in the RHEL/EPEL repos as I just refuse to compile every single package that comes out - sort of defeats the purpose of OS distros...I could technically build everything from source if I had enough play time.

**Comment by TinCanTech** [comment]
I will pass this information on to somebody with RedHat knowledge.

**Comment by ecrist** [comment]
@magsdev you'll need to open a ticket with Red Hat for that.  There is nothing within our repo the requires end-user compilation.  WE do not control the upstream repos, so your comment above is directed to the wrong audience.

**Comment by dsommers** [comment]
@magsdev File a ticket in the Red Hat Bugzilla, for the Fedora EPEL project.  The package maintainer for easy-rsa needs to update easy-rsa to a newer version for EPEL-9 and Fedora 36+, as those ship with OpenSSL 3.x by default.

https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora%20EPEL
