### ISSUE TITLE
state should not be abbreviated

### ISSUE THREAD

**Issue by coolaj86** [OpenVPN/easy-rsa#65]
In relation to https://github.com/OpenVPN/easy-rsa/pull/64

Screenshot:

![Imgur](http://i.imgur.com/SEctVvl.png)

Why does the tool say the standard is one thing, but you're saying the standard is something else? Which is the standard?

**Comment by ecrist** [comment]
Can you elaborate?  Where is the inconsistency?

**Comment by ecrist** [comment]
Looks like this is already resolved.
