### ISSUE TITLE
[RFE] include EASYRSA_EXT_DIR in 'DIRECTORY STATUS' output

### ISSUE THREAD

**Issue by dekeonus** [OpenVPN/easy-rsa#654]
currently easyrsa outputs a DIRECTORY STATUS indicating what directories it considers EASYRSA and PKI to be, it would be beneficial to also know what directory easyrsa was sourcing the x509-types from.

**Comment by TinCanTech** [comment]
Yes, I can see how that would help.

**Comment by TinCanTech** [comment]
FTR, copying `x509-typs` to the PKI, always sets `EASYRSA_EXT_DIR` to the copy within the PKI, unless it is set externally.

**Comment by dekeonus** [comment]
Yes I am aware, and was intending to use that feature with a pre-prepared x509-types folder.
I forgot to copy the folder in and my test certs did not look as expected, then I realised my error.

**Comment by TinCanTech** [comment]
#655 adds a message to display the location of `x509-types`.

**Comment by TinCanTech** [comment]
Re-opening for testing and feedback.

**Comment by dekeonus** [comment]
mmm, not quite what I wanted: I wanted the x509-types dir to be indicated in the `easyrsa help` output.
Also I'm not sure the clutter of having the `vars` and `x509-types-dir` shown on every command is the right choice.

I think both "vars location"and "EASYRSA_EXT_DIR" should be added to the "DIRECTORY STATUS" help output AND that "DIRECTORY STATUS" block added to the --version string (perhaps only if the current PWD has a pki subdir).

**Comment by TinCanTech** [comment]
This is a good idea, I shall look into it. Thanks!

**Comment by dekeonus** [comment]
Unfortunately when `usage()` runs `find_x509_types_dir()` is called without *EASYRSA_PKI* set.
This results in `easyrsa help` always indicating a system location for 'x509-types:'
Thus there is a disconnect between what is displayed from help and what directory will actually be used when performing signing operations.

**Comment by TinCanTech** [comment]
Alas .. You are correct.

**Comment by TinCanTech** [comment]
#665 passed my tests but I may have missed something.

**Comment by TinCanTech** [comment]
Testing welcome.
