### ISSUE TITLE
[user experience] In `vars` clarify that use of "EASYRSA" in the file will require it to be set by the user

### ISSUE THREAD

**Issue by dekeonus** [OpenVPN/easy-rsa#658]
in `vars` _EASYRSA_ is referenced by the example for _EASYRSA_EXT_DIR_ however _EASYRSA_ is not set until after `vars` is sourced (unless the user has set it via command line).
If the user uncomments the example (but does not uncomment & set _EASYRSA_) then _EASYRSA_EXT_DIR_ will be set to `/x509-types` ie under root /

suggestion replacing the preceding comment block similar to:
```
# The default value of this variable is the location of the easyrsa script
# itself, which is also where the configuration files are located in the
# easy-rsa tree.
# If you reference "$EASYRSA" in this file you MUST set this

#set_var EASYRSA        "${0%/*}"
```

**Comment by TinCanTech** [comment]
Your assumption about `$EASYRSA` is incorrect. `$EASYRSA` is designed to point to the parent of your PKI. However, I don't like it either but changing it would be a little too dramatic. So that will not change.

I will take a look at your point about `x509-types` to see if/how that can be improved.

**Comment by dekeonus** [comment]
perhaps some clarification:
I prefer to have x509-types/ as a sibling to pki/
I have vars set with:
```
set_var EASYRSA "$PWD"
set_var EASYRSA_TEMP_DIR        "$EASYRSA/tmp"
set_var EASYRSA_EXT_DIR "$EASYRSA/x509-types"
```
A naive read of vars without reading the code in easyrsa *might* lead a user to infer they can uncomment the example as shown and have things work. this is the above list as presented in the default vars:
```
#set_var EASYRSA        "${0%/*}"
#set_var EASYRSA_TEMP_DIR       "$EASYRSA_PKI"
#set_var EASYRSA_EXT_DIR        "$EASYRSA/x509-types"
```
Users may note that EASYRSA has been set to their current working dir rather than the program dir.
As the EASYRSA_EXT_DIR example is using EASYRSA they might infer some magic happens in easyrsa and they can just uncomment that example as-is

### proposal:
write EXT_DIR example in vars as
`#set_var EASYRSA_EXT_DIR        "$EASYRSA_PKI/x509-types"`
*which is the project's expected default (for a local-to-pki x509-types)*

**Comment by TinCanTech** [comment]
> this is the above list **as presented in the default vars**:

I must point this out: **Not** _as presented in the default vars_

The `vars.example` file reads as follows:
```
# !!
# NOTE: ADVANCED OPTIONS BELOW THIS POINT
# PLAY WITH THEM AT YOUR OWN RISK
# !!

<<schnipp>>

# X509 extensions directory:
# If you want to customize the X509 extensions used, set the directory to look
# for extensions here. Each cert type you sign must have a matching filename,
# and an optional file named "COMMON" is included first when present. Note that
# when undefined here, default behaviour is to look in $EASYRSA_PKI first, then
# fallback to $EASYRSA for the "x509-types" dir.  You may override this
# detection with an explicit dir here.
#
#set_var EASYRSA_EXT_DIR	"$EASYRSA/x509-types"

```
The point being:
- these are `ADVANCED OPTIONS `
-  With a warning: `PLAY WITH THEM AT YOUR OWN RISK`

However .....

If you feel so inclined, I would appreciate your feedback regarding how `git/master` handles the `x509-types` directory.

You should install the `easyrsa` script to `/usr/local/sbin` and the data file to `/usr/local/share/easy-rsa` for the best results.

I'm happy to help get you started.

**Comment by dekeonus** [comment]
RE advanced options, true enough.

I think for many, if not most, users the default location for x509-types under `/usr/{local/}/share/easy-rsa` is correct.

However COMMON should probably direct the users to also read EasyRSA-Advanced.md 
EasyRSA-Advanced.md should be updated to mention creating a local-to-pki x509-types folder which is particular need if the user is using multiple CAs and/or subCAs as crlDP and aia.caIssers will need to be set per CA

**Comment by TinCanTech** [comment]
It seems to me that you **ignored** the warning, until I pointed it out to you.

**Comment by dekeonus** [comment]
yes, yes I did ignore that warning (or more lost it in my mental model).

I'm then unsure about how to indicate to users that if they want to edit COMMON for multiple CAs they should create a local x509-types.
Automatically copying in a x509-types for every init-pki looses the advantage of those cert-types being automatically updated with new releases.
The x509-types override is an advanced option, but edits to any of those files, in the default shared location, will be lost (with most package managers) during an upgrade.
Using the EasyRSA-Advanced.md to suggest to advanced users to make a pki-local copy seems reasonable (I also assume advanced users would then realise that updates to the shared copies won't propagate automatically).

**Comment by TinCanTech** [comment]
> Automatically copying in a x509-types for every init-pki looses the advantage of those cert-types being automatically updated with new releases.

`easyrsa` `git/master` does **not** copy `x509-types` to the PKI.

> The x509-types override is an advanced option, but edits to any of those files, in the default shared location, will be lost (with most package managers) during an upgrade.

This is known as _advanced use_.

The packaged files are not for customisation. The PKI files are.

> Using the EasyRSA-Advanced.md to suggest to advanced users to make a pki-local copy seems reasonable (I also assume advanced users would then realise that updates to the shared copies won't propagate automatically).

Advanced users know what they are doing.

**Comment by dekeonus** [comment]
> `easyrsa` `git/master` does **not** copy `x509-types` to the PKI.

yes, and I agree with that for the reasons I previously stated. (you did ask my opinion on how git/master handles the x509-types).

The point I'm driving at here is the commented crlDP and/or aia.caIssuers in COMMON.
Editing this file means the user is now entering advanced use case territory. I'm suggesting that perhaps directing them to have a read of EasyRSA-Advanced.md first would not be a bad idea.

**Comment by TinCanTech** [comment]
The reason to leave `x509-types` to the system is because users do not need to change them.  An advanced user has the option of copying them to the PKI to make their changes. This is a basic hierarchical system.

For the record; that system also works with a soft reset.

If you want to propose improvements to documentation then go ahead.

**Comment by TinCanTech** [comment]
> If the user uncomments the example (but does not uncomment & set _EASYRSA_) then _EASYRSA_EXT_DIR_ will be set to `/x509-types` ie under root /

This is user error, it is of no further concern to `easyrsa`. If `/x509-types` does not exist then the error is `x509-types folder cannot be found: /x509-types`
