### ISSUE TITLE
[user experience] build-ca provides no guidance on changing CN for ca nor defaults to a different name for a sub-ca

### ISSUE THREAD

**Issue by dekeonus** [OpenVPN/easy-rsa#659]
I realise this is resultant from changes in #598
Currently:
- **`easyrsa help build-ca`** does not indicate how to change the CN.
- **`easyrsa help options`** indicates
> --req-cn=NAME     : default CN to use (DEPRECATED)

 *this is, currently, the correct way to set the CN for build-ca*

- vars has comment text:

> \# Default CN:
> \# This is best left alone. Interactively you will set this manually,

- **`easyrsa build-ca subca`** does not change the CN to indicate a sub CA ( eg Easy-RSA CA -> Easy-RSA subCA )

This results in a subCA with the same DN as it's parent CA and consequently that the two certificates will have the same subject_hash.

- the org mode vars instructions indicate:

> \# certificate.  Don't leave any of these fields blank, although interactively
> \# you may omit any specific field by typing the "." symbol (not valid for

This information is incorrect, to remove a field from the resulting DN for the CA certificate it needs to be uncommented and set to ""
eg `set_var EASYRSA_REQ_CITY        ""`
this yields:

>         Subject:
>             countryName               = US
>             stateOrProvinceName       = California
>             organizationName          = Copyleft Certificate Co
>             organizationalUnitName    = My Organizational Unit
>             commonName                = Easy-RSA CA
>             emailAddress              = me@example.net

This also works for cli `easyrsa --req-city="" build-ca`

### Proposal:
- Add text to **`help build-ca`** to indicate how to set commonName
- possibly, turn interactive mode back on for dn-mode=cn_only
- Update the comment block in `vars` for Organizational fields
- Set a canary value in *`vars_setup`* and bailout if dn-mode=org and the user hasn't set values (suggest EASYRSA_REQ_ORG for canary)

**Comment by TinCanTech** [comment]
> --req-cn=NAME : default CN to use (DEPRECATED)

That deprecation will be rescinded. 

The reason for the initial deprecation was due to trying to finding a way to disconnect `commonName` from `filename`.  That work has stopped, for the time being.

-----

> * **`easyrsa build-ca subca`** does not change the CN to indicate a sub CA

That is a good point, which can be addressed.

-----

> * possibly, turn interactive mode back on for dn-mode=cn_only

Possibly. I think I would prefer an `--interactive|-i` switch, which would enable the SSL interactive mode on request. I'll look into that.

-----

As for `help`, you can always offer PRs for consideration. Documentation is often overlooked, sorry.

**Comment by dekeonus** [comment]
> Possibly. I think I would prefer an --interactive|-i switch, which would enable the SSL interactive mode on request. I'll look into that.

would a `easyrsa build-ca prompt` be a better fit? as interactive is the default for all other operations

**Comment by TinCanTech** [comment]
> would a `easyrsa build-ca prompt` be a better fit? **as interactive is the default for all other operations**

Which interactive operations do you mean ?

My impression is that you are currently using an older version of `easyrsa`.

**Comment by dekeonus** [comment]
I am testing with git-master, and I suppose I just mean gen-req (I had thought build-*-full was interactive)

I am now looking at `build_full()` and see it calls gen_req with batch arg and sets commonName to 'file_name_base'  (which looks like it thus overrides --req-cn='whatever')
```
EASYRSA_REQ_CN="$name"
gen_req "$name" batch ${nopass+ nopass}
```

**Comment by dekeonus** [comment]
fortunately in vars_setup `set_var EASYRSA_REQ_CN                  ChangeMe` is a nice canary value, would a PR setting build_full() and gen_req() to sting compare and honour a user set req-cn be welcome?

**Comment by TinCanTech** [comment]
> would a PR setting build_full() and gen_req() to sting compare and honour a user set req-cn be welcome?

A PR on the subject does help to explain exactly what changes you wish for.

However, changing core functions is a lot of work and not only for you.

**Comment by TinCanTech** [comment]
> > * **`easyrsa build-ca subca`** does not change the CN to indicate a sub CA
> 
> That is a good point, which can be addressed.
> 
> > * possibly, turn interactive mode back on for dn-mode=cn_only
> 
> Possibly. I think I would prefer an `--interactive|-i` switch, which would enable the SSL interactive mode on request. I'll look into that.

I'm coming around to the idea of enabling interactive SSL level, if EasyRSA has an undefined CA `commonName` .. bsically, re-instate the old behaviour (almost).

**Comment by TinCanTech** [comment]
Minor typ0: https://github.com/OpenVPN/easy-rsa/blob/ed54b1abd099e310ef980dc23ddc5bcbedb33616/easyrsa3/easyrsa#L475
