### ISSUE TITLE
"--keep-tmp" does not keep temporary certificate extension file.

### ISSUE THREAD

**Issue by dekeonus** [OpenVPN/easy-rsa#676]
In sign_req() at https://github.com/OpenVPN/easy-rsa/blob/917d0780451dcf926d00f5dcac66627bd81d680d/easyrsa3/easyrsa#L1778 the temporary file tmp_ext is removed.
This file should be kept for user debugging of the sign-req process (and other processes that call sign_req)

**Comment by dekeonus** [comment]
I also note that the help string for the option does not indicate that this option is a debug / trouble shooting feature and shouldn't be used in normal operation

**Comment by dekeonus** [comment]
perhaps if the option was called something akin to *--debug-tmp / --debug-tmp-files / --dbg-tmp-files* it would be enough to hint to the user that it is not only a non-default option (like --san) but also a non-normal operation option

**Comment by trasherdk** [comment]
The `no banana` milestone :rofl:

**Comment by TinCanTech** [comment]
@trasherdk the `banana` scale proved to be too _fruity_ for my taste `;-)`
