### ISSUE TITLE
can not build ca

### ISSUE THREAD

**Issue by PikuZheng** [OpenVPN/easy-rsa#679]
./easyrsa build-ca produced errors like below. These commands work fine in 3.0.8.

```
EasyRSA Shell
# ./easyrsa build-ca
* Notice:
Using Easy-RSA configuration from: C:/Program Files/OpenVPN/EasyRSA-3.1.0/pki/vars

FATAL: Startup failure (dev note: apps_startup()) for openssl

Easy-RSA error:

secure_session - rand ''

Host: win | @(#)MIRBSD KSH R39-w32-beta14 $Date: 2013/06/28 21:28:57 $ |


EasyRSA Shell
#
```

**Comment by TinCanTech** [comment]
Download this version `3.1.1`: [**`easyrsa`**](https://raw.githubusercontent.com/OpenVPN/easy-rsa/master/easyrsa3/easyrsa)

**Replace** the version you have in `C:/Program Files/OpenVPN/EasyRSA-3.1.0`

**Comment by PikuZheng** [comment]
Not for this reason. The problem is that openssl.exe in the release package can't start normally on windows7 system, but it can run on windows10 system.

any suggestion?

**Comment by PikuZheng** [comment]
replace openssl.exe and dlls with version 3.0.5 from http://slproweb.com/products/Win32OpenSSL.html, everything works. Expected that the release of this project can be updated synchronously

**Comment by TinCanTech** [comment]
Microsoft no longer support Windows 7, so you are on your own with that.

`easyrsa` version `3.1.0` has known bugs. 
Use `easyrsa` version `3.1.1`. A.K.A. [`git/master`](https://raw.githubusercontent.com/OpenVPN/easy-rsa/master/easyrsa3/easyrsa)
