### ISSUE TITLE
`sign-req ca` does not honour user set critical flag in "ca" type if --subca-len provided

### ISSUE THREAD

**Issue by dekeonus** [OpenVPN/easy-rsa#691]
in this code
https://github.com/OpenVPN/easy-rsa/blob/d99bef68e11b0c31171d3d61f881fb94be2263a1/easyrsa3/easyrsa#L1701-L1703
A basicConstraints line is appended to the generation of the temporary extensions file, overriding whatever line is currently in the `ca` x509-type file.

**Comment by TinCanTech** [comment]
A word to the wise;
    this, particular, rabbit hole
    is a lot deeper
    than you realise.

**Comment by TinCanTech** [comment]
Ref:
- https://github.com/OpenVPN/easy-rsa/commit/e80c229559dec4ce71e79d891faa4540e513cb9c
- https://github.com/OpenVPN/easy-rsa/commit/bce4dadc43a51a2f5cb6b2f3ab3c07abe9e10db8

**Comment by dekeonus** [comment]
I'm talking about signing a SUB CA:
```
cd rootCA
easyrsa import-req path/to/subCA/pki/reqs/ca.req subCA

easyrsa --subca-len="1" sign-req ca subCA
```

**Comment by dekeonus** [comment]
Your changes for `build_ca()` work admirably - they do exactly what I want.

I wanted the `sign-req ca` to also keep the *critical* flag if present.
With my PR the temp extension file will look like:
*tmp_dir_foo/temp.21ca37bb*
```
# X509 extensions added to every signed cert

# This file is included for every cert signed, and by default does nothing.
# It could be used to add values every cert should have, such as a CDP as
# demonstrated in the following example:

crlDistributionPoints = URI:http://example.net/pki/git_rootCA.crl

# The authority information access extension gives details about how to access
# certain information relating to the CA.

authorityInfoAccess = caIssuers;URI:http://example.net/pki/git_rootCA.crt
# X509 extensions for a ca

# Note that basicConstraints will be overridden by Easy-RSA when defining a
# CA_PATH_LEN for CA path length limits. You could also do this here
# manually as in the following example in place of the existing line:
#
# basicConstraints = CA:TRUE, pathlen:1

basicConstraints = critical, CA:TRUE
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer:always
keyUsage = cRLSign, keyCertSign
basicConstraints = critical, CA:TRUE, pathlen:1
```

**Comment by TinCanTech** [comment]
I had an old `openssl-easyrsa.cnf` installed.

**Comment by dekeonus** [comment]
I keep doing the same, and then remembering after looking at the rootCA cert.

**Comment by dekeonus** [comment]
My issue here is easyrsa is pulling the distro installed data files (3.0.8 in /usr/share). My testing with git-master isn't installed per-se, just staged.

However this is an issue that might need further thought: existing Easy RSA CAs will have an old openssl-easyrsa.cnf in pki/ I wonder if an easyrsa version should be placed into that file and tested?

**Comment by TinCanTech** [comment]
Agreed, I am drafting a PR and will create an issue soon.

**Comment by TinCanTech** [comment]
> Your changes for `build_ca()` work admirably - they do exactly what I want

@dekeonus Thank you, your feedback is highly appreciated. :cake: :beers:
