### ISSUE TITLE
[RFE] extend `--keep-tmp` so with no option automatically uses a datestamp for preserved session directory

### ISSUE THREAD

**Issue by dekeonus** [OpenVPN/easy-rsa#707]
I'd suggest a format similar to `+%FT%H%M%S` ~~ YYYY-mm-dd**T**HHMMSS
This is pseudo ISO-8601 'seconds' as `:` are invalid for filenames under Windows, and adding the timezone is unnecessary for this date stamp.
I think for most interactive cases a 1 second resolution is sufficient for unique session dirs per easyrsa invocation.

**Comment by TinCanTech** [comment]
`--keep-tmp=foo` is done that way for the following reasons:
- `foo` is **required** to be _defined by the user_.
- Having user definition means that left overs are not caused by `easyrsa`.

Your proposal would probably require a command to clean up. eg: `clean-tmp`

**Comment by dekeonus** [comment]
that's fair, I could probably wrangle alias & shell profile to auto-datestamp

**Comment by TinCanTech** [comment]
The way I see it: `--keep-tmp=foo` provides a single snapshot of the command.

Linking: #610  - The source of this discussion

**Comment by dekeonus** [comment]
I have had an occasional need to do A/B comparisons of generated temporary files. I've sometimes accidentally hit enter when repositioning the cursor to update the --keep-tmp=foo to update the directory.

My feature request was really an attempt to mitigate my clumsy fingers. I can just adjust my local environment to mitigate my own unforced errors.

**Comment by TinCanTech** [comment]
I think this current way is a bit too risky..

**Comment by TinCanTech** [comment]
I want to keep the current behavior but I may need to black-list some names.
eg: `issued`, `private` etc ..

**Comment by TinCanTech** [comment]
I'm not going to date-stamp directory names but a better approach could be to move the old temporary folder from `$temp-dir/$rand` to '$temp-dir/$NAME-$rand`.
