### ISSUE TITLE
How to extend expiry date (renew) of OVPN servers certificate and CA certificate without regenerating client certificates?

### ISSUE THREAD

**Issue by talavs** [OpenVPN/easy-rsa#708]
Hello!
Sorry for noob question in advance :)
I'm wondering is it possible to extend expiry date (renew) of OVPN's server and CA without regenerating client certificates? In my case there are around 800 connected clients and it would be hell of a job if I had to regenerate all of them after renewing servers and CA certs.

**Comment by TinCanTech** [comment]
See `help`.
