### ISSUE TITLE
commonName setting for build-client-full

### ISSUE THREAD

**Issue by nils-wisiol** [OpenVPN/easy-rsa#717]
I'm using the following script to generate a CA and issue a certificate:

```shell
#!/usr/bin/env bash

cd "$(mktemp -d)" || exit
git clone https://github.com/OpenVPN/easy-rsa.git
cat > easy-rsa/easyrsa3/vars << EOF
set_var EASYRSA_DN "cn_only"
set_var EASYRSA_KEY_SIZE 2048
set_var EASYRSA_REQ_CN   "ca@desec.example.com"
set_var EASYRSA_BATCH    "yes"
EOF

(
  cd easy-rsa/easyrsa3 || exit
  ./easyrsa init-pki
  mv vars pki/
  ./easyrsa build-ca nopass
  ./easyrsa build-client-full frontend.desec.example.com nopass
)
```

Recently, the `build-client-full` command (last command) started to fail with the following error message: 

> Option conflict: 'build-client-full' does not support setting an external commonName

I looked at [the code](https://github.com/OpenVPN/easy-rsa/blame/master/easyrsa3/easyrsa#L1860-L1861) that generates this message and found that it was changed recently by commit fe3cced16c62de5dd33f3a230ee03e904306a55b, which introduced (among other changes) the following new condition to the command:

```shell
[ "$EASYRSA_REQ_CN" = ChangeMe ] || die "\
Option conflict: '$cmd' does not support setting an external commonName"
```

Accordingly, if the above `build-client-full` command is changed to

```shell
./easyrsa --req-cn=ChangeMe build-client-full desec.example.com nopass
```

it works as expected.

However, setting `--req-cn=ChangeMe` does not seem to be a correct way to use the easyrsa CLI. Any suggestions on how to handle this?

Thanks for maintaining easyrsa! :rocket:

**Comment by TinCanTech** [comment]
Unless you want every entity in your PKI to share the same `commonName`, do **not** use `set_var EASYRSA_REQ_CN   "ca@desec.example.com"` in your `vars` file.

**Comment by TinCanTech** [comment]
The way to use `EASYRSA_REQ_CN` to set your CA `commonName` is:

    easyrsa --batch --req-cn="ca@desec.example.com" build-ca nopass

The way to use `EASYRSA_REQ_CN` to set an entity `commonName` is:

    easyrsa --batch --req-cn="client1@desec.example.com" gen-req client1 nopass

    easyrsa --batch sign-req client client1

**Comment by TinCanTech** [comment]
`EASYRSA_REQ_CN` should probably be removed from `vars.example`.

**Comment by nils-wisiol** [comment]
Thanks for the quick reply, it was very helpful! :rocket:
