### ISSUE TITLE
A link in the README.md to readthedocs.io would be helpful

### ISSUE THREAD

**Issue by Shapedsundew9** [OpenVPN/easy-rsa#721]
I navigated to the GitHub repo from https://openvpn.net/community-resources/how-to/#setting-up-your-own-certificate-authority-ca-and-generating-certificates-and-keys-for-an-openvpn-server-and-multiple-clients got started and ran into a few issues which I googled and found https://easy-rsa.readthedocs.io/en/latest/ which is very helpful. Cannot find a link to that documentation from this repo - I think it is worth adding or at least making more visible if it is here somewhere.

**Comment by TinCanTech** [comment]
Linking https://github.com/OpenVPN/easy-rsa/issues/258

**Comment by TinCanTech** [comment]
For the record: EasyRSA does not add such URLs to the source.

@Shapedsundew9 - Expanding your theory:

The documentation found here in the EasyRSA repo is copied verbatim by readthedocs. 

That makes it pure user preference that you chose to read some other documentation.

You _searched and found_ what you were looking for, the Internet works.
