### ISSUE TITLE
easyrsa file contains ^M character, could not execute under Linux.

### ISSUE THREAD

**Issue by jeweric** [OpenVPN/easy-rsa#724]
When I execute command
`./easyrsa3/easyrsa`
I got
`bash: ./easyrsa3/easyrsa: /bin/sh^M: bad interpreter: No such file or directory`

running under WSL2 (ubuntu wsl2 windows 11)

It works normal under MacOS

**Comment by TinCanTech** [comment]
The `easyrsa` source does not contain any `CRLF`.

**Comment by TinCanTech** [comment]
At this time, EasyRSA may or may not work with WSL.

I have not tried WSL and have made no attempt to support it.

If you can get it working then you can submit PRs with corrections.
https://github.com/OpenVPN/easy-rsa/blob/master/doc/EasyRSA-Contributing.md

**Comment by jeweric** [comment]
use this `cat -A easyrsa` to check.
