### ISSUE TITLE
GPG release key expired

### ISSUE THREAD

**Issue by fvanmaele** [OpenVPN/easy-rsa#726]
When verifying the `3.1.1` release archive, I get the following:
```
I:\>gpg --recv-keys C8FCA3E7F787072CDEB91D2F72964219390D0D0E
gpg: C:\\Users\\Ferdinand\\AppData\\Roaming\\gnupg\\trustdb.gpg: trustdb created
gpg: key F8489F839D7367F3: public key "Eric F Crist <ecrist@secure-computing.net>" imported
gpg: Total number processed: 1
gpg:               imported: 1

I:\>gpg --verify EasyRSA-3.1.1-win64.zip.sig
gpg: assuming signed data in 'EasyRSA-3.1.1-win64.zip'
gpg: Signature made 14/10/2022 23:22:30 W. Europe Summer Time
gpg:                using RSA key C8FCA3E7F787072CDEB91D2F72964219390D0D0E
gpg: Good signature from "Eric F Crist <ecrist@secure-computing.net>" [expired]
gpg:                 aka "Eric Crist <ecrist@openvpn.net>" [expired]
gpg:                 aka "Eric Crist <ecrist@sjm.com>" [expired]
gpg:                 aka "Eric Crist <eric@mnamberrun.org>" [expired]
gpg:                 aka "Eric F Crist <forums@openvpn.net>" [expired]
gpg:                 aka "[jpeg image of size 78808]" [expired]
gpg: Note: This key has expired!
Primary key fingerprint: 6F40 5682 1152 F03B 6B24  F2FC F848 9F83 9D73 67F3
     Subkey fingerprint: C8FC A3E7 F787 072C DEB9  1D2F 7296 4219 390D 0D0E
```

**Comment by ecrist** [comment]
Check the key you’re using, and the date on your machine.  This key is valid until December 5, 2022.  Public key attached here.


Eric F Crist




On Oct 16, 2022, at 04:41, Ferdinand Vanmaele ***@***.***> wrote:



When verifying the 3.1.1 release archive, I get the following:

I:\>gpg --recv-keys C8FCA3E7F787072CDEB91D2F72964219390D0D0E
gpg: C:\\Users\\Ferdinand\\AppData\\Roaming\\gnupg\\trustdb.gpg: trustdb created
gpg: key F8489F839D7367F3: public key "Eric F Crist ***@***.***>" imported
gpg: Total number processed: 1
gpg:               imported: 1

I:\>gpg --verify EasyRSA-3.1.1-win64.zip.sig
gpg: assuming signed data in 'EasyRSA-3.1.1-win64.zip'
gpg: Signature made 14/10/2022 23:22:30 W. Europe Summer Time
gpg:                using RSA key C8FCA3E7F787072CDEB91D2F72964219390D0D0E
gpg: Good signature from "Eric F Crist ***@***.***>" [expired]
gpg:                 aka "Eric Crist ***@***.***>" [expired]
gpg:                 aka "Eric Crist ***@***.***>" [expired]
gpg:                 aka "Eric Crist ***@***.***>" [expired]
gpg:                 aka "Eric F Crist ***@***.***>" [expired]
gpg:                 aka "[jpeg image of size 78808]" [expired]
gpg: Note: This key has expired!
Primary key fingerprint: 6F40 5682 1152 F03B 6B24  F2FC F848 9F83 9D73 67F3
     Subkey fingerprint: C8FC A3E7 F787 072C DEB9  1D2F 7296 4219 390D 0D0E

**Comment by ecrist** [comment]
I noticed in your output some IDs I’ve removed.  I have pushed my updated key to the keyservers.  Let me know if it works better now.

-----
Eric F Crist
Co-Author: Mastering OpenVPN
Author: Troubleshooting OpenVPN



On Oct 16, 2022, at 13:33, Eric F Crist ***@***.***> wrote:

Check the key you’re using, and the date on your machine.  This key is valid until December 5, 2022.  Public key attached here.


Eric F Crist

<Eric F Crist (9D7367F3) – Public.asc>



On Oct 16, 2022, at 04:41, Ferdinand Vanmaele ***@***.***> wrote:



When verifying the 3.1.1 release archive, I get the following:

I:\>gpg --recv-keys C8FCA3E7F787072CDEB91D2F72964219390D0D0E
gpg: C:\\Users\\Ferdinand\\AppData\\Roaming\\gnupg\\trustdb.gpg: trustdb created
gpg: key F8489F839D7367F3: public key "Eric F Crist ***@***.***>" imported
gpg: Total number processed: 1
gpg:               imported: 1

I:\>gpg --verify EasyRSA-3.1.1-win64.zip.sig
gpg: assuming signed data in 'EasyRSA-3.1.1-win64.zip'
gpg: Signature made 14/10/2022 23:22:30 W. Europe Summer Time
gpg:                using RSA key C8FCA3E7F787072CDEB91D2F72964219390D0D0E
gpg: Good signature from "Eric F Crist ***@***.***>" [expired]
gpg:                 aka "Eric Crist ***@***.***>" [expired]
gpg:                 aka "Eric Crist ***@***.***>" [expired]
gpg:                 aka "Eric Crist ***@***.***>" [expired]
gpg:                 aka "Eric F Crist ***@***.***>" [expired]
gpg:                 aka "[jpeg image of size 78808]" [expired]
gpg: Note: This key has expired!
Primary key fingerprint: 6F40 5682 1152 F03B 6B24  F2FC F848 9F83 9D73 67F3
     Subkey fingerprint: C8FC A3E7 F787 072C DEB9  1D2F 7296 4219 390D 0D0E

**Comment by fvanmaele** [comment]
Thanks for the quick reply. My system date is correct and synchronized 
with time.windows.com.

It seems the attached public key didn't make it to Github. I found the 
updated key on keys.openpgp.org, and the verification works as expected. 
keyserver.ubuntu.com still seems to have the old one.

**Comment by ecrist** [comment]
I've also updated they keys at ubuntu.
