### ISSUE TITLE
Easy-rsa gen-req failed after upgrade

### ISSUE THREAD

**Issue by pilchita** [OpenVPN/easy-rsa#761]
Hello everyone! after upgrading the version of easy-rsa (2 to 3), i try to create a certificate for a client and see this error:

`root@openvpnserver:/usr/share/migrate-from-v2-to-v3# ./easyrsa gen-req john nopass

Note: using Easy-RSA configuration from: /usr/share/migrate-from-v2-to-v3/vars
Using SSL: /usr/bin/openssl OpenSSL 1.1.1n  15 Mar 2022
req: Error on line 284 of config file "/usr/share/pki/easy-rsa-1534.lcBbpc/tmp.j4iw7D"
140075538937152:error:0E079065:configuration file routines:def_load_bio:missing equal sign:../crypto/conf/conf_def.c:407:line 284

Easy-RSA error:

Failed to generate request
`
My config is:

`
set_var EASYRSA_OPENSSL "/usr/bin/openssl"
set_var EASYRSA_PKI             "$PWD/pki"
set_var EASYRSA_CA_EXPIRE       3650
set_var EASYRSA_SSL_CONF        "/etc/openvpn/org/openssl.cnf"
set_var EASYRSA_PKCS11_MODULE_PATH="dummy"
set_var EASYRSA_PKCS11_PIN="dummy"
set_var EASYRSA_KEY_SIZE 2048
set_var EASYRSA_REQ_COUNTRY "AR"
set_var EASYRSA_REQ_PROVINCE "BA"
set_var EASYRSA_REQ_CITY "BuenosAires"
set_var EASYRSA_REQ_ORG "DevOps"
set_var EASYRSA_REQ_EMAIL "john@domain.com"
set_var EASYRSA_REQ_OU "SysAdmin"
set_var EASYRSA_KEY_CN="ORG CA"
set_var KEY_ALTNAMES="something"
set_var KEY_CN="CommonName"

`
Instances info:

`
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

OpenSSL 1.1.1n  15 Mar 2022

EasyRSA Version Information
Version:     3.0.8
Generated:   Wed Sep  9 15:59:45 CDT 2020
SSL Lib:     OpenSSL 1.1.1n  15 Mar 2022
Git Commit:  f12e00e53b4f486ce3d119ca429198780fa694ac
Source Repo: https://github.com/OpenVPN/easy-rsa

`

Thanks for the help.
Regards, Ema.

**Comment by TinCanTech** [comment]
@pilchita If you have further problems with your upgraded EasyRSA, please document then here.

**Comment by pilchita** [comment]
@TinCanTech Oh no!!! I’m so sorry that mistake so silly, I spent hours reading the documentation and I did not realize the mistake, my head was about to explode haha

I have created the first files for a client but I see that it has generated two files:

`
Keypair and certificate request completed. Your files are:
req: /usr/share/migrate-from-v2-to-v3/pki/reqs/sauron.req
key: /usr/share/migrate-from-v2-to-v3/pki/private/sauron.key
`
I read the documentation and then should run the following to generate the final files for the user:

`./easyrsa sign-req client sauron`

Can I use the already existing ca? I can’t generate another one because I will leave users offline who already connect to the openvpn.

Currently in openvpn I have set these files:

`
ca /etc/openvpn/devops/keys/ca.crt
cert /etc/openvpn/devops/keys/kiu.crt
key /etc/openvpn/devops/keys/kiu.key
dh /etc/openvpn/kiu/devops/dh2048.pem
crl-verify /etc/openvpn/devops/keys/crl.pem`

**Comment by TinCanTech** [comment]
@pilchita Did you try the upgrade ?
