### ISSUE TITLE
Release Version 3.0.1 missing mksh/Win32 shell

### ISSUE THREAD

**Issue by cpuwhiz22** [OpenVPN/easy-rsa#79]
The release package for Windows does not contain bin\sh.exe.

**Comment by mzer0-yu** [comment]
Version 3.0.0 still contains sh.exe and other bat files. Quoting "With 3.0.0, the binaries needed to run EasyRSA on Windows were missing." I don't know what does it mean.

**Comment by mzer0-yu** [comment]
I am sorry. Version 3.0.0 RC2 still contains those files but not 3.0.0.

**Comment by cpuwhiz22** [comment]
Thanks!

**Comment by mzer0-yu** [comment]
I don't know what's the problem about sh.exe and others.
@QueuingKoala @ecrist Would you like to have a look here?

**Comment by p-schneider** [comment]
In addition to the binaries that were bundled with previous releases we now also need mktemp(.exe).

**Comment by QueuingKoala** [comment]
mktemp is not POSIX for the shell, so whatever commit brought that into this release is highly suspect given that such compliance is a defined project goal.

The tool chain to bring utility support to Windows doesn't support non-POSIX utils. I'd suggest you sick with a prior release until such issues in the recent codebase are resolved.

**Comment by kotmage** [comment]
Yes there is a persistent problem with binaries being not included in last release. As for the mktemp problem, it originated here:
https://github.com/OpenVPN/easy-rsa/pull/26
I'm making a new issue for it

**Comment by ecrist** [comment]
These are mostly my issues.  I'll try to pull my head out of my ass and fix this stuff tonight. 

Eric Crist

**Comment by KurrKurr** [comment]
Still no windows binaries. How hard is it to include the .exe file in the archive?

**Comment by QueuingKoala** [comment]
It's impossible because non-POSIX code was committed to this project earlier in the development cycle while the POSIX-supporting windows binaries (and other POSIX platforms) are not required to support this. This is NOT simply a packaging problem and requires fixing the systemic code quality issues in recently merged commits.

It's on my radar, but demands for my time are high at the moment. If you have time to review pre- 3.0 release commits and have strong POSIX-2013 knowledge, feel free to lend a hand in the required review here.
-- 
Sent from my mobile device; please excuse my brevity.

**Comment by mzer0-yu** [comment]
I am angry with easy-rsa of unnecessary troubles in Windows and the ugly codes of shell, so I decide to write a new project in C/C++ instead of this one!!!

As a student in Mathematics of the top colleges in China, implementing RSA was one of my homeworks.

**Comment by jirutka** [comment]
> How hard is it to include the .exe file in the archive?

What if maintainers of this repo just don’t wanna support Windows? It’s free as a beer, they don’t have to support it, maybe it’s not worth the troubles. Maybe they don’t even have any copy of Windows system. However, according to your attitude, you’re willing to pay them for it, aren’t you? ;)

> I am angry with easy-rsa of unnecessary troubles in Windows and the ugly codes of shell…

If you don’t want unnecessary troubles, then why the f*ck do you use such crappy and broken-by-design system as Windows? How hard is to use proper OS…?
And why the hell did you ever choose PKI written in Bash, when you use OS that doesn’t support it natively and you even hate shell? There are many alternatives. Maybe you can buy some Enterprise PKI Manager for Microsoft Windows ®…

> I decide to write a new project in C/C++ instead of this one!!!

Great, good luck and have fun with segfaults and memory leaks!!!

> I founded a repository just now, and it will be completed in February, 2016.

Ah, every loves empty repositories on GitHub and empty promises…

> As a student in Mathematics of the top colleges in China, implementing RSA was one of my homeworks.

Oh, sorry my master, please teach as how to code! Let me take a look at [your projects](https://github.com/mzer0-yu?tab=repositories) at Github, you surely have a lot… oh… two repositories, one empty, the second one is just one TXT file… and 47 contribution points…

**Comment by ecrist** [comment]
Great!  Heaven forbid you volunteer to help. 

Eric

**Comment by Arthur-D** [comment]
Just dropped by to ask that the documentation within the release be updated, as README-Windows.txt contains 
> With the Windows binary Easy-RSA download, all the necessary utilities
       are already present.

Thank you, and I hope a more user-friendly option (as this seems to have been) can be developed. In any case, good luck for the project!

**Comment by coldmast** [comment]
> I founded a repository just now, and it will be completed in February, 2016.

Talk is cheap.

**Comment by ecrist** [comment]
The missing binaries are now included in the v3.0.2 release.
