### ISSUE TITLE
show-expire might fail when LC_TIME is not en_US  (or C)

### ISSUE THREAD

**Issue by AndersBlomdell** [OpenVPN/easy-rsa#819]
With LC_TIME=sv_SE.UTF-8, right now these commands fail with

```
# /usr/share/easy-rsa/3/easyrsa --days=140 show-expire
...
  cert_date_to_timestamp_s:
  'date' failed for 'in_date': maj 10 11:35:18 2023 UTC

# /usr/share/easy-rsa/3/easyrsa --days=305 show-expire
...
  cert_date_to_timestamp_s:
  'date' failed for 'in_date': okt 22 11:32:35 2023 UTC
```

**Comment by TinCanTech** [comment]
@AndersBlomdell Hi, thanks for your feedback.

FTR: The commands `show-expire`, `show-revoke` and `show-renew` were created to help manage the transition from the old style `renew` command (Which was completely broken), to the new style `renew` commands (Including: `revoke-renewed`).

Provided that no certificates have been _renewed_ the _old way_, these commands may not be necessary.

Also, it may not be possible to support multi-language date functions.

**Comment by AndersBlomdell** [comment]
> Also, it may not be possible to support multi-language date functions.

I guess that `LC_TIME=C date ...` would be a posix compatible fix for this specific issue

**Comment by TinCanTech** [comment]
On this particular issue, I believe that Easy-RSA has to step _carefully_ outside of POSIX.

**Comment by TinCanTech** [comment]
PR's **welcome** to improve the EasyRSA date functions.

**Comment by TinCanTech** [comment]
@AndersBlomdell if you find time, please test this patch:
```
diff --git a/easyrsa3/easyrsa b/easyrsa3/easyrsa
index a476fff..2a0891f 100755
--- a/easyrsa3/easyrsa
+++ b/easyrsa3/easyrsa
@@ -4031,6 +4031,9 @@ status() {
        # This does not build certs, so do not need fixed dates
        unset -v EASYRSA_FIX_OFFSET EASYRSA_BATCH EASYRSA_SILENT
 
+       # test fix: https://github.com/OpenVPN/easy-rsa/issues/819
+       export LC_TIME=C
+
        # If no target file then add Notice
        if [ -z "$target" ]; then
                # Select correct Notice
```
