### ISSUE TITLE
3.x does not work on SmartOS/Solaris unless shell is changed to /bin/bash

### ISSUE THREAD

**Issue by doublerebel** [OpenVPN/easy-rsa#86]
Error with `/bin/sh`:

``` sh
./easyrsa[977]: local: not found [No such file or directory]
./easyrsa[980]: local: not found [No such file or directory]
./easyrsa[1059]: local: not found [No such file or directory]
./easyrsa[1061]: local: not found [No such file or directory]
./easyrsa[1062]: eval[1]: export: =hB: is not an identifier
```

3.x versions work great on SmartOS instances in Joyent Public Cloud, as long as the shell is changed from `/bin/sh` to `/bin/bash`.

**Comment by ecrist** [comment]
bash is not as ubiquitous as sh and bash should interpret for sh without issue.  We need more details on what, exactly, the errors are.

Eric

**Comment by doublerebel** [comment]
Hi @ecrist , the only errors I received when using `/bin/sh` as the interpreter are posted above.  Is there something specific I can look into?  I'm not familiar enough with the differences between bash and sh to know why sh is complaining about 'local'.

**Comment by QueuingKoala** [comment]
Interesting, it turns out that Solaris provides a shell interpreter that does not include *local* support. While not strictly required by POSIX-2013 (and mentioned in the project compliance guidelines,) every other shell, at least on every other major platform, does support this.

I'm inclined to resolve this by documenting that Solaris users will need to run the code through a shell that does: mksh or dash are two fairly minimal shells, and of course the more bloated ones work as well (bash, zsh, and so on.) The code changes and complexity increase to deal strictly with global variables becomes messy, something I'd very much like to avoid.

**Comment by TyrfingMjolnir** [comment]
`[root@openvpn01 /opt/local/easy-rsa/easyrsa3]# ./easyrsa
./easyrsa[988]: local: not found [No such file or directory]
./easyrsa[991]: local: not found [No such file or directory]
./easyrsa[1070]: local: not found [No such file or directory]
./easyrsa[1072]: local: not found [No such file or directory]
./easyrsa[1073]: eval[1]: export: =hB: is not an identifier`

`# cat /etc/passwd | head -n 1
root:x:0:0:Super-User:/root:/usr/bin/bash`

**Comment by whitslack** [comment]
Easy-RSA 3.0.3 contains bashisms that prevent it from working completely correctly when `/bin/sh` is Dash.

```
$ checkbashisms.pl /usr/share/easy-rsa/easyrsa
possible bashism in /usr/share/easy-rsa/easyrsa line 644 (alternative test command ([[ foo ]] should be [ foo ])):
		if [[ "$crt_type" == 'server' ]]
possible bashism in /usr/share/easy-rsa/easyrsa line 644 (should be 'b = a'):
		if [[ "$crt_type" == 'server' ]]
possible bashism in /usr/share/easy-rsa/easyrsa line 944 (alternative test command ([[ foo ]] should be [ foo ])):
	if [[ $? -eq 0 ]]
```

Please either change the shebang to `#!/bin/bash` or make Easy-RSA POSIX-compliant.

**Comment by TinCanTech** [comment]
@whitslack  This has been fixed : https://github.com/OpenVPN/easy-rsa/pull/135

@ecrist  Both "Releases" of 303 still contain the "[[" error (tar.gz and .zip)

**Comment by ecrist** [comment]
@doublerebel Can you check out v3.0.4 or master and see if the errors still occur?

**Comment by gsauthof** [comment]
It's arguably more portable to rely on some version of bash being available somewhere than to rely on `/bin/sh` being POSIX compliant (and supporting some additional features like `local`).

Thus, using a shebang line like

    #!/usr/bin/env bash

should be very portable. And more portable than `#!/bin/sh`

For example, Solaris 10 ships with `/usr/bin/bash` (version 3.1.52) but their `/bin/sh` isn't POSIX compliant for backward-compatibility reasons. Their POSIX (2001) compliant `sh` is located under `/usr/xpg4/bin/sh`.

**Comment by ecrist** [comment]
We are not going to use bash. 

Eric Crist
