### ISSUE TITLE
`--silent` does not silence SSL output

### ISSUE THREAD

**Issue by medved-cz** [OpenVPN/easy-rsa#863]
When i run './easyrsa --silent gen-crl' for example, on stderr is something like 'Using configuration from XXXXX'. I think it is from openssl. Is there any way to suppress this? I dont want to redirect stderr to /dev/null.

**Comment by TinCanTech** [comment]
> Is there any way to suppress this?

No, not at this time.

Silent operation only silences EasyRSA, it does not try to silence SSL output.

**Comment by TinCanTech** [comment]
There is a reasonably simple fix but it is not a priority.

**Comment by TinCanTech** [comment]
After lengthy investigation, it has been determined that it is **not** possible for EasyRSA to disable OpenSSL output concerning the SSL config file.

**Comment by TinCanTech** [comment]
It turns out that there **may be** a way for EasyRSA to silence SSL output.
