### ISSUE TITLE
SAN (subjectAlternativeName) additions?

### ISSUE THREAD

**Issue by hvisage** [OpenVPN/easy-rsa#88]
Hi there,

 How would I go about to add SAN entries to a certificate where is is already included in a CSR?
Any directions would be appreciated, as I'm trying to get this "fixed" for a few internal websites I'd like to use EasyRSA for.

**Comment by dwt** [comment]
I found that adding the `copy_extensions = copy`option to the `[ CA_default ]` section did the trick for me.

**Comment by TinCanTech** [comment]
`easyrsa --subject-alt-name=DNS:foo gen-req bar text nopass`
