### ISSUE TITLE
why "./easyrsa gen-dh" takes much longer time than "openssl dhparam -out dh2048.pem 2048"?

### ISSUE THREAD

**Issue by YangQing1989** [OpenVPN/easy-rsa#890]
why "./easyrsa gen-dh" takes much longer time than "openssl dhparam -out dh2048.pem 2048"?

**Comment by TinCanTech** [comment]
Your command:

    openssl dhparam -out dh2048.pem 2048

EasyRSA command:

    "$EASYRSA_OPENSSL" dhparam -out "$tmp_dh_file" "EASYRSA_KEY_SIZE"

The same command.
