### ISSUE TITLE
There is no private key on the server side, but the client ovpn can connect

### ISSUE THREAD

**Issue by even0306** [OpenVPN/easy-rsa#921]
I use openvpn+easy rsa on a server and create an account aaa. For some reasons, the server was restored to an early point in time, and the account aaa also disappeared. It did disappear in pki/private, but the former aaa.ovpn can still be connected and used normally. Why is this?

**Comment by TinCanTech** [comment]
> There is no private key on the server side

If this were the case then `openvpn` would not start.
