### ISSUE TITLE
EASYRSA_VARS_FILE ignored

### ISSUE THREAD

**Issue by ericlenio** [OpenVPN/easy-rsa#923]
It seems `EASYRSA_VARS_FILE` is ignored as of 3.1.1, easyrsa only checks for it [here](https://github.com/OpenVPN/easy-rsa/blob/v3.1.1/easyrsa3/easyrsa#L4042), but that logic only kicks in when using `--vars` on the command line. (or am I misunderstanding the usage of `EASYRSA_VARS_FILE`?)

**Comment by TinCanTech** [comment]
Can you explain the problem that you are experiencing ?

**Comment by ericlenio** [comment]
Here's what I mean. Notice I set `EASYRSA_PKI` (among other variables) in my vars file, then I try a `show-cert` operation and the command complains it cannot find my PKI dir (which is different from my `EASYRSA_PKI` setting). Then, I use `--vars=...` on my command and `show-cert` succeeds. Hopefully this example makes sense.
```
pki@ops:~/bin:5.1$ export EASYRSA_VARS_FILE=$(pwd)/easyrsa-vars
pki@ops:~/bin:5.1$ cat $EASYRSA_VARS_FILE
# vim:filetype=bash
EASYRSA=/usr/local/share/easy-rsa
EASYRSA_PKI=$HOME/lw-pki
EASYRSA_REQ_COUNTRY="US"
EASYRSA_REQ_PROVINCE="New York"
pki@ops:~/bin:5.1$ easyrsa show-cert eml
* No Easy-RSA 'vars' configuration file exists!


Easy-RSA error:

EASYRSA_PKI does not exist (perhaps you need to run init-pki)?
Expected to find the EASYRSA_PKI at: /home/pki/bin/pki
Run easyrsa without commands for usage and command help.


WARNING: can't open config file: /home/pki/bin/pki/safessl-easyrsa.cnf
EasyRSA Version Information
Version:     3.1.1
Generated:   Thu Oct 13 06:37:48 CDT 2022
SSL Lib:     LibreSSL 3.6.0
Git Commit:  2083fb29b512c5b2fccf65db8e5f89771fbf90f5
Source Repo: https://github.com/OpenVPN/easy-rsa
Host: 3.1.1 | nix | OpenBSD | /usr/local/bin/bash | LibreSSL 3.6.0
pki@ops:~/bin:5.1$ easyrsa --vars=$EASYRSA_VARS_FILE show-cert eml
* Using SSL: openssl LibreSSL 3.6.0

* Using Easy-RSA configuration: /home/pki/bin/easyrsa-vars


Notice
------
Showing cert details for: 'eml'

This file is stored at:
* /home/pki/lw-pki/issued/eml.crt

Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            15:3a:3f:67:7a:37:0f:d6:44:03:21:80:c6:8f:8c:a4
    Signature Algorithm: sha256WithRSAEncryption
        Issuer:
            commonName                = LincWare CA
        Validity
            Not Before: Nov  8 23:21:57 2021 GMT
            Not After : Nov  6 23:21:57 2031 GMT
        Subject:
            commonName                = eml
        X509v3 extensions:
            X509v3 Basic Constraints:
                CA:FALSE
            X509v3 Subject Key Identifier:
                DA:41:5F:4B:B3:64:31:31:A8:46:0E:58:DA:9C:D2:63:2A:6E:DC:63
            X509v3 Authority Key Identifier:
                keyid:4B:FA:F8:B4:B6:4C:D7:23:A0:C8:04:AB:20:41:60:CD:25:2F:05:79
                DirName:/CN=LincWare CA
                serial:83:23:48:A3:92:13:66:B7

            X509v3 Extended Key Usage:
                TLS Web Client Authentication
            X509v3 Key Usage:
                Digital Signature

pki@ops:~/bin:5.1$ 
```

**Comment by TinCanTech** [comment]
The bug here is that externally setting `EASYRSA_VARS_FILE` does not work as expected.

That can be fixed but you are likely to experience further issues with `vars`.  I would like to work through these issues with you; your setup looks to be a little unorthodox, which makes it a good candidate for testing.

**Comment by ericlenio** [comment]
Yeah I can assist with some testing. What do you think about this patch?

```
diff --git a/easyrsa3/easyrsa b/easyrsa3/easyrsa
index 29609d6..2c49f12 100755
--- a/easyrsa3/easyrsa
+++ b/easyrsa3/easyrsa
@@ -4480,7 +4480,7 @@ vars_setup() {
 
 	# Find vars
 	# Explicit command-line path:
-	if [ "$user_vars_true" ]; then
+	if [ "$EASYRSA_VARS_FILE" ]; then
 		if [ -e "$EASYRSA_VARS_FILE" ]; then
 			vars="$EASYRSA_VARS_FILE"
 		else
```

**Comment by TinCanTech** [comment]
The patch fixes the problem, however, I will take this moment to make some related changes.

**Comment by TinCanTech** [comment]
@ericlenio can you test with #924 applied ?

I'm not sure how you have `easyrsa` setup, so this is how I do it:
- Create a new user directory for Easy-RSA git. eg: `/home/tct/git/easy-rsa/master`
- Clone Easy-RSA git to that location.
- Soft link `/usr/local/sbin/easyrsa` to `/home/tct/git/easy-rsa/master/easyrsa3/easyrsa`
- **Make a backup of you current PKI**..

To apply the patch, in the `easyrsa` git clone, I do as follows:
- `git checkout -b TinCanTech-externally-set-vars master`
- `git pull --no-ff --no-commit https://github.com/TinCanTech/easy-rsa.git externally-set-vars`

This will apply the patch but not commit it. The `easyrsa` script is ready to test from your `$PATH` environment.

Please let me know of any further issues.

**Comment by TinCanTech** [comment]
I forgot to `rebase`, sorry about that.

Have now done so and forced pushed an update.

Please try again.

**Comment by ericlenio** [comment]
It tests out successfully for me:
- when I set environment var `EASYRSA_VARS_FILE`, the `easyrsa` script picks it up
- when I unset `EASYRSA_VARS_FILE`, `easyrsa` commands fail (as expected)
- passing `--vars=/path/to/my/vars` to the `easyrsa` command picks up my vars file as expected

**Comment by TinCanTech** [comment]
@ericlenio Thank you for your help.
