### ISSUE TITLE
./easyrsa build-server-full issue on Windows

### ISSUE THREAD

**Issue by FreeBeing11** [OpenVPN/easy-rsa#929]
Hi,

With EasyRSA 3.1.2 on Windows, I have a problem to generate build-server-full certificate.
(EasyRSA 3.0.8 don't have the bug)

Command used :
./easyrsa build-server-full vpn-maxime nopass

Script pause after that, without error :
Notice
------
Keypair and certificate request completed. Your files are:
* req: C:/Program Files/OpenVPN/easy-rsa/pki/reqs/vpn-maxime.req
* key: C:/Program Files/OpenVPN/easy-rsa/pki/private/vpn-maxime.key

But, if I press "Enter" key 3 or 4 times, the script resume, and I have many "mv replace" questions.

**Full result of the command**
./easyrsa build-server-full vpn-maxime nopass

* Using Easy-RSA configuration:
  C:/Program Files/OpenVPN/easy-rsa/vars

* The preferred location for 'vars' is within the PKI folder.
  To silence this message move your 'vars' file to your PKI
  or declare your 'vars' file with option: --vars=<FILE>

* Using SSL: C:/Program Files/OpenVPN/bin/openssl.exe OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)

........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...........+...+.......+......+...+..+....+...+......+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.....+...+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
...+......+.......+..+............+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+...+.........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...+..+.+..+....+...+...+.........+..............+.......+..+.......+...+..+.........+..........+.........+...+...............+..+...+.........+...+...+....+...........+.........+......+.......+..+....+..+.......+.....+...+...+.+.........+......+.....+.........+....+..+..........+.....+.+...+..+..........+..................+......+........+..........+..+.........+..........+..+............+...+...............+...+....+...+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----

Notice
------
Keypair and certificate request completed. Your files are:
* req: C:/Program Files/OpenVPN/easy-rsa/pki/reqs/vpn-maxime.req
* key: C:/Program Files/OpenVPN/easy-rsa/pki/private/vpn-maxime.key

mv: replace `c:/program files/openvpn/easy-rsa/pki/0b528d3b/temp.8.x', overriding mode 0666? y
mv: replace `c:/program files/openvpn/easy-rsa/pki/0b528d3b/temp.9.x', overriding mode 0666? y
mv: replace `c:/program files/openvpn/easy-rsa/pki/0b528d3b/temp.8.x', overriding mode 0666? y
mv: replace `c:/program files/openvpn/easy-rsa/pki/0b528d3b/temp.9.x', overriding mode 0666? y
mv: replace `c:/program files/openvpn/easy-rsa/pki/0b528d3b/temp.8.x', overriding mode 0666? y
mv: replace `c:/program files/openvpn/easy-rsa/pki/0b528d3b/temp.9.x', overriding mode 0666? y
You are about to sign the following certificate.
Please check over the details shown below for accuracy. Note that this request
has not been cryptographically verified. Please be sure it came from a trusted
source or that you have verified the request checksum with the sender.

Request subject, to be signed as a server certificate
for '3650' days:

subject=
    commonName                = vpn-maxime

Type the word 'yes' to continue, or any other input to abort.
  Confirm request details: yes

mv: replace `c:/program files/openvpn/easy-rsa/pki/0b528d3b/temp.8.x', overriding mode 0666? y
mv: replace `c:/program files/openvpn/easy-rsa/pki/0b528d3b/temp.9.x', overriding mode 0666? y
Using configuration from C:/Program Files/OpenVPN/easy-rsa/pki/0b528d3b/temp.9.x
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'vpn-maxime'
Certificate is to be certified until Apr  3 21:17:30 2033 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated

Notice
------
Certificate created at:
* C:/Program Files/OpenVPN/easy-rsa/pki/issued/vpn-maxime.crt

Notice
------
Inline file created:
* C:/Program Files/OpenVPN/easy-rsa/pki/inline/vpn-maxime.inline

**Thank you for your help.**

**Comment by FreeBeing11** [comment]
Note : GitHub writer is a pain, because my terminal text pasted there is bad formated.

Also, it hides some "mv: replace" questions.

The right number of lines of "mv: replace" is 6 after "Keypair and certificate request completed", and 2 after "Confirm request details".

**Comment by TinCanTech** [comment]
This is a permission issue.

I believe it can be influenced by setting:
`export EASYRSA_NO_UMASK=1`
on the command line.

You can also try alternative values for `EASYRSA_UMASK`. The default is `077`. How this reacts with your Windows is unknown to me.

**Comment by FreeBeing11** [comment]
I tried
export EASYRSA_NO_UMASK=1
(no effect)

I tried
export EASYRSA_UMASK=777
(no effect)

The errors are the same :
mv: replace `c:/program files/openvpn/easy-rsa/pki/959e46d4/temp.8.x', overriding mode 0666?

Also, I have full Administrator rights on this Windows Server, and UAC is disabled.
Right are maximum on the folder (full control).

Maybe any other idea ?

Thank you for your help.

**Comment by TinCanTech** [comment]
The only suggestions I have are:
- Copy `C:\Program Files\Openvpn\easy-rsa` to your home directory: `C:\Users\${Your_name}` and run it from there.

If that does not work then comment out the line `5694`
```
# Be secure with a restrictive umask
#[ "$EASYRSA_NO_UMASK" ] || umask "${EASYRSA_UMASK:-077}"
```

If that does not work then I would use Linux instead of Windows.

**Comment by TinCanTech** [comment]
As a possible fix here, the `umask` could be removed for temp-files.

I will submit a PR for testing.

**Comment by FreeBeing11** [comment]
I tried to use easyrsa into C:\Users\${Your_name} folder, but same problem.

I even tried to change EASYRSA TMP dir (into vars) on C:\ with rights to maximum, but that's not improved things.

After, I commented the line
#[ "$EASYRSA_NO_UMASK" ] || umask "${EASYRSA_UMASK:-077}"

Same result.

At last, I tried your new easyrsa script, with your latest commit.
I obtain a lot of "mv" bugs, and certificate generate abort.


# ./easyrsa build-server-full vpn-maxime6 nopass

* Using Easy-RSA configuration:
  C:/Users/Administrateur/easy-rsa/vars

* The preferred location for 'vars' is within the PKI folder.
  To silence this message move your 'vars' file to your PKI
  or declare your 'vars' file with option: --vars=<FILE>

* Using SSL: C:/Program Files/OpenVPN/bin/openssl.exe OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)

mv: invalid option -- n
Try `mv --help' for more information.
mv: invalid option -- n
Try `mv --help' for more information.
mv: invalid option -- n
Try `mv --help' for more information.
mv: invalid option -- n
Try `mv --help' for more information.
mv: invalid option -- n
Try `mv --help' for more information.
mv: invalid option -- n
Try `mv --help' for more information.
mv: invalid option -- n
Try `mv --help' for more information.
mv: invalid option -- n
Try `mv --help' for more information.
mv: invalid option -- n
Try `mv --help' for more information.
mv: invalid option -- n
Try `mv --help' for more information.
mv: invalid option -- n
Try `mv --help' for more information.
mv: invalid option -- n
Try `mv --help' for more information.
mv: invalid option -- n
Try `mv --help' for more information.
mv: invalid option -- n
Try `mv --help' for more information.
mv: invalid option -- n
Try `mv --help' for more information.
mv: invalid option -- n
Try `mv --help' for more information.
mv: invalid option -- n
Try `mv --help' for more information.
mv: invalid option -- n
Try `mv --help' for more information.

Easy-RSA error:

easyrsa_mktemp - failed for: key_out_tmp @ depth=9
target: C:/Users/Administrateur/easy-rsa/pki/69e183c0/temp.1.9

EasyRSA Version Information
Version:     ~VER~
Generated:   ~DATE~
SSL Lib:     OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)
Git Commit:  ~GITHEAD~
Source Repo: https://github.com/OpenVPN/easy-rsa
Host: dev | win | @(#)MIRBSD KSH R39-w32-beta14 $Date: 2013/06/28 21:28:57 $ |

**Comment by FreeBeing11** [comment]
I've a simple idea : why not reusing "temp file manage" from EasyRSA 3.0.8, that don't have this bug on Windows ?

**Comment by TinCanTech** [comment]
@FreeBeing11 Can you please test now that #930 is merged.

You should not be prompted to move temporary files.
(There could still be other problems ..)

**Comment by FreeBeing11** [comment]
Got it :)

Thank you ; this version works ;)

**Comment by TinCanTech** [comment]
Thank you for your help.  

Closing this, please open new issues for new problems.

Please include the `easyrsa` error message.
