### ISSUE TITLE
Unknown cert type 'ca' or 'server' or 'client'

### ISSUE THREAD

**Issue by glafir** [OpenVPN/easy-rsa#93]
My system
`FreeBSD gw.1ok 10.2-RELEASE FreeBSD 10.2-RELEASE #0 r286666: Wed Aug 12 19:31:38 UTC 2015     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  i386`

My openVPN version 
```
openvpn --version
OpenVPN 2.3.10 i386-portbld-freebsd10.1 [SSL (OpenSSL)] [LZO] [MH] [IPv6] built on Apr  3 2016
library versions: OpenSSL 1.0.1p-freebsd 9 Jul 2015, LZO 2.09
Originally developed by James Yonan
Copyright (C) 2002-2010 OpenVPN Technologies, Inc. <sales@openvpn.net>
Compile time defines: enable_crypto=yes enable_crypto_ofb_cfb=yes enable_debug=yes enable_def_auth=yes enable_dlopen=unknown enable_dlopen_self=unknown enable_dlopen_self_static=unknown enable_fast_install=needless enable_fragment=yes enable_http_proxy=yes enable_iproute2=no enable_libtool_lock=yes enable_lzo=yes enable_lzo_stub=no enable_management=yes enable_multi=yes enable_multihome=yes enable_pam_dlopen=no enable_pedantic=no enable_pf=yes enable_pkcs11=no enable_plugin_auth_pam=yes enable_plugin_down_root=yes enable_plugins=yes enable_port_share=yes enable_selinux=no enable_server=yes enable_shared=yes enable_shared_with_static_runtimes=no enable_small=no enable_socks=yes enable_ssl=yes enable_static=yes enable_strict=no enable_strict_options=no enable_systemd=no enable_win32_dll=yes enable_x509_alt_username=no with_crypto_library=openssl with_gnu_ld=yes with_mem_check=no with_plugindir='$(libdir)/openvpn/plugins' with_sysroot=no
```

I generate Ca-key and Ca-cert
```
./easyrsa.real sign-req ca CA

Note: using Easy-RSA configuration from: ./vars

Easy-RSA error:

**Unknown cert type 'ca'**

```
or

```
./easyrsa.real sign-req 'server' vpn.1-ok.com

Note: using Easy-RSA configuration from: ./vars

Easy-RSA error:

Unknown cert type 'server'
```
How can fix it?

**Comment by RobertLarsen** [comment]
I'm seeing the same on Ubuntu 14.04:

```
$ ./easyrsa build-server-full VPN nopass
Generating a 2048 bit RSA private key
.....................+++
..+++
writing new private key to '/home/vagrant/CA/pki/private/VPN.key.f4i5UyAahh'
-----

Easy-RSA error:

Unknown cert type 'server'
```

**Comment by RobertLarsen** [comment]
I fixed my own problem. The x509-types directory needed to be located in the same directory as the 'easyrsa' script. I had created a new directory and simply symlinked the easyrsa script and the openssl-1.0.cnf file. After having symlinked x509-types everything worked.

**Comment by glafir** [comment]
Yes! Thanks! I already understanded this!

**Comment by RdL87** [comment]
Hi,
i'm facing the same issue on the following stack:

- CentOS Linux release 7.7.1908 (Core)
- OpenVPN 2.4.7 x86_64-redhat-linux-gnu
- Easy-RSA 3.0.6 

Hi tried a [solution ](https://forum.openwrt.org/t/problem-in-openvpn-basic-instructions-and-workaround/39530)that mentions this issue but i have always same error:

```
Note: using Easy-RSA configuration from: ./vars

Easy-RSA error:

Unknown cert type 'server'
```

**Comment by mmrvelj** [comment]
I had this problem as well on Centos 7.7 with easyrsa-3.0.6 and found out that the issue is incorrect setting of the variable EASYRSA_EXT_DIR which is set in "vars" file. After correcting it to point to correct location of x509-types folder everything works as expected.

**Comment by motorollo** [comment]
I use easyrsa-3.0.7 and OpenVPN-2.5.0-I601-amd64.msi and
easyrsa sign-req client rechner.domäne.de dosent't work.
I get the message: Unknown cert type 'client'
The x509-types-folder is in place and a file client is there.
easyrsa-3.0.8, which is delivered with OpenVPN-2.5.0-I601-amd64.msi has other problems.

**Comment by noah-seltzer** [comment]
@motorollo I had the same problem on windows, copying the `/x509-types` folder into the `pki` folder made it work for me

**Comment by 5er9e1** [comment]
I trying to follow official [manual](https://github.com/OpenVPN/easy-rsa/blob/master/README.quickstart.md):

```bash
./easyrsa init-pki
./easyrsa build-ca nopass
./easyrsa gen-req "${EASYRSA_REQ_CN}" nopass
./easyrsa show-req "${EASYRSA_REQ_CN}"
```

```text
Certificate Request:
    Data:
        Version: 0 (0x0)
        Subject:
            commonName                = example.com
        Attributes:
            a0:00
```

And finally:

```
./easyrsa sign-req client "${EASYRSA_REQ_CN}"
```

```text
Easy-RSA error:

Unknown cert type 'client'
```

Let's see `easyrsa` code:

```
sign_req() {
...
        # Cert type must exist under the EASYRSA_EXT_DIR
        [ -r "$EASYRSA_EXT_DIR/$crt_type" ] || die "\
Unknown cert type '$crt_type'"
...
}
```

What a stupid bug? Why `client` (or `server`) *must exist under the EASYRSA_EXT_DIR*? `easyrsa` never creates these files. How it supposed to be working?
