### ISSUE TITLE
Upgrade from v2 to v3 fails on Windows

### ISSUE THREAD

**Issue by itu7** [OpenVPN/easy-rsa#942]
Ugrading from v2.x to v3.1.2 on Windows fails with following error:

```
Easyrsa upgrade version: v1.0a (2020/01/08)
=========================================================================




This upgrade will TEST that the upgrade works BEFORE making any changes.

Type the word 'yes' to continue, or any other input to abort.
  * EasyRSA **TEST** upgrade (Changes will NOT be written): yes


Easy-RSA error:

easyrsa_mktemp - Non-existant temporary session:
*


Easy-RSA error:

easyrsa_openssl - easyrsa_mktemp failed
```

Workaround:
1. edit easyrsa script and insert `secure_session` after line 5537 right before `up23_manage_upgrade_23`
2. run the upgrade command with additional option:
`# ./easyrsa --tmp-dir=$PWD/tmp upgrade pki`

I also tried current master with applied PR #906 (see #905) but then the script tries to use `pki` folder as tempdir which presence would even prevent the upgrade:

```
# ./easyrsa upgrade pki

* No Easy-RSA 'vars' configuration file exists!

Easy-RSA error:

secure_session - Missing temporary directory:
* C:/Program Files/openvpn/easy-rsa-test/pki

```

**Comment by TinCanTech** [comment]
The `upgrade` command is not well tested, can you please raise a PR against `easyrsa-git/master`.
