### ISSUE TITLE
Easy-RSA error:  Conflicting 'vars' files found

### ISSUE THREAD

**Issue by harmv** [OpenVPN/easy-rsa#951]
When using easy-rsa out of the box it errors out, with a bogus (sounding) error.

It complains about finding the same 'vars' file twice. (on the same location)...

### steps to reproduce
```
 $ mkdir ~/pki
 $ cd ~/pki
 $ export EASYRSA_PKI=`pwd`
 $ easyrsa init-pki
 $ cd ..
 $ cd ~/pki                         (as init-pki  cleared the directory, you need to re-enter it to see the files)
```
So far so good, a new pki has been setup in directory ~/pki/   It has a `vars` file. Now issue the build-ca command

```
$ easyrsa build-ca
```
### result

The command build-ca fails

```
$ easyrsa build-ca
Found: /Users/<name>/pki/vars
Found: /Users/<name>/pki/vars

Easy-RSA error:

Conflicting 'vars' files found.

Priority should be given to your PKI vars file:
* /Users/<name>/pki/vars


EasyRSA Version Information
Version:     ~VER~
Generated:   ~DATE~
SSL Lib:     OpenSSL 3.1.0 14 Mar 2023 (Library: OpenSSL 3.1.0 14 Mar 2023)
Git Commit:  ~GITHEAD~
Source Repo: https://github.com/OpenVPN/easy-rsa
Host: dev | nix | Darwin | /bin/bash

```

The error seems bogus, it complains about finding the same (!!) file twice? On the same location?

### expected result

easyrsa build-ca is executed with ~/pki/vars  as --vars= file.  And no error is given.

### version
```$ brew list --version easy-rsa
easy-rsa 3.1.2
```
On macbook, macOS Ventura 13.3.1

### Notes

I just found out that this error only happens when you're actually  in the `~/pki`.  If you cd out of that directory the error disappears.

Still, I think the command should just as well work when inside the directory.

**Comment by TinCanTech** [comment]
> I think the command should just as well work when inside the directory.

Easy-RSA strongly disagrees.

However, if you insist, try using the command correctly:

    easyrsa --pki-dir=. --vars=./vars build-ca

**Comment by harmv** [comment]
Well I use the EASYRSA_PKI env variable instead of --pki-dir, which should be fine right?
And according to the docs it should look for the vars file in $EASYRSA_PKI too (amongst other directories), right? 

Then easyrsa, incorrectly, find the file twice.  it find it in $EASYRSA_PKI _and_ in the current dir.  but that not an error, as the current dir _is_ $EASYRSA_PKI.  Its the literally the same file.  I don't see any benefits in bailing out on that.

(Please note that I have only  _one_ vars file, inside $EASYRSA_PKI)

your suggestion: `easyrsa-pki-dir=. --vars=./vars build-ca`  works fine, as does simply cd-ing out of `./pki` dir.

IMHO. The error makes no sense in this case.
It _does_ make sense to error out if its ambiguous which `vars` file is to be used. But in this case there is zero ambiguity.
Fixing this would improve usability.

NB: I tested latest git/master  lasten version (2141bfa245117b5e) -> same issue.

**Comment by TinCanTech** [comment]
Please explain **why** you want to use Easy-RSA this way.
