### ISSUE TITLE
Openssl pkcs12 export Option legacy

### ISSUE THREAD

**Issue by chillriver** [OpenVPN/easy-rsa#957]
Hello,

I have a question about pkcs12 export. It is possible to use the option legacy, when the export pkcs12 is making?
The legacy option is enable since version openssl 3.x. Some Mac users has the problem how does it mentioned on the follow site:
[https://stackoverflow.com/questions/70431528/mac-verification-failed-during-pkcs12-import-wrong-password-azure-devops](https://stackoverflow.com/questions/70431528/mac-verification-failed-during-pkcs12-import-wrong-password-azure-devops)

When I use the option legacy, the Mac users can set they password.

**Comment by TinCanTech** [comment]
EasyRSA-3 has always used AES as the default.

Enabling `openssl` `-legacy` option would be a _giant leap_ backwards.

Your backward-compatibility issue is best resolved by your current solution.
