### ISSUE TITLE
batch in sign_req

### ISSUE THREAD

**Issue by VVD** [OpenVPN/easy-rsa#960]
Commit https://github.com/OpenVPN/easy-rsa/commit/00d7a69788afd0d0db0891338c7d11c97f681d73 removed commented line `#[ "$3" = "batch" ] ||`.
This line need for batch mode in sign_req (if uncomment it).
Example command:
`easy-rsa --passin=pass:"${CA_PASSWORD}" sign-req client "${USER}" batch`

Can you please return this line and uncomment it.
Or explain how to run command from example in full batch mode.

Thanks!

**Comment by TinCanTech** [comment]
Please post the output of the command that fails for you.

**Comment by VVD** [comment]
```
# easy-rsa gen-req usertest nopass batch

* Using Easy-RSA configuration:
  /usr/local/etc/openvpn/pki/vars

* Using SSL: openssl OpenSSL 1.1.1t-freebsd  7 Feb 2023

Generating a ED25519 private key
writing new private key to '/usr/local/etc/openvpn/pki/e5f77a88/temp.1.1'
-----

Notice
------
Keypair and certificate request completed. Your files are:
* req: /usr/local/etc/openvpn/pki/reqs/usertest.req
* key: /usr/local/etc/openvpn/pki/private/usertest.key

# easy-rsa --passin=pass:${CA_PASSWORD} sign-req client usertest batch

* Using Easy-RSA configuration:
  /usr/local/etc/openvpn/pki/vars

* Using SSL: openssl OpenSSL 1.1.1t-freebsd  7 Feb 2023

You are about to sign the following certificate.
Please check over the details shown below for accuracy. Note that this request
has not been cryptographically verified. Please be sure it came from a trusted
source or that you have verified the request checksum with the sender.

Request subject, to be signed as a client certificate 
for '3650' days:

subject=
    commonName                = usertest


Type the word 'yes' to continue, or any other input to abort.
  Confirm request details:
```
It as me 'yes', but I need true batch mode.
But with this line `[ "$3" = "batch" ] ||` it's real batch mode - without ask "yes/no" etc.

**Comment by TinCanTech** [comment]
> It ask me confirmation, but I need true batch mode.
> But with this line `[ "$3" = "batch" ] ||` it's real batch mode - without ask "yes/no" etc.

 Please see: `easyrsa help options` for help with _true_ batch mode.

**Comment by VVD** [comment]
Thanks!
`easy-rsa --batch --passin=pass:${CA_PASSWORD} sign-req client usertest batch` work as expected.
Last option in command line `batch` is required too.
