### ISSUE TITLE
Please, consider allow passing -keypbe, -certpbe and -macalg to export-p12

### ISSUE THREAD

**Issue by edvalley** [OpenVPN/easy-rsa#966]
OpenVPN 2.6 doesn't allow anymore SHA1 as MAC algorithm in PKCS12 files. That's the default while still using OpenSSL 1.x. Thanks.

**Comment by ecrist** [comment]
Current versions of EasyRSA ship with OpenSSL 3.x.

Eric F Crist
________________________________
